### ISSUE TITLE
instance crashes when using getMe

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#10]
Hello there.

Great thing we have here, if it would just work. I tried running it on my laptop, but it crashes when I do the "getMe" call. I can confirm it running before because the stats port I use works. I run it with filter set to `345017557/0`, since my bots id is that and I only want it to connect. I also followed all the buildings instructions and logged my bot out before attempting to use the local instance.

I'm gonna attach the log to this issue, hope it helps or you can show me where my error is. It happens to run on an Ubuntu 20.04 flavour, if that is the issue, I will happily install plain Ubuntu itself.
[log.log](https://github.com/tdlib/telegram-bot-api/files/5489944/log.log)

Also, you can PM me on telegram, same username, if you want a more direct form of communication.

**Comment by levlam** [comment]
You use the filter wrongly. "345017557/0" means "bot_user_id % 0 == 345017557" and this is definitely a crash. You need something like "345017557/2147283647".

**Comment by Poolitzer** [comment]
oh wow. I assumed the args where in the same order as they appear in the help string, but they are switched around. What I actually wanted was `0/345017557`. I don't understand your suggestion, but it worked as well, and I am no C++ coder, so I bet it makes sense. Anyway, thanks for the help!

**Comment by levlam** [comment]
@Poolitzer No, this is "<remainder>/<modulo>" exactly as written. For example, you can have shards "0/3", "1/3" and "2/3".

**Comment by Poolitzer** [comment]
>exactly as written

that is my issue. the full help string goes `"\"<remainder>/<modulo>\". Allow only bots with 'bot_user_id % modulo == remainder'"`. So I read the equation, where modulo comes before remainder, and assumed the flag would be written in the same way, not remembering the doc. Its not an actual issue (hence me closing this), just me understanding it wrongly.
