### ISSUE TITLE
How many instances of telegram-bot-api could be started with the same app-id?

### ISSUE THREAD

**Issue by ihoru** [tdlib/telegram-bot-api#100]
I have local/development, staging and production environments, each of them is separate machine. I want to start `telegram-bot-api` on each of them with the same `app-id` (because I can get only one for one Telegram account).
I also have other servers with another projects where I also want to start `telegram-bot-api` with the same `app-id`.

1. Is it normal to do like this?
2. Is there any safe number of maximum instances of `telegram-bot-api` running at the same time with the same `app-id`?
3. Is there any change my instances will be banned or somehow limited because of this?

**Comment by levlam** [comment]
1. Yes.
2. Any.
3. No.
