### ISSUE TITLE
copyMessage is working even after deleting message_id from the from_chat_id

### ISSUE THREAD

**Issue by SpEcHiDe** [tdlib/telegram-bot-api#101]
Steps to Reproduce 😬😬🙈
1. Send a message to a specific broadcast channel
2. call copyMessage API, with the from_chat_id == Id of broadcast channel, and message_id == the id of sent message in step 1.
3. Delete the message sent in step 1.
4. Repeat step 2.

Expected Behaviour 🤔😅
The message should not get copied to the chat_id

Actual Behaviour 🤒😖
The message gets copied to the chat_id

**Comment by levlam** [comment]
`copyMessage` works using information about the message cached on the Bot API server for 30 minutes. Bots often didn't receive message deletion updates and have no way to delete the data from the cache, so `copyMessage` will succeed for these 30 minutes.

**Comment by 0964770939** [comment]
sumsweet

Vào 20:34, Th 3, 2 thg 3, 2021 Shrimadhav U K <notifications@github.com> đã
viết:
