### ISSUE TITLE
Detect schedule message?

### ISSUE THREAD

**Issue by swandono** [tdlib/telegram-bot-api#102]
Hi guys, is there any chance to detect schedule message?
My use case need to know that person send a message in real time or not?
I already compare it to regular chat, but there's no difference.
![image](https://user-images.githubusercontent.com/2106030/109601512-95292080-7b51-11eb-8fab-de23f9bb76d6.png)

**Comment by levlam** [comment]
No, this is not possible. Only message sender knows whether the message was scheduled.
