### ISSUE TITLE
[Feature Request] Add user property to MessageEntity with type mention

### ISSUE THREAD

**Issue by UtopicPanther** [tdlib/telegram-bot-api#107]
Currently, `text_mention` MessageEntity has a `user` property so that bot can get the mentioned user ID, but `mention` does not.

However, when a user types `@` to mention another user in the Telegram client, `mention` is always created instead of `text_mention` as long as the target user has a username, and the bot API does not have a way to get the user ID by username, which prevents bot from getting the mentioned user ID.

My use case is to allow the creator/admin to modify the configuration of the some users in the bot database by mentioning the user.

Can you add that for bot API? Thanks.

**Comment by levlam** [comment]
This is not possible. It would allow to resolve usernames to corresponding users virtually with no limits, allowing to match unlimited number of usernames to corresponding users. You should store correspondence from username to user_id for known users in a local database if you need it.

**Comment by UtopicPanther** [comment]
> You should store correspondence from username to user_id for known users in a local database if you need it.

So can we have an API to resolve from username to user_id?
When the user is first mentioned, the bot needs a way to know the user_id.
BTW, The username may change and it is obviously not safe to store the username.

**Comment by levlam** [comment]
> So can we have an API to resolve from username to user_id?

No. The limit for username resolving is 200 usernames daily, so it would be exceed immediately and would be useless for any reasonable usage. And as I explained, there is no way the limit can be increased.

> BTW, The username may change and it is obviously not safe to store the username.

You can use `getChat` to recheck the username.

**Comment by UtopicPanther** [comment]
> No. The limit for username resolving is 200 usernames daily, so it would be exceed immediately and would be useless for any reasonable usage. And as I explained, there is no way the limit can be increased.

I see. I will close this issue.
