### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mirdoraghi** [tdlib/telegram-bot-api#109]
In my centos, 2core, 4G memery, When I compile, it has error

[ 76%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o] Error 1
gmake[1]: *** [td/CMakeFiles/tdcore.dir/all] Error 2

**Comment by ihoru** [comment]
> Killed signal terminated program

Somebody on your machine killed the process, no?

**Comment by mirdoraghi** [comment]
I don't know..

**Comment by ihoru** [comment]
1. Have you started compilation again?
2. Is it your private machine?

**Comment by mirdoraghi** [comment]
1. Yes. I started compilation 4 times.
2. Yes. Centos 7,2Core,4GB Ram.

**Comment by levlam** [comment]
You have not enough memory to build the code using g++. You can try to adapt build instructions for OpenBSD (https://tdlib.github.io/telegram-bot-api/build.html?os=OpenBSD) to use SplitSource.php before building, which will decrease peak memory usage in the expence of much longer build time.
