### ISSUE TITLE
Minimal server requirements

### ISSUE THREAD

**Issue by eric-cartman-dev** [tdlib/telegram-bot-api#111]
Hi. What server requirements needed for own bot server ? RAM/vCPU/Storage etc ? Per user requirements ? Or per request requirements ? Or minimal requirements.

**Comment by levlam** [comment]
There are no minimal requirements. It solely depends on load of bots, which will use the server. A bot without load will use around 1 MB RAM. The most popular bots can use up to 100 GB RAM in a week, but 2 vCPU should be enough even for them.

**Comment by 0964770939** [comment]
Vào 7:55, Th 7, 27 thg 3, 2021 Cartman ***@***.***> đã viết:
