### ISSUE TITLE
شابت

### ISSUE THREAD

**Issue by lli76** [tdlib/telegram-bot-api#113]
‏مرحبا 
‏حسابي ( ⁦‪@li_76‬⁩ ) 
‏المسجل برقم هاتفي ( 0594211232 ) الرقم قد انتهت خدمته ولااستخدمه الان وحسابي مسجل بهذا الرقم ولا استطيع الدخول اتمنى منكم المساعده وشكراً جزيلاً  ‬⁩

**Comment by levlam** [comment]
This is unrelated to Bot API.
