### ISSUE TITLE
Upload file error: EOF

### ISSUE THREAD

**Issue by kongkongzzz** [tdlib/telegram-bot-api#116]
An EOF error occurs when I upload a file that is larger than about 1GB（local mode）, even though the file is still sent successfully. This doesn't happen when I send files around 500MB. The POST request returns to the EOF about halfway through the file, but the request has been interrupted. After the result is returned, the file is still sent by the API.

**Comment by kongkongzzz** [comment]
This error is related to the time it takes the API to process the request. If multiple files are sent at the same time, but each file is sent slowly, this error can also occur on small files.Is this because the API forcibly pinches long time connections?

**Comment by kongkongzzz** [comment]
The err is "POST http://localhost:8081/botapi/method(such as sendvideo) EOF".

This error occurs in the middle of sending a file that is larger than about 1G(file URL). I use Golang to write my robot program, and this error often occurs when a server disconnects or for some other reason accidentally disconnects(in other Go program).

I wrote a simple file receiver server and sent more than 2GB files or connected for more than 1 hour to test whether the client was working properly, send a POST request to my own server and the error did not happen (there was no actual function, just the completion of the request).

**Comment by levlam** [comment]
Bot API server can't return anything called "EOF".

**Comment by kongkongzzz** [comment]
Yes, this error is caused by my program.But why does my program produce this error? Because the connection dropped unexpectedly. And it's a local connection break, there's no complex routing problem. And if the server is replaced by my own test server, there will be no errors. So I suspect the tg-bot-api forced the disconnect.

**Comment by levlam** [comment]
Bot API server has timeout of 600 seconds for reading incoming requests. It is very unlikely that sending a local file could take so much time.

**Comment by kongkongzzz** [comment]
Probably is after this time has produced the error. When I send a 1.5G file at 1 M/s, it takes about 1500 seconds.In my case, the transmission speed is between 1M/s and 6M/s, so more than 600 seconds is very likely.

**Comment by levlam** [comment]
The upload speed needs to be improved.
Between, you can send a file by a local path in a local mode.

**Comment by kongkongzzz** [comment]
I already send my file by a local path, but it's slowly。My server is in the Netherlands，and when I send data to the api.telegram.org, it can reach more than 30M/s. Maybe the local API will be speed-limited, just like a user account?

**Comment by kongkongzzz** [comment]
I will try to change the timeout time to a suitable range to solve this problem. Thank you for your answer.
I also hope the authorities provide some kind of interface to change the timeout if you think it is feasible.

**Comment by levlam** [comment]
No, local API isn't speed limited. This depends solely on your network connection.

**Comment by kongkongzzz** [comment]
OK, thank you very much.

**Comment by kongkongzzz** [comment]
Oh, okay, I found it by myself at the same time and edit the reply. Thank you very much.
