### ISSUE TITLE
Add option to get messages in an id interval

### ISSUE THREAD

**Issue by Moldoteck** [tdlib/telegram-bot-api#118]
This is possible anyway by iterating through id's, creating an reply to them, inspecting the result and deleting this reply. Would be very nice that instead of this workaround we would be able to just get the message object by it's id or getting all messages from an interval of id's

**Comment by levlam** [comment]
You should store message contents locally. if you need them. Quering remote server is very inefficient, is subject to rate limiting and can affect rate limits of other legitimate requests.

**Comment by Moldoteck** [comment]
Yes, I understand that this type of function should be somehow limited, to avoid problems.
My usecase is that i want to create a bot which takes all messages between start message and end message and transforms them into audio. start/end messages are specified by users, as reply to them with some commands. I thought that this will not be a problem, since there is an core telegram api for this usecase: https://core.telegram.org/method/messages.getMessages

**Comment by levlam** [comment]
No, it will be a problem. The bot can use direct replies to the messages instead.
