### ISSUE TITLE
Compilation fails on OpenBSD

### ISSUE THREAD

**Issue by la-ninpre** [tdlib/telegram-bot-api#12]
Hello! I tried compiling bot server on OpenBSD. I've done everything like described in build instructions.
Firstly I tried it on OpenBSD 6.8, but then I realized that official instruction points out that OpenBSD 6.7 should be used.
Then I tried on OpenBSD 6.7 and got the same error.
Compilation was performed from root user, so it's not the problem of memory access.
Here's my dmesg and error log (made with `cmake --build . --target install 2> error.log`).
Of course I suppose it could be an issue with VirtualBox, but it seems like there's something wrong in a different place.
```
ld: error: undefined symbol: td::Td::request(unsigned long long, td::tl::unique_ptr<td::td_api::Function>)
>>> referenced by ClientActor.cpp
>>>               ClientActor.cpp.o:(td::ClientActor::request(unsigned long long, td::tl::unique_ptr<td::td_api::Function>)) in archive td/libtdcore.a

ld: error: undefined symbol: td::Td::static_request(td::tl::unique_ptr<td::td_api::Function>)
>>> referenced by ClientActor.cpp
>>>               ClientActor.cpp.o:(td::ClientActor::execute(td::tl::unique_ptr<td::td_api::Function>)) in archive td/libtdcore.a

ld: error: undefined symbol: td::Td::Td(td::unique_ptr<td::TdCallback>, td::Td::Options)
>>> referenced by ClientActor.cpp
>>>               ClientActor.cpp.o:(td::ActorOwn<td::Td> td::Scheduler::create_actor<td::Td, td::unique_ptr<td::TdCallback>, td::Td::Options>(td::Slice, td::unique_ptr<td::TdCallback>&&, td::Td::Options&&)) in archive td/libtdcore.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (CMakeFiles/telegram-bot-api.dir/build.make:202 'telegram-bot-api': /usr/local/bin/cmake -E cmake_link_script CMakeFiles/te...)
*** Error 2 in . (CMakeFiles/Makefile2:379 'CMakeFiles/telegram-bot-api.dir/all': /usr/bin/make -f CMakeFiles/telegram-bot-api.dir/build.mak...)
*** Error 2 in /home/aaoth/telegram-bot-api/build (Makefile:130 'all': /usr/bin/make -f CMakeFiles/Makefile2 all)
```
[dmesg.txt](https://github.com/tdlib/telegram-bot-api/files/5491126/dmesg.txt)

**Comment by la-ninpre** [comment]
Update: same thing fails with the same error in QEMU

**Comment by levlam** [comment]
Do you have enough RAM on the server? g++ needs at least 4GB.

**Comment by la-ninpre** [comment]
> Do you have enough RAM on the server? g++ needs at least 4GB.

Yes, I tried it with 16GB RAM. Same error.

**Comment by la-ninpre** [comment]
And similarly fails on real hardware, not virtualized.

**Comment by levlam** [comment]
I have just received the same error on OpenBSD 6.7. It seems that there is not enough RAM or something other for system tools to finish building and they silently create broken static libraries. To fix the issue, do this:
```
cd telegram-bot-api/td
php-7.2 SplitSource.php
cd ../build
cmake --build . --target install
cd ../..
ls -l telegram-bot-api/bin/telegram-bot-api*
```

**Comment by la-ninpre** [comment]
Oh, sure, it actually worked, thanks!
And on OpenBSD 6.8 too.

But it worked exactly in this order:
1. Clone repo as usual
2. `cd telegram-bot-api`
3. `mkdir build && cd build`
4. `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.. ..`
5. Then try to compile
    `cmake --build . --target install`
    and catch an error as described earlier
6. And only after that run `php-7.2 SplitSource.php` in `telegram-bot-api/td`
7. And, finally, recompile like in step 5.

**Comment by levlam** [comment]
@la-ninpre Yes, In the previous comment I expected that you already have a directory with failed build. See https://tdlib.github.io/telegram-bot-api/build.html?os=OpenBSD for full updated build instructions for OpenBSD.

**Comment by la-ninpre** [comment]
@levlam , okay, thanks!
