### ISSUE TITLE
[Question] send files >50MB

### ISSUE THREAD

**Issue by ponwork** [tdlib/telegram-bot-api#123]
### The question is how to properly use the feature to send the files >50MB

!!! Alert: probably noob question, sorry

I am using the following Python function to send the video file and it works well for both Telegram API server and for telegram-bot-api when the file is  less than 50MB: [sendVideo](https://core.telegram.org/bots/api#sendvideo)

note: it works for the first time only (after server and bot restart) and after that fails for the next tries, to be honest.

Example below:

```
def send_video(api_server_url, bot_token, chat_id, video):
    """ Function to send Telegram video message """

    try:
        videoFile = {'video': open(video, 'rb')}
    except OSError as error:
        print(f'[*] Error with video file:\n{error}\n')
        exit()

    url = f'{api_server_url}bot{bot_token}/sendVideo'
    payload = {'chat_id': chat_id}
    try:
        r = requests.post(url, data = payload, files=videoFile)
    except requests.exceptions.RequestException as error:
        print(f'[*] Connection error for Video sending:\n{error}\n')
        exit()

    return r
```

The problem is that even when I did a Logout  and set a Webhook via telegram-bot-api server for for my Bot I cannot send files >50MB via function above.

According to the [sendVideo manual](https://core.telegram.org/bots/api#sendvideo), there is an option to send a video not only as file but also as a

- file_id
- HTTP URL

I tried HTTP URL via the function below and it fails as well:

```
def send_video_url(api_server_url, bot_token, chat_id, file_server_url, videoFileName):
    """ Function to send Telegram video message via URL"""

    url = f'{api_server_url}bot{bot_token}/sendVideo'
    payload = {'chat_id': chat_id, 'video': f'{file_server_url}{videoFileName}'}
    try:
        r = requests.post(url, data = payload)
    except requests.exceptions.RequestException as error:
        print(f'[*] Connection error for Video sending:\n{error}\n')
        exit()

    return r
```
_where **{file_server_url}{videoFileName}** is the full URL for MP4 file that is reachable over the Internet and placed on the same server as telegram-bot-api._

As for the **file_id** I have no idea how to properly upload the file to the telegram-bot-api server's directory and get the file_id accordingly.

Please help

Thank you

**Comment by levlam** [comment]
See https://github.com/tdlib/telegram-bot-api#usage. You need to specify `--local` option to the local Bot API server.

**Comment by ponwork** [comment]
> See https://github.com/tdlib/telegram-bot-api#usage. You need to specify `--local` option to the local Bot API server.

I did it as a first step when run the API server.
How make telegram Bot to send the files?

Thank you

**Comment by levlam** [comment]
Check that `api_server_url` really points to a local Bot API server. Local Bot API server has no restrictions on the size of uploaded files regardless used options.

**Comment by ponwork** [comment]
> Check that `api_server_url` really points to a local Bot API server. Local Bot API server has no restrictions on the size of uploaded files regardless of used command-line options.

Yes it is. 
Maybe you can help me to find the API server's logs?
At the moment I have only 8082 port a a stat page info.
Maybe you can point me to the more efficient tool (debug?) for the server?

Any help will be much appreciated

**Comment by levlam** [comment]
See `--help` for ways to manage the Bot API server logs.

**Comment by VChernomYA** [comment]
[]()
