### ISSUE TITLE
Problem with some of videos when using `sendVideo`

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#127]
When using `sendVideo` for some of local videos the output in the client has wrong resolution, thumbnail and duration

![photo_2021-05-01_17-21-09](https://user-images.githubusercontent.com/53290883/116783016-a636d500-aaa1-11eb-8c38-66a166dec27c.jpg)

1. Download [this file ](https://drive.google.com/file/d/1PE4mgRTi36d1v6FwBXMCMvPA4nqnBSLP/view?usp=sharing)
2. curl request: 

```
curl -s -X POST "https://api.telegram.org/botTOKEN/sendVideo?chat_id=CHATiD" -F video="@Official Trailer.mp4"

```

**Comment by WaffleLapkin** [comment]
How did you solve the problem?

**Comment by foremtehan** [comment]
I did not and dont think they care about this https://github.com/irazasyed/telegram-bot-sdk/issues/13

**Comment by levlam** [comment]
`sendVideo` has parameters `duration`, `width`, `height` and `thumb`, which aren't redundant and must be specified.

**Comment by foremtehan** [comment]
@levlam can you explain why it's working for some of videos without using any optional params ?

**Comment by levlam** [comment]
@foremtehan It can work for some video files, which are less than 10 megabytes in size. Also, on some clients the correct preview should appear after the video is fully downloaded.

**Comment by asil004** [comment]
has anyone found a solution to this?

**Comment by levlam** [comment]
@asil004 https://github.com/tdlib/telegram-bot-api/issues/127#issuecomment-830705735

**Comment by asil004** [comment]
> @asil004 https://github.com/tdlib/telegram-bot-api/issues/127#issuecomment-830705735
![IMG_20231121_130904.jpg](https://github.com/tdlib/telegram-bot-api/assets/72306088/eabd3988-34cb-47f5-ba54-b9dd19f78a75)

even if I give all the parameters, it comes out like this

**Comment by levlam** [comment]
This doesn't look like a video with a correctly specified thumbnail. Note that
> The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320. Ignored if the file is not uploaded using multipart/form-data. Thumbnails can't be reused and can be only uploaded as a new file, so you can pass “attach://<file_attach_name>” if the thumbnail was uploaded using multipart/form-data under <file_attach_name>.

**Comment by asil004** [comment]
@levlam 
if it is less than 10 mb, you will be able to watch the video during the download, if the thumb is in the right format, then you need to download it first and then watch it. Is it possible to send files above 10mb as if they are below 10mb?
