### ISSUE TITLE
CMAKE build stucks - 

### ISSUE THREAD

**Issue by mahdi1325** [tdlib/telegram-bot-api#129]
When following the installing instructions generator for Linux, Other  (rpi 3) at running the command "cmake --build . --target install", this displays:
Scanning dependencies of target tdsqlite
[ 0%] Building C Object td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o
And the program freezes...(+1 hour)

**Comment by levlam** [comment]
You are likely have too few RAM available to build it on the device. You need to cross-compile it.

**Comment by mahdi1325** [comment]
> You are likely have too few RAM available to build it on the device. You need to cross-compile it.

What should I do?

**Comment by levlam** [comment]
You need to cross-compile it.

**Comment by mahdi1325** [comment]
I'm newbie 😩


I need guide

**Comment by levlam** [comment]
I can't help this that, but https://stackoverflow.com/questions/19162072/how-to-install-the-raspberry-pi-cross-compiler-on-my-linux-host-machine and similar articles likely can.
