### ISSUE TITLE
Momory leak

### ISSUE THREAD

**Issue by mnkblog** [tdlib/telegram-bot-api#131]
I used pm2 for better management and after 4 days it's now 4.2gb used memory.

definitely by increasing the number of bots it will be even higher, the question is why ?

It have to be a memory leak ...

**Comment by levlam** [comment]
You can check that there are no memory leaks using any memory profiler tool like address sanitizer or valgrind.

Bot API server doesn't have constant memory footprint though. There are a lot of cached data such as users and chats stored in memory. The data speeds up request sending and allows bots to avoid server-side flood limits on the long run. The memory growth speed is decreased over time with the maximum increase on the first day. You can restart server instance once a day or less often if you want to flush the cache.

**Comment by mnkblog** [comment]
You said "to avoid server-side flood limits on the long run. ".

It's interesting! what's that ?
how does it effect my bots performance ?

**Comment by levlam** [comment]
For example, to send a message to a chat you need much more data then a raw chat identifier. This data is loaded on the first request with a given `chat_id` and cached, so any future request can reuse the data without need for additional requests.

**Comment by mnkblog** [comment]
so why you don't store older chat data in storage except whole time remaining on the ram.

**Comment by levlam** [comment]
Because usage of persistent storage for that would be too slow.

**Comment by levlam** [comment]
Bot API server can have so big throutput that it wouldn't be able to launch and fill memory cache after restart for dozens minutes if a local cache on persistent storage is involved. The server would be completely unusable while the cache isn't warmed up, which is unacceptable.

Deleting unused for some time chat data from memory violates guarantees provided by TDLib and isn't possible now either.

**Comment by dzek69** [comment]
I guess if you want to setup this server for your own single bot that handles one message every few minutes then storage caching would be enough and even desired.

But I guess this is what Telegram uses on their own servers, that are full of load because single instance handles thousands of bots and their messages.

**Comment by levlam** [comment]
@dzek69
If you want bot to handle one message every few minutes then you would never have problems with Bot API server memory usage. The memory usage will be negligibly small even after months of continuous running.

If you get such a bot, which cache grows to 4GB in a few days, then its load is very high and local database will make it unacceptably slow, until all the data is loaded into disk cache (i.e. RAM).
