### ISSUE TITLE
low speed of robots

### ISSUE THREAD

**Issue by GoldExynos** [tdlib/telegram-bot-api#133]
Hi.
I've install telegram-bot-api on my server based on "Telegram Bot API server build instructions generator" part with clang compiler in /usr/local directory and run it with this command :

telegram-bot-api --api-id=... --api-hash=... --local --dir=/var/log/tg --max-webhook-connections=100000 --log=/var/log/tg/log.tg --max-connections=1000

(api id and api hash that i wroted is fake).
so then i changed the telegram api of the source of my bot (php) to the ip address of my server.
I loged out the bot with logOut method, too.
now some part of my bot work fast and some part have 1 ~ 2 second delay for responsing.
I tried to examine the source code and requests and i find out that the handling requests with sendmessage method that have short text are faster than longer one.
How can i fix it?
Is there any misconfiguration while running telegram-bot-api?

I use it on server with 3 Gb of ram and 3 core of cpu (3.07Ghz). 
operating system : ubuntu 18
webserver : apache

note that I don't use ssl with domain . I use ip address and port number for sending requests and setwebhook.

**Comment by levlam** [comment]
You can increase Bot API server log verbosity level to 3 to check, how long queries are handled.

**Comment by GoldExynos** [comment]
Hi again ;)
I checked the logs as you say and i extract the query info of one simple sendmessage request.
Info:

[ 3][t 0][1620752485.568361759][Query.cpp:44][!HttpConnection]  QUERY: create [ptr:0x56387bea08b0][bot_____MYTOKEN____][time:  6569.0ns][method:               getme]
[ 3][t 0][1620752485.568476915][Query.cpp:71][#___SOMEID___][!Client/___MYTOKEN___]  QUERY: got ok [ptr:0x56387bea08b0][text:{"ok":true,"result":{"id":___SOMEID___,"is_bot":true,"first_name":"___BOTNAME___","username":"___BOTUSERNAME___","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}]
[ 2][t 0][1620752486.125062704][Stats.h:58]  CPU usage: 0.252313%
[ 3][t 0][1620752486.732761144][Query.cpp:44][!HttpConnection]  QUERY: create [ptr:0x56387bea08b0][bot___BOTTOKEN___][time:    10.4us][method:         sendmessage]{[chat_id;___SOMEID___], [text;___SOMETHING___], [parse_mode;html], [reply_to_message_id;], [reply_markup;{"keyboard":[[{"text":"___SOMETHING___"}],[{"text":"___SOMETHING___"},{"text":"___SOMETHING___"}],[{"text":"___SOMETHING___"},{"text":"___SOMETHING___"}],[{"text":"___SOMETHING___"},{"text":"___SOMETHING___"}],[{"text":"___SOMETHING___"}]],"resize_keyboard":false}]}

I hope that you can help me to fix my problem♥️☹️

**Comment by levlam** [comment]
You didn't show when the `sendmessage` request ended, so its durarion can't be seen.

**Comment by GoldExynos** [comment]
> You didn't show when the `sendmessage` request ended, so its durarion can't be seen.

Oh I'm sorry.

This is the end of the query:

[ 3][t 0][1620985629.883855342][UpdatesManager.cpp:358][#1872421883][!net_actor]  Update pts from 874 to 875 from process pending updates fast path
[ 3][t 0][1620985629.883996486][Query.cpp:71][#1872421883][!Client/1872421883:AAElS3lmssedQhr3qbtJ-AdT33NJbzbHw5Q]  QUERY: got ok [ptr:0x555dd237f270][text:{"ok":true,"result":{"message_id":864,"from":{"id":ROBOTUSERID,"is_bot":true,"first_name":"ROBOTNAME","username":"ROBOTUSER"},"chat":{"id":USERID,"first_name":"\ud835\udfd4$\ud835\udc07","username":"USERNAME","type":"private"},"date":1620985629,"text":"___SOMETEXT___","entities":[{"offset":163,"length":12,"type":"mention"}]}}]
[ 2][t 0][1620985630.699433088][Stats.h:58]  CPU usage: 0.505902%
[ 2][t 0][1620985631.700266599][Stats.h:58]  CPU usage: 0.404313%
[ 2][t 0][1620985632.699889659][Stats.h:58]  CPU usage: 0.336889%
[ 2][t 0][1620985633.699250221][Stats.h:58]  CPU usage: 0.288878%
[ 2][t 0][1620985634.699611663][Stats.h:58]  CPU usage: 0.252525%
[ 2][t 0][1620985635.699828624][Stats.h:58]  CPU usage: 0.336574%
[ 2][t 0][1620985636.699641942][Stats.h:58]  CPU usage: 0.302826%

If you want you can show me the way that I can send full log file to you in private.(something like telegram ID or e-mail)

I will really appreciate your help.♥️

**Comment by levlam** [comment]
Now the log misses beginning of the query. In the shown part of the log there are no any notable delays.

**Comment by GoldExynos** [comment]
[tg.log](https://github.com/tdlib/telegram-bot-api/files/6479208/tg.log)


> Now the log misses beginning of the query. In the shown part of the log there are no any notable delays.

ok. this is the full log file that you can see all info from it.
I hope it colud be helpful :(

**Comment by GoldExynos** [comment]
[tg(1).log](https://github.com/tdlib/telegram-bot-api/files/6479318/tg.1.log)


> Now the log misses beginning of the query. In the shown part of the log there are no any notable delays.

ok. I uploaded full log file for you. I hope it could be helpful.
I really need to fix the problem :(
(I deleted important info from log file, but I really appreciate it if you delete it after you checked it.♥️♥️

**Comment by levlam** [comment]
The message was sent in 33 millisecond. This looks like a ping time from you Bot API server to the Telegram DC.

**Comment by GoldExynos** [comment]
> The message was sent in 33 millisecond. This looks like a ping time from you Bot API server to the Telegram DC.

So why it take time to respond any command of bots that have return long text? I don't know how but I heard that there is some special configuration that can fix this problem.🤔

**Comment by levlam** [comment]
I don't see any problem in the log. The query was answered in the fastest possible way.

**Comment by GoldExynos** [comment]
> I don't see any problem in the log. The query was answered in the fastest possible way.

That's weired. Do you think it could be the problem of my webserver config? I mean apache.🤔

**Comment by levlam** [comment]
I don't know.

**Comment by GoldExynos** [comment]
> I don't know.

I fixed the problem by set the ip:port under domain that use cloudflare infrastructure for connection between server and domain.😁

Now I have just one simple question:

Which compiler is better to use while installing and does it have any affect on the speed and performance?

and How can I install telegram-bot-api with docker?

**Comment by levlam** [comment]
> Which compiler is better to use while installing and does it have any affect on the speed and performance?

There will be no significant difference.

>  How can I install telegram-bot-api with docker?

There are a lot of third-party Docker images.

**Comment by warshell** [comment]
> I fixed the problem by set the ip:port under domain that use cloudflare infrastructure for connection between server and domain.

hello can you explain ; how to do this ? thanks
