### ISSUE TITLE
Add (inline_query_placeholder) in (User) object, returned only in getMe

### ISSUE THREAD

**Issue by Muaath5** [tdlib/telegram-bot-api#134]
I suggest add `inline_query_placeholder` in `User` object, And returned only in `getMe` method.
It should be returned in JSON object when `supports_inline_queries == true`.

## Use cases
Useful for **third-party creator bots**, It can be in the settings, For inline bots.

<details>
<summary><b>Programming note</b></summary>

**I can implement this, But I need a permission to do that, After permission I'll send a pull request.**
Files will be edited in my pull request:
1. [`Client.cpp`](https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.cpp) ([`JsonUser` class](https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.cpp#L330), And [`add_user` method](https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.cpp#L8107))
2. [`Client.h`](https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.h) ([`UserInfo` class](https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.h#L558))
</details>

**Comment by levlam** [comment]
It can be added, but how is it useful? It is just a text and bot's functionality doesn't depend on it, nor the placeholder can be changed by the bot itself.

**Comment by vadimgrigoryevv** [comment]
,hard tema

**Comment by levlam** [comment]
This field wasn't added intentinally, because it doesn't affect bot's functionality and bots can't interact with it in any way. There are no reasons to provide this field through API.
