### ISSUE TITLE
Add authentication via HTTP header

### ISSUE THREAD

**Issue by KnorpelSenf** [tdlib/telegram-bot-api#138]
## Problem Description

While it's pretty simple to have the token in the URL (easy to get started with bots), it has a number of drawbacks. Most importantly, the token will [accidentally be written to logs](https://t.me/grammyjs/5043) if the log output of bots and can easily be revealed. Some bot frameworks even go so far as to [sanitize log output](https://github.com/telegraf/telegraf/blob/5588e0599769377468828f657f7125acbb7870ac/src/core/network/client.ts#L278) to mitigate this issue.

In fact, token leaks are so common that the [@BotTalk](https://t.me/bottalk) group regularly sees this sticker. [1] This is not solely related to logs, but it still happens often enough. (Also it is a bit annoying that bot logs contain confidential data, because they now have to be kept secure, or no requests can be logged in detail.)

## Desired Solution

It would be nice to be able to authenticate requests via HTTP header (e.g. via `Authorization: Bearer <token>` or via `X-Telegram-Bot-Api: <token>`) as an additional way of sending the token.

---

[1]
![image](https://user-images.githubusercontent.com/12952387/119199181-ec70ca00-ba8a-11eb-9a7b-b42e8af4a598.png)

**Comment by levlam** [comment]
Tokens leak because of carelessness of the bot owners. The proposed measures are very unlikely to change that.

Between, bot logs need to be kept private by default and mentioned "requests details" often need even more protection then the bot's token itself, which can be replaced in no time.
