### ISSUE TITLE
Undocummented api methods

### ISSUE THREAD

**Issue by JrooTJunior** [tdlib/telegram-bot-api#14]
I see in the server code undocummented methods - sendcustomrequest and answercusomquery

https://github.com/tdlib/telegram-bot-api/blob/551103b8cda61ef548b1f7673208fbd1acee7fa4/telegram-bot-api/Client.cpp#L245
https://github.com/tdlib/telegram-bot-api/blob/551103b8cda61ef548b1f7673208fbd1acee7fa4/telegram-bot-api/Client.cpp#L246

What is it? I dont see any information about how this methods can be used

**Comment by puppy0cam** [comment]
These methods are undocumented because they are intended for internal use. Not even the client API has documentation for it I believe.

**Comment by levlam** [comment]
@puppy0cam's answer is absolutely correct. The methods are for internal use and some testing without Bot API updates. They can be used only by a restricted list of bots.

**Comment by JrooTJunior** [comment]
Thanks
