### ISSUE TITLE
Add `offset` and `limit` parameters to `getFile` method

### ISSUE THREAD

**Issue by aofei** [tdlib/telegram-bot-api#141]
Currently, there is no way to download files larger than `20MB` through the [`getFile`](https://core.telegram.org/bots/api#getfile) method, except by using a local Bot API server. That's because the Bot API server needs to retrieve the entire file to its local disk before that file can be provided to users for download via the [`File.file_path`](https://core.telegram.org/bots/api#file), so the `20MB` limit is totally reasonable.

But it's undeniable that there is indeed a demand for downloading files over `20MB` in size. And yes, I know that this problem can be solved by using a local Bot API server, in fact I already did that (I've fallen in love with the local Bot API server since it was released ❤️). The truth is that even using a local Bot API server has some problems. For example, someone wants to get `1KB` part of a `1GB` file, there's no choice but to download the entire `1GB` file to the local Bot API server's disk first and then read that `1KB` of it. To be honest, this is an avoidable pressure on the bandwidth of Telegram DC and the local Bot API server.

Fortunately, these problems are easy to solve. In fact the perfect [`upload.getFile`](https://core.telegram.org/method/upload.getFile) method has already solved them for us by providing the `offset` and `limit` parameters.

Therefore, I would like to propose to add support for the `offset` and `limit` parameters to the [`getFile`](https://core.telegram.org/bots/api#getfile) method, which solves the existing problems without breaking compatibility.

**Comment by levlam** [comment]
"For example, someone wants to get 1KB part of a 1GB file," Why a bot may ever need this?

**Comment by aofei** [comment]
> "For example, someone wants to get 1KB part of a 1GB file," Why a bot may ever need this?

Maybe read a part of a zip file? I just gave an example.

And, thanks for the quick response! ❤️

**Comment by levlam** [comment]
Despite this is possible, I can't see which bot may need this.

And even these parameters are added, this wouldn't change restriction on the *total* file size at api.telegram.org.

**Comment by aofei** [comment]
I just submitted this proposal because I thought it might help some people too.

And, to be honest, I didn't propose to lift the total size limit for downloading files via [api.telegram.org](https://api.telegram.org) (even if it's possible).  Because since this awesome local Bot API server project was open sourced, I've dived into it and never used [api.telegram.org](https://api.telegram.org) again.

Sometimes there is really no need to download an entire file to the local disk just because someone wants to read a part of it. If the Bot API server is opened to multiple bots, those [`getFile`](https://core.telegram.org/bots/api#getfile) requests may quickly cause the server's disk to fill up, even if there's a cron job to clean up idle files. Well, not every Bot API server's disk is as plenty as [api.telegram.org](https://api.telegram.org). With partial get support, bots can get only the parts they need, which can **reduce the bandwidth pressure** of the Bot API server and save its disk.

I have implemented partial get by using [`td`](https://github.com/tdlib/td) in my own project, but I really hope that [`telegram-bot-api`](https://github.com/tdlib/telegram-bot-api) can also support this feature.

But in any case, this is just a proposal. 😄

**Comment by ammarfaizi2** [comment]
I support the proposal. I hope it gets merged to the official repo.

**Comment by levlam** [comment]
@ammarfaizi2 How do you want to use this?

**Comment by itsMoji** [comment]
Can we use this to download the file directly to the nginx response with `Accept-Ranges` header and solves the timeout problem on downloading large files?
Something like [downloadToResponse](https://github.com/danog/MadelineProto/blob/ba18d2caa5895ac553b1914871213bb1f5a71a1d/src/danog/MadelineProto/MTProtoTools/FilesLogic.php#L150) on MadelineProto?

**Comment by aofei** [comment]
@itsMoji Usually, with `offset` and `limit` support, people can find a way to serve `Range` requests. But it's not quite like the [downloadToResponse](https://github.com/danog/MadelineProto/blob/ba18d2caa5895ac553b1914871213bb1f5a71a1d/src/danog/MadelineProto/MTProtoTools/FilesLogic.php#L150) you mentioned, because [`getFile`](https://core.telegram.org/bots/api#getfile) will still download the file (or part of it) to the Bot API server's local disk before it can be provided to read via the [`File.file_path`](https://core.telegram.org/bots/api#file) (this is by design). The [downloadToResponse](https://github.com/danog/MadelineProto/blob/ba18d2caa5895ac553b1914871213bb1f5a71a1d/src/danog/MadelineProto/MTProtoTools/FilesLogic.php#L150) does that in streaming.

**Comment by levlam** [comment]
@itsMoji No, even these parameters are added, `offset` + `limit` will be limited by 20 MB for api.telegram.org.

**Comment by IRGC** [comment]
@levlam basically we want to download large file in 20mb chunks 🤣😂

**Comment by levlam** [comment]
@IRGC This isn't related in any way to offset and limit in `getFile`.
