### ISSUE TITLE
Server crashes after sending request through bot

### ISSUE THREAD

**Issue by Sakib0194** [tdlib/telegram-bot-api#142]
After starting the server on local and sending a request through the bot, the server instantly crashes. I am using Linux, Manjaro.
Getting the following error messages

`LOG:00000de0:  [ 3][t 0][1622847221.385524988][Td.cpp:4542][#1140389723][!Td][&td_requests]	Sending error for request 17179869440: error { code = 400 message = "Can't init database in the directory "./1140389723:AAFWcLi0X1cuudMx60o1XZsQ5ewF1v46FTc/": [PosixError : Invalid argument : 22 : Can't create directory "./1140389723:AAFWcLi0X1cuudMx60o1XZsQ5ewF1v46FTc"]" } 
LOG:00000f50:  [ 2][t 0][1622847221.385538101][Client.cpp:2475][#1140389723][!Client/1140389723:AAFWcLi0X1cuudMx60o1XZsQ5ewF1v46FTc]	Failed to initialize due to error { code = 400 message = "Can't init database in the directory "./1140389723:AAFWcLi0X1cuudMx60o1XZsQ5ewF1v46FTc/": [PosixError : Invalid argument : 22 : Can't create directory "./1140389723:AAFWcLi0X1cuudMx60o1XZsQ5ewF1v46FTc"]" }`

**Comment by levlam** [comment]
It says exactly, why the server can't start. It can't create a directory in the current working directory with the name "1140389723:AAFWcLi0X1cuudMx60o1XZsQ5ewF1v46FTc". You need to check that the server's working directory is writable and underlying file system supports colons in file names. Between, this is your bots token, so you need to revoke it now.

**Comment by Sakib0194** [comment]
Thank you for the response, yes I am aware that is my bot token. But I don't have any restriction set to prevent files from writing/reading or create a directory. Is it by any chance trying to create a directory starting with "./"? I have tried everything I could find already

**Comment by Sakib0194** [comment]
Thank you for your response, yes I am aware that it is my bot token. I realized after your reply that the colon is the problem. I had to reinstall to /usr/local instead of some other directory. Working fine after installing there. Appreciate the assist.

**Comment by levlam** [comment]
What is your file system, which doesn't support colon in filenames? All modern Linux filesystems should allow it and on Windows with NTFS it is replaced with '~'.

**Comment by Sakib0194** [comment]
I was using a mounted NTFS partition in my Linux system. I didn't know that NTFS doesn't support colons in folder names.

**Comment by levlam** [comment]
Thanks. It seems that the server needs to detect NTFS and FAT32 in runtime instead of expecting that noone uses writeable NTFS partitions on Linux.

**Comment by levlam** [comment]
This was fixed in Bot API 5.3. Now server automatically detects, whether underlying file system supports colons in directory names.
