### ISSUE TITLE
Timeout in api.telegram.org

### ISSUE THREAD

**Issue by AYMENJD** [tdlib/telegram-bot-api#146]
Hello!
I am making small bot-api server based on MTProto. 
In some cases i use api.telegram.org/getme.
When i revoke token and re-call ```api.telegram.org/getme``` its hangs my code i thought i have a problem with my code but when i check logs i found that its hangs on ``` starting new https connection to api.telegram.org/bot../getme``` after some seconds its returns ```api.telegram.org/bot../getme 504 Gateway Timeout``` .
Means if i have new Token and call api.telegram.org in the first request i get ```504 Gateway Timeout``` in the second request i get ```200 OK```

Sorry for the bad explanation 😅

**Comment by levlam** [comment]
How is api.telegram.org related to bot-api server based on MTProto?

**Comment by AYMENJD** [comment]
Is not related i am just mention where i use api.telegram.org

**Comment by AYMENJD** [comment]
![Screenshot_20210613_234220](https://user-images.githubusercontent.com/53928879/121821341-1a6bb780-cca1-11eb-9d37-7fe1288f93ff.jpg)

I think you know what i mean ?

This is from my browser when i open regular url https://api.telegram.org/bot.../getme

**Comment by levlam** [comment]
This is possible some time after revoking token of a very high-loaded bot. The only way to avoid this is not to revoke the token. Why are you doing this?

**Comment by AYMENJD** [comment]
Its new bot for testing purpose no load or anything just me and him 😅, i am making my own bot-api server and i am acting like regular user that revoke his bot token and i found this issue in https://api.telegram.org

**Comment by levlam** [comment]
Could you reproduce it on a local Bot API server?

**Comment by AYMENJD** [comment]
I tried now and its works fine, its just on api.telegram.org i think

**Comment by levlam** [comment]
This shouldn't be possible, because the server is the same. The only difference that this local Bot API server you will receive browser timeout instead of a JSON error.

Could you send to @tdlib_bot in Telegam bot's username, exact (up to 1 second) time of bot token revoking, exact time of `getMe` request and the exact request URL?

**Comment by AYMENJD** [comment]
Hmm, i retry now and its works fine, i don't know how but i will continue using api.telegram.org if i get the same error i will report you on @tdlib_bot

Sorry for disturbing you

**Comment by levlam** [comment]
Still send the bot username to @tdlib_bot.

**Comment by AYMENJD** [comment]
Ok

**Comment by levlam** [comment]
This looks like a temporary network problem and not an issue with the Bot API server.

**Comment by AYMENJD** [comment]
My network?

**Comment by levlam** [comment]
No.

**Comment by AYMENJD** [comment]
Another question, if i have a bot-api-server and i use my app_id to run it and i make it public then some users use it for spam or anything that Contrasted with the terms and conditions of telegram, me will get ban because i host that bot-api-server or the bot that used?

**Comment by levlam** [comment]
Bots can't spam by definition. If they violate terms of services, they are banned. This shouldn't affect the server itself.

**Comment by AYMENJD** [comment]
TnQ Dear Ali have nice day ❤️
