### ISSUE TITLE
Add ```retry_on_fail``` to ```setWebHook```

### ISSUE THREAD

**Issue by AYMENJD** [tdlib/telegram-bot-api#147]
Hey!

i have suggestion to ADD parameter ```retry_on_fail``` with Bool value to ```setWebHook```
if the entered value is ```false``` telegram should not send the update again if the server response 500+ Error code

if my server services down for some hour and back Telegram will send pending updates and will cause new load for my server and my server will go down again .

actually my server down two times because of this, i have a bot with 40K groups and its has a load already .

**Comment by IRGC** [comment]
Good feature I always wanted it @levlam please add this.

**Comment by levlam** [comment]
No, the update delivery must be reliable. It is completely useless to have unreliable update delivery system. If you want to drop all pending updates, you can always pass `drop_pending_updates = True` to `setWebhook`.

**Comment by IRGC** [comment]
You can make it optional and by default all updates to be retried.

**Comment by levlam** [comment]
No, there should be no options, which break basic fucntionality, like "allow_http" or this one.
