### ISSUE TITLE
Why is impossible to upload a big file?

### ISSUE THREAD

**Issue by pbanov** [tdlib/telegram-bot-api#150]
Why dont correct use method sendVideo? ... /sendVideo?chat_id=777&video=https://video.com/file.mp4? filesize over 50 Mb.
Bad Request: wrong file identifier/HTTP URL specified. 
--local option activated.
I want to upload direct url, ex. http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
Local file (file:///...) uploaded successfully.

**Comment by levlam** [comment]
This wouldn't work, because in local mode you can "**Upload** files up to 2000 MB". Sending a file using its HTTP URL is not a file uploading. Such files are downloaded by the Telegram servers from the specified URL and there is no way `--local` flag can change limits on their size.
