### ISSUE TITLE
Tdlib vs Bot-API

### ISSUE THREAD

**Issue by AYMENJD** [tdlib/telegram-bot-api#151]
Hi, I have a question about https://api.telegram.org also tdlib.

I have my high loaded bot `100 update` per second 
i am sure in weekend 100+ update per second 
Its group management bot 

I want to rebuild the bot source but I'm confused what to use `Tdlib` or `api.telegram.org` webhook, Who better?

If i use `Tdlib` will use more memory and more disk space (i try to login using my bot in the first 5 minutes db.sqlite gets 55M size) 

If i use `api.telegram.org` will be lot easier dealing with updates but i will lose access to some methods that not available on Bot-API like get user information by username etc and i need that .

I can use two instance `api.telegram.org` and `MTProto Client` (for other methods not available on Bot-API) I don't think is the right way to use that.

@levlam If it was you, what would you choose and why?

**Comment by levlam** [comment]
> If i use Tdlib will use more memory and more disk space (i try to login using my bot in the first 5 minutes db.sqlite gets 55M size)

You need to disable all databases in `setTdlibParameters` to have the same memory usage as in the Bot API server.

> get user information by username etc and i need that .

This request is very strictly flood-limited, so you will not be able to use in a bot with 100+ updates per second. You will exceed daily limit within 2 seconds. Instead, you can store correspondence username->user_id on the bot's side.

> I can use two instance api.telegram.org and MTProto Client (for other methods not available on Bot-API) I don't think is the right way to use that.

Bots aren't guaranteed to receive all updates if they have more than one session. This is especially true for high-loaded bots.

> If it was you, what would you choose and why?

I would use api.telegram.org and changed bot's functionality to use only available methods. For example, using a local database.

**Comment by AYMENJD** [comment]
Great answer, WebHook or Getupdates?
also webhook has limit right? means it can send 100 update per second?

**Comment by levlam** [comment]
> also webhook has limit right? means it can send 100 update per second?

No. Webhook can send up to 100 updates simultaneously, which is exactly the same as for `getUpdates`. If updates are processed in 10 ms (including ping time), then you can receive up to 10000 updates per second.

> WebHook or Getupdates?

Whatever you prefer.

**Comment by IRGC** [comment]
@levlam for 10ms we will need to buy server in datacenter where telegram servers are running. 😏

**Comment by AYMENJD** [comment]
> 
> 
> > also webhook has limit right? means it can send 100 update per second?
> 
> No. Webhook can send up to 100 updates simultaneously, which is exactly the same as for `getUpdates`. If updates are processed in 10 ms (including ping time), then you can receive up to 10000 updates per second.
> 
> > WebHook or Getupdates?
> 
> Whatever you prefer.

very good!
any other tips for high-loaded bot? if no TnQ for your time you can close this github issues

**Comment by AYMENJD** [comment]
> 
> 
> @levlam for 10ms we will need to buy server in datacenter where telegram servers are running. 😏

<img width="481" alt="Screenshot 2021-07-06" src="https://user-images.githubusercontent.com/53928879/124641221-1e04ef80-de97-11eb-9967-612cd9089e25.png">

not too far from durov's office 😂

**Comment by IRGC** [comment]
impressive latency. where is this server from?

**Comment by AYMENJD** [comment]
> impressive latency. where is this server from?

NL, Amsterdam server

**Comment by IRGC** [comment]
i meant to ask service provider name 😏

**Comment by AYMENJD** [comment]
[ServerSpace](https://serverspace.us/ref/292908) , its good server but the bad thing is bandwidth speed is too low 50MB maybe your home network speed fast then the server

**Comment by levlam** [comment]
@IRGC
> for 10ms we will need to buy server in datacenter where telegram servers are running. 😏

No, It can be up to ~1500 kilometeres away.

**Comment by levlam** [comment]
> any other tips for high-loaded bot?

1. Do all network requests asychronously.
2. If webhook is used, answer it as soon as possible, avoiding synchronous request to any API, including Bot API, before that.
3. Don't try to forward all incoming messages to a Telegram chat or log all errors in a Telegram chat (especially, errors about sending messages to the chat),

These seems to be the most common pitfalls.

**Comment by AYMENJD** [comment]
> > any other tips for high-loaded bot?
> 
> 1. Do all network requests asychronously.
> 2. If webhook is used, answer it as soon as possible, avoiding synchronous request to any API, including Bot API, before that.
> 3. Don't try to forward all incoming messages to a Telegram chat or log all errors in a Telegram chat (especially, errors about sending messages to the chat),
> 
> These seems to be the most common pitfalls.

useful informations thanks.
Bot-API has its own limitations ? Then MTPROTO limits?

**Comment by levlam** [comment]
It would be useless to have flood-limits on the Bot API side.

**Comment by AYMENJD** [comment]
perfect, this issue has good questions and answers to Bot-API 👍❤

have great day dear ALI .
