### ISSUE TITLE
Missing _Optional._ in documentation

### ISSUE THREAD

**Issue by WaffleLapkin** [tdlib/telegram-bot-api#152]
Current documentation (https://core.telegram.org/bots/api, [archived link], API version 5.3) is misleading about `ChatMember`.
- `custom_title` of `ChatMemberOwner` and `ChatMemberAdministrator`
- `can_edit_messages` and `can_post_messages` of `ChatMemberAdministrator`
  > channels only
- `can_pin_messages` of `ChatMemberAdministrator`
  > groups and supergroups only

These fields are _optional_ (i.e. they can be omitted by the bot API) but not marked as such.

[archived link]: https://web.archive.org/web/20210626142851/https://core.telegram.org/bots/api#chatmember

**Comment by levlam** [comment]
Thanks. Fixed.

**Comment by karb0f0s** [comment]
Same rules might apply to [ChatMemberRestricted](https://core.telegram.org/bots/api#chatmemberrestricted):



Field | Type | Description
-- | -- | --
can_pin_messages | Boolean | True, if the user is allowed to pin messages; **groups and supergroups only**

**Comment by levlam** [comment]
@karb0f0s No, this field is always available. The note is useless, because restricted users can be only in supergroups.
