### ISSUE TITLE
Error when building!

### ISSUE THREAD

**Issue by osofem** [tdlib/telegram-bot-api#153]
I got the below errors when I run the `cmake --build . --target install --config Release`. Everything up to this point runs smoothly.

I am on Windows 10 x64.

tdutils.lib(crypto.obj) : error LNK2019: unresolved external symbol crc32 referenced in function "unsigned int __cdecl
td::crc32(class td::Slice)" (?crc32@td@@YAIVSlice@1@@Z) [C:\Users\myname\tgBotServer\telegram-bot-api\build\tele
gram-bot-api.vcxproj]

tdutils.lib(Gzip.obj) : error LNK2019: unresolved external symbol deflate referenced in function "public: class td::Res
ult<enum td::Gzip::State> __cdecl td::Gzip::run(void)" (?run@Gzip@td@@QEAA?AV?$Result@W4State@Gzip@td@@@2@XZ) [C:\Users
\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.vcxproj]

tdutils.lib(Gzip.obj) : error LNK2019: unresolved external symbol deflateEnd referenced in function "public: __cdecl td
::Gzip::~Gzip(void)" (??1Gzip@td@@QEAA@XZ) [C:\Users\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.
vcxproj]

tdutils.lib(Gzip.obj) : error LNK2019: unresolved external symbol inflate referenced in function "public: class td::Res
ult<enum td::Gzip::State> __cdecl td::Gzip::run(void)" (?run@Gzip@td@@QEAA?AV?$Result@W4State@Gzip@td@@@2@XZ) [C:\Users
\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.vcxproj]

tdutils.lib(Gzip.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function "public: __cdecl td
::Gzip::~Gzip(void)" (??1Gzip@td@@QEAA@XZ) [C:\Users\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.
vcxproj]

tdutils.lib(Gzip.obj) : error LNK2019: unresolved external symbol deflateInit2_ referenced in function "public: class t
d::Status __cdecl td::Gzip::init_encode(void)" (?init_encode@Gzip@td@@QEAA?AVStatus@2@XZ) [C:\Users\myname\tgBot
Server\telegram-bot-api\build\telegram-bot-api.vcxproj]

tdutils.lib(Gzip.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function "public: class t
d::Status __cdecl td::Gzip::init_decode(void)" (?init_decode@Gzip@td@@QEAA?AVStatus@2@XZ) [C:\Users\myname\tgBot
Server\telegram-bot-api\build\telegram-bot-api.vcxproj]

C:\Program Files (x86)\GnuWin32\lib\zlib.lib : warning LNK4272: library machine type 'x86' conflicts with target machin
e type 'x64' [C:\Users\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.vcxproj]

C:\Users\oso.oluwafemi\tgBotServer\telegram-bot-api\build\Release\telegram-bot-api.exe : fatal error LNK1120: 7 unresol
ved externals [C:\Users\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.vcxproj]

**Comment by levlam** [comment]
```
C:\Program Files (x86)\GnuWin32\lib\zlib.lib : warning LNK4272: library machine type 'x86' conflicts with target machin
e type 'x64' [C:\Users\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.vcxproj]
```
Do use the latest `vcpkg` version and correctly specified its toolchain? Try from scratch using the build instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Windows.

**Comment by osofem** [comment]
> 
> 
> ```
> C:\Program Files (x86)\GnuWin32\lib\zlib.lib : warning LNK4272: library machine type 'x86' conflicts with target machin
> e type 'x64' [C:\Users\myname\tgBotServer\telegram-bot-api\build\telegram-bot-api.vcxproj]
> ```
> 
> Do use the latest `vcpkg` version and correctly specified its toolchain? Try from scratch using the build instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Windows.

I actually used instructions from that link. I used `git clone https://github.com/Microsoft/vcpkg.git` for `vcpkg`

**Comment by levlam** [comment]
If vcpkg toolchain is used, CMake should find zlib in the `vcpkg` directory and not in `C:\Program Files (x86)\GnuWin32\lib\zlib.lib`. 

If CMake still finds wrong zlib, then you can manually edit CMakeCache.txt file and place there a correct path to zlib shared library and include directory.

**Comment by osofem** [comment]
> 
> 
> If vcpkg toolchain is used, CMake should find zlib in the `vcpkg` directory and not in `C:\Program Files (x86)\GnuWin32\lib\zlib.lib`.
> 
> If CMake still finds wrong zlib, then you can manually edit CMakeCache.txt file and place there a correct path to zlib shared library and include directory.

This is actually weird, zlib is not getting installed via `./vcpkg.exe install openssl:x64-windows zlib:x64-windows` line even through not error is thrown. I will try installing zlib secretly and retry from the top and revert
