### ISSUE TITLE
How to login bot to local bot server

### ISSUE THREAD

**Issue by slowworks** [tdlib/telegram-bot-api#154]
Hey I already Logout bot from api.telegram.org but I don't know how to login bot to local bot server

**Comment by ihoru** [comment]
Simply make a request to your local bot API

**Comment by AYMENJD** [comment]
> Hey I already Logout bot from api.telegram.org but I don't know how to login bot to local bot server

http://your-ip:your-port/botToken/getupdates 

just change the ip and port and connect just like you request to http://api.telegram.org but changing the address to yours
