### ISSUE TITLE
`ChatMemberBanned` `until_date` is 0

### ISSUE THREAD

**Issue by karb0f0s** [tdlib/telegram-bot-api#155]
I receive `"until_date": 0` in `ChatMemberBanned` object for banned forever users, which doesn't make sense. Is this intentional behaviour? Could this field be optional for such occurrences?

**Comment by AYMENJD** [comment]
In `banChatMember` you can specify a unix time `until_date` when user ban will be lifted.
Its normal to get 0 in `until_date` if the user is banned forever, if not you will get a unix time.

**Comment by tuscen** [comment]
I think if a user in banned forever `until_date` should not be sent. So it's should be optional.

**Comment by AYMENJD** [comment]
> I think if a user in banned forever `until_date` should not be sent. So it should be optional.

How you can know that the user is banned forever?

**Comment by tuscen** [comment]
The field will be missing: so `undefined` in JavaScript case and `null` everywhere else.

**Comment by AYMENJD** [comment]
If `until_date` exists will not make any problem to your code, its something related to banned user information.

Maybe removing this field will broke others code, means in python you should first check if the key exists then access to it otherwise you will get KeyError, php you will get warnings.

In short Its presence does not harm, but its absence may harm.

**Comment by karb0f0s** [comment]
> > I think if a user in banned forever `until_date` should not be sent. So it should be optional.
> 
> How you can know that the user is banned forever?

it doesn't make sense, because 0 means that restrictions will be lifted on 1970-01-01, and in fact it's not true

**Comment by tuscen** [comment]
@AYMENJD Semantically it doesn't make sense since with permaban there is no date when the restriction will be removed from a user. It also harms semantics when you use domain types to represent it. In my case it's C# with `DateTime` type. What does it mean that a user receives `1970-01-01` date in there? It's nonsense.

**Comment by AYMENJD** [comment]
> @AYMENJD Semantically it doesn't make sense since with permaban there is no date when the restriction will be removed from a user. It also harms semantics when you use domain types to represent it. In my case it's C# with `DateTime` type. What does it mean that a user receives `1970-01-01` date in there? It's nonsense.

Hmm, thats right.
@levlam ?

**Comment by levlam** [comment]
This field can't be removed without breaking backward compatibility. Documentation for the field was improved to mention 0 as a special value of the field, meaning that the user is banned forever.

**Comment by kopax-polyconseil** [comment]
Hello, I am trying to the following:

```
    const res = await bot.banChatMember(CHAT_ID, USER_ID, {
      until_date: 0,
      revoke_messages: false,
    })
    console.log(res)
```

user get banned but can join in instantly.

**Comment by WaffleLapkin** [comment]
@kopax-polyconseil the time reported by the `ChatMemberBanned` is inconsistent with the `banChatMember`. From the documentation of the said method:
> Date when the user will be unbanned, unix time. If user is banned for more than 366 days or less than 30 seconds from the current time they are considered to be banned forever. Applied for supergroups and channels only.

You could argue that the date approximately 52 years ago is less than 30 seconds from the current time, but it seems from the point of bot API it's not. You should probably use a library to get the current date, add 367 days to it and convert it to Unix timestamp.

**Comment by levlam** [comment]
@WaffleLapkin
The date approximately 52 years ago is defintely less than 30 seconds ago, so the user is banned forever.

**Comment by WaffleLapkin** [comment]
@levlam so the behavior observed by @kopax-polyconseil is a bug in the API implementation?
