### ISSUE TITLE
Add more attributes to the Chat object

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#156]
Hi, there is some attributes present in the API which aren't shown here, but I think they would be helpful for bots:

- verified
- scam
- fake

- restricted
- restriction_reason

Only returning them when calling get_chat would be fine for me.

**Comment by levlam** [comment]
These attributes are only hints for users and apps. They aren't intended for automatic processing by bots and isn't sufficient for that.

**Comment by Poolitzer** [comment]
Hm? How can they not be intended, does it make a difference if a user can see it or the bot? Userbots can see them just fine ofc, so I dont understand the argumentation ofc.

Sufficient means what exactly? It would be great for bots imo to be able to check if the groups they have been added to e.g. have a scam label, so they can leave. Its good for the image (otherwise users might think the bots support whatever behaviour lead to the labels in the groups), and for the bot devs so they dont waste processing power on those chats if they dont want to.

**Comment by levlam** [comment]
If a bot see `scam` label then the chat is likely to be a scam chat, but if there is no such label, then this means nothing about the chat. There is no way `scam` field could help bots to avoid scam chats.

**Comment by WaffleLapkin** [comment]
@levlam it's still better than not having any information. Having a `scam` field may help avoid _some_ scam chats. Even though it won't help with all scam chats, it's strictly better.

Also, these fields may be useful for rendering group info in external resources. For example, a statistic bot can render a tick if the chat is `verified`.
