### ISSUE TITLE
Telegram Local Server shutting down when Ubuntu restart

### ISSUE THREAD

**Issue by muhammadyunusuz** [tdlib/telegram-bot-api#157]
I use Telegram Local Server. Per day i start telegram local server manually. Because, when ubuntu restart, telegram local server shutting down.  Is there a solution to this?

**Comment by muhammadyunusuz** [comment]
I found solution for this. I added crontab to Ubuntu. 

1. Write to console => `crontab -e`
2. Add this code at end of file => `@reboot /path/to/telegram-bot-api/bin/telegram --options`

**Comment by muhammadyunusuz** [comment]
This solution working incorrectly...

**Comment by IRGC** [comment]
Create a .service file

**Comment by muhammadyunusuz** [comment]
> Create a .service file

can you explain more?

**Comment by AYMENJD** [comment]
> > Create a .service file
> 
> can you explain more?

Search on Google how to create .service file on Ubuntu

**Comment by IRGC** [comment]
Example for nginx.service
https://www.nginx.com/resources/wiki/start/topics/examples/systemd/ 

Should be similar for telegram bot api
