### ISSUE TITLE
chat not found But user exists

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#159]
As of today i receiving this error for existing users: "Bad Request: chat not found"

the user using my bot for 8 month , he didnt deleted his account and i dont think he blocked my by bot because the error message is different , how is this possible ?

**Comment by levlam** [comment]
Did user wrote to the bot in private? Then this shouldn't happen if the `chat_id` is correct and you send request using the correct bot token.

**Comment by foremtehan** [comment]
the chat is private and i have the user_id in my database for about 8 month, just want to let to you know this.
