### ISSUE TITLE
Disable forwarding

### ISSUE THREAD

**Issue by zyadomer98** [tdlib/telegram-bot-api#161]
Is there any way to make a message with a bot so that cannot be forwarded?

**Comment by ihoru** [comment]
No

**Comment by zyadomer98** [comment]
So what is the purpose of "can_be_forwarded: true" in the update message object? I thought if it was there, it can be changed.

<img width="474" alt="Screen Shot 2021-07-27 at 11 13 29 AM" src="https://user-images.githubusercontent.com/78375592/127120186-7f67f101-65ed-4745-b64c-f9696e52e889.png">

**Comment by ksssomesh12** [comment]
> No

Maybe anytime in future?

**Comment by AYMENJD** [comment]
> 
> 
> So what is the purpose of "can_be_forwarded: true" in the update message object? I thought if it was there, it can be changed.
> 
> <img alt="Screen Shot 2021-07-27 at 11 13 29 AM" width="474" src="https://user-images.githubusercontent.com/78375592/127120186-7f67f101-65ed-4745-b64c-f9696e52e889.png">

its for service messages like changing Chat-title pin-messages etc.
You Can't forward that to any chat.

**Comment by zyadomer98** [comment]
Thanks

**Comment by zyadomer98** [comment]
It could be so great if telegram has added some features that enabled a user to post a video or anything else in a channel or group without worrying about the content to be shared or downloaded. There are many users that use telegram to share tutorial videos that you have to pay an amount to be able to watch it or use it. However, the user that purchases it can download it or forward it with his friends for free
