### ISSUE TITLE
“telegram.error.BadRequest: Entities_too_long” error when trying to send long markdown message. Max string length limited to 9500 chars?

### ISSUE THREAD

**Issue by XtremePwnership** [tdlib/telegram-bot-api#165]
This is the error i get when i try to send a long markdown message which has a ton of formatted hyperlinks in it:
```
context.bot.send_message(chat_id=update.effective_chat.id, text=longmsg, parse_mode="MARKDOWN")

#Output:
telegram.error.BadRequest: Entities_too_long
The actual message is hardly 500 characters long, but almost every word is hyperlinked which is making the string longmsg very long (>12k string length)
```
After a bit of testing I found out that string length passed to `bot.send_message` is limited to 9500 characters by Telegram API. But couldn't find this mentioned anywhere in the documentation. Please let me know if i'm mistaken.

**Comment by levlam** [comment]
This is a good approximation of the current limit on the total message entities size.

**Comment by XtremePwnership** [comment]
Thanks @levlam, noted.
