### ISSUE TITLE
[Documentation] All InputFile types should also accept String

### ISSUE THREAD

**Issue by Skayo** [tdlib/telegram-bot-api#167]
So, I just noticed that all methods that accept an `InputFile` type in the parameters, are also completely fine with a `String` in the form of `attach://<file_attach_name>`.
This is only described in `InputMediaPhoto`, `InputMediaVideo`, `InputMediaAnimation`, `InputMediaAudio` and `InputMediaDocument`, but also works for `sendPhoto`, `setChatPhoto`, `setWebhook`, and other methods that accept `InputFile` as type.

This seems to be either a mistake, or an undocumented feature.
I really hope it's the secondary, because I'm using this feature for uploading files in my Telegram Bot API client.
It just makes everything a lot simpler.

Here is a raw HTTP request which might be helpful for recreating this behaviour:
```
POST /bot<token>/setChatPhoto?chat_id=<chatid>&photo=attach://thisisanicefeature HTTP/2
Host: api.telegram.org
User-Agent: insomnia/2021.4.1
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
Accept: */*
Content-Length: 3815065

--X-INSOMNIA-BOUNDARY
Content-Disposition: form-data; name="thisisanicefeature"; filename="somepicture.png"
Content-Type: image/png

(3815065 bytes of image data...)
--X-INSOMNIA-BOUNDARY--
```

Feel free to ask any questions

**Comment by levlam** [comment]
This behavior is intentionally omitted from the documentation, because description of these fields is very long already and it is possible to use the corresponding field name as filename instead of "attach://<filename>".

There are no plans to remove this behavior ever, so you can use it.

**Comment by Bibo-Joshi** [comment]
Hi. I just found out that `attach://` does not seem to work for the `certificate` parameter of `setWebhook` - is that intended?
