### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by andrii-abramov-exa** [tdlib/telegram-bot-api#17]
It would be much easier to host Telegram Bot API server if it could be launched as a docker container.

Ideally, included with docker-compose example.

I am glad to help, but I don't have deep knowledge in C++ builds. Moreover, less knowledge in optimal C++ builds.
It would be awesome If you can at least point me to base image for building and base image for running.

**Comment by kolayne** [comment]
https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-722046986

**Comment by andrii-abramov-exa** [comment]
@kolayne my fail, thanks. Closing this.

**Comment by kolayne** [comment]
Btw, you might also want to join the discussion in #9

**Comment by levlam** [comment]
@andrii-abramov-exa You don't need any knowledge in C++ builds. Build instructions generator https://tdlib.github.io/telegram-bot-api/build.html covers the most popular cases.

**Comment by lukaszraczylo** [comment]
https://github.com/lukaszraczylo/tdlib-telegram-bot-api-docker - there's 54mb docker image if someone is looking for it ;)
