### ISSUE TITLE
Exact specification for `migrate_{to,from}_chat_id` update

### ISSUE THREAD

**Issue by Mr-Andersen** [tdlib/telegram-bot-api#170]
Hello. I am patching a telegram API client library, turns out when a group migrates to supergroup, the server sends two distinct updates, one with `migrate_to_chat_id` field, and another one with `migrate_from_chat_id`. The question is: is it possible that server sends (or might send in future) a single update with both fields? The documentation does not give a clear answer.

**Comment by levlam** [comment]
A message belongs to a fixed chat, It clearly can't belongs to both the old chat and the new chat,

**Comment by Mr-Andersen** [comment]
Thank you
