### ISSUE TITLE
Changing Dc of A telegram bot

### ISSUE THREAD

**Issue by anuragmaurya2105** [tdlib/telegram-bot-api#175]
How to change telegram bot dc?

**Comment by levlam** [comment]
This is not possible. Bot is bound to a fixed datacenter when it is created.

**Comment by AYMENJD** [comment]
> This is not possible. Bot is bound to a fixed datacenter when it is created.

Based on creator account dc?

**Comment by levlam** [comment]
Yes.

**Comment by dheiro** [comment]
DC is selected by phone number or IP when register?

**Comment by levlam** [comment]
DC of a bot coincides with DC of its creator. It is unspecified, how DC is chosen for users.
