### ISSUE TITLE
"After the bot is logged out, you can replace the address to which the bot sends requests"

### ISSUE THREAD

**Issue by antonydandrea** [tdlib/telegram-bot-api#176]
How/Where do I do this?

**Comment by levlam** [comment]
This is done in the source code of your bot.

**Comment by antonydandrea** [comment]
> This is done in the source code of your bot.

I'm still not understanding.

I created a bot using botfather. I have code that reads the server for new messages. But how do I link bot to server, after all that's what the logOut is for.

**Comment by levlam** [comment]
You are sending requests to api.telegram.org. To use a local Bot API server you need to send requests to the server instead of api.telegram.org.

**Comment by antonydandrea** [comment]
I know this, and I'm asking how?

**Comment by antonydandrea** [comment]
I called logOut(), got the OK and now I'm stuck with how to add the new one.

**Comment by levlam** [comment]
How do you send requests to api.telegram.org?

**Comment by antonydandrea** [comment]
Using the app I created in botfather

**Comment by levlam** [comment]
BotFather gets you only a token. How do you use it to send requests?

**Comment by antonydandrea** [comment]
It let me make a bot that starts a chat on the Telegram app, and i can send messages using that.

Then I have a script that calls an API to read the messages that I have sent.

**Comment by levlam** [comment]
Then you need to change the URL in the script to the URL of a local Bot API server or find a developer who will do that for you.

**Comment by antonydandrea** [comment]
I do not know if I am misunderstanding something completely here. But as I have said, it is the link between the Bot on the Telegram App and the Server that is not working because the documentation says "Run logOut" but doesn't say how to point to the new one.

The script that reads the messages is working fine.

**Comment by levlam** [comment]
There are no links between Telegram apps and the Bot API server. The Bot API server is an HTTP server which can be used instead of api,telegram.org to get updates and send request from the bot. You can try to get some help in the chat @BotTalk in Telegram. I think that people there can guide you.

**Comment by antonydandrea** [comment]
So once I have done "logOut", where are messages I am sending from the phone going?

**Comment by levlam** [comment]
Nothing changes. All messages sent to the bot are sent to Telegram servers. Bot API server provides an HTTP interface to get the messages from Telegram servers.

**Comment by antonydandrea** [comment]
I really appreciate your patience and help with this :-)
