### ISSUE TITLE
FR: Add a way to send multipart requests with json payload

### ISSUE THREAD

**Issue by WaffleLapkin** [tdlib/telegram-bot-api#177]
As noted in https://github.com/tdlib/telegram-bot-api/issues/167, you can already combine URL query string and `multipart/form-data` to send requests with files. I propose to add a similar way of combining json payload and `multipart/form-data`. This would make telegram bot API clients a lot easier to write, since it's generally easier to serialize to json, than to `multipart/form-data` or URL query string.

I imagine requests like this could work:
```http
POST /bot<token>/sendDocument HTTP/2
Host: api.telegram.org
user-agent: insomnia/2021.5.0
content-type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
accept: */*
content-length: 280

--X-INSOMNIA-BOUNDARY
Content-Disposition: form-data; name="payload"
{"chat_id": 1234567890,"document":"attach://file"}
--X-INSOMNIA-BOUNDARY
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain
(test file)
--X-INSOMNIA-BOUNDARY--
```

ie json payload is sent via `"payload"` form-data part

**Comment by levlam** [comment]
It is not possible to use a name like "payload", because this can be a valid name for a request parameter. Moreover, some methods already have such parameter, e.g. `sendInvoice`. This is a minor issue though.

The most important, I don't see, how this is "a lot easier" if you can already use the standard "application/x-www-form-urlencoded" content type and it's very easy to convert between this form and the proposed JSON. For example, in PHP it would be something like
```
  $json = '{"chat_id": 1234567890,"document":"attach://file"}';
  $parameters = array_map(fn($val) => (is_array($val) ? json_encode($val) : $val), json_decode($json, true));
  $urlencoded = http_build_query($parameters);
```
In real code it should be even simpler, because you should have $parameters in the first place.

**Comment by WaffleLapkin** [comment]
Well, it can be named differently, `payload` was just a placeholder.

While it may be true, that for PHP there isn't any difference, I still think that for other languages there may be a difference. 

I think it's a lot easier to use JSON for the following reasons:
1) It's more widespread. There are simply more serializers to JSON than to "application/x-www-form-urlencoded". And they are generally better too.
2) For methods like `sendMediaGroup` you'll still need JSON because some fields (namely `media`) is expected to be serialized using it. This probably means that you'll need to make your own serializer because there aren't any that use "application/x-www-form-urlencoded" for top-level and JSON for inner structures.

I have experience of writing libraries for Telegram bot API in both `kotlin` and `rust`, and I can confidentially say that writing serialization to `multipart/form-data`/"application/x-www-form-urlencoded" is a lot harder (and annoying) than using JSON.

**Comment by levlam** [comment]
I don't understand, why do you need to write the serialization to "multipart/form-data" at all? This should be provided by your HTTP client library, which can even use HTTP/2.0 under the hood. So you just provide the parameter names and values (some of which are JSON encoded) and everything other is done by the library.

**Comment by WaffleLapkin** [comment]
Because the HTTP client library usually only provides a builder or alike for creating "multipart/form-data" from key/value pairs. At the same time, it's desirable for requests to be classes/structures, so you need to convert said classes/structures to "multipart/form-data" by hand, writing every field to the builder. This is very error-prone and is not sustainable to typos. 

With JSON however, this can be done by the serialization library.

**Comment by levlam** [comment]
If you have a library, which serializes for you to JSON, but don't have a library, which serialize to `multipart/form-data`, you can always deserialize JSON and pass all the data to the "multipart/form-data" builder similar to my sample code in PHP. The necessity to write an additional line of code in some languages is not enough justification for inventing a non-conventional way to pass arguments in "multipart/form-data".

**Comment by WaffleLapkin** [comment]
> deserialize JSON and pass all the data to the "multipart/form-data" builder similar to my sample code in PHP

Why would I want to do that though? That's a lot of unnecessary work 😄 

> The necessity to write an additional line of code in some languages [...]

I would argue that a good implementation would take way more than one line.

> [...] is not enough justification for inventing an unconventional way to pass arguments in "multipart/form-data".

I'm actually quite surprised that it's unconventional! It seems very convenient and makes everything more consistent by allowing using JSON not only for requests without files. I've also seen this "way to pass arguments in "multipart/form-data"" used quite a few times (though I couldn't remember any public APIs with this, only local company ones). 

---

Also, would you mind accepting a PR with this feature? Or do you think this will make bot API worse in some way?

**Comment by gagarski** [comment]
Hi @levlam.

Is that really done or was closed as `completed` by mistake?
