### ISSUE TITLE
Setting sticker emoji with `send_sticker`

### ISSUE THREAD

**Issue by Bibo-Joshi** [tdlib/telegram-bot-api#179]
Hi.
I just again stumbled over the fact, that one can specify the emoji associated with a sticker when adding it to a sticker pack with `addStickerToSet`, but not when sending them directly via `send_sticker`. Is there a specific reason for that? If not, would it be possible to add this functionality to `send_sticker`? 🙂

**Comment by levlam** [comment]
This is possible. But similarly to any other file attribute, the attached emoji will be ignored unless the sticker is just uploaded.

**Comment by Bibo-Joshi** [comment]
I'm not sure if I understand what you mean. Are you saying that passing and emoji to `send_sticker` wouldn't have any effect if the sticker is sent via file_id?
If so: That makes sense and would be expected behavior for me personally. My main user case would be uploading new stickers anyway - that just don't need to end up in a sticker set.

**Comment by Bibo-Joshi** [comment]
Looks like this is covered in API 6.6 https://core.telegram.org/bots/api-changelog#march-9-2023.
Many thanks! :)
