### ISSUE TITLE
Ability to switch from HTTP 1.1.  to gRPC

### ISSUE THREAD

**Issue by akhunovaa** [tdlib/telegram-bot-api#18]
Is there such an opportunity to rewrite the implementation of **HTTP** 1.1 to modern **gRPC**? Where the speed of information exchange is very fast. I have this implementation in JAVA, where I communicate with **TDLib** (_Telegram Database library_) over **JNI**. But native things from **Telegram** developers are more better and it will be better to inject and implement here some **gRPC** :-) Thank you!

**Comment by levlam** [comment]
This is definitely possible, but is out of scope of this repository. Official Bot API is supposed to have an HTTP interface.
