### ISSUE TITLE
Problem when trying to build (Windows)

### ISSUE THREAD

**Issue by MohammadZarifiyan** [tdlib/telegram-bot-api#181]
```
PS C:\Users\moham\Documents\telegram-bot-api\build> cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=.. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows/include C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows/debug/lib/libssl.lib;C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
CMake Warning (dev) at vcpkg/installed/x64-windows/share/zlib/vcpkg-cmake-wrapper.cmake:13 (_find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  td/tdutils/CMakeLists.txt:12 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows/include optimized;C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/Users/moham/Documents/telegram-bot-api/vcpkg/installed/x64-windows/debug/lib/zlibd.lib
CMake Error at td/tdutils/generate/CMakeLists.txt:28 (message):
  Could NOT find gperf.  Add path to gperf executable to PATH environment
  variable or specify it manually using GPERF_EXECUTABLE option, i.  e.
  'cmake -DGPERF_EXECUTABLE:FILEPATH="<path to gperf executable>"'.


-- Configuring incomplete, errors occurred!
See also "C:/Users/moham/Documents/telegram-bot-api/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/moham/Documents/telegram-bot-api/build/CMakeFiles/CMakeError.log".
```

[CMakeOutput.log](https://github.com/tdlib/telegram-bot-api/files/7161561/CMakeOutput.log)
[CMakeError.log](https://github.com/tdlib/telegram-bot-api/files/7161562/CMakeError.log)

What is the problem ?!

**Comment by levlam** [comment]
Do you use the latest build instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Windows?

**Comment by MohammadZarifiyan** [comment]
> Do you use the latest build instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Windows?

Yes totally.

**Comment by levlam** [comment]
Thanks.

Run
```
cd vcpkg
./vcpkg.exe install gperf:x64-windows
```

And then continue from the failed command.

**Comment by MohammadZarifiyan** [comment]
> Thanks.
> 
> Run
> 
> ```
> cd vcpkg
> ./vcpkg.exe install gperf:x64-windows
> ```
> 
> And then continue from the failed command.

`PS C:\Users\moham\Desktop\telegram-bot-api\build> cmake --build . --target install --config Release
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  generate_mime_types_gperf.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\tdutils\generate\Release\generate_mime_types_gperf.exe
  Generating ../../../../td/tdutils/generate/auto/mime_type_to_extension.gperf, ../../../../td/tdutils/generate/auto/extension_to_mime_type.gperf
  Extension "wmz" matches more than one type
  Extension "sub" matches more than one type
  Generating ../../../../td/tdutils/generate/auto/extension_to_mime_type.cpp
  Generating ../../../../td/tdutils/generate/auto/mime_type_to_extension.cpp
  extension_to_mime_type.cpp
  mime_type_to_extension.cpp
  Generating Code...
  tdutils.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\tdutils\Release\tdutils.lib
  memprof.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\Release\memprof.lib
  tdactor.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\tdactor\Release\tdactor.lib
  tl-parser.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\td\generate\tl-parser\Release\tl-parser.exe
  Generate TLO files
  tdtl.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\tdtl\Release\tdtl.lib
  generate_common.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\td\generate\Release\generate_common.exe
  Generate common TL source files
  tdapi.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\Release\tdapi.lib
  tdsqlite.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\sqlite\Release\tdsqlite.lib
  tddb.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\tddb\Release\tddb.lib
  tdnet.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\tdnet\Release\tdnet.lib
  tdcore.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\td\Release\tdcore.lib
  telegram-bot-api.vcxproj -> C:\Users\moham\Desktop\telegram-bot-api\build\Release\telegram-bot-api.exe
  -- Install configuration: "Release"
  -- Installing: C:/Users/moham/Desktop/telegram-bot-api/build/../bin/telegram-bot-api.exe
  -- Up-to-date: C:/Users/moham/Desktop/telegram-bot-api/build/../bin
  -- Up-to-date: C:/Users/moham/Desktop/telegram-bot-api/build/../bin/libcrypto-1_1-x64.dll
  -- Up-to-date: C:/Users/moham/Desktop/telegram-bot-api/build/../bin/libssl-1_1-x64.dll
  -- Up-to-date: C:/Users/moham/Desktop/telegram-bot-api/build/../bin/zlib1.dll
PS C:\Users\moham\Desktop\telegram-bot-api\build> cd ../..
PS C:\Users\moham\Desktop> dir telegram-bot-api/bin/telegram-bot-api*


    Directory: C:\Users\moham\Desktop\telegram-bot-api\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         9/14/2021  11:01 PM       18496000 telegram-bot-api.exe


PS C:\Users\moham\Desktop> telegram-bot-api --help
telegram-bot-api : The term 'telegram-bot-api' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ telegram-bot-api --help
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (telegram-bot-api:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by levlam** [comment]
Build instructions were fixed. Thanks.
