### ISSUE TITLE
Stuck Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o

### ISSUE THREAD

**Issue by seththefirst** [tdlib/telegram-bot-api#183]
Hi, I'm trying to build the bot, follow the html instructions for Ubuntu, but It get's stuck building ContactsManager.cpp.o

Is there anything that I can check ?

Thank You

**Comment by levlam** [comment]
You need 4+ GB of RAM when building with g++ and 2+ GB of RAM when building with clang.

**Comment by seththefirst** [comment]
Thx for that.
