### ISSUE TITLE
Too Many Requests: retry after 2282

### ISSUE THREAD

**Issue by miladrajabi2002** [tdlib/telegram-bot-api#184]
Hi when forward a message for all users(200,000) i got this error

```
{
    "ok": false,
    "error_code": 429,
    "description": "Too Many Requests: retry after 2282",
    "parameters": {
        "retry_after": 2282
    }
}
```

**Comment by levlam** [comment]
There is no issue there. You can retry the request after 2282 seconds.

**Comment by miladrajabi2002** [comment]
I dont want to get into this error because I have many users, I send 30 messages per second and I dont want to get this error, what should I do?

**Comment by levlam** [comment]
Forwarding and sending messages is a different thing.

**Comment by javidee** [comment]
@miladrajabi2002  Did you solve it?
