### ISSUE TITLE
Got an error while compiling bot api in ubuntu

### ISSUE THREAD

**Issue by anonyindian** [tdlib/telegram-bot-api#185]
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [td/CMakeFiles/tdcore.dir/build.make:336: td/CMakeFiles/tdcore.dir/td/telegram/AuthManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:527: td/CMakeFiles/tdcore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

How do I solve it?

**Comment by levlam** [comment]
You have not enough RAM to build the Bot API server with g++. You need at least 5 GB RAM for g++ or at least 2 GB RAM when building with clang.

**Comment by anonyindian** [comment]
Ok, Thank You for the information.
