### ISSUE TITLE
Problems with editChatInviteLink after API 5.4 update

### ISSUE THREAD

**Issue by Bibo-Joshi** [tdlib/telegram-bot-api#196]
Hi.

Thanks for new API update! Neat new features :)
While working to incorporate the changes into `python-telegram-bot`, I've noticed that the update seems to have introduced problems with `editChatInviteLink`: passing `member_limit` or `name` has unexpected effects on the existing settings for the invite link.

Example:

1. create a new invite link, pass `chat_id` and `member_limit`
2. edit the link, pass the parameters `chat_id`, `invite_link` and `name`. Expected result: the `member_limit` set in step 1 still holds an the name is added. Actual result: the `member_limit` is deleted and the `name` is applied
3. edit the link again, pass `chat_id`, `invite_link` and `member_limit`. Expected result: the name set in step 2 still holds and the `member_limit` is added. Actual result: Neither name nor `member_limit` are applied

Another example:

1. create a new invite link, pass `chat_id` and `member_limit`
2. edit the link, pass `chat_id`, `invite_link` and a different `member_limit`. Expected result: the new `member_limit` is applied. Actual result: The `member_limit` is deleted

A third example:

1. create a new invite link, pass `chat_id` and `member_limit`
2. edit the link, pass `chat_id`, `invite_link` and a `creates_join_request=True`. Expected result: the new `member_limit` is removed and `creates_join_request` is applied. Actual result: The `member_limit` is set to 1 and `creates_join_request` is not applied

I'm not sure what to make of this and would be happy for a response :)

**Comment by levlam** [comment]
The method `editChatInviteLink` doesn't support partial edits, all invite link parameters are replaced by this method. Value of a nonspecified parameter is changed to its default value.

Other mentioned issues was fixed in Bot API 5.4.1: member_limit and creates_join_request can be edited correctly now.
