### ISSUE TITLE
[Question]: Can I get the URL on the Telegram servers of a file?

### ISSUE THREAD

**Issue by billy4479** [tdlib/telegram-bot-api#197]
I'm running the API in local mode.
I've noticed that users can download the files sent by my bot even when my server is down, so the files are stored also on Telegram's servers, am I right?
I'd like to get the URL to download the file directly from Telegram servers without going through mine. Is it possible?
Thanks

**Comment by levlam** [comment]
Files stored on Telegram servers aren't available through HTTP, so they have no HTTP URLs.

**Comment by billy4479** [comment]
Oh ok, thanks for the clarification. Is there any other way I can get them?

**Comment by levlam** [comment]
The only way is to download them locally, for example, using the method `getFile`.

**Comment by billy4479** [comment]
Ok thank you
