### ISSUE TITLE
How to use `file_unique_id` on other bots?

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#199]
I'm just wondering how can we use `file_unique_id` value on other bots? I mean if we cannot use this in anyway "Can't be used to download or reuse the file" so where we able to use them ? why do you show us this id at all ?

**Comment by AYMENJD** [comment]
You can't use file_unique_id in sending files.
Its just a unique file identifier that let you recognize the file.
Because "file_id" will not be the same for all bots.
But "unique_id" will be the same for all other bots.
