### ISSUE TITLE
Undelivered messages

### ISSUE THREAD

**Issue by taranovegor** [tdlib/telegram-bot-api#20]
When a user sends a message to a group in `//@senders_username some text` format, it will not be delivered to the bot

![image](https://user-images.githubusercontent.com/16158349/98354485-71355280-2029-11eb-906a-0f05503153e6.png)

**Comment by levlam** [comment]
Server identifies the message text as a command "/" to the bot with username "taranovegor", so the message is accessible only to the identified bot. "/" is definitely a valid command, but "taranovegor" is definitely not a username of a bot participating in the group, so this behavior probably can be improved.

**Comment by FACF302** [comment]
https://discord.gg/J8fzt9mzFA

**Comment by ShiSHcat** [comment]
This is a serverside issue.

**Comment by LucaTheHacker** [comment]
Well, I don't really mind if is a command for another bot, I want to know what's going on in my group, and with privacy mode off, I must see that message.

**Comment by nyuszika7h** [comment]
If you turned off privacy mode try removing the bot from the group and adding it back again.

**Comment by LucaTheHacker** [comment]
> If you turned off privacy mode try removing the bot from the group and adding it back again.

It's not about privacy mode, the bot doesn't receive the update.

**Comment by levlam** [comment]
This was fixed some time ago.
