### ISSUE TITLE
Getting 404 on getFile

### ISSUE THREAD

**Issue by kiran-venugopal** [tdlib/telegram-bot-api#201]
I am using docker in heroku to serve the bot api, when i try to call the getFile ( `https://xxxxxxx.herokuapp.com/file/botTOKEN/documents/file_0.png` ) it gives the response as:

`{"ok":false,"error_code":404,"description":"Not Found"}`

Dockerfile: 
```
FROM alpine

RUN export BUILD_ONLY_PKGS="alpine-sdk cmake git gperf linux-headers openssl-dev zlib-dev" \
	&& apk add --no-cache $BUILD_ONLY_PKGS \
	&& git clone --recursive https://github.com/tdlib/telegram-bot-api.git /tmp/telegram-bot-api \
	&& mkdir /tmp/telegram-bot-api/build \
	&& cd /tmp/telegram-bot-api/build \
	&& cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local .. \
	&& cmake --build . --target install \
	&& rm -rf /tmp/* \
	&& apk del $BUILD_ONLY_PKGS

RUN apk add --no-cache libstdc++ openssl zlib

CMD telegram-bot-api -p $PORT
```

**Comment by levlam** [comment]
Files are saved locally by Bot API server. If you want them to be available through HTTP, you need to set up a separate HTTP server for them, capable of serving static content.

**Comment by kiran-venugopal** [comment]
how we can do that within the Dockerfile, is there any example or blogpost available?

**Comment by levlam** [comment]
See, for example, https://github.com/aiogram/telegram-bot-api.
