### ISSUE TITLE
Unauthorized: invalid api-id/api-hash

### ISSUE THREAD

**Issue by DilshodUzakov** [tdlib/telegram-bot-api#203]
Hello, dear support team. 
Please suggest me solution for resolving an issue with Error Unauthorized: invalid api-id/api-has
My log file is attached. Maybe someone has been faced with the same issues in past? How to resolve it? 
[api.log](https://github.com/tdlib/telegram-bot-api/files/7611311/api.log)

P.S. API is valid. logOut from api.telegram.org was successfully done.

**Comment by AYMENJD** [comment]
Are you sure that you pass a vaild API_ID/API_HASH?

**Comment by DilshodUzakov** [comment]
> Are you sure that you pass a vaild API_ID/API_HASH?

Yep, I just copy past from BotFather, double-check. Nothing... maybe the issue with my network, I'm not sure.

**Comment by AYMENJD** [comment]
> > Are you sure that you pass a vaild API_ID/API_HASH?
> 
> Yep, I just copy past from BotFather, double-check. Nothing... maybe the issue with my network, I'm not sure.

No, API_ID/API_HASH you must create it from my.telegram.org.
See: https://core.telegram.org/api/obtaining_api_id

**Comment by DilshodUzakov** [comment]
> > > Are you sure that you pass a vaild API_ID/API_HASH?
> > 
> > 
> > Yep, I just copy past from BotFather, double-check. Nothing... maybe the issue with my network, I'm not sure.
> 
> No, API_ID/API_HASH you must create it from my.telegram.org. See: https://core.telegram.org/api/obtaining_api_id

Tried =( Unauthorized
![image](https://user-images.githubusercontent.com/17160451/143670871-fb1159cb-4be7-4262-9985-5c7dee515ad7.png)

**Comment by AYMENJD** [comment]
> > > > Are you sure that you pass a vaild API_ID/API_HASH?
> > > 
> > > 
> > > Yep, I just copy past from BotFather, double-check. Nothing... maybe the issue with my network, I'm not sure.
> > 
> > 
> > No, API_ID/API_HASH you must create it from my.telegram.org. See: https://core.telegram.org/api/obtaining_api_id
> 
> Tried =( Unauthorized ![image](https://user-images.githubusercontent.com/17160451/143670871-fb1159cb-4be7-4262-9985-5c7dee515ad7.png)

You should get api-id and api-hash from https://my.telegram.org.

Then pass the api-id and api-hash.

For example:
```
./telegram-bot-api --api-id=16793201 --api-hash="268....." --local --http-port=8082 --log=/mnt/api.log --verbosity=4
```

**Comment by DilshodUzakov** [comment]
It works! I just input " " before and end of hash. Great Thanks!
