### ISSUE TITLE
[Documentation wording] banChatSenderChat

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#207]
Tests revealed that banning a channel from a chat means the user account cannot post as any channel they own anymore. If that is intended, I would suggest to do the following wording adjustment:

```html
<p>Use this method to ban a channel chat in a supergroup or a channel. The owner of the chat will not be able to send messages and join live streams on behalf of any chat, unless it is <a href="#unbanchatsenderchat">unbanned</a> first. The bot must be an administrator in the supergroup or channel for this to work and must have the appropriate administrator rights. Returns <em>True</em> on success.</p>
```

**Comment by harshil21** [comment]
Also, it seems that the `until_date` parameter of this method was removed. Is it intentional?

**Comment by Poolitzer** [comment]
It is implemented in the public code at least: https://github.com/tdlib/telegram-bot-api/blob/04361155aaa2966af5466b1352ee9fc2ab7e8fe3/telegram-bot-api/Client.cpp#L7695

**Comment by levlam** [comment]
"until_date" was added accidentally to the documentation. There is no way to ban chats temporarily.

**Comment by Poolitzer** [comment]
and the other paragraph is back, cool
