### ISSUE TITLE
Proposal 2 Options

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#211]
When the webhook was enabled add these options:

1. Dont resend update when you receive none 200 response

Lets say i have these in my code:

```php
$this->sendMessage('Waiting...'); //send message to current user to wait

--> i have bug here, so responding to telegram with none 200 http response 
```
At this point telegram retry and resend the update about 3 or 5 times right? So the end user sees 5 times of 'Waiting...'

So my suggestion is to add option to webhook something like `retry` and when it was set to false, telegram should've send update once and ignore any error from the server. Because i can not handle that error at the time there are no reason to resend updates.

2. Consider timeout from telegram side
 
In part of my code i have an unexpectedly recursive function and it took forever, So my suggestion is to add some option like `timeout` in webhook and when its have value for example 15s, Telegram should've wait for 15 seconds otherwise terminate the request.

--------------
These settings are optional and there is no bc for another devs. Thanks in advanced!

**Comment by levlam** [comment]
1. This would make bots unreliable. Such behavior must not be encouraged. There are a lot of reasons for webhook update to fail.

2. The webhook response is awaited for at most 60 seconds now. After the time passes, the connection is closed and the request is re-sent. This time can't be reliably increased and there are no reasons to decrease it.

**Comment by foremtehan** [comment]
As i said those are optional, When i want to telegram to ignore failures it means i know what i'm doing,  Thanks for the response btw.

**Comment by levlam** [comment]
Resnding will give up after some time. Moreover, only updates from a fixed chat will be affected, so it is better to wait for bot's code fix than silently drop updates.
