### ISSUE TITLE
Cannot receive  "inline feedback" when querying with anonymous account

### ISSUE THREAD

**Issue by PumpkinCheshire** [tdlib/telegram-bot-api#213]
Usually my bot will use inline feedback to edit the "ChosenInlineResult". But when using bot with anonymous account (AKA, a group), the feedback will not be sent to bot.

I believe this issue also happens on telegram official bots, like:
![image](https://user-images.githubusercontent.com/30663626/146112239-328ea74b-4e43-41e9-9ff4-d0ecfe2a2a19.png)

**Comment by levlam** [comment]
This is expected behavior for protection of the sender's anonimity. As always was stated in https://core.telegram.org/bots/inline#collecting-feedback, "Either way, feedback collection should only be used for statistical purposes rather than functional."

**Comment by PumpkinCheshire** [comment]
> This is expected behavior for protection of the sender's anonimity. As always was stated in https://core.telegram.org/bots/inline#collecting-feedback, "Either way, feedback collection should only be used for statistical purposes rather than functional."

Thanks.

But is there any way to achieve "editing the chosen inline result"?

Also, will the @imdb bot get fix? For now it cannot be used on anonymous mode.

**Comment by levlam** [comment]
> But is there any way else to achieve "editing the chosen inline result"?

No. The desired message is supposed to be sent immediately.

> Also, will the @imdb bot get fix?

Noone knows.

**Comment by PumpkinCheshire** [comment]
> > But is there any way else to achieve "editing the chosen inline result"?
> 
> No. The desired message is supposed to be sent immediately.
> 
> > Also, will the @imdb bot get fix?
> 
> Noone knows.

Good to know, I'll change my bot behaviour then.

Also, the inline mode bot can get user's real identity even in anonymous mode.
`InlineQuery -> from` still shows the real user name & id instead of anonymous id (which is negative)

**Comment by levlam** [comment]
The bot can't know, in which chat the query is sent, so it can't reliably match the user and the channel.
