### ISSUE TITLE
server doesn't start

### ISSUE THREAD

**Issue by sssss123455** [tdlib/telegram-bot-api#215]
Hello, i have a problem when i start the server with gitbush
telegram-bot-api.exe api-id = my_id api-hash = my_hash. nothing has been done. it processes this command. and does not output anything: not an error, nothing else
![server](https://user-images.githubusercontent.com/54313725/146745645-ce4d69ef-df41-48ab-ba72-afc88a36929a.jpg)

**Comment by levlam** [comment]
It succesfully started.

**Comment by vahidvalai** [comment]
The problem was solved. It started successfully.

**Comment by sssss123455** [comment]
I thought there was a new command line or startup message .  won't it happened?

**Comment by sssss123455** [comment]
> It succesfully started.
I thought there was a new command line or startup message . won't it happened?

**Comment by levlam** [comment]
Why should it print anything, if you didn't ask about that by increasing log verbosity level?
