### ISSUE TITLE
PhotoSize is sometimes empty in updates

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#216]
Look at this update:

![image](https://user-images.githubusercontent.com/53290883/147254508-6aa12228-72b3-45df-8830-80613125c668.png)

I uploaded some image to telegram using `sendPhoto`, the returned result get me empty array on `photo` object

Empty photo key without any error ! this is so bad. Can you debug this on your side ? 

I cant get you the image file because when i try to re-upload this it will be fine

**Comment by levlam** [comment]
Do you have full raw request response? Could you send it to https://t.me/tdlib_bot?

**Comment by foremtehan** [comment]
Can i manipulate chat_ids for security concerns ?

**Comment by levlam** [comment]
@foremtehan Ok.

**Comment by foremtehan** [comment]
sent.
