### ISSUE TITLE
Bad Request: chat not found (But user exists)

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#219]
I dont know why i'm getting the `chat not found` for users whom /start the bot! I'm 100% user started to my bot some times telegram give me this error: "Bad Request: chat not found"

It happens some times, But again, i save the users telegram_id in my db and 100% sure the user started my bot.

**Comment by levlam** [comment]
Are you sure that the user wrote to your bot in a private chat and not in a group chat?

**Comment by foremtehan** [comment]
> Are you sure that the user wrote to your bot in a private chat and not in a group chat?

Nope, It disabled from botfather in first place, It happened several month ago but it came today

**Comment by levlam** [comment]
Could you send bot's username and the user_id to https://t.me/tdlib_bot?

**Comment by foremtehan** [comment]
sent

**Comment by levlam** [comment]
Thank you. This was fixed.

**Comment by akhilbro12** [comment]
how you fixediam also having same problems

**Comment by levlam** [comment]
@akhilbro12

Are you sure that the user wrote to your bot in a private chat and not in a group chat?

**Comment by akhilbro12** [comment]
No not, it's private group no one is there just for reference I have tested and facing this issue, I have no idea why this is happening! And for /start command pm also same problem

**Comment by levlam** [comment]
Bots can't start conversations with users. The user must send them a message first.
