### ISSUE TITLE
Wrong response when using drop_pending_updates

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#22]
When i drop all pending requests like:
```
https://api.telegram.org/botTOKEN/setWebhook?drop_pending_updates=true
```

It says: "Webhook was deleted"

**Comment by levlam** [comment]
This is a correect response. You call `setWebhook` with an empty `url`, which effectively deletes webhook.

**Comment by foremtehan** [comment]
So,
