### ISSUE TITLE
[question] Does restrictChatMember work correctly?

### ISSUE THREAD

**Issue by uriid1** [tdlib/telegram-bot-api#220]
Hello.
I have a question about **restrictChatMember**.
For example, if before the bot changes the user's rights, I change them, for example, by prohibiting the sending of stickers and media. Then after **can_send_messages = false** in **restrictChatMember** and after the specified **until_date** - Telegram returns both sending messages and sending media.
Maybe I'm doing something wrong, or this is how it should be, but I need to do it differently...

I would like to have such an opportunity, it looks logical. :)

**Comment by levlam** [comment]
Everything works as documented in https://core.telegram.org/bots/api#restrictchatmember. You pass new user's pemissions and the date when all "restrictions will be lifted for the user".
