### ISSUE TITLE
Bot not receiving updates when other bots post a message in a group

### ISSUE THREAD

**Issue by smogili1** [tdlib/telegram-bot-api#221]
Noticed that the bot no longer receives updates when a bot posts a message in the group. This did not use to be the case a few months back. Looking the change log I can't find any mention of this. 

Would like to know if this is intentional or a bug?

**Comment by AYMENJD** [comment]
Bots can't see other bots messages.

**Comment by levlam** [comment]
This has never been changed: https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots.
