### ISSUE TITLE
Can you help me in php ?

### ISSUE THREAD

**Issue by sallsabil** [tdlib/telegram-bot-api#223]
Hi
I'm using php-telegram-bot library.

I run locally:
`$bin: ./telegram-bot-api --api-id=***** --api-hash=*********************** --local &`

```
$telegram = new Longman\TelegramBot\Telegram(BOT_TOKEN, BOT_USERNAME);
$telegram->useGetUpdatesWithoutDatabase();

$output = Request::logOut();

$output = Request::setCustomBotApiUri(
    $api_base_uri          = 'https://example.com', // Default: https://api.telegram.org
    $api_base_download_uri = __DIR__ . "/files/".BOT_TOKEN     // Default: /file/bot{API_KEY}
);
```

> Fatal error: Uncaught Longman\TelegramBot\Exception\InvalidBotTokenException: Invalid bot token!

What is wrong with php code ?
What should I set in `$api_base_uri`  ?

**Comment by levlam** [comment]
Check Bot API server logs and the exact response. It is likely that you specified invalid api_id or api_hash.
