### ISSUE TITLE
Ubuntu 20.10 use to build clang++ (recommended)

### ISSUE THREAD

**Issue by kraserge** [tdlib/telegram-bot-api#23]
after cmake --build . --target install
gmake[1]: вход в каталог «/home/user/telegram-bot-api/build»
gmake[2]: вход в каталог «/home/user/telegram-bot-api/build»
Scanning dependencies of target tdsqlite
gmake[2]: выход из каталога «/home/user/telegram-bot-api/build»
gmake[2]: вход в каталог «/home/user/telegram-bot-api/build»
[  0%] Building C object td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o
[  0%] Linking C static library libtdsqlite.a
gmake[2]: выход из каталога «/home/user/telegram-bot-api/build»
[  0%] Built target tdsqlite
gmake[2]: вход в каталог «/home/user/telegram-bot-api/build»
Scanning dependencies of target generate_mime_types_gperf
gmake[2]: выход из каталога «/home/user/telegram-bot-api/build»
gmake[2]: вход в каталог «/home/user/telegram-bot-api/build»
[  0%] Building CXX object td/tdutils/generate/CMakeFiles/generate_mime_types_gperf.dir/generate_mime_types_gperf.cpp.o
/home/user/telegram-bot-api/td/tdutils/generate/generate_mime_types_gperf.cpp:7:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 error generated.
gmake[2]: *** [td/tdutils/generate/CMakeFiles/generate_mime_types_gperf.dir/build.make:63: td/tdutils/generate/CMakeFiles/generate_mime_types_gperf.dir/generate_mime_types_gperf.cpp.o] Ошибка 1
gmake[2]: выход из каталога «/home/user/telegram-bot-api/build»
gmake[1]: *** [CMakeFiles/Makefile2:814: td/tdutils/generate/CMakeFiles/generate_mime_types_gperf.dir/all] Ошибка 2
gmake[1]: выход из каталога «/home/user/telegram-bot-api/build»
gmake: *** [Makefile:130: all] Ошибка 2

**Comment by levlam** [comment]
Did you run
```
export CXXFLAGS="-stdlib=libc++"
```
before running cmake for the first time?

**Comment by levlam** [comment]
I have just used exact build instructions from https://tdlib.github.io/telegram-bot-api/build.html?os=Linux to build Telegram Bot API server on Ubuntu 20 with clang. Could you show the whole output of the commands from the build instructions?
