### ISSUE TITLE
change local server file path

### ISSUE THREAD

**Issue by hasanizadt** [tdlib/telegram-bot-api#233]
i'm wondring whether the file path that bot creates on the local server can be changed before download the file or not?
For example, can I transfer a file to a subdomain before download it?

**Comment by levlam** [comment]
The path can't be changed. Between what do you mean by "transfer a file to a subdomain"? Bot API server has nothing to do with domains.

**Comment by nxfi777** [comment]
Any way to use an R2 cloudflare bucket as the file store?
