### ISSUE TITLE
How to use multi-core CPU?

### ISSUE THREAD

**Issue by mylukin** [tdlib/telegram-bot-api#236]
My server has an 8-core CPU. Currently, only 1 CPU is used, and the other 7 are idle. I hope to reply, thank you!

DURATION	inf	5sec	1min	1hour
uptime	2482.520765
bot_count	4379
active_bot_count	150
rss	18GB
vm	18GB
rss_peak	18GB
vm_peak	18GB
total_cpu	118.269319%	113.913043%	114.552656%	118.269319%
user_cpu	99.416224%	100.347826%	99.993907%	99.416224%
system_cpu	18.853095%	13.565217%	14.558749%	18.853095%
buffer_memory	3040MB
active_webhook_connections	3281
active_requests	174706
active_network_queries	172347
request_count	614.006956	364.547365	294.479924	614.006956
request_bytes	271470.504437	166391.486635	129315.445543	271470.504468
request_file_count	0.000000	0.000000	0.000000	0.000000
request_files_bytes	0.000000	0.000000	0.000000	0.000000
request_max_bytes	0	0	0	0
response_count	543.640529	347.578607	347.736007	543.640529
response_count_ok	76.525494	107.880848	70.113676	76.525494
response_count_error	467.115035	239.697759	277.622331	467.115035
response_bytes	136281.333011	162937.389112	112554.637102	136281.333026
update_count	1348.788008	1905.333100	2052.825080	1348.788008

**Comment by levlam** [comment]
You can run 8 instances and split bots between them by their ID, using "--filter 0/8", ..., "--filter 7/8" options.

**Comment by mylukin** [comment]
> You can run 8 instances and split bots between them by their ID, using "--filter 0/8", ..., "--filter 7/8" options.

Thank you very much for your answer

I have another question, that is, there are too many single Bot callbacks, which will cause API 502 and cannot serve normally. Is there any solution?

**Comment by erfanmola** [comment]
> You can run 8 instances and split bots between them by their ID, using "--filter 0/8", ..., "--filter 7/8" options.

Why in the world would someone do this ? Why not add a parameter --workers-count=8 ?
Running 8 instances and splitting between them is not the best option, At least you can handle this internally, AFAIK 1 Core is not really enough for large scales, people tend to buy 8 cores to handle more requests, not have 7 cores idle

**Comment by levlam** [comment]
> Why in the world would someone do this ?

Everyone does this. This is called "horizontal sharding" and you will need it anyway if you are gonna have more than one server. 

> Why not add a parameter --workers-count=8 ?

It is possible to add this option, but Bot API server is very rarely limited by CPU performance, so the option would just create 8 idle main threads instead of 1.

**Comment by mylukin** [comment]
> > Why in the world would someone do this ?
> 
> 
> 
> Everyone does this. This is called "horizontal sharding" and you will need it anyway if you are gonna have more than one server. 
> 
> 
> 
> > Why not add a parameter --workers-count=8 ?
> 
> 
> 
> It is possible to add this option, but Bot API server is very rarely limited by CPU performance, so the option would just create 8 idle main threads instead of 1.

I have several bots that process 100 million messages every day, and I expect the number to increase by 2-3 times in the future. I am afraid that one CPU will not be enough.

**Comment by erfanmola** [comment]
> It is possible to add this option, but Bot API server is very rarely limited by CPU performance, so the option would just create 8 idle main threads instead of 1.

I suppose that api.telegram.org is handling entire requests on one core ?

**Comment by levlam** [comment]
@erfanmola api.telegram.org uses exactly the same server as provided in this repository.

**Comment by levlam** [comment]
> I wonder how api.telegram.org is deployed?

@mylukin The same way you would deploy any other software. api.telegram.org has only nginx шт front ot Telegram Bot API server to terminate TLS and serve files.

**Comment by mnkblog** [comment]
@mylukin my question is how did you get this statics ?
sometimes i get really slow connection for example sendMessage takes 1 sec to respond.

**Comment by mylukin** [comment]
Find the DC where your bot is located and deploy it near the DC where the bot is located

**Comment by mylukin** [comment]
This statistic comes with the bot server, you just need to add the switch when running the server.  Find the DC where your bot is located and deploy it near the DC where the bot is located

**Comment by mnkblog** [comment]
@mylukin what is DC stands for ?
I'm using pm2 to manage the running API...

**Comment by erfanmola** [comment]
> what is DC stands for ?

DC is short version of **Data Center**

**Comment by mylukin** [comment]
yes

**Comment by mnkblog** [comment]
bot_count 4379
active_bot_count 150

Anyway ! how do you get these stats in ubuntu server ?

**Comment by AYMENJD** [comment]
@mnkblog Specify a port number for option `-s` when running `./telegram-bot-api`.
And then open that port using your browser you will see a stats page.

For more information execute: `./telegram-bot-api --help`
