### ISSUE TITLE
I have a 429 error, what should I do?

### ISSUE THREAD

**Issue by mylukin** [tdlib/telegram-bot-api#237]
[ 2][t 1][1645311903.610625982][Stats.h:58]	CPU usage: 20.524691%
[ 2][t 1][1645311903.860482454][Session.cpp:512][#1376476108][!Session:5:main]	Session with 0 pending requests was closed: [Error : 0 : Connection closed] Session:5:main::Connect::Tcp::[149.154.171.5:80] to DcId{5} from [172.20.0.2:45604]
[ 2][t 1][1645311903.868497610][Session.cpp:512][#1376476108][!Session:5:main]	Session with 0 pending requests was closed: [Error : 500 : MTProto error: -429] Session:5:main::Connect::Tcp::[91.108.56.184:443] to DcId{5} from [172.20.0.2:47176]
[ 2][t 1][1645311903.871340036][Session.cpp:512][#1376476108][!Session:5:main]	Session with 0 pending requests was closed: [Error : 500 : MTProto error: -429] Session:5:main::Connect::Tcp::[149.154.171.5:443] to DcId{5} from [172.20.0.2:44344]
[ 2][t 1][1645311903.874144792][Session.cpp:512][#1376476108][!Session:5:main]	Session with 0 pending requests was closed: [Error : 500 : MTProto error: -429] Session:5:main::Connect::Tcp::[149.154.171.5:5222] to DcId{5} from [172.20.0.2:60140]

**Comment by levlam** [comment]
You are sending too much requests. There is no way to avoid these errors with so much requests.

**Comment by pridclow68** [comment]
> You are sending too much requests. There is no way to avoid these errors with so much requests.

The number of connections allowed by my server is low, this problem is solved, thank you very much!

**Comment by pridclow68** [comment]
> You are sending too much requests. There is no way to avoid these errors with so much requests.

Will this error cause the bot to go offline?  After this message, my webhook callback also slowed down

**Comment by mylukin** [comment]
> You are sending too much requests. There is no way to avoid these errors with so much requests.

Will this error cause the bot to go offline?  After this message, my webhook callback also slowed down

**Comment by levlam** [comment]
Yes.

**Comment by erfanmola** [comment]
> You are sending too much requests. There is no way to avoid these errors with so much requests.

And what are the limits exactly ? If my bot can have 100,000 Active webhook connections at a time, isn't it logical to send 100,000 Requests Per Second to telegram ?

**Comment by levlam** [comment]
No, it is not logical to send so much requests simultaneously.

**Comment by erfanmola** [comment]
> No, it is not logical to send so much requests simultaneously.

How many Rqeusts Per Second are allowed ?
Is it a hard limit per IP ? or a more intelligent limit considering Number of Bots being served on the server or etc

I mean, are limits the same for a server with 1 bot, with a server with 10 bots ?

**Comment by mylukin** [comment]
> > 不，同时发送这么多请求是不合逻辑的。
> 
> 每秒允许多少个Rqeusts？这是每个IP的硬限制吗？或更智能的限制，考虑服务器上服务的机器人数量等
> 
> 我的意思是，对于具有1个机器人的服务器，具有具有10个机器人的服务器，限制是否相同？



> > No, it is not logical to send so much requests simultaneously.
> 
> How many Rqeusts Per Second are allowed ? Is it a hard limit per IP ? or a more intelligent limit considering Number of Bots being served on the server or etc
> 
> I mean, are limits the same for a server with 1 bot, with a server with 10 bots ?

I have 4000 bots on my server causing this kind of error.

I want to use local server to serve bots I manage
Our bot is similar to @livegrambot and provides many bot bindings

**Comment by mylukin** [comment]
> > No, it is not logical to send so much requests simultaneously.
> 
> How many Rqeusts Per Second are allowed ? Is it a hard limit per IP ? or a more intelligent limit considering Number of Bots being served on the server or etc
> 
> I mean, are limits the same for a server with 1 bot, with a server with 10 bots ?

I have 4000 bots on my server causing this kind of error.

I want to use local server to serve bots I manage
Our bot is similar to @livegrambot and provides many bot bindings

**Comment by mylukin** [comment]
Is it possible to allow 1 IP to log in to an unlimited number of Bots?

Because my bot is on dc5, the client bots I serve are also on dc5

If we all use api.telegram.org, our access is very slow, there will be a delay of at least 200ms, and the user experience is very bad.

If the bot local server is allowed to log in to an unlimited number of bots, we can set up our own api.myhost.com near dc5 to provide users with a better experience.

@levlam

**Comment by levlam** [comment]
There are no limits based on IP address. Flood limits by IP address would be absolutely meaningless, restricting most of real users, which don't have dedicated IP addresses, and failing to prevent real flood.

There is no limit on the number of active bots per server either. In the provided log only bot 1376476108 had issues, because it sent too much queries.

**Comment by mylukin** [comment]
Because the bot 1376476108 calls too many queries, will it cause all other
bots to go offline?  I found that all bots have problems receiving
messages, and the webhook cannot be called back. All bots on this server
have generated a lot of message accumulation.

**Comment by levlam** [comment]
> Because the bot 1376476108 calls too many queries, will it cause all other bots to go offline? 

No.

**Comment by mylukin** [comment]
> > Because the bot 1376476108 calls too many queries, will it cause all other bots to go offline?
> 
> No.

My bot has too many messages, and received a lot of 420 errors, how can I avoid this?




[ 2][t 1][1645716333.117565870][NetQueryDelayer.cpp:73][#401234709][!NetQueryDelayer]   Failed: [Query:[id:6254034944][tl:0xad8c9a23][state:Query]] [timeout:26.000000][total_timeout:26.000000] 
because of [Error : 420 : FLOOD_WAIT_26] from Session:5:main#18::Connect::Tcp::[91.108.56.181:443] to DcId{5} from [172.19.0.14:32892]
[ 2][t 1][1645716333.117607116][NetQueryDelayer.cpp:73][#401234709][!NetQueryDelayer]   Failed: [Query:[id:6255017984][tl:0xad8c9a23][state:Query]] [timeout:26.000000][total_timeout:26.000000] 
because of [Error : 420 : FLOOD_WAIT_26] from Session:5:main#18::Connect::Tcp::[91.108.56.181:443] to DcId{5} from [172.19.0.14:32892]
[ 2][t 1][1645716333.118942022][NetQueryDelayer.cpp:73][#401234709][!NetQueryDelayer]   Failed: [Query:[id:6254755840][tl:0xad8c9a23][state:Query]] [timeout:26.000000][total_timeout:26.000000] 
because of [Error : 420 : FLOOD_WAIT_26] from Session:5:main#12::Connect::Tcp::[91.108.56.181:443] to DcId{5} from [172.19.0.14:60792]

**Comment by levlam** [comment]
@mylukin You need to find, why does it try to get so much messages from the server. Most of the time messages should be taken from the Bot API cache, so there is no need for the server request.

**Comment by mylukin** [comment]
> @mylukin You need to find, why does it try to get so much messages from the server. Most of the time messages should be taken from the Bot API cache, so there is no need for the server request.

It looks like I need to get rid of all these accumulated messages, otherwise, my bot can't continue to serve.

head_update_id 636905444
tail_update_id 640627459
pending_update_count 551057
webhook_max_connections 10000
request_count/sec 394.659405 189.188595 309.219208 394.659406
update_count/sec 1422.103991 1335.163216 1381.293465 1422.103992
