### ISSUE TITLE
Any Update Mechanism ?

### ISSUE THREAD

**Issue by erfanmola** [tdlib/telegram-bot-api#240]
Is there any plan on updating mechanism ? I suppose the current way of keeping our telegram-bot-api is we vitit this repo daily, to see if any new commits made, then re-clone/fetch the repo and build again and again and again

Are there any plans for internal updates ? or at least some binary releases that we can update weekly from a repo ?

**Comment by levlam** [comment]
There are no plans to automatically download and run executables on your server.

There is no way to provide binary releases, given the amount of supported operating systems.

**Comment by nordiauwu** [comment]
> There is no way to provide binary releases, given the amount of supported operating systems.

You could at least provide Linux binary, as everyone uses it.

**Comment by levlam** [comment]
@nordiauwu There are no such thing as "Linux binary", unless you link all dependencies statically, which is discouraged by virtually any Linux distribution. And even in this case you must build separately for all supported architectures.
