### ISSUE TITLE
file download request doesn't download the file sometimes

### ISSUE THREAD

**Issue by aliforever** [tdlib/telegram-bot-api#241]
Hi.

I'm not sure if this is a problem with the API or something with my server, wanted to check with you.

The problem is that sometimes the request to download a file succeeds with a response but the file is not downloaded. Although it takes some time for the request to finish (the process of downloading the file).

This is the JSON I receive:
```json
{"ok":true,"result":{"file_id":"BAACAgQAAxkDAAEEk8RiHbVeuyEut_IvFkAGTtp-aQ5eWAACmAoAAjRacVEYHJro99UtfSME","file_unique_id":"AgADmAoAAjRacVE","file_size":1412025372,"file_path":"/root/telegram-bot-api/bin/API/videos/file_219.mp4"}}
```

But when checking the path "/root/telegram-bot-api/bin/API/videos/file_219.mp4", there are no such files there.

The solution is to repeat the file download. How am I supposed to track this issue?

**Comment by levlam** [comment]
The file must be there for at least an hour after getFile call. You can try to set log verbosity level to 6 and try to find some clues in the log.

**Comment by aliforever** [comment]
Unfortunately I wasn't able to track the problem using log level 6. I've made a few changes to my bot to only download files if they are not already downloaded (available on disk). I've also added a mutex to prevent 2 users downloading the same file_unique_id at the same time. This seems to have fixed the problem, but i'll update the issue if it happens again.
