### ISSUE TITLE
getFile method won't work

### ISSUE THREAD

**Issue by Mahdi-Elvis** [tdlib/telegram-bot-api#244]
Hi, recently I've been encountered a problem. when I try to use method `getFile` on a file it just stuck on loading, I tested both large and small size (200KB) no difference. is there any solution?

**Comment by levlam** [comment]
Do you use api.telegram.org?

**Comment by Mahdi-Elvis** [comment]
> Do you use api.telegram.org?

No I logged out of telegram cloud and ran it on local server, I was just fine about a week ago. I did test it again and after long duration it finally downloaded. Don't know why it takes it so long. (Btw `getFile` on api.telegram.org is slow too)

**Comment by levlam** [comment]
Then there is no issue. Likely, you have some network issue, which prevents file downloading. You can check Bot API server logs with verbosity level 2 to see them.

**Comment by Mahdi-Elvis** [comment]
> Then there is no issue. Likely, you have some network issue, which prevents file downloading. You can check Bot API server logs with verbosity level 2 to see them.

Yeah looks like telegram limited my ip connection speed. I tried download links with different server and works fine. Thanks.

**Comment by levlam** [comment]
Telegram never limits IP addresses.

**Comment by Mahdi-Elvis** [comment]
> Telegram never limits IP addresses.

My friend has same issue, he and I both tested same dl url with different ips and worked just fine, I can show u screenshot if u like. Im using proxy for solution currently.

**Comment by levlam** [comment]
The cause can be anywhere, but not on Telegram's side.
