### ISSUE TITLE
Request documenting the behavior of `MessageEntity` type `text_mention` when sending messages

### ISSUE THREAD

**Issue by SpriteOvO** [tdlib/telegram-bot-api#245]
Context: https://github.com/teloxide/teloxide/issues/547

After some testing, we can use `MessageEntity`'s `text_mention` type to mention users when sending messages, and the required fields of `user` are `id` only. But this behavior is undocumented, may we document it?

**Comment by levlam** [comment]
It is dcumented that you can pass a list of MessageEntity when sending messages. What exactly is undocumented?

**Comment by SpriteOvO** [comment]
@levlam Using `MessageEntity`'s `text_mention` type to mention users, and the required fields of `user` are `id` only. This is undocumented.

**Comment by levlam** [comment]
All fields are required, but some of them might be currently ignored or fixed to the expected value.

Bots are supposed to use a `MessageEntity`/`User` object, received from Bot API, without the need to change it.

**Comment by SpriteOvO** [comment]
Then how we mention users by id via `MessageEntity`? The type `text_link` with URL `tg://user?id=<user_id>` didn't work as expected, Telegram clients treat the link as a normal URL and not as a user mention URL. In different clients, such "user mention URLs as normal URLs" are handled differently:

- In `tdesktop`, clicking on the URL does not give any response.
- In Telegram iOS, clicking on the URL asks and then jumps to the user panel.

**Comment by RememberTheAir** [comment]
@SpriteOvO just to make sure you're building the url correctly: you are supposed to use it within an `<a>` tag. For example, `<a href="tg://user?id=1234567">this is a text mention</a>`. Not every app is capable to properly handle `tg://` urls, because some of them are not intended to be used "raw"

**Comment by RememberTheAir** [comment]
@SpriteOvO sorry, for some reason my brain completely erased the fact that you're providing a `MessageEntity` array. Nvm.

**Comment by SpriteOvO** [comment]
@levlam Ok. If we have to use `MessageEntity` `text_mention` with a full `User` structure to mention a user:
- We need to store the full `User` structure in the database, not just a user id. But that's ok, not a big deal.
- Users may change some states in the meantime, which makes it inconsistent with the `User` data we have stored.
- If some fields will be added to the `User` structure in the future, this would be a breaking change for the stored `User` data.

Forgive me for still wondering if is it possible to change the `MessageEntity` `text_link` behavior to be consistent with `formatting-options` `link`? If we think of it as a bug fix, it's probably not a breaking change.

**Comment by SpriteOvO** [comment]
I noticed that the bug seems to be fixed in Bot API 6.0, so I'm going to close this issue, thanks @levlam!

**Comment by WaffleLapkin** [comment]
@SpriteOvO can you explain what exactly was fixed?

**Comment by SpriteOvO** [comment]
> @SpriteOvO can you explain what exactly was fixed?

@WaffleLapkin Before Bot API 6.0, constructing a `MessageEntity` `text_link` as a request with `tg://user?id=1234567` would be incorrectly formatted as a normal URL instead of a special UserLink. This caused some of the problems [mentioned above](https://github.com/tdlib/telegram-bot-api/issues/245#issuecomment-1067025515).

Since Bot API 6.0, it can now be properly formatted as a special UserLink, and this does not require any changes from Bot clients.
