### ISSUE TITLE
[Feature Request] Add 'scheduled' property to Message

### ISSUE THREAD

**Issue by Agadar** [tdlib/telegram-bot-api#246]
Message exposes a 'voice_chat_scheduled' property, but weirdly enough not a simple 'scheduled' property. This is an issue because a bot I am working on has to ignore scheduled messages and only allow unscheduled (i.e. normal) messages.

TDLib does already support a 'from_scheduled' field (https://core.telegram.org/constructor/message).

**Comment by levlam** [comment]
There is no way to distinguish "scheduled" messages. They are absolutely the same as ordinary messages. It is clearly theoretically impossible to know whether a message was sent by a user or "scheduled" and send automatically by some means.

**Comment by Agadar** [comment]
Forgive my ignorance, but if it is theoretically impossible to know, then how is it possible that the Bot API already supports another type of scheduled indicator 'voice_chat_scheduled' and that TDLib **does** support a 'scheduled_from'field?

**Comment by RememberTheAir** [comment]
Because the API is designed to expose such information just for scheduled voice chats - which are a completely different topic. tdlib can go as far as the API lets it go - if no such information is delivered to clients by the API, tdlib cannot expose it either

**Comment by levlam** [comment]
@Agadar

"voice_chat_scheduled" is a type of the message content. It is not different from "photo" or "sticker" and it is completely unrelated to message scheduling.

Also, TDLib has nothing like "'scheduled_from" in TDLib API: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl.

**Comment by SergeyOdnosteblets** [comment]
Still no way to keep track of scheduled messages? Didn't find any new information on this issue

**Comment by MajorTom007** [comment]
Still no way to keep track of scheduled messages? Didn't find any new information on this issue

**Comment by levlam** [comment]
@MajorTom007 Scheduled messages are supposed to be exactly the same as non-scheduled one. There is no way to distinguish them.

**Comment by MajorTom007** [comment]
@levlam It is not right.
Sometimes you need to distinguish between such messages.
Bots are used in different chats, this feature would be very helpful

**Comment by levlam** [comment]
This feature isn't planned. Users aren't suppose to distinguish scheduled messages of other users.
