### ISSUE TITLE
How to view service logs for my Telegram Bot

### ISSUE THREAD

**Issue by lpkoh** [tdlib/telegram-bot-api#247]
I've set up a Telegram bot. It can receive messages and broadcast it to a channel I created, as intended. All queries to the Telegram Bot API must be served over HTTPS and are presented in this form: https://api.telegram.org/bot/METHOD_NAME (Reference: https://core.telegram.org/bots/api)

How do I check the history of requests to the API?

For example, if I made a request of form: HTTP POST https://api.telegram.org/bot/?confirmationToken={confirmationToken} How do I see this request to the API?

**Comment by levlam** [comment]
If you've got any questions about bots kindly contact [@BotSupport](https://t.me/BotSupport) in Telegram or ask a question in [BotTalk](https://t.me/BotTalk).
