### ISSUE TITLE
Add callback_data to KeyboardButton (reply_markup.keyboard)

### ISSUE THREAD

**Issue by mihaon** [tdlib/telegram-bot-api#251]
Without the callback_data field in the reply_markup.keyboard field I need to do some extra conditions in the bot code when I want to use the reply_markup.keyboard as the menu.

# Example 1

I have something like this:
```
/sendMessage
{
	"chat_id": 12345,
	"text": "Choose action",
	"reply_markup": {
		"keyboard": [
			[{"text": "Show services"}],
			[{"text": "Show products"}]
		]
	}
}
```

## Actual result
1. When a user clicks the keyboard button
2. Then a new message is added to the chat (e.g. "Show services" message)
3. Then the bot receives Update.message.text
4. Then the bot sends a new message with the related content

## Expected result
1. The reply_markup.keyboard buttons has callback_data field
2. When a user clicks the keyboard button
3. Then the bot receives Update.callback_query.data
4. Then the bot sends a new message with the related content. I.e. the user doesn't see the "Show services" message (which is obviously redundant)

# Example 2

I have something like this:
```
/sendMessage
{
	"chat_id": 12345,
	"text": "Enter search query",
	"reply_markup": {
		"keyboard": [
			[{"text": "Add advert"}],
			[{"text": "Back"}],
		]
	}
}
```

## Actual result
1. When a user sends the message with the search query (e.g. "car")
2. Then the bot receives the Update.message.text and in the bot code I have to manually check for the search query is not equal to "Add advert" or "Back" to keep the keyboard functionality.

## Expected result
The keyboard buttons contains callback_data and the bot handler triggers on Update.callback_query.data rather then on Update.message.text. Therefore I don't need to distinguish the keyboard button click from the search query input.

**Comment by levlam** [comment]
Keyboard buttons and inline keyboard buttons have very different behavior and serve different purposes. Keyboard buttons are expected to always send a message as result of they clicking. Inline keyboard buttons on the contrary aren't supposed to send a message and can only send callback query instead. This makes button behavior predictable for users and isn't expected to change.
