### ISSUE TITLE
Long responses while high load !

### ISSUE THREAD

**Issue by mnkblog** [tdlib/telegram-bot-api#254]
I'm experiencing some issues as mentioned in title !

It takes longer than usual forexample a sendMessage takes about 1 second to respond back.

I'm using curl_multi_init in PHP to send message to multiple users at the same time. for a game & chat purpose and I can't change because users are happy with it.

I'm not getting 429 error ! but also I can't understand why it should be slow on high loads!

It's not a resource problem as CPU in average 2% and only 10% of server's memory is in use.

I have no clue about the networking of the server but it's hetzer finland location.

here is some logs:
( I must mention that the api= is actually a different bot token. )
It clearly shows this problem happens on high load because texts are similar.

URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=125405****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۲</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>محدثه</b></u> به <u><b>مهتا</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:02] Took 1.383043 to finish api=0
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=180390****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۲</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>محدثه</b></u> به <u><b>مهتا</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 2.044794 to finish api=5
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=1254056****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.380002 to finish api=5
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=126607****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.370661 to finish api=1
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=137855****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.356331 to finish api=1
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=140552****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.345066 to finish api=1
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=148424****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.378432 to finish api=1
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=157359****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.230961 to finish api=17
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=171450****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.919404 to finish api=0
URL=> http://127.0.0.1:8081/botXXXXX/sendMessage?chat_id=180390****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.304997 to finish api=22
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=206386****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.466971 to finish api=23
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=518169****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:03] Took 1.385182 to finish api=0
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=89304****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>مهتا</b></u> ‏<b>۱</b> رای، \n‏<u><b>تابان</b></u> به <u><b>لـئو ستاره</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:04] Took 1.021891 to finish api=5
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=125405****&text=‏<u><b>لـئو ستاره</b></u> ‏<b>۳</b> رای، ‏<u><b>کت وومن</b></u> ‏<b>۱</b> رای، \n‏<u><b>محدثه</b></u> رای خود را پس گرفت و به <u><b>کت وومن</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:05] Took 1.182429 to finish api=3
URL=> http://127.0.0.1:8081/botXXXX/sendMessage?chat_id=106844****&text=‏<u><b>سوگندی</b></u> ‏<b>۳</b> رای، \n‏<u><b>مهی</b></u> به <u><b>سوگندی</b></u> رای داد.&parse_mode=html
[2022-04-11 23:32:06] Took 1.586595 to finish api=6

**Comment by levlam** [comment]
If CPU usage remains low, then the problem isn't in the server. Increase server log verbosity level to 3 with the parameter `-v3` and try to find the clues in the log.

**Comment by mnkblog** [comment]
what should I look for in log in particular?

Are you sure telegram doesn't limit my requests by volume ?

**Comment by levlam** [comment]
> what should I look for in log in particular?

Track, how the request was completed.

> Are you sure telegram doesn't limit my requests by volume ?

Absolutely.

**Comment by mnkblog** [comment]
Here are some in normal condition

[ 2][t 1][1649926389.039792060][Stats.h:58]	CPU usage: 12.599928%
[ 2][t 1][1649926390.040127754][Stats.h:58]	CPU usage: 12.285834%
[ 2][t 1][1649926391.039160728][Stats.h:58]	CPU usage: 12.367688%
[ 2][t 1][1649926392.040053129][Stats.h:58]	CPU usage: 12.527142%
[ 2][t 1][1649926393.039263248][Stats.h:58]	CPU usage: 12.759171%
[ 2][t 1][1649926393.482245922][telegram-bot-api.cpp:144]	[rss:2741MB]
[ 2][t 1][1649926393.482260465][telegram-bot-api.cpp:145]	[vm:3113MB]
[ 2][t 1][1649926393.482263326][telegram-bot-api.cpp:146]	[rss_peak:2741MB]
[ 2][t 1][1649926393.482265949][telegram-bot-api.cpp:147]	[vm_peak:3113MB]
[ 2][t 1][1649926393.482268571][telegram-bot-api.cpp:149]	[buffer_mem:37MB]
[ 2][t 1][1649926393.482271432][telegram-bot-api.cpp:150]	[buffer_slice_size:0B]
[ 2][t 1][1649926393.482273817][telegram-bot-api.cpp:154]	[pending queries:22][pending requests:22]
[ 2][t 1][1649926393.482276678][telegram-bot-api.cpp:164]	[TOKEN][time:   **476.7ms**][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🏆<a href="https://jxs6sdzq3mvne.ir/">‏</a> <u><b>عمورامین</b></u> ‏: مخلصم]}
[ 2][t 1][1649926393.482284784][telegram-bot-api.cpp:164]	[TOKEN][time:   **312.4ms**][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🏆<a href="https://szpajsyk359a.ir/">‏</a> <u><b>سارا</b></u> ‏: اسنا بشات🛑]}
[ 2][t 1][1649926393.482290506][telegram-bot-api.cpp:164]	[TOKEN][time:    60.6ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🦂<a href="https://jxs6sd30ejn51.ir/">‏</a> <u><b>ساحل</b></u> (لکتر) ‏: پدررررر نوب سگگگگ]}
[ 2][t 1][1649926393.482295989][telegram-bot-api.cpp:164]	[TOKEN][time:    52.3ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🏆<a href="https://jxs6sdzh2k1yk.ir/">‏</a> <u><b>عشق بازپرس</b></u> ‏: باز منو بگیر]}
[ 2][t 1][1649926393.482315063][telegram-bot-api.cpp:164]	[TOKEN][time:    46.3ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🥈<a href="https://szpajs7rpor8.ir/">‏</a> <u><b>دایی بازپرس</b></u> ‏: گزارش شه😂]}
[ 2][t 1][1649926393.482320308][telegram-bot-api.cpp:164]	[TOKEN][time:    44.7ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏⚔️<a href="https://szpajtmmxjd4.ir/">‏</a> <u><b>گلومرول</b></u> ‏: نقطه میپرسی؟]}
[ 2][t 1][1649926393.482324838][telegram-bot-api.cpp:164]	[TOKEN][time:    43.8ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🌪<a href="https://jxs6sdpb95m3l.ir/">‏</a> <u><b>آئو آکانه</b></u> ‏: ساحره از کارا اس بگیر]}
[ 2][t 1][1649926393.482329607][telegram-bot-api.cpp:164]	[TOKEN][time:    29.6ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🎖<a href="https://jxs6sdzu62bq3.ir/">‏</a> <u><b>کیمیا</b></u> ‏: چغوک تک🛑🛑]}
[ 2][t 1][1649926393.482334136][telegram-bot-api.cpp:164]	[TOKEN][time:    28.7ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏💫<a href="https://jxs6sd5wajlj7.ir/">‏</a> <u><b>دختر وحشی</b></u> ‏: شاید رل شدیم]}
[ 2][t 1][1649926393.482339143][telegram-bot-api.cpp:164]	[TOKEN][time:    27.0ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🏆<a href="https://hpk1gsh3j7gl.ir/">‏</a> <u><b>مهتاب</b></u> ‏: گناه]}
[ 2][t 1][1649926393.482343196][telegram-bot-api.cpp:164]	[TOKEN][time:    25.6ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏💥<a href="https://jxs6sdu7bpl1j.ir/">‏</a> <u><b>کاناشی</b></u> ‏: پری]}
[ 2][t 1][1649926393.482347965][telegram-bot-api.cpp:164]	[TOKEN][time:    24.4ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🌈<a href="https://szpajtupkmza.ir/">‏</a> <u><b>شری</b></u> ‏: مظفر میگمممم نوبااا]}
[ 2][t 1][1649926393.482352495][telegram-bot-api.cpp:164]	[TOKEN][time:    23.1ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🦂<a href="https://jxs6sdpcmejs2.ir/">‏</a> <u><b>کویین</b></u> ‏: باز ادا بگیر]}
[ 2][t 1][1649926393.482357025][telegram-bot-api.cpp:164]	[TOKEN][time:    12.7ms][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🏆<a href="https://hpk1gsj90rye.ir/">‏</a> <u><b>سحرطلا</b></u> ‏: حله]}
[ 2][t 1][1649926393.482361078][telegram-bot-api.cpp:164]	[TOKEN][time:  9696.1us][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🥉<a href="https://jxs6sd5xv7hmc.ir/">‏</a> <u><b>ثَنآَمٖـ</b></u> ‏: اصکل]}
[ 2][t 1][1649926393.482365846][telegram-bot-api.cpp:164]	[TOKEN][time:  3109.7us][method:         sendmessage]{[chat_id;****], [parse_mode;html], [text;‏🐲<a href="https://jxs6sd4gc8phs.ir/">‏</a> <u><b>همتا</b></u> ‏: دو]}
[ 2][t 1][1649926393.482372045][telegram-bot-api.cpp:164]	[TOKEN][time:  1209.2us][method:         sendmessage]{[text;‏<u><b>نَِرَِگَِسََِِ</b></u> از بازی خارج شد.], [parse_mode;html], [chat_id;****]}
[ 2][t 1][1649926393.482376337][telegram-bot-api.cpp:164]	[TOKEN][time:   937.1us][method:         sendmessage]{[text;‏<u><b>نَِرَِگَِسََِِ</b></u> از بازی خارج شد.], [parse_mode;html], [chat_id;****]}
[ 2][t 1][1649926393.482384443][telegram-bot-api.cpp:164]	[TOKEN][time:   857.3us][method:         sendmessage]{[text;‏<u><b>نَِرَِگَِسََِِ</b></u> از بازی خارج شد.], [parse_mode;html], [chat_id;****]}
[ 2][t 1][1649926393.482388734][telegram-bot-api.cpp:164]	[TOKEN][time:   794.3us][method:         sendmessage]{[text;‏<u><b>نَِرَِگَِسََِِ</b></u> از بازی خارج شد.], [parse_mode;html], [chat_id;****]}
[ 2][t 1][1649926393.482393264][telegram-bot-api.cpp:164]	[TOKEN][time:   724.8us][method:         sendmessage]{[text;‏<u><b>نَِرَِگَِسََِِ</b></u> از بازی خارج شد.], [parse_mode;html], [chat_id;****]}
[ 2][t 1][1649926393.482397317][telegram-bot-api.cpp:164]	[TOKEN][time:   656.8us][method:         sendmessage]{[text;‏<u><b>نَِرَِگَِسََِِ</b></u> از بازی خارج شد.], [parse_mode;html], [chat_id;****]}
[ 2][t 1][1649926393.482414960][NetQueryStats.cpp:25]	[pending net queries:22]
[ 2][t 1][1649926393.482418537][NetQueryStats.cpp:43]	[user:5227720348][Query:[id:7044929355776][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:476.7ms][state:Session: trying to send to mtproto::connection][in this state:476.6ms][state changed:8][resend count:0][fail count:0][ack state:1][unknown:false]
[ 2][t 1][1649926393.482426643][NetQueryStats.cpp:43]	[user:5120860417][Query:[id:7044932304896][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:312.4ms][state:Session: trying to send to mtproto::connection][in this state:312.4ms][state changed:8][resend count:0][fail count:0][ack state:1][unknown:false]
[ 2][t 1][1649926393.482432365][NetQueryStats.cpp:43]	[user:5184383316][Query:[id:7044934533120][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:60.6ms][state:Session: trying to send to mtproto::connection][in this state:60.6ms][state changed:8][resend count:0][fail count:0][ack state:1][unknown:false]
[ 2][t 1][1649926393.482438087][NetQueryStats.cpp:43]	[user:1371555189][Query:[id:7044934598656][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:52.3ms][state:Session: trying to send to mtproto::connection][in this state:52.3ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482443809][NetQueryStats.cpp:43]	[user:5293008611][Query:[id:7044934664192][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:46.3ms][state:Session: trying to send to mtproto::connection][in this state:46.3ms][state changed:8][resend count:0][fail count:0][ack state:1][unknown:false]
[ 2][t 1][1649926393.482449293][NetQueryStats.cpp:43]	[user:1339857399][Query:[id:7044934729728][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:44.7ms][state:Session: trying to send to mtproto::connection][in this state:44.6ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482454776][NetQueryStats.cpp:43]	[user:1327750607][Query:[id:7044934795264][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:43.8ms][state:Session: trying to send to mtproto::connection][in this state:43.8ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482460498][NetQueryStats.cpp:43]	[user:1319343343][Query:[id:7044934860800][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:29.6ms][state:Session: trying to send to mtproto::connection][in this state:29.6ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482466220][NetQueryStats.cpp:43]	[user:1385965744][Query:[id:7044934926336][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:28.7ms][state:Session: trying to send to mtproto::connection][in this state:28.6ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482475280][NetQueryStats.cpp:43]	[user:1177538436][Query:[id:7044934991872][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:27.0ms][state:Session: trying to send to mtproto::connection][in this state:27.0ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482481002][NetQueryStats.cpp:43]	[user:1316451765][Query:[id:7044935057408][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:25.6ms][state:Session: trying to send to mtproto::connection][in this state:25.5ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482486486][NetQueryStats.cpp:43]	[user:1327750607][Query:[id:7044935122944][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:24.4ms][state:Session: trying to send to mtproto::connection][in this state:24.4ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482491731][NetQueryStats.cpp:43]	[user:1680298430][Query:[id:7044935188480][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:23.1ms][state:Session: trying to send to mtproto::connection][in this state:23.1ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482497453][NetQueryStats.cpp:43]	[user:1385965744][Query:[id:7044935254016][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:12.7ms][state:Session: trying to send to mtproto::connection][in this state:12.7ms][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482503175][NetQueryStats.cpp:43]	[user:1348513040][Query:[id:7044935319552][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:9694.3us][state:Session: trying to send to mtproto::connection][in this state:9653.4us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482509136][NetQueryStats.cpp:43]	[user:1697949566][Query:[id:7044935385088][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:3095.3us][state:Session: trying to send to mtproto::connection][in this state:3051.8us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482514858][NetQueryStats.cpp:43]	[user:1697949566][Query:[id:7044935450624][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:1224.9us][state:Session: trying to send to mtproto::connection][in this state:1182.9us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482520103][NetQueryStats.cpp:43]	[user:5127996686][Query:[id:7044935516160][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:681.2us][state:Session: trying to send to mtproto::connection][in this state:387.0us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482525825][NetQueryStats.cpp:43]	[user:1177538436][Query:[id:7044935581696][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:614.5us][state:Session: trying to send to mtproto::connection][in this state:374.0us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482530832][NetQueryStats.cpp:43]	[user:1275796526][Query:[id:7044935647232][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:557.8us][state:Session: trying to send to mtproto::connection][in this state:366.2us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482536315][NetQueryStats.cpp:43]	[user:1216433802][Query:[id:7044935712768][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:498.6us][state:Session: trying to send to mtproto::connection][in this state:358.8us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926393.482541561][NetQueryStats.cpp:43]	[user:1122796290][Query:[id:7044935778304][tl:0x0d9d75a4][state:Query]][total flood:0.0ns][since start:441.5us][state:Session: trying to send to mtproto::connection][in this state:349.2us][state changed:8][resend count:0][fail count:0][ack state:0][unknown:false]
[ 2][t 1][1649926394.039416074][Stats.h:58]	CPU usage: 13.041661%
[ 2][t 1][1649926395.039160966][Stats.h:58]	CPU usage: 12.892444%
[ 2][t 1][1649926396.039318084][Stats.h:58]	CPU usage: 12.784625%
[ 2][t 1][1649926397.039487361][Stats.h:58]	CPU usage: 12.588192%

**Comment by mnkblog** [comment]
[ 2][t 1][1649926693.484029769][telegram-bot-api.cpp:164]	[bot1][time:  1519.0ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏💎<a href="https://jxs6tf6teplr0.ir/">‏</a> <u><b>دخترک</b></u> ‏: نوبا دید مرد]}
[ 2][t 1][1649926693.484039306][telegram-bot-api.cpp:164]	[bot4][time:   634.8ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏💥<a href="https://szpanm6abfft.ir/">‏</a> <u><b>بلقیس</b></u> ‏: چ شانسی]}
[ 2][t 1][1649926693.484044790][telegram-bot-api.cpp:164]	[bot3][time:   555.5ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏👻<a href="https://jxs6tf91seskj.ir/">‏</a> <u><b>پادمیرا</b></u> ‏: گفت فرشته ام ولی فک کنم زر زده]}
[ 2][t 1][1649926693.484050512][telegram-bot-api.cpp:164]	[bot1][time:   134.2ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏🧛🏻‍♂️<a href="https://jxs6tf9nu29jk.ir/">‏</a> <u><b>دِوًاًّژًِدَهِ</b></u> <i>(مرده)</i> ‏: درست سیو کردم]}
[ 2][t 1][1649926693.484056711][telegram-bot-api.cpp:164]	[bot1][time:   128.4ms][method:         sendmessage]{[chat_id;********], [text;‏<u><b>استقلال زاگرس</b></u><i> (شیاد)</i> : ‏<b>زاکر سامورایی</b> را انتخاب کرد.], [parse_mode;html]}
[ 2][t 1][1649926693.484061956][telegram-bot-api.cpp:164]	[bot1][time:   124.8ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏💎<a href="https://szpannj3zs6j.ir/">‏</a> <u><b>مَهدیه</b></u> ‏: زد]}
[ 2][t 1][1649926693.484067916][telegram-bot-api.cpp:164]	[bot1][time:   118.4ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏🌾<a href="https://szpanm1vsx8o.ir/">‏</a> <u><b>دختِ شـیـ ـرآزی</b></u> ‏: حالا بگیر تو]}
[ 2][t 1][1649926693.484073400][telegram-bot-api.cpp:164]	[bot2][time:   100.3ms][method:         sendmessage]{[chat_id;********], [parse_mode;html], [text;‏🎗<a href="https://szpannip7q2s.ir/">‏</a> <u><b>آنیسا</b></u> ‏: ارسی]}

**Comment by mnkblog** [comment]
@levlam some messages took 35 seconds to complete
what the hell is wrong!
my log is almost 1.5gb how can I find error in that and what kind of error I must look for ?

**Comment by iamDonkey** [comment]
@mnkblog please avoid such harsh words 😐 it is not the right way to approach our engineer  @levlam

**Comment by mnkblog** [comment]
@iamDonkey hey donkey i'm sorry , i definetly need help... can't keep my users happy :(

**Comment by iamDonkey** [comment]
Did you try sendMessage api request via curl cli command? Is it the same speed as php curl? Did you also test php file_get_contents function? What is your php version?

**Comment by levlam** [comment]
@mnkblog If you need help with finding the exact cause, you can send the log in an archive to https://t.me/tdlib_bot,

**Comment by mnkblog** [comment]
@levlam does telegram slow me down if i'm trying to send more than 1 message per second to the same private chat?

**Comment by doaortu** [comment]
hey @mnkblog , did you solved this? can you please share with us what's wrong? and how to solve it? Thanks.
