### ISSUE TITLE
Whether the server supports network proxy

### ISSUE THREAD

**Issue by 2378415** [tdlib/telegram-bot-api#256]
I checked the source code and found that there is SOCKS5 support, but through Google inquiries, I found that it supports the client, and the server has no relevant instructions.

**Comment by levlam** [comment]
What do you mean by "supports network proxy" and "Google inquiries"?

**Comment by 2378415** [comment]
supports network proxy means that MTProxy or SOCKS5 can be set like a telegram client

**Comment by 2378415** [comment]
Google inquiries means that I can't find a way to set a network proxy on Google search or related documents

**Comment by levlam** [comment]
No. The Bot API server is supposed to be placed in a place, from which Telegram is reachable.

**Comment by 2378415** [comment]
I'm in China, which means I can't access telegram, I used a global VPN to solve the problem, but it's too much trouble, I hope the server can support network proxy

**Comment by levlam** [comment]
It isn't a good idea to host the server in China anyway. Sending all request through a proxy may have very bad impact on bot's performance, so it would be much better to host the bot and the local Bot API server in a place close to the corresponding Telegram DC. If this is not an option, you can add call to td_api::addProxy just before https://github.com/tdlib/telegram-bot-api/blob/c57b04c4c8c4e8d8bb6fdd0bd3bfb5b93b9d8f05/telegram-bot-api/Client.cpp#L4145-L4147

**Comment by 2378415** [comment]
Ok thanks for your help, I will consider deploying Bot Server near Telegram DC
