### ISSUE TITLE
ReverseProxy WebApps

### ISSUE THREAD

**Issue by erfanmola** [tdlib/telegram-bot-api#258]
Hi, It would be nice if you add a feature to ReverseProxy WebApps by telegram, One main goal that Developers use telegram is it's security that it offers, We do know that our webhook is never revealed by telegram to the user, we also do know that no matter how many requests there are to the bot, telegram is gonna throttle them so we will not be under pressure

But this new WebApps is entirely putting the Web Apps in front of users UnGuarded

Firstly, It potentially reveals the URL of the WebApp and by knowing the url, It would be easy to find IP address and start DDOS on the server by malicious users, We do know that it is not telegram's concern to protect us from attacks, but in such cases we have to use another ReverseProxy like CloudFlare or etc which add another latency to the end user requests

It would be really nice if telegram adds ability to ReverseProxy our URL to our server, or even further you can launch your own WebApp Platform and even provide us with DNS Settings to route our domains or telegram provided subdomains (example.app.telegram.org) to our own servers, knowing that we are behind the telegram, just as our bots are

Most people will try to run their WebApps on the same server that their bots are on, so this may actually threaten the security of their bots, We do know that we have to implement security checks on our own, but it would be nice if telegram makes us needles of

**Comment by hamidreza01** [comment]
I hope Telegram implements this, Telegram has always been the best, it will definitely be now.

**Comment by tbaltrushaitis** [comment]
@erfanmola ,

чувак, никто и ничто не мешает тебе настроить всё, что ты описал - самостоятельно. Доступны и ресурсы и инструменты управления ними. Дерзай ))

w/ kind regards!

**Comment by levlam** [comment]
@erfanmola 
For now, this is unlikely to be implemented, because it is similar to performing a MiTM attack on all HTTPS requests of the user, which were originated from a Web App.

Also, because any site can be open from a web app, it would transform Telegram into a widely used web proxy, which would just lead to blacklisting of relevant Telegram IP addresses by all major hosting providers.

**Comment by erfanmola** [comment]
> @erfanmola 
> 
> For now, this is unlikely to be implemented, because it is similar to performing a MiTM attack on all HTTPS requests of the user, which were originated from a Web App.
> 
> 
> 
> Also, because any site can be open from a web app, it would transform Telegram into a widely used web proxy, which would just lead to blacklisting of relevant Telegram IP addresses by all major hosting providers.

Thanks for response, What about a tiny platform for Server-Less static WebApps that we upload to telegram, and is served by telegram as static content ?

Most apps may not even need a server to perform

**Comment by levlam** [comment]
> What about a tiny platform for Server-Less static WebApps that we upload to telegram, and is served by telegram as static content?

This is possible and is very likely to be hosted by Telegram.

**Comment by erfanmola** [comment]
> > What about a tiny platform for Server-Less static WebApps that we upload to telegram, and is served by telegram as static content?
> 
> 
> 
> This is possible and is very likely to be hosted by Telegram.

Looking forward to it

Also as the WebApps are WebViews, the MTProto Proxies or other in-app level proxies don't affect them, and as the WebApp JS file is served from telegram domain, it gets blocked in countries like IRAN that deny any connection to Telegram, causing a blank screen

Would be nice if telegram serves its JS file from a CDN like jsdeliver or etc, and always maintain it to the latest version
