### ISSUE TITLE
Download files from not local mode

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#26]
The file path is like documents/file_5, but I cant figure out how to download it. It doesn't work like the cloud API suggests, I am getting a 404 not found error then. Am I missing something?

**Comment by levlam** [comment]
After `getFile` request the downloaded files are stored locally in the server working directory under the path returned in `getFile` response. After that the files can be served from that directory using any HTTP-server suitable for serving static files.

**Comment by Poolitzer** [comment]
so I have to run a separate process for serving the files, alright. Thanks for clearing that up.

**Comment by levlam** [comment]
@Poolitzer Yes. But you can usually use the same process, which is used as a TLS-terminating proxy.

**Comment by TopperBG** [comment]
Could be I miss something, but in that construction .getFile() returns me file_paht in form:
http://nginx:88/file/botTOKEN//var/lib/telegram-bot-api/TOKEN/documents/file_17.exe
Obviously doubled path and somekind concatenated ?
@Poolitzer how did you manage to get local file trough API ?

**Comment by levlam** [comment]
@TopperBG 
Local Bot API server returns only "/var/lib/telegram-bot-api/TOKEN/documents/file_17.exe". It is your Bot API library adding the rest. because doesn't know that the server is run in a local mode.
