### ISSUE TITLE
Bad Request: can't parse entities....

### ISSUE THREAD

**Issue by uriid1** [tdlib/telegram-bot-api#265]
If I want to send bold text with parse_mode=HTML
For example, this: **TEST <3**
I am replacing `<3` with `&lt;`
Then text I want to send is: `<b>TEST &lt;3</b>`

Test in browser:
https://api.telegram.org/botTOKEN/sendMessage?parse_mode=HTML&chat_id=YOUR_CHAT_ID&text= `<b>TEST &lt;3</b>`

Unfortunately, sending such a text leads to an error:
Bad Request: can't parse entities: Can't find end tag corresponding to start tag b

This has never happened before.

**Comment by levlam** [comment]
The error message is 100% correct. You are sending a request with parameter `text` = "<b>TEST " and parameter `lt;3</b>` without value.

**Comment by nmlorg** [comment]
(And so what you should do is call [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) or equivalent; in this case you'd send `text=%3Cb%3ETEST%20%26lt%3B3%3C%2Fb%3E`.)

**Comment by nmlorg** [comment]
The raw `&` is the problem—that's what separates fields in [`application/x-www-form-urlencoded`](https://url.spec.whatwg.org/#urlencoded-serializing). You need to replace it with `%26` (which `encodeURIComponent`, etc., should do for you).

**Comment by uriid1** [comment]
Yes, it looks like this is the solution. Thanks!
