### ISSUE TITLE
Passing text entities to sendMessage, or any other methods doesn't seems to work

### ISSUE THREAD

**Issue by sabbyX** [tdlib/telegram-bot-api#27]
That's it. entities doesn't seem to apply at all.

An example I tried out:
text: `bold`
entities: `[{"type":"bold", "offset": 0, "length": 4}]`

**Comment by levlam** [comment]
The parameters are correct, but the request is wrong then. You can try in a browser that the request works: https://api.telegram.org/botTOKEN/sendmessage?chat_id=CHAT_ID&text=bold&entities=[{%22type%22:%22bold%22,%22offset%22:0,%22length%22:4}]

**Comment by sabbyX** [comment]
Yeah, it worked, its a bug in the library I used
