### ISSUE TITLE
implement getFile progress

### ISSUE THREAD

**Issue by aliforever** [tdlib/telegram-bot-api#272]
Hi,

In every mtproto client users are able to find out about the download progress. As I was checking it is also written in log with this package.

Currently the only way to find out about the download progress is by checking `temp` directory:
```/root/telegram-bot-api/bin/<Token>/temp```

If we constantly do `ls -l --block-size=M` there, we can see file sizes growing because of the download process.

One can implement weird solutions to match those integer file names with their file id and find out about the download prgress programmatically.

Now my question is that is it possible for this package to store information regarding file download progress on a storage? We can pass the storage to it, it just needs to provide an interface to write such information.

Please let me know if there are other solutions you can think of regarding this problem.

![image](https://user-images.githubusercontent.com/14090252/168535558-9f7a6273-b10f-4aeb-809c-7304aa1ac92b.png)

**Comment by levlam** [comment]
This is out of scope for Bot API server. See https://github.com/tdlib/telegram-bot-api/issues/37 for more details.

But download progress is handled by the function https://github.com/tdlib/telegram-bot-api/blob/8a0f1dd730aa41ab7b792b9ff03d92b1c5022c9f/telegram-bot-api/Client.cpp#L4306

Hence you can implement download progress in some way.
