### ISSUE TITLE
Getting Sticker statistics

### ISSUE THREAD

**Issue by SeMech** [tdlib/telegram-bot-api#274]
Hi! I would like to know how to get statistics on sticker sets. How can I do this?

**Comment by levlam** [comment]
Bots can't do that. The user, which owns the sticker set, can do this through @stickers bot.

**Comment by SeMech** [comment]
Is such an opportunity expected to appear in the future?

**Comment by levlam** [comment]
This is unlikely, because statistical data polling is not scalable.

**Comment by SeMech** [comment]
Thanks for the reply. 
Can I expect to be able to delete a set?

**Comment by levlam** [comment]
For sticker set deletion you can follow https://github.com/tdlib/telegram-bot-api/issues/262.

**Comment by SeMech** [comment]
That is, to delete a set, you need to remove all the stickers from it?

**Comment by levlam** [comment]
No, currently only the user owning the set can delete it. But even the set is deleted, it doesn't mean that the set's name can be reused immediately.

**Comment by SeMech** [comment]
Well, thank you!
I will keep an eye on updates :)
