### ISSUE TITLE
Help plz in sending  local files

### ISSUE THREAD

**Issue by rootgithubbeta** [tdlib/telegram-bot-api#277]
Hello all 

I built the source code and started server with --local tag and I want to send a file in my /root folder
test.zip as document.
I found that I have to use something starting with file:/// 

Can someone send me a example url  of how to do that using localhost:8081/botToken/sendDocument api url
Thank you

**Comment by levlam** [comment]
https://en.wikipedia.org/wiki/File_URI_scheme has a lot of examples.

**Comment by rootgithubbeta** [comment]
> https://en.wikipedia.org/wiki/File_URI_scheme has a lot of examples.

Thank you for replying sir .
but I get 
b'{"ok":false,"error_code":400,"description":"Bad Request: wrong remote file identifier specified: Wrong character in the string"}'
this error message when i use this
http://localhost:8081/botToken/sendDocument?chat_id=123123123&document=file:///root/test.zip
to upload.
Am I doing it wrong?

**Comment by rootgithubbeta** [comment]
Well this error doesn't when using curl in terminal .Only occurs when using python requests library to send the request.
I'll try to solve it.
If anyone have any idea please post it

**Comment by rootgithubbeta** [comment]
Well it was a mistake in my program.
Sorry guys
