### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by BulykinLife** [tdlib/telegram-bot-api#279]
My hosting only has version 2.8. The hoster says that there is no way to upgrade to 3.2. What can be done in this case? I need to upload videos over 50MB.

CMake Error at td/CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.0.2 or higher is required. You are running version 2.8.12.2
-- Configuring incomplete, errors occurred!

**Comment by levlam** [comment]
Then you can build cmake 3 yourself.
