### ISSUE TITLE
Can't upload files > 20MB on Self Host

### ISSUE THREAD

**Issue by Nickelza** [tdlib/telegram-bot-api#28]
### Behaviors
**Expected behavior**: Being able to upload files < 2000MB if telegram-bot-api is running in local mode
**Actual behavior**: `{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}`

### What I've tried
- Using both HTTP and HTTPS
- URI Scheme: file://path/to/file.jpg with both absolute and relative path, hitting `{"ok":false,"error_code":400,"description":"Bad Request: realpath failed for <path to file>"}`
- Asking on @bottalk, where the above option was suggested but also they (an Admin) couldn't get it to work on his system

### Notes
--local flag is correctly enabled
Upload works for all files < 20 MB

**Comment by levlam** [comment]
> Using both HTTP and HTTPS

This wouldn't work, because in local mode you can "**Upload** files up to 2000 MB". Sending a file using its HTTP URL is not a file uploading. Such files are downloaded by the Telegram servers from the specified URL and there is no way `--local` flag can change limits on their size.

> URI Scheme: file://path/to/file.jpg with both absolute and relative path, hitting {"ok":false,"error_code":400,"description":"Bad Request: realpath failed for &lt;path to file&gt;"}

The provided path is wrong as the error message suggest. The error message includes the wrong path, so you should clearly see the error. You can find examples of valid file URI in https://en.wikipedia.org/wiki/File_URI_scheme#Examples.

**Comment by Nickelza** [comment]
Solved. I added "/" to the real file path, making it ` file:///<absolute path to file.jpg>`, in my case `file:///var/www/....`

**Comment by Nickelza** [comment]
I stand corrected. A new error arises:` {"ok":false,"error_code":400,"description":"Bad Request: stat for file \"<path to file>" failed"}`

**Comment by levlam** [comment]
The file is still not accessible. Check access rights of the file.

**Comment by mrbesen** [comment]
Does it work with files smaller than 20MB?

**Comment by levlam** [comment]
@mrbesen The error isn't related in any way to size of the file. The file doesn't exist or there are no enough rights to access it.

**Comment by Nickelza** [comment]
> The file is still not accessible. Check access rights of the file.

I'm afraid you're right, still trying to figure it out

**Comment by Nickelza** [comment]
> Does it work with files smaller than 20MB?

No

**Comment by Nickelza** [comment]
> @Nickelza Was your problem solved?

Not yet, but I think I've more or less understood what to fix, just not how to fix it. The user that is used to access the script (www-data) isn't able to view upper level folders, so a realpath is more or less meaningless to it (I confirmed this by verifying the PHP realpath function returns false). So now I just have to figure out how to give www-data executable permission for upper folders without changing their ownership or making them 777

**Comment by Nickelza** [comment]
All solved. As @levlam initially stated, it was a problem with permissions. The permission of the last folder inside of which the file to send was had executable permission set only for the owner, I set it for all (711). This definitely fixed the issue. Thanks for the help @levlam and @mrbesen for chipping in too.
