### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by Jemacivan** [tdlib/telegram-bot-api#283]
I can't get files through the local API, I always get 404, but the files are in a folder on the server

Link example: `http://127.0.0.1/file/botTOKEN/file_path`

![изображение](https://user-images.githubusercontent.com/63158240/171840002-bd0520a5-c9b3-4a41-ba83-8e0c5c5bd31c.png)

![изображение](https://user-images.githubusercontent.com/63158240/171840477-d987b173-0334-44f5-9d2c-0fd8ce0537c3.png)

![изображение](https://user-images.githubusercontent.com/63158240/171840296-691e5a26-1c5b-4ef8-b9ec-2178711d4f08.png)

Command to start the server:
![изображение](https://user-images.githubusercontent.com/63158240/171840694-3b756154-8464-4e98-9311-e97e2e8dd368.png)

**Comment by levlam** [comment]
Files aren't served by the Bot API server. You need to use provided local path to access them directly.

**Comment by Jemacivan** [comment]
Why are the files not being served on the server?  It is not safe, if so why is there no key to enable this feature forcibly?

**Comment by levlam** [comment]
Because they are already available locally. There is no reason to copy them over local network and save again.

**Comment by Jemacivan** [comment]
After all, it is not convenient if you need to move from the official API to the local
