### ISSUE TITLE
Incorrect showing amount in invoices on Apple devices

### ISSUE THREAD

**Issue by Monk228** [tdlib/telegram-bot-api#284]
I have a bot on telegram api (.net)

when im sending Invoice in IDR currency to user, on Android/Windows devices currency and amount in invoice show correctly. BUT on apple devices it show incorrect

Steps to reproduce
Send invoice from api, and specify 27900000 amount and currency is IDR

Expected behavior
In apple devices (ios, mac os) it will be 279.000 IDR in invoice

Actual behavior
But, now, in invoice it will be 27.900.000 IDR in invoice

Screenshots
on android/windows
![CQqCT](https://user-images.githubusercontent.com/49035634/173020286-7459ee41-0509-4b87-becc-eea70438418c.png)

on apple
![OfJMy](https://user-images.githubusercontent.com/49035634/173020303-38166af2-4e0d-4796-a91c-5e40e3e50b0f.png)

Environment data
*.NET Version: 5

*IDE: VS2019

Telegram.Bot Version : 17.0.0
Telegram.Bot.Extensions.Polling Version : 1.0.0

**Comment by levlam** [comment]
This issue isn't related to the Bot API server, and it should be already fixed in the iOS app anyway.
