### ISSUE TITLE
How to do update library

### ISSUE THREAD

**Issue by miladrajabi2002** [tdlib/telegram-bot-api#285]
i want to update my library
this version who i use it is (Bot API 5.3) i want to update it pleas help me

**Comment by levlam** [comment]
What library do you want to update?

**Comment by miladrajabi2002** [comment]
this -> https://github.com/tdlib/telegram-bot-api

**Comment by levlam** [comment]
This is not a library. The Bot API server is an executable, which just needs to be replaced with a newer version.

**Comment by miladrajabi2002** [comment]
you said i should delete bot api server and then install it again?

**Comment by levlam** [comment]
You need to replace the `telegram-bot-api` binary.

**Comment by miladrajabi2002** [comment]
how can i help me to replace it

**Comment by erfanmola** [comment]
> how? can i help me to replace it

Build It, Then Replace the binary file dude

**Comment by miladrajabi2002** [comment]
how in centos 7?
