### ISSUE TITLE
support for MTProto Proxies

### ISSUE THREAD

**Issue by AliDjango** [tdlib/telegram-bot-api#29]
Telegram is blocked in some countries like Iran and we need to use a VPN for telegram or bot development itself.

Now that we know this project is using tdlib internally, it must be easily possible to add mtproto proxy support to it. This has multiple advantages:

1. no need to use VPN/remote ssh during the development
2. being able to deploy a bot on a server located inside the country. This is mainly related to the costs because of the horrible economic situation we are in. This helps us to save a little on the servers.
Another reason for this can be lower "website" ping when a website has a telegram bot but lower ping for that website is preferred
3. improving the security in general. People who are paranoid about using a local api server can use a mtproto proxy to ensure their security

I am really desperate for this. You guys can never understand how hard it is for me to make a bot here....would really appreciate some help!

**Comment by levlam** [comment]
You can add `td_api::addProxy` request on the line https://github.com/tdlib/telegram-bot-api/blob/9692d581953d553b9bf2055d9bb89f960fd07739/telegram-bot-api/Client.cpp#L3785.

**Comment by AliDjango** [comment]
@levlam thanks for pointing it out.i never used tdlib directly and im not that good at c++ either.can u give me a hardcoded example on how to do that?

**Comment by levlam** [comment]
```
      send_request(make_object<td_api::addProxy>("1.1.1.1", 1111, true,
                                                 make_object<td_api::proxyTypeMtproto>("secret")),
                   std::make_unique<TdOnOkCallback>());
```

**Comment by ipetrovmgn** [comment]
Hi! Is it possible to provide a code block of Client.cpp send_request method to work via proxyTypeHttp ? Thanks in advance.

**Comment by levlam** [comment]
@ipetrovmgn
If the proxy can transparently proxy any TCP connections and not only HTTP requests, it is somethimg like
      send_request(make_object<td_api::addProxy>("1.1.1.1", 1111, true,
                                                 make_object<td_api::proxyTypeMtproto>("username", "password", false)),
                   td::make_unique<TdOnOkCallback>());

If it can proxy only HTTP requests, then you can pass `true` instead of `false`, but bots are expected to work very bad through such proxy.

**Comment by ipetrovmgn** [comment]
Dear @levlam is it possible to show directly where your proxy code block should be placed? Maybe I paste it in wrong place in  Client.cpp but unfortunately compilation fails in this case. Thank you!

**Comment by levlam** [comment]
@ipetrovmgn I added code block around the code to fix its appearance.

**Comment by ipetrovmgn** [comment]
> @ipetrovmgn I added code block around the code to fix its appearance.

Hi! added proxy lines in Client.cpp starting from ln4929  and unfortunately got a compilation error: 

`
[ 98%] Building CXX object CMakeFiles/telegram-bot-api.dir/telegram-bot-api/Client.cpp.o
In file included from /opt/telegram-bot-api/td/td/telegram/ClientActor.h:11,
                 from /opt/telegram-bot-api/telegram-bot-api/Client.h:13,
                 from /opt/telegram-bot-api/telegram-bot-api/Client.cpp:7:
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h: In instantiation of ‘td::td_api::object_ptr<Type> td::td_api::make_object(Args&& ...) [with Type = td::td_api::proxyTypeMtproto; Args = {const char (&)[5], const char (&)[9], bool}; td::td_api::object_ptr<Type> = td::tl::unique_ptr<td::td_api::proxyTypeMtproto>]’:
/opt/telegram-bot-api/telegram-bot-api/Client.cpp:4958:113:   required from here
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:34:27: error: no matching function for call to ‘td::td_api::proxyTypeMtproto::proxyTypeMtproto(const char [5], const char [9], bool)’
   return object_ptr<Type>(new Type(std::forward<Args>(args)...));
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/telegram-bot-api/td/td/telegram/ClientActor.h:11,
                 from /opt/telegram-bot-api/telegram-bot-api/Client.h:13,
                 from /opt/telegram-bot-api/telegram-bot-api/Client.cpp:7:
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:14739:12: note: candidate: ‘td::td_api::proxyTypeMtproto::proxyTypeMtproto(const string&)’
   explicit proxyTypeMtproto(string const &secret_);
            ^~~~~~~~~~~~~~~~
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:14739:12: note:   candidate expects 1 argument, 3 provided
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:14737:3: note: candidate: ‘td::td_api::proxyTypeMtproto::proxyTypeMtproto()’
   proxyTypeMtproto();
   ^~~~~~~~~~~~~~~~
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:14737:3: note:   candidate expects 0 arguments, 3 provided
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:14733:7: note: candidate: ‘td::td_api::proxyTypeMtproto::proxyTypeMtproto(td::td_api::proxyTypeMtproto&&)’
 class proxyTypeMtproto final : public ProxyType {
       ^~~~~~~~~~~~~~~~
/opt/telegram-bot-api/td/td/generate/auto/td/telegram/td_api.h:14733:7: note:   candidate expects 1 argument, 3 provided
gmake[2]: *** [CMakeFiles/telegram-bot-api.dir/build.make:90: CMakeFiles/telegram-bot-api.dir/telegram-bot-api/Client.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:372: CMakeFiles/telegram-bot-api.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
`

>

Can you please advice what is wrong now?

**Comment by ipetrovmgn** [comment]
Dear @levlam, now solution with proxyTypeHttp is really works! Thanks for your support!

**Comment by MoYuYuDe** [comment]
> ```
>       send_request(make_object<td_api::addProxy>("1.1.1.1", 1111, true,
>                                                  make_object<td_api::proxyTypeMtproto>("secret")),
>                    td::make_unique<TdOnOkCallback>());
> ```
Hello, where should I add the code block of the MTProto Proxies now? The code has been modified a lot

**Comment by levlam** [comment]
@MoYuYuDe Before the call to `setTdlibParameters`.

**Comment by MoYuYuDe** [comment]
> @MoYuYuDe Before the call to `setTdlibParameters`.
It worked, thank you very much for your help

**Comment by MoYuYuDe** [comment]
@levlam 
Is there support for other proxies besides MTProto, like socks5 ? Currently, I am using the golang version of MTProto-go  via proxie (socks5), Is there a security impact when using socks5 or MTProto in another language?

**Comment by chansanya** [comment]
How should I make this modification to the latest code?  [code]( https://github.com/nupzil/telegram-bot-api/commit/8d7d2d241c98d8d9ad5bd2685953db185789648b)
