### ISSUE TITLE
How to compile the whole app into one executable file ?

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#290]
I have a very negligible experience in Linux stuff, Is it possible to compile/build the whole into one file ?

I mean the compiled file should run in any Linux system without any extra steps/dependecy,  Is it possible at all ? 

Edit: It will be great if someone wrote the steps thanks in advance.

**Comment by levlam** [comment]
Despite possible, Linux architecture greatly discourages such builds. You need to search for somethins like "build portable executable".
