### ISSUE TITLE
error when install telegram-bot-api

### ISSUE THREAD

**Issue by miladrajabi2002** [tdlib/telegram-bot-api#293]
virtual memory exhausted: Cannot allocate memory
gmake[2]: *** [td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o] Error 1
gmake[1]: *** [td/CMakeFiles/tdcore.dir/all] Error 2
gmake: *** [all] Error 2

i got this error what is problem?

**Comment by levlam** [comment]
C++ compiler needs more RAM. You can try to switch to clang.

**Comment by dani-fmena** [comment]
@levlam you tip work for me. Thanks 👍🏽👍🏽
