### ISSUE TITLE
Docs are unclear about `file_size` fields

### ISSUE THREAD

**Issue by WaffleLapkin** [tdlib/telegram-bot-api#294]
`file_size` fields of [`PhotoSize`](https://core.telegram.org/bots/api#photosize), [`Animation`](https://core.telegram.org/bots/api#animation), [`Audio`](https://core.telegram.org/bots/api#audio), [`Document`](https://core.telegram.org/bots/api#document), [`Video`](https://core.telegram.org/bots/api#video), [`VideoNote`](https://core.telegram.org/bots/api#videonote), [`Voice`](https://core.telegram.org/bots/api#voice), [`Sticker`](https://core.telegram.org/bots/api#sticker), [`PassportFile`](https://core.telegram.org/bots/api#passportfile) and [`File`](https://core.telegram.org/bots/api#file) are optional. However, I couldn't find anywhere in the docs why are these field optional, when are they not present, etc. Could you please clarify this (here, but also in docs, if possible)?

And while we are at it, can `file_size` in `PhotoSize`, `Sticker`, `VideoNote` and `PassportFile` always fit in 32 bit integer? (the documentation for these two fields doesn't mention need for 52 bits)

**Comment by levlam** [comment]
> However, I couldn't find anywhere in the docs why are these field optional, when are they not present, etc. 

You have already asked this in https://github.com/tdlib/telegram-bot-api/issues/192.

> And while we are at it, can file_size in PhotoSize, Sticker, VideoNote and PassportFile always fit in 32 bit integer?

Photos, stickers, video notes and passport files are at most 12 MB now, so their size is very far from exceeding 32-bit.

**Comment by WaffleLapkin** [comment]
> But the classes can be used in some other places, where file size is unknown.

What are these places?

**Comment by levlam** [comment]
I don't think that such places are already exposed by Bot API. The only such place is ChatPhoto, but it doesn't use any of the mentioned classes.

**Comment by WaffleLapkin** [comment]
Why are the fields marked as optional then, if API never exposes them as such?

And while we are at it, is `file_path` field of the `File` also always present?

**Comment by levlam** [comment]
> Why are the fields marked as optional then, if API never exposes them as such?

Because they can be generally unknown. It is almost impossible to assure that they are always known for the current use cases.

> And while we are at it, is file_path field of the File also always present?

Definitely, no. Since Bot API 6.1 `File` is used for `Sticker.premium_animation`, which definitely has no file_path.

**Comment by WaffleLapkin** [comment]
> Because they can be generally unknown. It is almost impossible to assure that they are always known for the current use cases.

I do not understand what you mean, your words seem to contradict themselves. 

This: 
> For files inside messages `file_size` should be always known. But the classes can be used in some other places, where file size is unknown.

And this:
> I don't think that such places are already exposed by Bot API.

Implies that the size is always known, so it's unclear what means that the size is "generally unknown" and how it's "impossible to assure that they are always known for the current use cases" if in all places where `file_size` is exposed in bot API it **is** known.

-----

> Definitely, no. Since Bot API 6.1 `File` is used for `Sticker.premium_animation`, which definitely has no `file_path`.

Is it safe to assume that `file_path` is always present when `File` is returned from `get_file` and never present otherwise?

**Comment by WaffleLapkin** [comment]
> The classes are used in a lot of places in TDLib and in Telegram API. In a lot of these places file size can be unknown. Luckily, Bot API exposes these classes only in already sent messages, and so file_size should always present there, But this can change any time.

**Comment by WaffleLapkin** [comment]
> The classes are used in a lot of places in TDLib and in Telegram API. In a lot of these places file size can be unknown. Luckily, Bot API exposes these classes only in already sent messages, and so file_size should always present there, But this can change any time.

But bot API is not TDLib, it shouldn't necessarily expose its implementation details. If need be for `file_size` to be optional in some cases a new type can be introduced for this purpose, there is no reason to "poison" all current cases where it is in fact non-optional. At least a clarification in docs that it's currently always present would be nice.

Other than that, my questions are answered, so closing the issue.

**Comment by levlam** [comment]
> At least a clarification in docs that it's currently always present would be nice.

Documentation of the field as optional is correct. It **should** be present all the time for files in server messages, but it can be missed even now. For example. if the server will send an invalid file size.
