### ISSUE TITLE
Allow several messages to be forwarded at once (for media groups)

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#297]
The method the bot API will call is [forwardMessages](https://core.telegram.org/method/messages.forwardMessages). Currently the bot API only allows to forward one message in [forwardMessage](https://core.telegram.org/bots/api#forwardmessage).

This decision doesn't allow bots to forward (parts of) media groups. If a bot e.g. encounters a media group in a channel and wants to forward it as a group, the bot has to send a new media group. This degrades the user experience, since the link to the channel is lost and the bot has to add it manually to the media caption if it is to persist, not to speak of the view counter which the bot can not replicate even if it wants to.
The other solution is to forward each media of a media group, which can lead to 10 updates at once for an user, which they certainly do not appreciate either.

It would be better if a bot can forward multiple messages at once, as the MTProto API and clients support.

**Comment by oleggromov** [comment]
Yes! It would be very helpful to have this functionality in the bot API, especially if it's already present in MTProto.

**Comment by T1MOXA** [comment]
The same request for copyMessage.

**Comment by harshil21** [comment]
yay, Bot API 7.0 fixes this
