### ISSUE TITLE
Clarification on characters used in a Bot Token

### ISSUE THREAD

**Issue by harshil21** [tdlib/telegram-bot-api#300]
Hi.

I wanted to know which all characters could be used in a bot token. A bot token looks like for [e.g.](https://core.telegram.org/bots/#creating-a-new-bot) `110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw`. Here:

- part before the `:` is the bot ID.
- part after `:` is some random string/hash of fixed length 35...? If yes, can this length increase in the future?

What are the characters which could be used in the random string/hash? So far I've found it to be `a-zA-Z0-9`, `-`, and `_`. Is there more characters which could be used (in the future too)?

I'm asking this since we want to perform a simple bot token validation (https://github.com/python-telegram-bot/python-telegram-bot/pull/3167), before checking via `getMe` in our library and since I couldn't find any docs about this, we're asking here :D

**Comment by levlam** [comment]
> If yes, can this length increase in the future?

Everything can completely change in the future. There is no way to do a future-proof token validation.

You can do validation the same way as in https://github.com/tdlib/telegram-bot-api/blob/24ee05d15fca6f771c8229c38d96d6008b81c64a/telegram-bot-api/ClientManager.cpp#L69-L80, but this code may change any time without notice.
