### ISSUE TITLE
Videos without sound can not be send in media groups

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#301]
This behavior works fine on the client, suggesting a shortcoming on the bot API side. More so, sending a video without sound even works with the sendVideo endpoint!

MWE:
`https://api.telegram.org/botBOTTOKEN/sendVideo?chat_id=208589966&video=https://poolitzer.eu/withoutSound.mp4`

This suggests either the API or telegrams backend are capable of working with mp4s without sound (which are the GIFs in telegrams environment from my understanding) even if they are not send as GIFs, which is great!
This should be doable with the media group as well.

MWE:
`https://api.telegram.org/bot745729713:AAFSxig_-ZJM6OKmrS0od1o3a0sNJ9rH-38/sendMediaGroup?chat_id=208589966&media=[{%22type%22:%22video%22,%22media%22:%22https://poolitzer.eu/withoutSound.mp4%22},%20{%22type%22:%22video%22,%22media%22:%22https://poolitzer.eu/withSound.mp4%22}]`

Sadly this yields `"Bad Request: failed to send message #1 with the error message \"Wrong file identifier/HTTP URL specified\""`

One fix would be to introduce `InputMediaAnimation` to allow sending GIFs, the (arguably better) fix would be to do the same magic sendVideo is capable of and just send it as a video.

**Comment by levlam** [comment]
This is intended behavior. Animations aren't supposed to be used in media groups, which can contain only photos and videos. Each URL has fixed content of a specific automatically deduced type. The provided link points to an animation, so it can be used only to send an animation. When you use `sendVideo` request with the specified URL you still send an animation. The Bot API response to the request contains an `animation`, not a `video`.

**Comment by levlam** [comment]
> Telegram API allows the media group to be constructed by any InputMedia which includes Animations from my understanding (and the observed behavior from official clients)

This understanding is incorrect. There are only 3 types of albums allowed currently: Photo + Video, Audio only, Documents only.

> they need to edit the media file,

No, this will not work. As stated in https://core.telegram.org/bots/api#editmessagemedia: "If a message is part of a message album, then it can be edited only to an audio for audio albums, only to a document for document albums and to a photo or a video otherwise."

**Comment by Poolitzer** [comment]
Okay! So what the clients do is treat no sound mp4s as videos, and in the bot api they are treated as animations. And this is not possible for the bot api to do? Tbh I don't personally like that videos without sounds are treated as animations if I don't send them via send_animation.


>> they need to edit the media file,

> No, this will not work.

I meant locally. If I have a video file I want to send in a media group which has no sound to it, I need to edit sound in (locally) in order to be able to send it.

**Comment by levlam** [comment]
> Tbh I don't personally like that videos without sounds are treated as animations if I don't send them via send_animation.

One URL = one file. There is no way the file can be treated differently, no matter how you try to send it. You have an issue, because you are trying to use a URL to an animation instead of a video URL. If you would use multipart/form-data to upload a video without sound in an album, Bot API will ensure that it is uploaded as a video and not as an animation. But this still will be a video in an album, which isn't looped and played only when opened.

**Comment by Poolitzer** [comment]
Because URL upload is not handled by the telegram bot api, but by telegram itself, now I get it, great.

Just one question remains now, if you can answer it: Is there a way for web servers to announce to telegram that a file should not be treated as an animation? I imagine that there could be a setup where one has multiple bots which want to send the same file, and it makes more sense to them to store URLs in a database then sharing a file system.

**Comment by levlam** [comment]
> Is there a way for web servers to announce to telegram that a file should not be treated as an animation? 

No.

**Comment by Poolitzer** [comment]
Assumed as much. Might be cool for the aforementioned scenario, but I imagine it is very much of an edge case. Verified that uploading the file locally works as expected (it doesn't turn into an animation), thanks for clearing this up to me!
