### ISSUE TITLE
Does Local Bot API save files ?

### ISSUE THREAD

**Issue by erfanmola** [tdlib/telegram-bot-api#303]
Hi, I was wondering : does local bot api that I ran on my server, downloads all files on my server ? When I call getFile, it gives me local path, so does that mean if I send a 2GB file to my bot that is being served on my server using local bot api, does my server download that 2GB even without calling getFile ?
and if it downloads when I call getFile, how often does it clear downloaded files ?

**Comment by levlam** [comment]
The file is downloaded during call to `getFile`.

Files are guaranteed to be available for one hour after download, but can be kept for about 25 hours.

**Comment by erfanmola** [comment]
> The file is downloaded during call to `getFile`.
> 
> Files are guaranteed to be available for one hour after download, but can be kept for about 25 hours.

To prevent storage issues, I delete each file instantly after using it manually (by my own bot script), is it ok to do ? does this interfere the telegram-bot-api mechanism for deleting files ?

**Comment by levlam** [comment]
> To prevent storage issues, I delete each file instantly after using it manually (by my own bot script), is it ok to do ?

Yes.

> does this interfere the telegram-bot-api mechanism for deleting files ?

No. Only temporaty files in the directory `/temp` and files in the Bot API server working directory itself must not be accessed or deleted.

**Comment by alexandre-imaginacom** [comment]
There one question that is still not answered:
_"... how often does it clear downloaded files?"_

I know you answered _"Files are guaranteed to be available for one hour after download, but can be kept for about 25 hours."_, but is this configurable? How does exactly telegram-bot-api handles this?

I'm building a server, and I'm trying to calculate how much free space I must allocate, or if I should worry about monitoring and keeping things clean myself.

Thanks!

**Comment by levlam** [comment]
@alexandre-imaginacom Deletion of downloaded files after one hour is an implementation detail and isn't configurable, but you are free to delete the files manually.
