### ISSUE TITLE
403 forbidden on downloading files since yday

### ISSUE THREAD

**Issue by makdisse** [tdlib/telegram-bot-api#306]
We have a bot that makes 2 calls to get a file sent by the user (PDF):

1) GET the filePath from: `https://api.telegram.org/bot1...0:A...A/getFile?file_id=B....Q`
2) GET file from bot `/file/` endpoint + `filePath`. Eg: `https://api.telegram.org/file/bot1...0:A...A/documents/file_108.pdf`

This was working fine until the 8 Aug. Since yday it started to error when trying to download the file: `403 Forbidden`

Did anything change? I've checked the changelog but there was nothing in there.
I'm not sure why this was working fine until yday and without any changes on our side it stopped.

**Comment by levlam** [comment]
Do you sill have the issue?

**Comment by makdisse** [comment]
Worked now! :)
Was it a backend issue on Telegram's side?
Thanks

**Comment by levlam** [comment]
It was an issue at api.telegram.org backend, affecting a few bots.
