### ISSUE TITLE
bot limits

### ISSUE THREAD

**Issue by graymind123** [tdlib/telegram-bot-api#309]
I have two question about telegram bot limits, I appreciate if anyone can help me with that.

1- consider a management bot, like the ones who remove spam messages from a group. if bot was subscribed into too many different groups, will telegram send all the messages to bot( webhook address) without any problem? and the bot doesn't reach to any limits if exist?

2- consider a popular bot, witch is called by more than 200 people at same time. due telegram [documentation](https://core.telegram.org/bots/faq#:~:text=When%20sending%20messages%20inside%20a,messages%20per%20second%20or%20so.)(bot has  a limit 30 message per second), the bot shouldn't respond all the request Instantly? should I use a queue approach to answer  upcoming requests?

**Comment by levlam** [comment]
> will telegram send all the messages to bot( webhook address) without any problem? and the bot doesn't reach to any limits if exist?

Yes.

> due telegram [documentation](https://core.telegram.org/bots/faq)(bot has a limit 30 message per second),

There is nothing like that in the documentation. It states that "If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so."

**Comment by graymind123** [comment]
Thanks.
