### ISSUE TITLE
Error when installing telegram-bot-api in vps

### ISSUE THREAD

**Issue by fadilbjm** [tdlib/telegram-bot-api#310]
my vps are 1GB memory and 50GB storage but when i try to install i found these error:
1. using gcc lack of memory
2. try using clang get this error:
```
cc: error: unrecognized command line option ‘-Qunused-arguments’
make[2]: *** [td/sqlite/CMakeFiles/tdsqlite.dir/build.make:63: td/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1247: td/sqlite/CMakeFiles/tdsqlite.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
3. try with this issue #109 and i got still error like number 2

any solution to this issue? please

**Comment by levlam** [comment]
Did you completely delete build directory before trying clang?

**Comment by fadilbjm** [comment]
> Did you completely delete build directory before trying clang?

Sure i've delete build folder every time i change the method to reinstall

**Comment by levlam** [comment]
> cc: error: unrecognized command line option ‘-Qunused-arguments’

This error is definitely from gcc and not clang, which means that the correct compiler wasn't specified as this is done in https://tdlib.github.io/telegram-bot-api/build.html?os=Linux.

**Comment by fadilbjm** [comment]
> > cc: error: unrecognized command line option ‘-Qunused-arguments’
> 
> This error is definitely from gcc and not clang, which means that the correct compiler wasn't specified as this is done in https://tdlib.github.io/telegram-bot-api/build.html?os=Linux.

Do i need to uninstall gcc and start from scratch?

**Comment by fadilbjm** [comment]
i forgot to mention when i change the c++ compiler using `update-alternatives --config c++` is it ok?

**Comment by fadilbjm** [comment]
i reinstall with clang recommended step in https://tdlib.github.io/telegram-bot-api/build.html?os=Linux.
i made a progres but the installer stop at 52% when try to build `td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o`
and stopped it self with these error:
```
make[2]: *** [td/CMakeFiles/tdcore.dir/build.make:609: td/CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o] Error 137
make[1]: *** [CMakeFiles/Makefile2:517: td/CMakeFiles/tdcore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by levlam** [comment]
It looks like you have not enough RAM even for clang. Try to increase size of swap memory.

**Comment by fadilbjm** [comment]
> It looks like you have not enough RAM even for clang. Try to increase size of swap memory.

my provider using openVz so i can't create swap file :rofl: 

can i copy build folder from my computer to my server?

**Comment by levlam** [comment]
> can i copy build folder from my computer to my server?

Yes, if operationg systems are exactly the same.

**Comment by fadilbjm** [comment]
> > can i copy build folder from my computer to my server?
> 
> Yes, if operationg systems are exactly the same.

Even if my laptop ubuntu 18 and server ubuntu 20?

**Comment by levlam** [comment]
No. Those are different operating systems.

**Comment by fadilbjm** [comment]
Ok i will downgrading my vps hope it's fine
Thank you for your help
