### ISSUE TITLE
About the use of network blocked areas

### ISSUE THREAD

**Issue by UoUoio** [tdlib/telegram-bot-api#312]
Since the area I am in is a network block area (China). I always use a proxy when calling https://api.telegram.org. can be used normally

Now I compiled and started this project locally, I found that I can't connect to the local and use it normally.
I don't know if it's because of the network, I added a proxy when I started this project
Even I added a proxy when calling 127.0.0.1:8081/bot locally, it doesn't work..
Below are the commands launched and the requests that are attempted to be invoked
(127.0.0.0:7890 this address is my proxy)
![image](https://user-images.githubusercontent.com/63728294/187579017-ba7d90f7-5848-4827-9a3c-a181180985fc.png)
![image](https://user-images.githubusercontent.com/63728294/187579388-f342ee04-63b3-4631-ada7-da265fdf5fb9.png)

**Comment by UoUoio** [comment]
If I deliberately write the wrong token, I will be prompted with the following information. This can prove that the project is successfully started
![image](https://user-images.githubusercontent.com/63728294/187580315-2391be25-1b13-49fd-8ad5-628944d008a1.png)

**Comment by levlam** [comment]
If you receive no response, then the Bot API server can't connect to Telegram servers. You can fix this using a system-wide VPN or proxy.

**Comment by UoUoio** [comment]
> If you receive no response, then the Bot API server can't connect to Telegram servers. You can fix this using a system-wide VPN or proxy.

![image](https://user-images.githubusercontent.com/63728294/187608625-f1b54885-541a-4b35-998e-46c72cb69ec5.png)
Thanks, I changed the proxy and it still didn't work.
(51.75.5.209 32648)

I still can't use it after starting it... and there is no result.. I can't connect to the local bot server, this problem has plagued me for two days

**Comment by UoUoio** [comment]
> > If you receive no response, then the Bot API server can't connect to Telegram servers. You can fix this using a system-wide VPN or proxy.
> 
> ![image](https://user-images.githubusercontent.com/63728294/187608625-f1b54885-541a-4b35-998e-46c72cb69ec5.png) Thanks, I changed the proxy and it still didn't work. (51.75.5.209 32648)
> 
> I still can't use it after starting it... and there is no result.. I can't connect to the local bot server, this problem has plagued me for two days

![image](https://user-images.githubusercontent.com/63728294/187609433-09869e80-f389-4756-beea-429e0a6cf562.png)

### I don't understand where I am going wrong

**Comment by levlam** [comment]
You specified a proxy for outgoing webhook connections. The proxy can't be used for connections to Telegram servers. You need a system-wide VPN to allow the Bot API server to connect to Telegram servers.

**Comment by UoUoio** [comment]
> You specified a proxy for outgoing webhook connections. The proxy can't be used for connections to Telegram servers. You need a system-wide VPN to allow the Bot API server to connect to Telegram servers.

Yes Yes,
But how should I set it correctly? I changed this way and it still doesn't work
![image](https://user-images.githubusercontent.com/63728294/187616493-7f187cff-7aaf-49bc-ab7e-3965ad028b52.png)

But how should I set it correctly? I changed the settings in this way and it still doesn't work (127.0.0.1:7890 is a service that I blocked locally through the network. When I did not deploy a local server and directly connected to api.telegram.org, I will proxy to this address to communicate with telegram.org)


Are there any tutorials or documents for related settings? My situation is very special. I have been searching for a long time and have not found any relevant materials that can be used for reference.

**Comment by levlam** [comment]
HTTP_PROXY/HTTPS_PROXY are environment variables, which can be used by some specific software. Bot API server can't use them. There is no way to specify a proxy server for connection to Telegram servers without source code modifications.

The only way to make Bot API server working in a blocked area is to enable a system-wide VPN, which will cause all network connections to be proxied through the VPN service provider's server.

**Comment by UoUoio** [comment]
thank you my problem is solved
