### ISSUE TITLE
Bot Api server taking too long to upload files.

### ISSUE THREAD

**Issue by BostyBro** [tdlib/telegram-bot-api#316]
Bot Api server with ip 2001:67c:4e8:f004::9 taking too long to upload files. To fix this I have changed ip in hosts file to 149.154.167.220 and it have worked. Hope you will fix this to help other developers.

**Comment by levlam** [comment]
Bot API server can't use 2001:67c:4e8:f004::9 or 149.154.167.220. These IP addresses belong to api.telegram.org and aren't related to the self-hosted Bot API server.

**Comment by Allouch21** [comment]
@SoldesBot
