### ISSUE TITLE
[Question] Method editMessageText slow response in channels

### ISSUE THREAD

**Issue by DorianPeregrim** [tdlib/telegram-bot-api#318]
Hello.

I try to edit message in channel 20 times (according to group limits in docs) with 1-2 second frequency. For groups with ~10 members it works fine. But in groups with 100+ members I get delay from up to 6+ seconds from second editMessageText method call.

In groups same logic works fine for 10 or 100+ members.

Is this normal behaviour or a bug? Are any ways to speed up my requests in channels?

**Comment by DorianPeregrim** [comment]
But in groups can?

**Comment by levlam** [comment]
Limits can be different for different chats.

**Comment by DorianPeregrim** [comment]
Why is it not 429 like the sendMessage method? 
What are the actual limits for channels? How can I to avoid slow requests editMessageText? 
Will it change in the future?
