### ISSUE TITLE
[Documentation suggestion] Add a list of all usable t.me Deep links for bots

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#321]
Hi.

I recently stumbled upon https://corefork.telegram.org/api/links. I think it makes sense to also have this list for all the t.me links bots can use and how to use/generate them.

**Comment by levlam** [comment]
Bots can use any links from https://core.telegram.org/api/links. What exactly do you ask for?

**Comment by Poolitzer** [comment]
Have a curated list of all applicable links (e.g. Video chat/Livestream links wouldn't be in there) and then linking to the proper methods/objects to get the params for the links.

**Comment by levlam** [comment]
Why "Video chat/Livestream links wouldn't be in there"? Bots can use them as any other link. The list of all links, which can be used by bots or any user, is documented at https://core.telegram.org/api/links.

**Comment by Poolitzer** [comment]
> Why "Video chat/Livestream links wouldn't be in there"?

Because the bot API doesn't generate them/the invite_hash

**Comment by levlam** [comment]
Bot API doesn't generate links at all.
