### ISSUE TITLE
How to login bot back to cloud api server?

### ISSUE THREAD

**Issue by rippak** [tdlib/telegram-bot-api#324]
Hi!

I used logout method and raised local server. Everything works fine.

But what should i do to login back to cloud server?

**Comment by AYMENJD** [comment]
Call any methods for example `getMe` it should login automatically.

**Comment by rippak** [comment]
So, I need to execute `logOut` on local server where the bot is attached, then call any method addressing api.telegram.org?

**Comment by AYMENJD** [comment]
Yes.

**Comment by rippak** [comment]
Great thanx!

**Comment by jnxyatmjx** [comment]
> So, I need to execute `logOut` on local server where the bot is attached, then call any method addressing api.telegram.org?

but it do not work after logOut on local server and call any method to api.telegram.org?

**Comment by gagarski** [comment]
> Call any methods for example `getMe` it should login automatically.

@levlam, can you confirm that? Will `getMe` log you back in or you need to call update-related method (`getUpdates`/`setWebhook`)?

Is it possible to mix cloud API usage with local API: e.g., get updates from cloud and upload/download using local server?

**Comment by levlam** [comment]
@gagarski Yes, invocation of any method (including `getMe`) logs you back.

It is not possible to mix cloud API usage with local API.
