### ISSUE TITLE
Video upload on very slow connection causes network error 104

### ISSUE THREAD

**Issue by Amomum** [tdlib/telegram-bot-api#325]
I'm currently have to use internet connection with very low upload speed - about 250 kbps. I can upload files using official telegram client, however when I use bot API I very frequently getting error 104.

Can I do something about it?

**Comment by levlam** [comment]
Nothing can be done. HTTP connections must have small enough timeout to be reliable.

**Comment by Amomum** [comment]
@levlam how does it work in the telegram client then?

**Comment by erfanmola** [comment]
> @levlam how does it work in the telegram client then?

Telegram Clients uses MTProto, You can try using TDLib
