### ISSUE TITLE
[Question] Build in local machine

### ISSUE THREAD

**Issue by siamakdals** [tdlib/telegram-bot-api#327]
Can we build it locally and upload it to the server?

**Comment by erfanmola** [comment]
Hi, The build process is based on OS and libraries are linked and loaded dynamically, basically there is not just a single binary file to publish it to all users, each build is different based on OS and ..., AFAIK there are no pre-built binaries either.

**Comment by siamakdals** [comment]
Ok, thanks for the quick reply.
