### ISSUE TITLE
How to write own Telegram bot API library?

### ISSUE THREAD

**Issue by Filipp-Druan** [tdlib/telegram-bot-api#328]
Hello!
I'm a Lisp programmer and wee haven't got a Telegram bot API library. I want to wright it.
It's my questions:
1) In documentations I saw a lot of available types. Do I need to write classes to all of them?
2) Can you tall my about architecture of library? What classes are being used and so.
Thanks!

**Comment by levlam** [comment]
Everything is up to you. You can look at libraries in other programming languages at https://core.telegram.org/bots/samples and compare their features and architecture.

**Comment by Filipp-Druan** [comment]
Скажите пожалуйста, а если брать самую общую архитектуру, какой она должна быть? Я просто очень начинающий программист, да и то, только на Лиспе, для меня все указанные библиотеки - китайская грамота.
Нужно ли создавать множество классов для всех типов данных?
Сколько времени может уйти на разработку?

Please tell me, if we take the most general architecture, what should it be? I'm just a very beginner programmer, and even then, only in Lisp, for me all these libraries are a Chinese letter.
Do I need to create multiple classes for all data types?
How long can development take?

**Comment by levlam** [comment]
Everything is up to you. There are different libraries with different features. Development time will dependent on the set of features and your skills and can be anything between 1 hour and a few years.
