### ISSUE TITLE
[Fetaure request] add grpc support to bot api

### ISSUE THREAD

**Issue by smaznet** [tdlib/telegram-bot-api#329]
https://grpc.io/

Some of great features which is very useful for bots:

- No need to search docs in browser it can be used with server reflection ([More info](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) 

- Two way messaging which is very good for bots and chats (streams)

- Can group similar methods in services

- Can create multi stream connections

- Easy to use

- Can generate library to any language with .proto files

And many more

My proposal:
create a grpc service for mesages
- some methods
- sendMessage
- sendVideo
...
- sendContact

And one stream for listening to groups and user messages
- subscribeMessages

and one for channels
- subsribeChannelMessages

**Comment by levlam** [comment]
See https://github.com/tdlib/telegram-bot-api/issues/18.
