### ISSUE TITLE
[QUESTION] How many bot api server can run at the same time?

### ISSUE THREAD

**Issue by NormandoHall** [tdlib/telegram-bot-api#330]
Using the same `--api-id` and `--api-hash`, can I launch more than one server without any issue? It is because we have some bot clients running in some servers, and we want to separate, so, those bot running on a server must login to the same api server on the same server. Of course, each server has different URL.

Thanks

**Comment by AYMENJD** [comment]
Yes, you can run multiple bot-api server with the same `--api-id` and `--api-hash`.

**Comment by NormandoHall** [comment]
@AYMENJD thanks!
