### ISSUE TITLE
[QUESTION] Still get updates from logged out api cloud

### ISSUE THREAD

**Issue by NormandoHall** [tdlib/telegram-bot-api#331]
I logged out from cloud server (api.telegram.org) and switched to a local server and activated webHooks. All runs fine.

If I check on local server, the reply is ok:

```
https://example.com/bot<token>/getUpdates

{"ok":false,"error_code":409,"description":"Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"}
```

That is ok. But querying cloud server, I still get the updates:

```
https://api.telegram.org/bot<token>/getUpdates

{"ok":true,"result":[..........results]}
```

Is this ok?

**Comment by AYMENJD** [comment]
After calling `logOut`, you must never call the cloud api again unless you want to move back to it.

Because when you `logout` and you call `getUpdates` again it may re-login which will return updates.

**Comment by NormandoHall** [comment]
Ahhh, ok. Thank you!
