### ISSUE TITLE
getChatMember method does not work

### ISSUE THREAD

**Issue by zhvarikk** [tdlib/telegram-bot-api#332]
Hi! I am trying to call getChatMember api to know if the user who entered the bot has joined my telegram channel so that then I can send him a link to free checklist. And whenever I pass user_id which is 298499497 in my case, the api gives me the error - user not found.

Do you know why it is happening?

**Comment by levlam** [comment]
It can return "User not found" only if the user never contacted the bot in private.

**Comment by zhvarikk** [comment]
Got it, so the user should contact the bot in private but what does it mean exactly? Also, what should I do to make it work?

**Comment by levlam** [comment]
If the user sent a private message to the bot, then bot will be able to find the user.

**Comment by foremtehan** [comment]
User should have already `/start` the bot.
