### ISSUE TITLE
[BUG] copyMessage return message caption is too long

### ISSUE THREAD

**Issue by aiskendi** [tdlib/telegram-bot-api#334]
Can't copyMessage from channel with premium user caption length

Action:
copyMessage message_id from channel send to any user.

**Comment by AYMENJD** [comment]
This is not a bug. 

You should not `copyMessage` that contains any premium feature such as custom emoji or long caption length. Instead use `forwardMessage`.

**Comment by aiskendi** [comment]
> This is not a bug.
> 
> You should not `copyMessage` that contains any premium feature such as custom emoji or long caption length. Instead use `forwardMessage`.

Thank for the info.

But copyMessage with premium caption length FROM bot TO channel or user it can send successfully, only FROM channel problem occur.

**Comment by levlam** [comment]
Do you add `reply_markup`, or specify `teply_to_message_id` in the `copyMessage` request?

**Comment by levlam** [comment]
I can't reproduce the issue. If message is copied as is, then the request succeeds. The mentioned error can be received, only if the bot tries to edit the copied message, replacing its `caption`, `reply_markup`, or `reply_to_message_id`, which is expected to fail for non-premium users and bots.
