### ISSUE TITLE
Stale status result of getChatMember

### ISSUE THREAD

**Issue by aiskendi** [tdlib/telegram-bot-api#337]
Sometime result of getChatMember status (left/member) not changing, only after restarting telegram-bot-api its work normal again.
Uptime telegram-bot-api before restart it 3 day.

**Comment by AYMENJD** [comment]
Are you using multiple sessions for the bot?

**Comment by aiskendi** [comment]
> Are you using multiple sessions for the bot?

single telegram-bot-api for multiple bot.

**Comment by AYMENJD** [comment]
This is expected to happen if the bot has multiple active session. Example: using `api.telegram.org` and local `Bot-API` server at the same time or using custom MTProto implementation alongside with `Bot-API`.

Make sure that your bot has only one active session.

**Comment by aiskendi** [comment]
> This is expected to happen if the bot has multiple active session. Example: using `api.telegram.org` and local `Bot-API` server at the same time or using custom MTProto implementation alongside with `Bot-API`.
> 
> Make sure that your bot has only one active session.

Ok thank for the info.
I'm using custom MTProto and Local Bot-API session for the same bot.

**Comment by AYMENJD** [comment]
@aiskendi that's not a fix. The fix is to use only one active session. Using custom `MTProto` implementation alongside with `Bot-API` will get things worse in the future use of your bot. You can either completely switch to the custom `MTProto` implementation or `Bot-API`. You can't both.
