### ISSUE TITLE
How not to close the webapp after opening links such as channels/groups

### ISSUE THREAD

**Issue by alon-sys** [tdlib/telegram-bot-api#338]
How not to close the webapp after opening links such as channels/groups

**Comment by alon-sys** [comment]
> You can't open the links inside a web app, so what do you mean by "not to close" it?

It’s not that the link cannot be opened, but when you click on the content of the a tag, a prompt will pop up, do you want to open, how to eliminate this prompt

**Comment by levlam** [comment]
What link is clicked? What prompt is shown?

**Comment by AYMENJD** [comment]
@alon-sys Is this what you mean?

![Screenshot_20221213_174114](https://user-images.githubusercontent.com/53928879/207363351-6b80fc1e-d7a6-40fe-ae8c-d568a7b9d09b.jpg)

**Comment by alon-sys** [comment]
> @alon-sys Is this what you mean?
> 
> ![Screenshot_20221213_174114](https://user-images.githubusercontent.com/53928879/207363351-6b80fc1e-d7a6-40fe-ae8c-d568a7b9d09b.jpg)

Yes, that's right

**Comment by alon-sys** [comment]
Now open channels/groups/bot, etc. through the webapp, and after returning, the webapp will be closed, which is very inconvenient for users

**Comment by levlam** [comment]
Channels/group links are opened by the same app. There is no way for Web App to stay open, as there is no way for a browser tab to keep the state after opening a link inside it. It is theoretically possible to open the Web App again, but it doesn't make much sense, because it is state will be lost anyway.
