### ISSUE TITLE
Inconvenient way to handle Media Groups

### ISSUE THREAD

**Issue by OwnMind-ai** [tdlib/telegram-bot-api#339]
### What's the problem

I ran into a problem with handling **media group** messages, in other words — messages with multiple medias attached. The current version of bot API sends each media in a separate message and adds **mediaGroupID** to it, which makes sense since each media can have their own caption. 
 
However, it makes a problem when you try to handle a whole group and store it, for instance. That happens because the code doesn't know when sending media group stops, only which message belong to media group and which not. 

The only way I see is to make a timer, like for a second, during which the bot will look for messages with specific mediaGroupID. After the expiration of time, if no other message with mediaGroupID sent, the timer stops.
Obviously, this is a terrible solution, so there should be another way to do it (if you have some idea, feel free to write them below).

### How to solve a problem

To solve this problem, just let the bot know how much messages a group contains. 
There are two ways how to do it:

- Put number of messages in group right into API response, next to the mediaGroupID for each message from the group; 
- Create new method, that receives a mediaGroupID and returns a number of messages in group, like that:
` 
    https://api.telegram.org/bot<token>/mediaGroupSize?media_group_id=<your id>
`

**Comment by levlam** [comment]
> The only way I see is to make a timer, like for a second, during which the bot will look for messages with specific mediaGroupID.

This is the only working way.

> To solve this problem, just let the bot know how much messages a group contains.

Messages can be deleted from a message group any time, so there is no such thing as "how much messages a group contains". If bot will try to wait for any specified number of messages without a timeout, it can just hang never receiving them. Moreover, the number of messages in a group isn't known until the last message is sent.

> Create new method, that receives a mediaGroupID and returns a number of messages in group, 

This is useless. Any data returned from API are data from some time point in the past. It would be a programming error to use the count for noninformational purposes, because the returned value is unrelated to the current number of messages in the group.

**Comment by OwnMind-ai** [comment]
> Messages can be deleted from a message group any time, so there is no such thing as "how much messages a group contains". If bot will try to wait for any specified number of messages without a timeout, it can just hang never receiving them.

@levlam Yes, I agree with you, it makes sense.
Then, you can add a method that will return a list of messages which belong to a specific media group. If you do so, the problem about 'time point' fall away, because if even message was deleted, the bot still has content of messages, not just their IDs (somehow is the same as Message.reply_to_message).

>  Moreover, the number of messages in a group isn't known until the last message is sent.

If the server hasn't known a number of messages yet, you can just add a timeout **for the method** described above. But if it does know, there is no problem. Technically speaking, it is kinda the same as 'timer solution' that I described comment above, but on the server. It would be really nice to add it, because current implementation looks a bit messy and force programmers to write their own 'timers'.

**Comment by levlam** [comment]
> Then, you can add a method that will return a list of messages which belong to a specific media group.

And the method will return different number of messages dependent on the time it is called and the number of already sent messages. It will change nothing.

> If the server hasn't known a number of messages yet, you can just add a timeout for the method described above.

It is better to have client-side timers. Many frameworks already have extensions for this.

**Comment by SpriteOvO** [comment]
How about adding a new `MediaGroupComplete` update from server side? This update is sent if the server has sent all media `Message` updates, and it will contain information about all media data of the group.

**Comment by Vibgitcode27** [comment]
I was facing same issue, most frameworks use (grammY, Telegraf, GramIO) the in-memory timer approach. But my bot was running on multi instance setup (e.g. Cloud Run, K8s), in-memory was clearly not going to work for me.

What worked for me: Redis as a shared buffer with leader election.

Every instance pushes the raw update JSON to a Redis list keyed by media_group_id
Every instance tries to acquire a lock (SET NX EX 5)
The one that gets the lock (leader) sleeps ~700ms - 1s, then reads all buffered updates and processes them as a single message
The rest return immediately
