### ISSUE TITLE
file is too big on getFile with local bot api

### ISSUE THREAD

**Issue by idotnetdev** [tdlib/telegram-bot-api#343]
Hi,
I have a problem with telegram bot server on my server.
I have created a service in Linux Ubuntu for telegram bot api with this details:

`[Unit] 
Description=Telegram bot api on Ubuntu 

[Service] 
#WorkingDirectory=/root/telegram-bot-api/bin 
ExecStart=/root/telegram-bot-api/bin/telegram-bot-api --local --api-id=12345 --api-hash=[my hash id]
Restart=always 
RestartSec=10 # Restart service after 10 seconds if dotnet service crashes 
SyslogIdentifier=telegram-bot-api-service

[Install] 
WantedBy=multi-user.target

`

When I call getFile api with this data, I got **Bad Request: file is too big**.

![image](https://user-images.githubusercontent.com/20996286/209575996-37db2188-c613-4787-92c4-20580bd790b3.png)

Is there any solution for this problem?

**Comment by levlam** [comment]
The error "Bad Request: file is too big" can be returned only if the server is launched without `--local` parameter. Both places where it is returned can be reached only in non-local mode.

**Comment by idotnetdev** [comment]
Thanks, but I flag --local in service

telegram-bot-api --local --api-id=12345 --api-hash=[my hash id]

Even I execute telegram-bot-api with this command I've got this error.

**Comment by levlam** [comment]
Try to launch it manually on a different port and send the request to this port.

**Comment by idotnetdev** [comment]
You are amazing. Very thanks my problem has resolved by changing port 8081 to another port.

**Comment by levlam** [comment]
This happened, because on the port 8081 a server without `--local` flag is launched.
