### ISSUE TITLE
Cannot download file in local mode

### ISSUE THREAD

**Issue by weekly71** [tdlib/telegram-bot-api#345]
I setted up nginx server as in aiogram/telegram-bot-api/example repo. Without local mode files downloading without any problems but when I turn local mode on bot returns this error:
`aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://localhost:80/file/bot<token>//var/lib/telegram-bot-api/<token>/documents/file_3.p12')`

**Comment by levlam** [comment]
The path is very likely to be expected as `http://localhost:80/file/bot<token>/documents/file_3.p12` instead of the provided one.

**Comment by d-idea** [comment]
Thats a path bot uses without local mode. In local mode it uses full path

**Comment by levlam** [comment]
That's a path you are very likely need to use with a properly configured nginx.

Also, if you run `aiogram/telegram-bot-api` in a Docker container, make sure that nginx have access to filesystem of the docker container.

**Comment by d-idea** [comment]
nginx and aiogram/telegram-bot-api are in the same container. Can you tell me how to configure path please? Im using the same config as in `aiogram/telegram-bot-api/example`

**Comment by levlam** [comment]
See nginx config and how it rewrites the URL to a local path. The final local path, which is served by nginx, should be "/var/lib/telegram-bot-api/<token>/documents/file_3.p12".
