### ISSUE TITLE
`read ECONNRESET` when calling `sendMessage` API

### ISSUE THREAD

**Issue by brijeshshah13** [tdlib/telegram-bot-api#351]
I'm using the `sendMessage` API of the telegram bot using Axios library in a cron using node js. One message is sent at the start of the cron, then the business logic is executed for around 3 hours, and then one more message is sent to mark the end. But every now and then, I get `read ECONNRESET` error for the last message.

Attaching the error log:
```
cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
```
Any ideas on how to resolve this and what might be causing this issue?

**Comment by levlam** [comment]
ECONNRESET is a netwrok error, which means that the TCP connection was closed. You need to resend the request.

**Comment by brijeshshah13** [comment]
@levlam I'm using the following function to send message each time. Shouldn't this take care of that automatically?

Function to make API call

```
_sendMessageToTelegramChannel(
    botHTTPAPIToken: string,
    chatId: number | string,
    text: string,
    parseMode: string,
  ): Promise<AxiosResponse<SendMessageResponse>> {
    return this.httpService.axiosRef.post<SendMessageResponse>(
      `https://api.telegram.org/bot${botHTTPAPIToken}/sendMessage`,
      {
        chat_id: chatId,
        text,
        parse_mode: parseMode,
      },
    );
  }
```

**Comment by levlam** [comment]
You need to check function documentation, but I doubt that the function can automatically resend requests in case of a network error. Such behavior would be harmful in a lot of cases. It is up to you to resend or not thr request in case of a network error.

**Comment by brijeshshah13** [comment]
@levlam You mean I should implement a retry mechanism in case of a network error?

**Comment by levlam** [comment]
If you want to retry the request, then yes.
