### ISSUE TITLE
Why does sendSticker send WEBM incorrectly?

### ISSUE THREAD

**Issue by aerospike2010** [tdlib/telegram-bot-api#355]
Telegram sends a document instead of an animated sticker with the webm format, I used **sendSticker** method, tell me please what's wrong?

Example request: 
`curl --location --request POST 'https://api.telegram.org/bot<TOKEN>/sendSticker' \ 
--form 'chat_id="chatId"' \ 
--form 'sticker=@"video.webm"'`

**Comment by levlam** [comment]
Telegram clients are expected to show a WEBM file as a sticker, only if the file belongs to a sticker set. Otherwise, viewing of ordinary WEBM videos would be broken. Hence, there is no way to upload WEBM file as a sticker.
