### ISSUE TITLE
More information about Bandwidth

### ISSUE THREAD

**Issue by PBhadoo** [tdlib/telegram-bot-api#357]
When we use Local Bot Server and send a file to Upload on Telegram using link, Will it consume Server's bandwidth as if it'll download and upload file or its direct Upload to Telegram from URL?

**Comment by AYMENJD** [comment]
This is called link preview. It is uploaded by telegram not local Bot-API nor cloud Bot-API.

**Comment by PBhadoo** [comment]
> This is called link preview. It is uploaded by telegram not local Bot-API nor cloud Bot-API.

I'm not talking about link preview.

I'm talking about full files.

Eg. There is a 1 GB file and i want to upload it via Bot.

Bot api cannot upload it because of 20 mb limit.

But if i host the bot server locally then it'll be able to upload the file, i am asking which bandwidth it'll use.

**Comment by AYMENJD** [comment]
It will use your local Bot-API server bandwidth.

**Comment by levlam** [comment]
> send a file to Upload on Telegram using link,

and

> There is a 1 GB file and i want to upload it via Bot.

are two completely independent questions. Both were correctly answered by @AYMENJD though.

Limits for upload by URL can't be changed by switching to the local Bot API server, because the file is downloaded from a Telegram datacenter. And direct upload of a file to a Telegram datacenter definitely uses server bandwidth.

**Comment by murqlegend** [comment]
There is no information on exactly how we should do it, how to send the file over 50mb, I am using C# but I am constantly stuck.

Example please..

**Comment by AYMENJD** [comment]
If you want to send files over 50MB, you must launch your own Bot API server with `--local` option. 

For more information: https://github.com/tdlib/telegram-bot-api#usage.
