### ISSUE TITLE
getFile returning "invalid file_id" on local server, but works on api.telegram.org

### ISSUE THREAD

**Issue by alexandre-imaginacom** [tdlib/telegram-bot-api#359]
This problem started about 1 week ago, and I can't figure out what is happening.

The exactly same botToken and file_id works fine using api.telegram.org, but gives me "invalid file_id" on my local bot server.
- https://api.telegram.org/{token}/getFile { file_id: "xxxx" } --> Works fine
- http://localhost/{token}/getFile { file_id: "xxxx" } --> Bad Request: invalid file_id

Ps: Literally the *exactly same request*, the **only** difference in the requests is the hostname (`https://api.telegram.org/` vs `http://localhost/` [or others]).

I already redeployed the server in other locations (including my localhost), but it just doesn't work anymore.
I tried with different bots, but the issue still persists.
I also found nothing other than "invalid file_id" in the verbose=4 logs.

Strangely enough, using file_ids older than one week (before the issue started) *still works* fine, and I can `getFile` on them.
Any clues what I'm missing here?

**Comment by levlam** [comment]
You need to update the local Bot API server to the latest version. Old Bot API servers can't use file identifiers received from newer Bot API versions.

Also, ensure that you use exactly one Bot API server. You can't use simultaneously api.telegram.org and a local Bot API server.

**Comment by alexandre-imaginacom** [comment]
@levlam you were right! I updated the bot server, and getFile started working again, thanks!
But this raised me another question: How may I know when I must update the bot server, or when the "file_id" is actually invalid.

Also, about your "You can't use simultaneously api.telegram.org and a local API server" statement..
- I made a lot of tests and found no issues doing it.
- Updates (messages, events, etc.) arrive at both server as usual.
- I'm relying on "api.telegram.org" to dispatch webhook and events, and I use my local API server just for downloading files.

Are there any risks if I keep doing this way?

In Telegram's documentation, they tell me to disconnect/logout from api.telegram.org and unsetting the webhook *before* moving to local server to avoid losing any updates/webhooks. However, I though that this was only to protect me against losing updates.

Anyway, thanks for your time and pacience!

**Comment by levlam** [comment]
> How may I know when I must update the bot server

You don't need to know this, if only one Bot API server is used.

> I made a lot of tests and found no issues doing it.

This proves nothing.

> Updates (messages, events, etc.) arrive at both server as usual.

This is not guaranteed and there are a lot of cases for which this isn't true for any bot.

> I'm relying on "api.telegram.org" to dispatch webhook and events, and I use my local API server just for downloading files.

This is not supposed to work.

> I though that this was only to protect me against losing updates

This is mandated to protect the bot from losing updates in the future and to avoid a lot of other issues.
