### ISSUE TITLE
Get update for channel comments

### ISSUE THREAD

**Issue by bsde1234** [tdlib/telegram-bot-api#36]
How to make getupdate api receive response from channel comments which implements recently in telegram

**Comment by levlam** [comment]
You need to join channel's discussion group to receive updates from it.

**Comment by bsde1234** [comment]
Can you please elaborate. I already get comments in channel. But I need that comment when I call `file_get_contents('https://api.telegram.org/bot$token/getUpdates`

**Comment by levlam** [comment]
Comments don't belong to the channel. They are messages sent to the channel's discussion group, which are replies to automatically forwarded channel message. To receive them in updates, your bot must be added to the discussion group.
