### ISSUE TITLE
How to run api server behind nat?

### ISSUE THREAD

**Issue by ZonD80** [tdlib/telegram-bot-api#360]
I'm unable to run bot server behind NAT, **even if running DMZ to local ip address**.
All my infrastructure is behind datacenter router that manages all connections.
Getting errors:

[ 3][t 5][1675677789.714329004][HttpConnectionBase.cpp:106][#1498911219][!Connect:768]  Receive flush_read error: [PosixError : Connection refused : 111 : Error on [fd:26]]

This is something that may help, bot is using local IP address, instead of public one:

[ 3][t 1][1675677789.980463266][Session.cpp:623][#1498911219][!Session:2:main]  Session connection with 0 pending requests was closed: OK Session:2:main::Connect::Tcp::[149.154.167.41:443] to DcId{2} from [10.88.113.68:51756]

There is no option to configure public IP that server will use.
Can you help me with this?

**Comment by levlam** [comment]
Bot API server needs direct connection to Telegram datacenters. You can find the list of networks, access to which must be allowed, at https://core.telegram.org/resources/cidr.txt.
