### ISSUE TITLE
`getChatMember` returns wrong result

### ISSUE THREAD

**Issue by cc00010** [tdlib/telegram-bot-api#368]
I don't know what's happening but when I call `getChatMember` I get wrong result. It always returns `"status": "left"` even though my bot is admin in the channel and I'm a subcriber.

But if I switch to `https://api.telegram.org` everything is ok.

**Comment by AYMENJD** [comment]
See #337.

**Comment by cc00010** [comment]
I did. But didn't understand the meaning of "Are you using multiple sessions for the bot?"

**Comment by cc00010** [comment]
@AYMENJD Does this mean: "Only one local bot server should use that account"?

**Comment by AYMENJD** [comment]
For example, you moved to use local Bot API without calling `logOut` from `api.telegram.org`. Which leads to multiple bot session (`api.telegram.org` and your local Bot API are active and handles bot updates).

You need to make sure that: 

- You've called `logOut` from `api.telegram.org`. 
- There is no other active client such as custom MTProto implementation.

For more see: https://github.com/tdlib/telegram-bot-api#moving-a-bot-to-a-local-server.

**Comment by cc00010** [comment]
@AYMENJD this makes more sense now. Let me try this one and tell you the result.

**Comment by cc00010** [comment]
@AYMENJD I think I accidentally did this in local bot server. Now it's stuck with `Logged out`. How do I login back?

**Comment by cc00010** [comment]
I did this in both local and `api.telegram.org` servers. Both stuck

**Comment by AYMENJD** [comment]
After `logOut` you can't login back for 10 minutes.

For local Bot API server try restarting it. It may help.

**Comment by AYMENJD** [comment]
No, you should re-attempt.

**Comment by cc00010** [comment]
`"status": "member"` yay! it's working now. Thank you man @AYMENJD I appreciate that a lot. I didn't know about that logout thing.
