### ISSUE TITLE
I want to generate my Telegram Bot API library's code, but don't want to parse documentation web page.

### ISSUE THREAD

**Issue by nickname76** [tdlib/telegram-bot-api#369]
I am developing a library for the Telegram Bot API, and I decided to generate some of its code. To do that I need a description of all the structures and methods of the API, however, the only thing I see available is the HTML page https://core.telegram.org/bots/api .

Is the https://core.telegram.org/bots/api page generated from something, or is it written by hand? If it is generated, I would really like to see the source material, and use it to generate code in my library.

If there is something that can help generate code for the Telegram Bot API libraries, maybe you should publish it in this repository?

Thank you.

**Comment by nickname76** [comment]
> If there is something that can help generate code for the Telegram Bot API libraries, maybe you should publish it in this repository?

Another option I could suggest is to create an endpoint like https://core.telegram.org/bots/api.json (or not .json, but another suitable format) which could be accessed from a program that will generate code (the web server will not block it from accessing this url specifically).

**Comment by AYMENJD** [comment]
Currently, there is no official TL for Telegram Bot API which can help you to generate Bot API methods.

Something similar of what you need: https://github.com/PaulSonOfLars/telegram-bot-api-spec (not affiliated with Bot API).
