### ISSUE TITLE
How to get file upload progress?

### ISSUE THREAD

**Issue by n2j7** [tdlib/telegram-bot-api#37]
With standard Bot API we know when we start uploading, can check that we are still uploading and finally know when upload ends

With TDLib and Telegram API according to this https://core.telegram.org/api/files we know part_size, count of parts and completely control upload process with upload.saveBigFilePart so we know current progress

With you solution we can handle upload progress like with Bot API, but, maybe you can provide some extra endpoint for upload progress or some explanation of how we can handle it?

I just want to know the state of uploading .

P.S.: sorry for bad english it is not my native language. hope you understand me (:

**Comment by levlam** [comment]
You don't have uploading progress with Bot API. HTTP doesn't have any progress notifications. At most, you can know number of sent bytes, which after some time will or won't reach Telegram servers. All incoming HTTPS requests at api.telegram.org are handled by Nginx web server. Uploaded files are stored locally by Nginx. After the file is fully uploaded to the Nginx server, the request is passed to Telegram Bot API server. It receives the file in an HTTP request and saves it locally to a temporary folder. Only after the file is fully received by the Bot API server, uploading of the file to Telegram servers begins. There is no way, you can know real file upload progress in this scenario.

If you use local Bot API server, then you can eliminate Nginx step, but you still can't know file upload progress.

> With TDLib and Telegram API according to this https://core.telegram.org/api/files we know part_size, count of parts and completely control upload process with upload.saveBigFilePart so we know current progress

TDLib doesn't provide direct access to Telegram API or `upload.saveBigFilePart`. This is completely irrelevant to what is provided by TDLib.

If you want to know real file upload progress, you need to proxy somehow `updateFile` updates handled in https://github.com/tdlib/telegram-bot-api/blob/9692d581953d553b9bf2055d9bb89f960fd07739/telegram-bot-api/Client.cpp#L3741 to your app. There is no way, you can do this using HTTP/1.1.

**Comment by n2j7** [comment]
Thanks a lot! This is the more detailed explanation I've ever seen for the Telegram Bot API.

It's a common case to upload files via the API, so yes, you're right, there is no way to know the progress of the upload.
But this can be a big advantage for using telegram-bot-api server locally!

By default (I mean using the api.telegram.org server) you can upload up to 50MB files and the upload progress doesn't really matter as it is counted in fractions of a second. With files up to `20 << 20` bytes this can take a long time (minutes I think)

I may be wrong with TDLib, but as described here https://core.telegram.org/api
``` The Telegram and TDLib APIs allow you to create your own customized Telegram clients.```
For me, this means that I can use TDLib and the Telegram API to create my own client to upload files (and I do have one).

After my file has been uploaded by this "client", I can send this file to the bot, and then the bot will be able to work with this file. 

Inside the "client" I split the file into chunks (512KB each) and upload them separately (in parallel and in a queue) so I know the progress for each file. I've built my own infrastructure around this and hope your solution with a upload progress endpoint can make my life easier

I understand that Bot API and Client API are different and work differently, but it would be great to have this feature in telegram-bot-api-server

Thanks for the advice on proxying `updateFile`, I'll try to work with it. I don't want to handle upload progress in the same connection, i want some extra point to control this.

Thanks anyway for your work !!! It is awesome!

**Comment by levlam** [comment]
Bot API works over HTTP and there is no way in HTTP/1.1 to notify about any progress. This makes impossible to add this feature to the Bot API.

**Comment by luckydonald** [comment]
One idea would be that you provide some kind of unique string with your uploads (maybe `upload_id`) under which it would get tracked and you could then have a separate endpoint to check for upload progress using the same `upload_id` you assigned yourself.

**Comment by n2j7** [comment]
@luckydonald Actually, the full filename (path + base name) or just filename is enough and you don't need to change the bot api for that ... I'll try to implement that soon ...

**Comment by luckydonald** [comment]
@n2j7 Do you have the filename even available before the upload is finished? I thought it is generated by the api after the download?

**Comment by n2j7** [comment]
I'm talking about using the service with the `--local` flag, so yes, the file is on the local filesystem. `file_id` will be available only after uploading
