### ISSUE TITLE
Failure to launch Local mode

### ISSUE THREAD

**Issue by klynch999** [tdlib/telegram-bot-api#371]
I am trying to get my bot running in local mode on the telegram bot api server. I have downloaded and installed all prerequisites, and set up the server. Here is my main() function.

async def main() -> None:               

    builder = Application.builder()
    builder.token(token)
    builder.http_version('1.1')
    builder.get_updates_http_version('1.1')
    builder.base_url(r'http://localhost:8081/bot')
    builder.base_file_url(r'http://localhost:8081/file/bot')
    builder.local_mode(local_mode = True)
    app = builder.build()
             
    conv_handler1 = ...
    conv_handler2 = ...

    app.add_handler(conv_handler1)
    app.add_handler(conv_handler2)
    
    await app.run_polling()

token = "..."
nest_asyncio.apply()

if __name__ == "__main__":
    asyncio.run(main())

I have looked at netstat and I've found the following:

  TCP    127.0.0.1:8081         127.0.0.1:53515        ESTABLISHED     25732
  TCP    MY_IP:53513     149.154.167.92:443     ESTABLISHED     25732

with the pid 25732 the one belonging to the running of telegram-bot-api.exe 

When I run the bot it connects and I can send/recieve commands, messages and files perfectly well. But when I attempt to send the 
bot a file of size > 50mb I get the telegram.error.BadRequest: File is too big error, indicating that the bot is not running is local mode. 
FTR here is the command I am using to start the api server:

./telegram-bot-api --api-id=??? --api-hash=??? --local

When I ping the server with: 
curl -X POST 127.0.0.1:8081/bot{MYTOKEN}/getUpdates
I get:
{"ok":true,"result":[]}

What am I doing wrong???

**Comment by AYMENJD** [comment]
What method you use to send that file? 

Also, double check that you pass `--local` correctly.

**Comment by klynch999** [comment]
I am using 

file = await bot.get_file(file_id)
url = file.file_path

and then I am downloading from the url.

How should --local be passed? Is it not correct as I have it above?

**Comment by levlam** [comment]
The error can be returned only if the Bot API server is run without `--local` parameter. Likely, the process listening on the port 8081 was run without the flag. You need to kill the process and restart the server with `--local` flag.

**Comment by klynch999** [comment]
As I stated in my question: 

FTR here is the command I am using to start the api server:

./telegram-bot-api --api-id=??? --api-hash=??? --local

Is there something wrong with this?

**Comment by AYMENJD** [comment]
No, but you could also change Bot API server port using `--http-port` flag. So:

```bash
./telegram-bot-api --api-id=??? --api-hash="???" --http-port=??? --local
```

**Comment by levlam** [comment]
The command is correct. But the server started on port 8081 is started with a different command. You can see the command, for example, using `top`.

**Comment by klynch999** [comment]
Are you saying that I should change the http port from the default 8081? I used http-port=8081 and the problem has persisted.

**Comment by klynch999** [comment]
I have also changed the port being used to one not in use. Still getting the same error.

**Comment by AYMENJD** [comment]
> Are you saying that I should change the http port from the default 8081? I used http-port=8081 and the problem has persisted.

Let me make it clear for you.

Your issue is that Bot API server running on port 8081 is running with different command (a.k.a without `--local` flag).

So, you need to terminate that process which uses different command from what you want. You can see the command, for example, using `top` or `htop`.

**Comment by klynch999** [comment]
Yeah I'm using windows not unix. Here is the command I am now using to start the server-It doesn't work:

 ./telegram-bot-api --api-id=17654549 --api-hash=992a1cfe9b95caba868f1cd565ee68b6 --http-port=8081 --local

I have been using the --local flag each time, and I am now specifying the port.

**Comment by klynch999** [comment]
Here is the command I am now using to start the server:

 ./telegram-bot-api --api-id=? --api-hash=? --http-port=8081 --local

it does not work. And I am using windows, not unix/linux

**Comment by levlam** [comment]
Then you can use Task Manager to see the parameters, which were used to launch the process. And there will be no `--local` parameter among them.

**Comment by klynch999** [comment]
Okay, so what do I do to resolve this? I have terminated my script, I have terminated the server process. I try to get things running again with the local parameter, and it doesn't work. All processes on port 8081 were terminated.

**Comment by levlam** [comment]
Check parameters of the Bot API server with Task Manager.
