### ISSUE TITLE
Message is too long

### ISSUE THREAD

**Issue by Tipo-4ek** [tdlib/telegram-bot-api#374]
Hi, i ran into [same](https://stackoverflow.com/questions/68768069/telegram-error-badrequest-entities-too-long-error-when-trying-to-send-long-ma) problem

When im trying to send a markdownV2 message length < 3000 symbols - Telegram bot api returning `telegram.error.BadRequest: Message is too long`

I cant solve this problem because i cant calculate len of string after using method `update.message.reply_text(answer, parse_mode="MarkdownV2")`

What should i do to control this? Could you support this at the library level?

**Comment by levlam** [comment]
"Message is too long" can be received only if message text is longer that 4096 characters after entities parsing. There is no way to send longer messages.

**Comment by Tipo-4ek** [comment]
But how can I find out the size of the string after parsing?
Now I calculate the string before parsing, make sure it is shorter than 4096 characters, try to send it with the parse_mode argument and get message is too long.

I understand why this happens, but I don't understand how to programmatically protect myself from 100% of such errors.

**Comment by levlam** [comment]
Strings can't extend after entities parsing. If it was less than 4096 characters, then it will be less than 4096 characters after the parsing.
