### ISSUE TITLE
Uploading of `InputSticker` - To `attach://` or not `atttach://`

### ISSUE THREAD

**Issue by Bibo-Joshi** [tdlib/telegram-bot-api#375]
Hi there!

At `python-telegram-bot` we're currently working on incorporating the latest changes of Bot API 6.6 (https://github.com/python-telegram-bot/python-telegram-bot/pull/3584) and we noticed that it's a bit unclear how uploading of the `sticker` field of `InputSticker` should work.

More precisely, the docs of that field don't mention that it can be uploaded via `attach://` and from the discussion in tdlib/telegram-bot-api#167 and tdlib/telegram-bot-api#259 we learned not to rely on undocumented behavior :D On the other hand, using `attach://` does work and IISC it's the only way that would make sense: With request data for `create_new_sticker_set` defined as

```python
data = {'user_id': '123', 'name': 'sticker_set_name', 'stickers': '[{"sticker": "attach://UID", "emoji_list": ["😀"]}]', ...}
files = {'attachedUID': (…)}
```

the receiving end can know that the attached file with id UID is to be inserted at `data['stickers']['sticker']`. Without attach://, it would have to be

```python
data = {'user_id': '123', 'name': 'sticker_set_name', 'stickers': '[{"emoji_list": ["😀"]}]', ...}
files = {'stickers': (…)}
```

and I don't see how this could be correctly parsed because it's unclear where the `stickers` files should be inserted.

---

Is the omission of `attach://` in the documentation of `InputSticker.sticker` just a mistake or on purpose? If it is on purpose, can you clarify how you expect us to pass the multipart data?

I'm looking forward to a short reply :)

**Comment by levlam** [comment]
Thank you. I improved wording to mention attach://&lt;file_attach_name&gt; as the expected way to upload stickers.
