### ISSUE TITLE
Can read from the connection

### ISSUE THREAD

**Issue by mpak2** [tdlib/telegram-bot-api#376]
Подскажите, в чем проблема при запуске?

https://0.0.0.0:8082/bot123456:ABC-DEFABCABCABCABCABCABCABC-ABC11/getMe

При попытке получить ответ с сервера надолго зависает и отваливается.

[ 3][t 7][1679319385.858909606][HttpServer.h:51][!HttpServer]	Create TCP listener [address:0.0.0.0][port:8082]
...
[ 4][t 7][1679319388.540576696][HttpConnectionBase.cpp:102][!HttpInboundConnection]	Can read from the connection
[ 4][t 7][1679319388.540602922][BufferedFd.h:198][!HttpInboundConnection]	Flush read: +517B[total:517B]
[ 4][t 7][1679319388.540609836][HttpConnectionBase.cpp:156][!HttpInboundConnection]	Can write to the connection
[ 4][t 7][1679319388.548172712][HttpConnectionBase.cpp:102][!HttpInboundConnection]	Can read from the connection
[ 4][t 7][1679319388.548195600][BufferedFd.h:198][!HttpInboundConnection]	Flush read: +517B[total:517B]
[ 4][t 7][1679319388.548204660][HttpConnectionBase.cpp:156][!HttpInboundConnection]	Can write to the connection

**Comment by levlam** [comment]
Bot API server accepts only HTTP requests. Use http://0.0.0.0:8082/bot123456:ABC-DEFABCABCABCABCABCABCABC-ABC11/getMe.
