### ISSUE TITLE
Does not output after the content of the response: Connection: close

### ISSUE THREAD

**Issue by mpak2** [tdlib/telegram-bot-api#377]
When the file is received, the contents are not closed because of this, the download script falls out after a timeout.

root@c3fb30025d8a:~/git/telegram-bot-api/build# wget -q --save-headers --output-document - http://0.0.0.0:8081/bot2024012152:blablaqblablablablablablablabla_5Zg/getme

HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json
Content-Length: 277

{"ok":true,"result":{"id":2024012152,"is_bot":true,"first_name":"\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0442\u0435\u043b\u0435\u0433\u0440\u0430\u043c","username":"surftg_1_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}

How to make sure that "Connection: close" appears at the end of the output and the download script does not fall off by timeout?

You can check the work of the download script via php from the console:
$ php -r '$microtime =microtime(true) ;echo file_get_contents("http://0.0.0.0:8081/botblablablaXgablaWceabla_5Zg/getme"); echo "\n Time:" .(microtime(true) -$microtime) ."\n";';

root@c3fb30025d8a:~/git/telegram-bot-api/build# php -v
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.11, Copyright (c), by Zend Technologies

With requests for api.telegram.org there are no such delays.

**Comment by levlam** [comment]
All HTTP/1.1 connection are kept alive by default. Don't use `file_get_contents` to get URL content, use `curl` extension instead.
