### ISSUE TITLE
Bad Request: the method is not available to bots

### ISSUE THREAD

**Issue by mpak2** [tdlib/telegram-bot-api#378]
Hello. For the bot to work, you need a method that receives the properties of invitation links from the channel admin page. To do this, I built a telegram_bot_api on my server and added the getChatInviteLink method to it

```
 8663 td::Status Client::process_get_chat_invite_link_query(PromisedQueryPtr &query) {
 8664   auto chat_id = query->arg("chat_id");
 8665   auto name = query->arg("name");
 8670   check_chat(chat_id, AccessRights::Write, std::move(query),
 8671              [this, name = name.str()](int64 chat_id, PromisedQueryPtr query) {
 8672                send_request(make_object<td_api::getChatInviteLink>(chat_id, name),
 8673                   td::make_unique<TdOnGetChatInviteLinkCallback>(this, std::move(query))
 8674                );
 8675              });
 8676   return td::Status::OK();
 8677 }
```

When launching the method, the bot displays an error
{"ok":false,"error_code":400,"description":"Bad Request: the method is not available to bots"}

There is a method for editing an invitation link. Bot can createChatInviteLink, bot can editChatInviteLink, but the bot cannot get the number of subscribers who clicked on this link.

Explain how it can be prohibited for a bot to receive the properties of an invitation link if it created it itself. To do this, there is a createChatInviteLink method in the standard interface, because the created link can be its own.

Is it possible to somehow circumvent this restriction and then get the properties of the invitation links in the channel admin panel?

**Comment by mpak2** [comment]
If you can't read the number of subscribers from the link, then how else can you track the transitions in the channel by the invitation link with the bot?

**Comment by ljs19923** [comment]
For me chat_member getUpdates polling or webhook is not sustainable. Sometimes I don't receive an update even though the user has used the link. So yes.. we need a method to know if a link created by the bot has been used and by whom

**Comment by ljs19923** [comment]
@mpak2 did you find a solution?
