### ISSUE TITLE
BadRequest when banChatMember

### ISSUE THREAD

**Issue by jyxjjj** [tdlib/telegram-bot-api#379]
FROM_MESSAGE_BOT_DISABLED was often reported when call banChatMember,
This started 2 days ago, without any codes edited.
I searched the doc but seems no errors in my codes, i think it is due to the BotAPI server updated.
Or maybe some new MTProto updates have not been supported by BotAPI.
Can you help me fix this if it is my wrong or can you just tell me why it happened if this is an issue from BotAPI server?

**Comment by jyxjjj** [comment]
>> Please note that only global Bot API issues that affect all bots are suitable for this repository.

I think it affected many bots because i cannot ban members via a lot of bots.
But this issue "often" instead of "always" happened.

**Comment by AYMENJD** [comment]
> I searched the doc but seems no errors in my codes, i think it is due to the BotAPI server updated.

This should be fixed by tdlib/td@007e3d8, and the fix is coming to Bot API.

**Comment by levlam** [comment]
Thank you. Fixed in Bot API 6.6.2.
