### ISSUE TITLE
Cannot check file from local path

### ISSUE THREAD

**Issue by nugraizy** [tdlib/telegram-bot-api#381]
after getting the file_path using getFile and went to check it from server it returns :
```
{
"ok": false,
"error_code": 404,
"description": "Not Found"
}
```

url format : `https://<tunnel_domain>/file/bot<bot_token>/<file_path>` or `http://localhost:8081/file/bot<bot_token>/<file_path>`

**Comment by AYMENJD** [comment]
See: #283.

**Comment by nugraizy** [comment]
> As levlam said [#283 (comment)](https://github.com/tdlib/telegram-bot-api/issues/283#issuecomment-1145877495).
> 
> Bot API running in local mode won't serve locally available files because you already can access them locally by the given path in `file_path`.
> 
> But if you really want to serve locally available files through HTTP, then consider configuring your web server to serve local paths returned by the `getFile` method.

thank you so much for the explantion. solve my problem. have a great day
