### ISSUE TITLE
False edited message update

### ISSUE THREAD

**Issue by saiinc** [tdlib/telegram-bot-api#388]
The strange behavior began at the end of the previous year. My bot sometimes catches edited message updates, but the author of the message swears that he did not edit it and edited tag don't shows under the message. I have update of the original and the edited, where should I send it?

**Comment by AYMENJD** [comment]
This is normal,  bots could ever receive `edited_message`updates, while nothing is visible (for example: a first reaction has been added to the message).

**Comment by saiinc** [comment]
> This is normal, bots could ever receive `edited_message`updates, while nothing is visible (for example: a first reaction has been added to the message).

I previously tested adding reactions and no updates were generated. Receive `edited_message` updates while adding the first reaction looks like a bug. So, can I get a list of all invisible `edited_message` updates actions? 

The problem is that my bot checks messages for mentioning an administrator, including edited ones, and forwards them to pm. As a result, some messages are forwarded twice.

**Comment by levlam** [comment]
There is no way to always avoid "edited_message" updates without actual changes for bots.
