### ISSUE TITLE
[BUG] Telegram Bot API not sending all chat_member updates

### ISSUE THREAD

**Issue by ljs19923** [tdlib/telegram-bot-api#396]
I have noticed an issue with the Telegram API where it is not sending all updates related to the chat_member field, specifically when a user joins a channel where my bot is a member. In my use case, I generate an invitation link for a user in a channel where my bot is an admin, and when the user clicks on the link and enters the channel, I expect to receive an update indicating that the user has joined. However, in 20% of cases, I do not receive this update, even though I have received all other updates (verified by checking the update_id).

It's worth noting that in 80% of cases, I do receive the update indicating that the user has joined, so it's not a problem with my setup or configuration.

This issue is not sustainable as it affects the reliability of my bot's functionality. I have tried using both webhook and polling methods to receive updates, but the issue persists.

**What I do ** 
1. Generate an invitation link for a user in a channel where your bot is an admin.
2. The user clicks on the link and enters the channel.
3. Check for updates using getUpdates or webhook.
4. In 20% of cases, the update indicating that the user has joined may not be received.

I suspect that the issue may be related to users not having a username, but I am not sure. Please investigate this issue and let me know if there is a solution. Thank you.

**More explanations:**

I have a Telegram bot in a channel.
I use the API to generate unique invitation links.
I invite people with these links. They successfully join my channel.

I use https://api.telegram.org/bot" + BOT_TOKEN + "/getUpdates with allowed_updates: [
"update_id",
"chat_member",
"message",
"channel_post",
]

I successfully retrieve the updates and store everything in my database. I have checked and I have all the update_id, so I have not missed any updates, I have a complete list of numbers.

Previously, I was using the webhook, but I had the same problem I have now, so I switched, thinking that it could be different and more reliable, but it's the same.

In my updates, I successfully retrieve chat_member but not 100% of the time, it seems.

When I give 100 invitation links to my channel to 100 people,

I obtain chat_member updates with the link inside, which proves that it is the chat_member object generated by link X.

The problem is that I do not receive 100% of the chat_member updates. In about 15-20% of cases, I do not receive any chat_member updates, and I do not have any missed update_id.

It is as if Telegram does not create chat_member objects in some cases... yet these 100 tests are on the same channel with the same bot, using the same code and configuration, for 100 random people.

**So my question is:**

Are there limits that prevent the bot API from creating 100% of the chat_member objects? If there are many objects to create in a short period of time?

Or are there users who are causing problems? If they do not have a username, for example?

I think the problem lies with Telegram during the creation of objects because I do have the complete sequence with the update_id number. I have tried to find a pattern among the users, but it is difficult to see anything.

**Thank you very much**

<img width="558" alt="Screen Shot 2023-04-15 at 16 58 15" src="https://user-images.githubusercontent.com/5727223/232202687-e61ccc22-ad9d-4e62-8ebb-1439e795156c.png">

**Comment by ljs19923** [comment]
@levlam if you have few minutes to check this. Thanks a lot

**Comment by levlam** [comment]
This can be caused only by using multiple sessions for the bot. If the bot uses multiple sessions, then updates can be missed.

See https://github.com/tdlib/telegram-bot-api#moving-a-bot-to-a-local-server for the correct way to move the bot to a local server (or any other Bot API implementation).
