### ISSUE TITLE
[BUG] deleteMyCommands without language_code

### ISSUE THREAD

**Issue by VodoGamer** [tdlib/telegram-bot-api#397]
in the [documentation](https://core.telegram.org/bots/api#deletemycommands) about the language_code field it says that if it is empty, the commands are deleted for all users from the given scope, but this does not happen.

Also I haven't been able to clear commands of my bot via BotFather.

Commands are cleared without a specified language_code, but not with a predefined language_code

**Comment by levlam** [comment]
It works as intended. "If empty, commands will be applied to all users from the given scope, for whose language there are no dedicated commands". You need to delete commands in more specific scopes by separate requests.
