### ISSUE TITLE
Termux Output Nothing

### ISSUE THREAD

**Issue by nitincodery** [tdlib/telegram-bot-api#398]
I've successfully built from source, but when I run the command, it outputs nothing. I'm using Termux application on Android.

What is the problem here?

![IMG_20230422_082207_582.jpg](https://user-images.githubusercontent.com/54881266/233757647-74d907e5-fef6-40ab-ab4d-a4bc92e5c9ac.jpg)

![IMG_20230422_082204_430.jpg](https://user-images.githubusercontent.com/54881266/233757656-4d971ac8-94aa-46fd-a18f-22ccd3a2e9fb.jpg)

**Comment by levlam** [comment]
The issue was resolved by the correct cmake set up in Termux before building TDLib.
