### ISSUE TITLE
can run with http proxy?

### ISSUE THREAD

**Issue by avaldid** [tdlib/telegram-bot-api#399]
how can start with proxy i from iran

**Comment by levlam** [comment]
You need to call `addProxy` method before `setTdlibParameters`.

**Comment by ipetrovmgn** [comment]
Hi! Is it possible to provide instructions how build binaries from src with http proxy support? Unfortunately there is no another options in many corporate networks instead of working via proxy. 

> You can't use the Bot API server without source code modifications from a place, where Telegram is blocked.
> 
> You can add a call to `addProxy` method before `setTdlibParameters`. but this is likely to result in a slow bot response speed. It would be better to use api.telegram.org through a proxy instead.
