### ISSUE TITLE
editMessageText occasionally returns `Bad Request: message to edit not found`

### ISSUE THREAD

**Issue by rovnyart** [tdlib/telegram-bot-api#400]
I did search for a similar issues (actually, I did search for the whole Internet:( ) and found nothing, maybe somebody can clarify it for me?

Situation:
We have an integration which uses bot token for mass message sending (we follow all rate limits possible) and editing messages based on user actions. We use `sendMessage` for creating messages, then store `chatId` and `messageId` to database, and then on some conditions we call `editMessageText` method to edit these messages. In MOST of the cases everything works fine, but there is a small amount of `editMessageText` calls returning `400: Bad Request: message to edit not found`.
We can't figure why is it happening. All messages are created by bot, therefore, there should be no message "age" limit for editing (as far as I could google it, there is really a lack of info in doco). Somebody on Internet says about some "48 hours" max message age, but in our cases the oldest errored message was ~17 hrs old (created in the evening, edited in the morning")
Can anyone please help me to understand wtf is going wrong? I'm confused, I literally did a text search in all `tdlib` repos, for string `message to edit not found` - didn't find anything:( there is no such string in any official doco pages, repos, issues, etc. Seems like some kind of mystery.

**Comment by levlam** [comment]
The error means that the message doesn't exist. It was deleted by the user or just became inaccessible to the bot: "[Bots have limited cloud storage – older messages may be removed by the server shortly after they have been processed.](https://core.telegram.org/bots#how-are-bots-different-from-users)"

**Comment by rovnyart** [comment]
Oh I see. So it means there is nothing for us to do with it?

**Comment by levlam** [comment]
Yes. The message doesn't exist for the bot anymore, so it can't be edited. Only callback queries can be received from the message.
