### ISSUE TITLE
Strange `callback_query` responses for older messages.

### ISSUE THREAD

**Issue by zombeer** [tdlib/telegram-bot-api#401]
Hey.
I'm getting `callback_queries` like this:
```json
{
    "callback_query": {
        "chat_instance": "-3762349473594986056",
        "data": "check:35",
        "from": {
            "first_name": "Michael",
            "id": 238051111,
            "is_bot": false,
            "language_code": "en",
            "last_name": "S.",
            "username": "Michael"
        },
        "id": "1022421917380556503",
        "message": {
            "chat": {
                "first_name": "Michael",
                "id": 238051111,
                "last_name": "S.",
                "type": "private",
                "username": "Michael"
            },
            "date": 0,
            "message_id": 875400
        }
    }, 
    "update_id": 695385399
}
```
If I'm trying to push buttons of messages older that several hours or day maybe. With newly arrived messages everything is fine and callback_queries are parsed correctly. But older ones give this issue.

I use Rust teloxide crate as client, but found similar issue at go-telegram-bot repo. Could you please take a look?

https://github.com/go-telegram-bot-api/telegram-bot-api/issues/645 - go telegram bot issue.
https://github.com/teloxide/teloxide/issues/873 - teloxide issue

**Comment by WaffleLapkin** [comment]
(note that `callback_query.message` is missing almost all fields, this is the problem)
