### ISSUE TITLE
Is there any limitation on calling the API in order to remove messages?

### ISSUE THREAD

**Issue by busslina** [tdlib/telegram-bot-api#403]
Like Telegram Docs says, there is a limitation when sending messages. I wanted to know there is a limitation on removing them. I didn't found that answer on Telegram Docs.

I want to remove all chat history by iterating from one message (the last message) to the initial message by subtracting 1 to current message id. Breaking iteration when `Bad Request: message can\'t be deleted for everyone` response received.

So I want to know if I have to put time limitations on this iteration.

Thanks

UPDATE: It seems that it is working okay without time limitation but I want to be sure of that.

**Comment by levlam** [comment]
You must never do any arithmetic operations on message identifiers. Also, bots can't delete messages older than 48 hours.

**Comment by levlam** [comment]
> I know when I have to stop deleting when I receive this Bad Request: message can\'t be deleted for everyone. This indicates that this message is 48+ hours ago.

No, this only indicates that the bot sent a wrong request.

> It's the only way because there is not an API way to clear history efficiently. 

No, you must store identifiers of messages, which you want to delete. Otherwise, you will exceed limits were quickly.

**Comment by busslina** [comment]
> No, this only indicates that the bot sent a wrong request.

It is not true, 400 HTTP status code indicates a wrong request. But also there is more info if you dig into... There is a more detailed info that you can get (you must know) if you read the different messages that Telegram sends together with the status code. Since I dind't found any offical documentation about these different erros (reasons), I digged into. These are the different "wrong request" message I studied:

```
switch (error.description) {
      case 'Bad Request: message can\'t be edited':
        return TelegramResponseError.messageCantBeEdited;
      case 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message':
        return TelegramResponseError.messageContentNotChanged;
      case 'Bad Request: message to edit not found':
        return TelegramResponseError.messageNotFound;
      case 'Bad Request: query is too old and response timeout expired or query ID is invalid':
        return TelegramResponseError.invalidCallbackQuery;
      case 'Bad Request: message to delete not found':
        return TelegramResponseError.messageToDeleteNotFound;
      case 'Bad Request: message can\'t be deleted for everyone':
        return TelegramResponseError.messageCantBeDeletedForEveryone;
      case 'Bad Request: failed to get HTTP URL content':
        return TelegramResponseError.failedToGetHttpUrlContent;
      case 'Bad Request: wrong file identifier/HTTP URL specified':
        return TelegramResponseError.wrongFileIdentifierOrHttpUrlSpecified;
      default:
        return TelegramResponseError.other;
    }
```

I can tell you this:
1) When you try to delete a non existent (or yet deleted) message, the error description is Bad Request: message to delete not found.
2) When you try to delete and old message (48+ hours), the error description is Bad Request: message can\'t be deleted for everyone.

Conclusion: No, it doesn't indicate only that the bot sent a wrong request.


> No, you must store identifiers of messages, which you want to delete. Otherwise, you will exceed limits were quickly.

I do store message identifiers. But also I want to remove all "prehistory" messages (48- hours). So repeat my question. Is it possible to know the limits for removing messages the same way we do know the limits for sending messages.

Have a good logic day

**Comment by levlam** [comment]
> No, it doesn't indicate only that the bot sent a wrong request.

This is absolutely wrong. The error tells nothing about message send date and can be returned because of dozens other errors in the request.

You must not use guessed message identifiers in requests.

**Comment by busslina** [comment]
I tested it and it operates like I described, even without knowing the code (black box) using induction. If it is round and bounce, it is a ball.

Thank you very much

**Comment by levlam** [comment]
> I tested it and it operates like I described

This only means that the code is incorrect by design.

**Comment by busslina** [comment]
Not round, squared then
