### ISSUE TITLE
Apple bot start problem

### ISSUE THREAD

**Issue by alon-sys** [tdlib/telegram-bot-api#405]
In the new version of Apple, if you click the link of the current robot on the robot dialogue interface and follow the ?start=xxxxxx parameter, there will be a problem of no response to the click, but clicking the link on other dialogue interfaces can successfully invoke the robot and enter the satrt command . Clicking on the link of the current robot on the current robot interface on both the Android and PC side responds normally. This problem makes some logic of robot interaction impossible to realize, which affects users a lot. Please find out the reason and fix it as soon as possible.

**Comment by erfanmola** [comment]
See https://github.com/TelegramMessenger/Telegram-iOS/issues/1091

**Comment by gnurlan** [comment]
I had a similar issue with the Start parameter and my solution was to add another GET parameter to the URL: `https://t.me/botusername/appname?start=test&secont=1`
