### ISSUE TITLE
Hanging webhooks

### ISSUE THREAD

**Issue by uPagge** [tdlib/telegram-bot-api#407]
Hello

I develop a bot, and there are often situations when a user sends a message, but a webhook message comes in 10-15 seconds, this happens if the user has not written for a long time. This happens without using your telegram-bot-api. Actually, my question is, will using your local server help to solve this problem?

P.S I understand that this is not an Issue, I don't know who to turn to anymore, I can't understand what's going on

**Comment by levlam** [comment]
This is likely an issue with the server where your bot is hosted, or with the bot's code.
