### ISSUE TITLE
Telegram Web App Navigation

### ISSUE THREAD

**Issue by Firas-salah** [tdlib/telegram-bot-api#408]
Hello,  I'm encountering a problem where I can't navigate through my webapp without it prompting to open every link I press, and when I accept to proceed, it opens the link inside the telegram web browser and not inside the web app instance.

I couldn't find anyone else encountering this problem, I am using django as the backend and changing url's is essential so that the web app can work correctly (as that is how django is built), although when I open the webapp via Telegram desktop it navigates fine within the webapp instance and does not open links in an external browser.

This problem only occurs on mobile it seems, btw im using an android phone,  haven't tried ios (if that could make any difference), I am also hosting the web app on ngrok for testing...

**Comment by levlam** [comment]
Do you have `target=_blank` attribute on the links, or try to open them with `window.open`?

**Comment by Firas-salah** [comment]
> Do you have `target=_blank` attribute on the links, or try to open them with `window.open`?

Can you please elaborate a bit more I didn't understand your question ?

**Comment by levlam** [comment]
https://www.w3schools.com/tags/att_a_target.asp
https://www.w3schools.com/jsref/met_win_open.asp

**Comment by Firas-salah** [comment]
> https://www.w3schools.com/tags/att_a_target.asp https://www.w3schools.com/jsref/met_win_open.asp

Oh ok I got what you mean, tbh im not sure because I'm using django's default admin page, and I have not customly edited it,

but even on my custom html page I still encounter this problem, here's the body of the html code, down where the sign up button is , is where it asks me to got side of the web app and into telegrams browser which ruins the smooth experience 


  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">


            <h3 id="form-title">LOGIN</h3>
          </div>
          <div class="d-flex justify-content-center form_container">

            {% if user.is_authenticated %}
                <h2>Logged in succesfully!</h2>
            {% else %}
                <form method="POST" action="">
                    {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" name="username" placeholder="Username..." class="form-control">
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" name="password" placeholder="Password..." class="form-control">
                </div>

                <div class="d-flex justify-content-center mt-3 login_container">
                    <input class="btn login_btn" type="submit" value="Login">
                </div>
                </form>
            {% endif %}
          </div>

          <div class="mt-4">
            <div class="d-flex justify-content-center links">
              Don't have an account? <a href="/form/" class="ml-2">Sign Up</a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </body>

</html>

**Comment by levlam** [comment]
Then it is a bug of the app. It has a ticket at https://bugs.telegram.org/c/18649.

**Comment by Firas-salah** [comment]
> Then it is a bug of the app. It has a ticket at https://bugs.telegram.org/c/18649.

So what do you suggest I do now?

**Comment by levlam** [comment]
Load other pages using JavaScript, or wait until the bug is fixed in the app.

**Comment by Firas-salah** [comment]
what methods would you suggest ? because I did try some before with no avail :(

**Comment by levlam** [comment]
Currently, you have no other options than avoiding ordinary HTTP links.

**Comment by Firas-salah** [comment]
> Currently, you have no other options than avoiding ordinary HTTP links.

I'm not aware of any other linking methods, any heads up? (keeping in mind im using django)

**Comment by levlam** [comment]
The bug has been fixed in the Android app some time ago.
