### ISSUE TITLE
Is Web App feature behavior restricted to Single Page App behavior only?

### ISSUE THREAD

**Issue by xtianpu** [tdlib/telegram-bot-api#410]
Hello! Currently, I'm developing a bot to connect bot users to their Twitter account using a Web App.

But it looks like the Telegram for Windows doesn't clear any data for web app which make bot users stuck to one account when connecting another Twitter account since the web app storing the session of twitter login. Is there any solution for this? Or am I misunderstood that Web App should be used with Single Page App rather than server side rendering (like redirect)?

Solution for now, I was using an Inline Button to open web URL rather than web app, so the user can log out their Twitter account and login with another one.

**Comment by levlam** [comment]
Web App is launched in WebView, which is just an embedded browser. There are no subtle differences between opening a web page in a browser and running a Web App in WebView.

**Comment by xtianpu** [comment]
> Web App is launched in WebView, which is just an embedded browser. There are no subtle differences between opening a web page in a browser and running a Web App in WebView.

Hello, thank you for your response. So is there a way to clear session or cookies of logged account on web app on Telegram for Windows?

**Comment by erfanmola** [comment]
> > Web App is launched in WebView, which is just an embedded browser. There are no subtle differences between opening a web page in a browser and running a Web App in WebView.
> 
> Hello, thank you for your response. So is there a way to clear session or cookies of logged account on web app on Telegram for Windows?

No there isn't, Telegram Web Apps are just web pages that have an extra js file which talks to telegram clients

The web pages are rendered in WebView, meaning that the WebView has no idea even what Telegram is, so it has no idea of any extra data, it's job is to render to web page

But telegram clients tend to pass some extra information to the Web Pages opened with their WebView, such as: basic information of the user who opened it, information about the theme of the Telegram Client and etc, and the Telegram Web App JS file parses those data passed by URL, then makes it accessible in JS side as objects, that's the whole thing, no magic or direct relation with telegram

**Comment by xtianpu** [comment]
> Web App is launched in WebView, which is just an embedded browser. There are no subtle differences between opening a web page in a browser and running a Web App in WebView.

Just test on Android, iOS, and Windows platform. But looks like Telegram for Windows doesn't use any default browser because when I go to twitter.com there is no logged in account.

**Comment by xtianpu** [comment]
> > > Web App is launched in WebView, which is just an embedded browser. There are no subtle differences between opening a web page in a browser and running a Web App in WebView.
> > 
> > 
> > Hello, thank you for your response. So is there a way to clear session or cookies of logged account on web app on Telegram for Windows?
> 
> No there isn't, Telegram Web Apps are just web pages that have an extra js file which talks to telegram clients
> 
> The web pages are rendered in WebView, meaning that the WebView has no idea even what Telegram is, so it has no idea of any extra data, it's job is to render to web page
> 
> But telegram clients tend to pass some extra information to the Web Pages opened with their WebView, such as: basic information of the user who opened it, information about the theme of the Telegram Client and etc, and the Telegram Web App JS file parses those data passed by URL, then makes it accessible in JS side as objects, that's the whole thing, no magic or direct relation with telegram
> 
> Telegram WebView does not set any cookies that I recall, Setting or clearing any cookies or etc is your responsibility, just take note that on some clients such as Telegram iOS, the WebView does not respect the multiple instances, it just shares the WebView cookies and local storage data across the entire Telegram iOS app, so beware of what data you set as Cookies/LocalStorage

maybe you want check my last reply

**Comment by levlam** [comment]
Web Apps aren't restricted to Single Page App. There was a bug in the official Android app, which prevented usage of redirects, but it was fixed some time ago.

WebView behavior regarding cookies and local storage is inheritenly platform-specific, but if there is a way to change it on a specific platform to work in the same way as on the other platforms, you can create a ticket for this at https://bugs.telegram.org

**Comment by jwcheon** [comment]
@xtianpu Hello did you manage to do a Twitter login within the Telegram Webapp by any chance?

**Comment by dasturchioka** [comment]
can we store data like auth tokens to Cookies or LocalStorage?

**Comment by levlam** [comment]
@dasturchioka Yes. You can also store them in WebApp.CloudStorage.

**Comment by chimit** [comment]
@levlam I noticed it's not that simple in the web version of Telegram (web.telegram.org) because the mini app is opened in an iframe, and I couldn't set cookies there. This is probably because of different domains. I tried to set SameSite to `none`, set a cookie domain explicitly but without success. Is it possible?
