### ISSUE TITLE
Compilation Error: Invalid application of 'sizeof' to incomplete type 'td::DialogFilter'

### ISSUE THREAD

**Issue by LokiVKlokeNaAndoke** [tdlib/telegram-bot-api#411]
Hello,

I am trying to compile the project on my machine and have run into a compilation error.

**Environment**
- OS: Linux 6.3.1-zen2-1-zen
- Compiler version: gcc (GCC) 13.1.1
- CMake version: 3.26.3
- Branch/Commit ID: 251589221708a8280ffcad32fcdc5348d014a6ae

**Steps to Reproduce**
```bash
cd telegram-bot-api
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
cmake --build . --target prepare_cross_compiling
cd ../td
php SplitSource.php
cd ../build
cmake --build . --target install
cd ../td
php SplitSource.php --undo
cd ../..
```

**Expected Result**
I expected the project to compile without errors.

**Actual Result**
I am getting the following error message during the compilation process:
```
/home/dima/build/telegram-bot-api/td/tdutils/td/utils/unique_ptr.h:49:19: error: invalid application of ‘sizeof’ to incomplete type ‘td::DialogFilter’
   49 |     static_assert(sizeof(T) > 0, "Can't destroy unique_ptr with incomplete type");
      |                   ^~~~~~~~~
```
This appears to be related to the `td::DialogFilter` class being an incomplete type when it's being used in `td::unique_ptr<T>`.

**Attachments**
I have attached the full error log [here](https://github.com/tdlib/telegram-bot-api/files/11472959/error.txt).

Is this a known issue or am I missing something in the compilation process? Any guidance would be greatly appreciated.

Thanks!

**Comment by AYMENJD** [comment]
You are not correctly building local Bot API.

See: https://github.com/tdlib/telegram-bot-api#installation.

**Comment by levlam** [comment]
`SplitSource` build was fixed in https://github.com/tdlib/td/commit/f755ed8e977b20094471c84b72a328b199d309fc. You can do the following to fix it in Bot API:
```
cd telegram-bot-api/td
git pull --ff-only
git reset --hard f755ed8e977b20094471c84b72a328b199d309fc
cd ../..
```

With this TDLib commit, you will be able to build Bot API.

**Comment by LokiVKlokeNaAndoke** [comment]
Thanks, it compiles now.
