### ISSUE TITLE
"One or more errors occurred. (Logged out)"

### ISSUE THREAD

**Issue by PabloSergi** [tdlib/telegram-bot-api#413]
Hello everyone, iv encountered a peculiar issue with my telegram bot api server. I followed the instructions provided at https://tdlib.github.io/telegram-bot-api/build.html to install it. I have a static IP address for my server and I have successfully started the server using my api id and hash. iv verified its functionality by using the command "netstat -tuln" and confirmed that it is working.
Next i updated my bot's code and added my servers ip address and port to the following line:
bot = new TelegramBotClient(TlgToken, new HttpClient { BaseAddress = new Uri("apiTlgServer") });
Afterwards, as mentioned in the documentation, i logged out my bot: “To guarantee that your bot will receive all updates, you must deregister it with the https://api.telegram.org server by calling the method [logOut](https://core.telegram.org/bots/api#logout). After the bot is logged out, you can replace the address to which the bot sends requests with the address of your local server and use it in the usual way. If the server is launched in --local mode, make sure that the bot can correctly handle absolute file paths in response to getFile requests.”
However, when I started my application, i encountered the error message "One or more errors occurred. (Logged out)". im unable to comprehend why this occurred, as my bot should have been successfully logged out to allow logging in to the new server. What could be the potential cause of this problem?

**Comment by levlam** [comment]
Check that you send requests to the new local server and not to https://api.telegram.org. The error message "One or more errors occurred. (Logged out)" is very likely to be received for a request to https://api.telegram.org.
