### ISSUE TITLE
Is port 8081 only accessible locally? Is it not accessible from outside the local?

### ISSUE THREAD

**Issue by augushong** [tdlib/telegram-bot-api#417]
I run telegram-bot-api on a server, no matter whether I add the -local parameter or not, only localhost:8081 can access it, and other networks cannot access it.
Is that so?

**Comment by levlam** [comment]
No. By default. the server can be accessed by all local IPv4 interfaces, i.e. it can be freely accessed from a local network via IPv4. You need to pass the parameter `--http-ip-address` to change this behavior. For example, you can pass "127.0.0.1" to allow only incoming IPv4 localhost connections, "::" to allow IPv6 and IPv4 connections from local network, or "::1" to allow IPv6 and IPv4 connections only from the same host.

**Comment by augushong** [comment]
Thanks, it is very helpful.
