### ISSUE TITLE
getFile method fails to generate a valid url

### ISSUE THREAD

**Issue by el-lsan** [tdlib/telegram-bot-api#42]
For some weird reason my bot stopped working after couple of tries.
Base on [API documentation for getfile](https://core.telegram.org/bots/api#getfile) I should get a valid url for at least one hour for any file below 20mb and I don't see any more limitation on this method.
However I'm getting 404 response after the second try for each file format.

This issue started happening after couple of hours of testing my bot.
At the beginning I was just testing my bot with animation files ( GIFs ) and after 1-2 hours of testing which I've downloaded ~20 files it stopped working. 
After that I tried with a photo and it worked for the first file and failed for further attempts.
Same thing happened to audio and video files, so after the first successful attempt it started giving 404.

I tried following solutions:

 - Using both http (`http://api.telegram.org/file/bot<token>/<file_path>`) and https (`https://api.telegram.org/file/bot<token>/<file_path>`)
 - Revoking my token and tried with a new token.
 - Creating a new bot and using its token
 - Rebooting my modem to get a new public IP ( in case it was somehow blacklisted/limited )
 - Using another device on a different network

But none of these changed anything.

Any idea what could be the reason ?

**Comment by WaffleLapkin** [comment]
How have you fixed the problem? Have you figured out what it was?

**Comment by arladmin** [comment]
@el-lsan 
Facing the same problem. 
Were you able to find out a solution for this?
Thanks.

**Comment by el-lsan** [comment]
@WaffleLapkin @arladmin 
This was happening because I was calling deletemesssage method before download was made/finished.
so apparently if you remove your message the bot can't access to the file anymore.

**Comment by malikovss** [comment]
Facing the same problem. 
I always get 404. File is not saved on my local machine after I called getFile method. what should I do?
![image](https://user-images.githubusercontent.com/47824375/115102805-e0af5680-9f66-11eb-80f6-38b91e1abf0a.png)

http://localhost:8081/file/botToken/documents/file_2
![image](https://user-images.githubusercontent.com/47824375/115102848-1d7b4d80-9f67-11eb-8164-9114fcb95e06.png)

**Comment by levlam** [comment]
@malikovss The file is saved in the bots folder in the server's working directory.
