### ISSUE TITLE
Installation failed in MacBook

### ISSUE THREAD

**Issue by falahatiali** [tdlib/telegram-bot-api#423]
I get this error after running `cmake --build . --target install` command.

```
fatal error: 'td/db/KeyValueSyncInterface.h' file not found
#include "td/db/KeyValueSyncInterface.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/telegram-bot-api.dir/telegram-bot-api/telegram-bot-api.cpp.o] Error 1
make[1]: *** [CMakeFiles/telegram-bot-api.dir/all] Error 2
```

**Comment by levlam** [comment]
Follow the instructions at https://tdlib.github.io/telegram-bot-api/build.html?os=macOS.

**Comment by falahatiali** [comment]
@levlam I followed this instruction. but it throws that error. I checked and the problem is this:
inside build folder we dont have this path. `td/db/KeyValueSyncInterface.h`
the correct path is this : `td/tddb/td/db/KeyValueSyncInterface.h`

**Comment by levlam** [comment]
The real issue is that the repository wasn't correctly pulled. The correct command is `git clone --recursive https://github.com/tdlib/telegram-bot-api.git`.

**Comment by falahatiali** [comment]
the problem was some packages didnt install correctly
`
brew install gperf cmake openssl
`
I run this command again and it fixed.
@levlam  thanks for your reply and help.
