### ISSUE TITLE
getUpdates: Concurrent short polling drops updates and 100 limit is too low

### ISSUE THREAD

**Issue by halaei** [tdlib/telegram-bot-api#43]
Yesterday we have issue with long polling. The requests to get updates took a couple of seconds, instead of a fraction of a second. Meanwhile users was sending updates to bot with rate higher than 100 updates per second. So updates were getting accumulated in Telegram server. I guess it was on your side or something global in AWS, because we have issue in 2 servers.

I was thinking of a workaround for situation like this. My idea was to detect such congestions by counting the number of updates received by getUpdates(timeout: 10). If the count is 100, it means updates are overflowing, so I can fall back into sending multiple concurrent short polling, e.g. getUpdates(timeout: 0, offset: nextOffset), getUpdates(timeout: 0, offset: nextOffset + 100). However, it didn't work well in my tests because Telegram occasionally droped some of updates, probably when the second request get handled by Telegram before the first one.

So my plan doesn't work unless you can relax some of the limitations.
One option is to increase the limit of offset, maybe from 100 to 1000. It seems that you drop old updates anyway, so why not?

**Comment by levlam** [comment]
Increasing long polling limit is not an option, because It will increase maximum response size and significantly increase bot's latency. If you have a high-loaded bot, then you need to process updates asynchronously and send new `getUpdates` request immediately after receiving result of the previous `getUpdates` request. Ping to a local Bot API server or to api.telegram.org from Amsterdam is less than 1 ms, so you can fetch about 100000 updates per second this way.

Manually adjusting offset before receiving `getUpdates` response is wrong. There is no guarantee that update IDs are consecutive without gaps.

**Comment by halaei** [comment]
> If you have a high-loaded bot, then you need to process updates asynchronously and send new getUpdates request immediately after receiving result of the previous getUpdates request.

We're doing as you say. But updates was overflowing yesterday. If it happens again, I check ping as well.

> Manually adjusting offset before receiving getUpdates response is wrong. It is not guaranteed that update IDs are consecutive without gaps.

I know. It is just a dirty fix. I removed duplicate updates in my code to not processing an update twice.


> Increasing long polling limit is not an option, because It will increase maximum response size and significantly increase bot's latency.

I don't know if increasing response size is an issue for you but it's fine for us. In terms of increasing bot's latency, its going to be far better than what happened yesterday. Our bot was down for an hour and your current implementation can offer nothing better than dropping updates.

I suggest don't changing the default offset, but let it's maximum be a bit more, maybe 500 or 200 if you are not OK with 1000?

**Comment by levlam** [comment]
If you have ping of 81 ms, then switching to a local Bot API server, as provided by this repository, could improve performance of your bot. Or you can move the bot to AWS server in Central Europe to significantly reduce ping time.

**Comment by halaei** [comment]
Thanks. I look into it. Also I let you know if I detect issues in ping from Europe too.
