### ISSUE TITLE
1

### ISSUE THREAD

**Issue by wochuogege** [tdlib/telegram-bot-api#430]
1

**Comment by levlam** [comment]
> Can't lock file "/root/tqueue.binlog", because it is already in use; check for another program instance running

**Comment by wochuogege** [comment]
[!ClientManager]    Unexpected Status [PosixError : Resource temporarily unavailable : 11 : Can't lock file "/root/tqueue.binlog", because it is already in use; check for another program instance running] in file /root/telegram-bot-api/telegram-bot-api/ClientManager.cpp at line 326            
[pid 295226] [time 1688216751] ------------------------
root@3f8:~# pidof telegram-bot-api
166310
root@3f8:~# kill 166310
root@3f8:~# pidof telegram-bot-api
root@3f8:~# telegram-bot-api --api-id=23442359 --api-hash=2c62fe221ce44e7ea47e4f2da6f5db17 --
FAIL TO START

**Comment by AYMENJD** [comment]
Try:
```bash
fuser -k "/root/tqueue.binlog"
```

**Comment by wochuogege** [comment]
https://tdlib.github.io/telegram-bot-api/build.html?os=Linux
