### ISSUE TITLE
0

### ISSUE THREAD

**Issue by wochuogege** [tdlib/telegram-bot-api#431]
1

**Comment by levlam** [comment]
https://tdlib.github.io/telegram-bot-api/build.html

**Comment by wochuogege** [comment]
/usr/local/bin/telegram-bot-api[0x4161ef]
/usr/local/bin/telegram-bot-api[0x511cf7]
/usr/local/bin/telegram-bot-api[0x53d1dd]
/usr/local/bin/telegram-bot-api[0x4155a0]
/usr/local/bin/telegram-bot-api[0x540256]
/usr/local/bin/telegram-bot-api[0x541bff]
/usr/local/bin/telegram-bot-api[0x541dbb]
/usr/local/bin/telegram-bot-api[0x53adfb]
/usr/local/bin/telegram-bot-api[0x53ad7a]
/lib64/libpthread.so.0(+0x7ea5)[0x7fc6e3410ea5]
/lib64/libc.so.6(clone+0x6d)[0x7fc6e3139b0d]
-------------------------------
[root@3f8 ~]# /usr/local/bin/telegram-bot-api --api-id=20991359 --api-hash=44033cd8d1a0a9258c685e99860db1 --local --http-port=8081 --http-stat-port=8082

DURATION	inf	5sec	1min	1hour
uptime	4287.834279
bot_count	2
active_bot_count	2
rss	25036KB
vm	581MB
rss_peak	25036KB
vm_peak	636MB
total_cpu	0.703469%	0.441826%	0.436866%	0.703469%
user_cpu	0.334359%	0.294551%	0.205060%	0.334359%
system_cpu	0.369110%	0.147275%	0.231807%	0.369110%
buffer_memory	98KB
active_webhook_connections	1
active_requests	52
active_network_queries	56
request_count	0.013757	0.000000	0.011753	0.013760
request_bytes	4.369491	0.000000	4.195694	4.370510
request_file_count	0.000000	0.000000	0.000000	0.000000
request_files_bytes	0.000000	0.000000	0.000000	0.000000
request_max_bytes	0	0	0	0
response_count	0.001632	0.000000	0.000000	0.001633
response_count_ok	0.001632	0.000000	0.000000	0.001633
response_count_error	0.000000	0.000000	0.000000	0.000000
response_bytes	0.270237	0.000000	0.000000	0.270300
update_count	0.000000	0.000000	0.000000	0.000000



{"ok":true,"result":true,"description":"Webhook was set"}

8081
{"ok":false,"error_code":404,"description":"Not Found"}

**Comment by wochuogege** [comment]
> https://tdlib.github.io/telegram-bot-api/build.html

This step has been installed
