### ISSUE TITLE
How Run Telegram Bot Api Local With Proxy?

### ISSUE THREAD

**Issue by azkadev** [tdlib/telegram-bot-api#432]
I am using wifi network with manual proxy, how to run telegram-bot-api with proxy?

I've added these parameters 
```bash
--proxy=http://192.168.101.91:8080
```

in the terminal but the local api bot can't be accessed / doesn't work

**Comment by azkadev** [comment]
sorry, I set the wrong network connection

**Comment by levlam** [comment]
The `proxy` option changes HTTP proxy server for outgoing webhook requests. It doesn't affect connections to Telegram servers.

**Comment by azkadev** [comment]
> The `proxy` option changes HTTP proxy server for outgoing webhook requests. It doesn't affect connections to Telegram servers.

Can telegram api local bots use proxies?

i tried but it shows this error in logs

![Screenshot from 2023-07-04 23-47-27](https://github.com/tdlib/telegram-bot-api/assets/82513502/b65d7d46-8248-471f-bb9e-f1cca62610ba)

i tried curl http://localhost:9000/bot<token_bot>/getMe but it freezes, but i can run bot/telegram using my proxy

**Comment by AYMENJD** [comment]
@azkadev See #399.
