### ISSUE TITLE
Error 137 n 2

### ISSUE THREAD

**Issue by RootMagnus** [tdlib/telegram-bot-api#433]
i try build om my linux mint n its work, but i try build on my ubuntu 20 server (1gb RAM (maybe little?)) n got this error.  Used instruction for install

[ 70%] Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o
Killed
make[2]: *** [td/CMakeFiles/tdcore.dir/build.make:1766: td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o] Error 137
make[1]: *** [CMakeFiles/Makefile2:517: td/CMakeFiles/tdcore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by levlam** [comment]
You need at least 4GB RAM to build the server with GCC and about 2GB RAM to build it with clang.

**Comment by RootMagnus** [comment]
> You need at least 4GB RAM to build the server with GCC and about 2GB RAM to build it with clang.

Oh.. Okay, ty
