### ISSUE TITLE
raspberry pi bulls-eye link error

### ISSUE THREAD

**Issue by zweistein22** [tdlib/telegram-bot-api#437]
I get 

 undefined reference to `__atomic_fetch_add_8'

and other symbols from libatomic undefined.

Obviously libatomic is not linked.
I tried with enviromment:
export LDFLAGS="-L/usr/lib/arm-linux-gnueabihf -latomic"
export CXXFLAGS="-latomic"

but still no success.  I don't want to mess around too much in the CMakeLists.txt (which doesn't exist anyway).  Please give indication on how to modify build process to link in libatomic.

gnu compiler toolchain

Best regards
Andreas

**Comment by zweistein22** [comment]
found CMakeLists.txt and added atomic to the linking process.
target_link_libraries(           atomic)

AL

**Comment by levlam** [comment]
See https://github.com/tdlib/td/issues/790#issuecomment-553993433.
