### ISSUE TITLE
Support streaming download

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#440]
I would really appreciate it if you could add an option to the `getFile` method to return the byte stream instead of downloading files to the disk.

**Comment by levlam** [comment]
There is no way to do this without significantly reducing download speed. The file must be cached somewhere to have acceptable download performance and disk is the best option for such cache.

**Comment by foremtehan** [comment]
I want to serve some telegram files over http, with current implementation i have to wait to telegram-bot-api to download it first then i serve it to user which is waste of time and disk space

**Comment by levlam** [comment]
Telegram files aren't intended to be served over HTTP.
