### ISSUE TITLE
Send update when user join/left channel/group

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#441]
As much as I love the telegram-bot-api over other libraries, I wonder why we can't have these kinds of updates in the telegram-bot-api I want to receive updates when a user joins or leaves a channel, but currently, we don't receive any updates. Here is an example of how it works in other libraries:

```
{
	"result": {
		"update": {
			"_": "updateChannelParticipant",
			"via_chatlist": false,
			"channel_id": 98765432,
			"date": 1389498115,
			"actor_id": 12345678,
			"user_id": 12345678,
			"prev_participant": {
				"_": "channelParticipant",
				"user_id": 12345678,
				"date": 1589498060
			},
			"qts": 129180296
		}
	}
}
```

**Comment by levlam** [comment]
See https://core.telegram.org/bots/api#update.

**Comment by foremtehan** [comment]
I mean the 'normal' user and not the bot itself i know it send the update when a bot joined the chat but it wont send update when a normal user join a channel...

**Comment by levlam** [comment]
Updates are always sent as documented. You must explicitly enable "chat_member" updates to receive them.
