### ISSUE TITLE
startapp=XXX does not work on iPhone

### ISSUE THREAD

**Issue by kmfrick** [tdlib/telegram-bot-api#443]
The startapp parameters in the web app URL are not passed to the app when opened from iPhone but the work when opened from desktop or an Android phone (same link). I tried opening this twice on bugs.telegram.org but it was closed with no comment. Let me know if there is any more info that I need to provide.

# Steps to reproduce
1. Create a bot and register a web app using BotFather
2. Send some data to the app, i.e. `t.me/botname/appname?startapp=2`
3. On the receiving end, prettyprint `Telegram.WebApp.initData`, e.g. `alert(JSON.stringify (Telegram.WebApp.init_data))`
4. The start param field will only be there on desktop
# Device info
Telegram iOS 9.6.3 (25780), iPhone 11, 16.2
# Pictures
Attached.

<img width="288" alt="does not work on iPhone" src="https://github.com/tdlib/telegram-bot-api/assets/15724656/4b304834-7eff-45b4-935c-b89ad3bd0854">
<img width="288" alt="works on desktop" src="https://github.com/tdlib/telegram-bot-api/assets/15724656/d171505a-69a5-46a8-8c4a-d7fa7cb115ae">

**Comment by AYMENJD** [comment]
This is known bug and probably will be fixed in the next appstore release. 

Current workaround is passing `startapp=XXX&startApp=XXX`.

**Comment by kmfrick** [comment]
Great, thanks! This also solves the issue of why my tickets on bugs.telegram.org were closed.
