### ISSUE TITLE
how to make request by bot api call sendMediaGroup to send album use python

### ISSUE THREAD

**Issue by johngao01** [tdlib/telegram-bot-api#444]
i have a album to send by bot perfer use bot api call https://api.telegram.org/bot{token}/sendMediaGroup?chat_id={chat_id}, according to [issue315 ](https://github.com/tdlib/telegram-bot-api/issues/315) i have write code like this:
`import requests

token = '54321'
url = f'https://api.telegram.org/bot{token}/'
chat_id = 123456

data = {
    "media": "[{\"type\":\"photo\",\"media\":\"https://media.cnn.com/api/v1/images/stellar/prod/230719152236-04-how-to-stop-the-next-cuban-missile-crisis.jpg?c=16x9&q=h_720,w_1280,c_fill/f_webp\"},"
             " {\"type\":\"photo\",\"media\":\"https://media.cnn.com/api/v1/images/stellar/prod/230719152208-03-how-to-stop-the-next-cuban-missile-crisis.jpg?c=16x9&q=h_720,w_1280,c_fill/f_webp\"}]"
}

r = requests.post(url + f'sendMediaGroup?chat_id={chat_id}', data=data)
print(r.text)`

it is works.
but i want send photos load from local disk, i change my code to this:
`import requests

token = '54321'
url = f'https://api.telegram.org/bot{token}/'
chat_id = 123456

data = {
    "media": [{"type": "photo", "media": open('test1.jpg', mode='rb')},
              {"type": "photo", "media": open('test2.jpg', mode='rb')}]
}

r = requests.post(url + f'sendMediaGroup?chat_id={chat_id}', data=data)
print(r.text)`

i get error response is {"ok":false,"error_code":400,"description":"Bad Request: can't parse media JSON object"}.

according to [bot api](https://core.telegram.org/bots/api#sendmediagroup) say: 'A JSON-serialized array describing messages to be sent, must include 2-10 items', i change my code data to 
`data = json.dumps({
    "media": [{"type": "photo", "media": open('20230720_4925588140461486_2.jpg', mode='rb')},
              {"type": "photo", "media": open('20230720_4925588140461486_1.jpg', mode='rb')}]
})`
but get error: TypeError: Object of type BufferedReader is not JSON serializable.

how can i send photos load from local disk. i have no idea.

**Comment by levlam** [comment]
See https://core.telegram.org/bots/samples#python.

**Comment by johngao01** [comment]
not found any example by make request to https://api.telegram.org/bot{token}/sendMediaGroup to send album,the file should be load from disk.

most example is instance bot,then use bot.sendMediaGroup(),But I don't think this will work because the bot is already running on other projects.

**Comment by levlam** [comment]
You can check source code of the libraries if you can't use one of them.

**Comment by johngao01** [comment]
sorry, I try read [source code](https://github.com/tdlib/telegram-bot-api/blob/251589221708a8280ffcad32fcdc5348d014a6ae/telegram-bot-api/Client.cpp#L8323), and get the get_input_message_contents method get media_content.

I won't cpp, I can't read the code

can you give me a example, how to make request to [https://api.telegram.org/bot{token}/sendMediaGroup](https://api.telegram.org/bot%7Btoken%7D/sendMediaGroup) to send album, the file should be load from disk.

real thanks

**Comment by levlam** [comment]
I can't you give an example of the code in Python, but all libraries from https://core.telegram.org/bots/samples#python should have it.
