### ISSUE TITLE
Local instance: InlineQueryResultPhoto WEBDOCUMENT_URL_INVALID

### ISSUE THREAD

**Issue by studentenherz** [tdlib/telegram-bot-api#446]
`Bot API 6.7.1`

I'm running the API with `--local`,

This request:

```
{
  "inline_query_id": "xxxxxxxxxxxxxxxx",
  "results": [
    {
      "type": "photo",
      "id": "my_id",
      "photo_url": "http://localhost:8000/12345.jpg",
      "thumbnail_url": "http://localhost:8000/12345.jpg"
    }
  ],
  "cache_time": 0
}
```

Results in 

```
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: WEBDOCUMENT_URL_INVALID"
}
```

Also with `photo_url` using `file://`

**Comment by levlam** [comment]
The URL must be public and globally available as described in https://core.telegram.org/bots/api#inlinequeryresult, therefore you can't use a URL, which is valid only locally.

**Comment by levlam** [comment]
It applies to the cases when the file is uploaded during the request, i.e. the parameter is documented as `InputFile`.
