### ISSUE TITLE
Bot API Server is sending wrong `message_thread_id`

### ISSUE THREAD

**Issue by HeySreelal** [tdlib/telegram-bot-api#447]
When a user replies to the Bot's message on the "GENERAL" topic of any forum the Bot API attaches a totally random `message_thread_id` with the incoming `Message` update to the bot. 

Hence using this `message_thread_id` in `sendMessage` or any other method to send messages will fail throwing the following error:
```json
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: message thread not found"
}
```

**Comment by levlam** [comment]
The behavior is correct. See https://github.com/tdlib/telegram-bot-api/issues/356#issuecomment-1405378400.

**Comment by HeySreelal** [comment]
Thanks for the reply. Now I understand this is the intended behavior.

But when the received `message_thread_id` is utilized in a method such as `sendMessage`, the bot generates an error. Shouldn't it, instead, send the message to the General Topic rather than throwing an error?

**Comment by levlam** [comment]
You don't need to specify `message_thread_id`, if you want to reply a message that doesn't belong to a topic. Actually, you never need to specify `message_thread_id` explicitly when replying to a message without `allow_sending_without_reply`.

**Comment by HeySreelal** [comment]
Thanks @levlam, yeah I'm aware of that. 

The actual reason why I had to open up this issue was an issue with my Telegram Bot API wrapper library. Whenever the incoming message is from a Topic the `message_thread_id` will be set automatically on the `reply` method (a context-aware alias for `sendMessage`). And you already know the rest of the story. When the user responds to a bot message in General Topic, there's a valid message identifier present as `message_thread_id` but when used with `sendMessage` the API call fails.

I think if the chat is a forum, and `message_thread_id` is present the API could just send the message to the General Topic in this case (if `message_thread_id` is a root id of a message in the General Topic). Just my thoughts.

Thanks for your responses again :)

**Comment by HeySreelal** [comment]
I understand how this works, thanks again. 

I'm closing this issue as this is not a bug or problem with the Bot API.
