### ISSUE TITLE
telegram-api-server for big telegram bots ? 

### ISSUE THREAD

**Issue by sepsoh** [tdlib/telegram-bot-api#449]
can i use telegram-api-server for big telegram bots ? or using orginal webhook is better ?

**Comment by levlam** [comment]
It is the same server that is used at api.telegram.org, so it definitely can be used for bots with extremely high load. But if you don't know, why do you need to use a self-hosted Bot API server, then it is better to use api.telegram.org.

**Comment by sepsoh** [comment]
Thanks , I thought this library is only for testing locally, so now I can safely log into it with my Orginal Telegram account and use it in production?

**Comment by levlam** [comment]
The server is for bots, which use Bot API.
