### ISSUE TITLE
Issue with hosting multiple local bot

### ISSUE THREAD

**Issue by devsdocs** [tdlib/telegram-bot-api#451]
Hi, I want to run multiple local bot on same local bot api server, on port 8081, but whenever one bot started, the other previously started bot get terimated. why? any additional args need to passed when starting bot api server?

my command
 ./telegram-bot-api --api-id=123 --api-hash="123" --local

**Comment by levlam** [comment]
What do you mean by "the other previously started bot get terimated"? The Bot API server has no way to "terminate" the bot.

**Comment by devsdocs** [comment]
the other local bot that already started, get terminated, I think this has something to do with localhost port maybe, any idea?

**Comment by levlam** [comment]
Bots use the server on the given port, they don't interfere with the server in any way. What do you mean by "the other local bot", and who terminates it?
