### ISSUE TITLE
Connecting Telegram client to my local server

### ISSUE THREAD

**Issue by culda** [tdlib/telegram-bot-api#454]
Might be a stupid question but how do I plug in the TG client to my bot server. 
Local bot server is running fine, but I can't work out how to send messages to it as if I'm a user.

**Comment by levlam** [comment]
This is a Telegram Bot API server, not a Telegram API server, so users can't connect to it. See https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-721873231 for more details.
