### ISSUE TITLE
Compile Android Successfully but when run it doesn't display any text

### ISSUE THREAD

**Issue by azkadev** [tdlib/telegram-bot-api#458]
I know android is not a suitable device to run api bot, but I'm building a program,

I'm trying to build telegram api bot
Here is my repos: https://github.com/azkadev/codespaces

When run on adb shell / termux it doesn't appear even though I have chmoded it

![Screenshot from 2023-08-15 19-20-09](https://github.com/tdlib/telegram-bot-api/assets/82513502/b549e621-e745-419c-a154-916e14f39aa6)

Previously I tried to succeed, what's wrong can you give me information?

This is the Terminal Build Command I did

```bash
cd telegram-bot-api
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=/workspaces/codespaces/ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ..
cmake --build .
```

My Cmake Version

```bash
cmake version 3.26.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by levlam** [comment]
You can try to increase log verbosity level to find, what is going on.

**Comment by azkadev** [comment]
Can you help me?

I have tried to compile and run on android, it works but there is no log even though I added verbos to level 3

**Comment by levlam** [comment]
Then the process is killed before it actually starts. You can try to run it under any debugger like gdb. I can hardly help with remote debugging.
