### ISSUE TITLE
Missing update_id in getUpdates

### ISSUE THREAD

**Issue by testumadio** [tdlib/telegram-bot-api#464]
I noticed that if you often publish and delete albums with photos or videos, then sometimes there are gaps in getUpdates. For example, after the album is published, there are post IDs [10,11,12,13,14,15], and when requesting getUpdates, I get the result in the format [update_id => post_id] - [10010 - 10, 10011 - 11, 10012 - 12, 10013 - 14, 10014 - 15 ].

Real channel id = -1001557067948
Real updates id => messages id in format:
[987842251 => 7000,
987842252 => 7001,
987842253 => 7002,
987842254 => 7003,
987842255 => 7004,
987842256 => 7005,
987842257 => 7006,
987842258 => 7007, (here missing 7008 id post)
987842259 => 7009, 
987842260 => 7010,
987842261 => 7011]

As I understand it, update_ids are generated entirely on the Telegram side and I have no influence on the generation of update_id?

This bug was noticed couple times, not once...

**Comment by testumadio** [comment]
<img width="647" alt="Снимок экрана 2023-08-23 в 21 59 31" src="https://github.com/tdlib/telegram-bot-api/assets/26800765/d2faf651-6ae3-4441-998f-74ffe6b26243">

**Comment by levlam** [comment]
It is `message_id`, not `update_id`. If there is no message, then the bot has no access to the message, or the message has already been deleted.

**Comment by testumadio** [comment]
The whole strangeness is that the message was just the same, we deleted it today (after 8-9 days). In the same way, it was displayed on the tgstat statistics website.

boot update_id went one after the other, but missing 7008 post id

**Comment by testumadio** [comment]
> It is `message_id`, not `update_id`. If there is no message, then the bot has no access to the message, or the message has already been deleted.

The whole strangeness is that the message was just the same, we deleted it today (after 8-9 days). In the same way, it was displayed on the tgstat statistics website.

boot update_id went one after the other, but missing 7008 post id

**Comment by testumadio** [comment]
> It is `message_id`, not `update_id`. If there is no message, then the bot has no access to the message, or the message has already been deleted.

The whole strangeness is that the message was just the same, we deleted it today (after 8-9 days). In the same way, it was displayed on the tgstat statistics website.

boot update_id went one after the other, but missing 7008 post id

ALL OF THOSE messages is ALBUM which was posted at the same time:
<img width="647" alt="Снимок экрана 2023-08-23 в 21 59 31" src="https://github.com/tdlib/telegram-bot-api/assets/26800765/59b15b68-ad64-491c-b3fb-e7b16d004fc8">

**Comment by testumadio** [comment]
> How is it possible that time_added is yesterday and "we deleted it today (after 8-9 days)"?
> 
> Do you have full raw JSON response of `getUpdates` and the date when it was received?

Yeah, youre right, so sorry for my mistake. This posts was posted yesterday at 10:55 Moscow time.

Have no JSON full now, sadly. But anyway can send all info (channel link / channel id / updates id)

**Comment by levlam** [comment]
The only way for the message to be missing is to be already deleted at the time the updates were created, so I would like to see full raw JSON response of getUpdates, the date when it was received and to be able to check that the message isn't deleted yet.
