### ISSUE TITLE
setMyCommands do not update menu button

### ISSUE THREAD

**Issue by Vladrog** [tdlib/telegram-bot-api#465]
When i do api command bot.setMyCommands, i need to reopen the chat to update the commands in menu button. If i dont reopen it, commands dont update

Steps to reproduce:
-  set default commands
-  do setMyCommands with scope on /start, for example
-  after typing /start bot changes his commands in this scope and getMyCommands returns updated list of commands. But on telegram client i see default commands in menu, if i reopen chat i see updated commands

**Comment by Sindraaj** [comment]
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes


async def hello(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(f'Hello {update.effective_user.first_name}')


app = ApplicationBuilder().token("YOUR TOKEN HERE").build()

app.add_handler(CommandHandler("hello", hello))

app.run_polling()

**Comment by levlam** [comment]
@Vladrog
All needed updates are sent immediately to the user if a bot changes commands in the private chat with the user. There are no server-side or Bot API issues with this, but you can create cards for specific affected apps at https://bugs.telegram.org/.
