### ISSUE TITLE
[Request] Add Feature setMyProfilePicture And getMyOwnerBot for Telegram Bot Api

### ISSUE THREAD

**Issue by azkadev** [tdlib/telegram-bot-api#466]
I am planning to create an ai project, it will need many bots and owner accounts,

Please add a method to change the photoprofile for the bot and getOwnerBot to get the owner of the bot itself

Sorry, my English is bad

**Comment by levlam** [comment]
The features aren't planned, because bot can have only one profile picture and it can be set once from any Telegram app, which provide a fully-featured GUI for this, and there is no way to find the bot's owner, even token of the bot is known.

**Comment by azkadev** [comment]
:(
