### ISSUE TITLE
send files by SendDocument

### ISSUE THREAD

**Issue by sepsoh** [tdlib/telegram-bot-api#467]
why this is doesn't work for sendDocument?

document : "file://etc/hosts"

output :

(object) array(
   'ok' => false,
   'error_code' => 400,
   'description' => 'Bad Request: wrong remote file identifier specified: Wrong character in the string',
)

**Comment by levlam** [comment]
"file" protocol is allowed only if the server is launched in a local mode using `--local` parameter.
