### ISSUE TITLE
Aspect Ratio Alteration in Uploaded Videos Using Telegram Local API Server

### ISSUE THREAD

**Issue by RayFang** [tdlib/telegram-bot-api#468]
I'm using the Telegram local API server and have encountered an issue with uploaded video files. I can assure that the original file's aspect ratio is correct. However, after uploading through the local API server, the aspect ratio seems altered, and the problem persists when viewing the file on different devices. Is there any parameter or setting within the local API server to prevent this alteration of the aspect ratio?

**Comment by levlam** [comment]
Video files are kept exactly the same as uploaded and are never altered by Telegram. Ensure that you specify correct video width and height in the `sendVideo` request.
