### ISSUE TITLE
sendMessage with allow_sending_without_reply=false replies to deleted message

### ISSUE THREAD

**Issue by p1v0zavr** [tdlib/telegram-bot-api#469]
The [documentation](https://core.telegram.org/bots/api#sendmessage) states that passing True with the `allow_sending_without_reply` parameter in the `sendMessage` API method will send the message even if the specified replied-to message is not found. Based on this, I assume that if I pass False as a parameter, the message should not be sent. However, there seems to be an issue or ambiguity in this behavior.

Steps to reproduce the issue:
1. I send the message to the Supergroup (let's say its ID is 1)
2. I delete this message by myself using the UI
3. I call `sendMessage` method with `allow_sending_without_reply=false` and `reply_to_message_id=1` (`https://api.telegram.org/bot{{token}}/sendMessage?chat_id={{chatId}}&reply_to_message_id=1&allow_sending_without_reply=false&text=replied`)

And the bot successfully replies to the message that is already deleted.

I highlighted that I deleted the message by myself because in all the other cases everything works as expected:
1. I delete the message posted by the user using `deleteMessage` method
2. I delete the message posted by the bot using `deleteMessage` method
3. I delete the message posted by the bot using UI

In all those cases `sendMessage` method with `allow_sending_without_reply=false` returns `Bad Request: replied message not found`.

This issue happens only at the first call, the second one already returns `Bad Request: replied message not found`.

The issue is also not the case in e.g. `forwardMessage` and `copyMessage` methods _(I haven't checked all the methods that work with existing messages)_, they can detect that the replied-to message doesn't exist anymore right away.

I'm wondering if there's some delay before the message is considered deleted? Cause in my application it's crucial to not send the message back if the user deleted his message within the first few seconds.

**Comment by levlam** [comment]
> Based on this, I assume that if I pass False as a parameter, the message should not be sent. 

No, it means exactly as stated, that message is sent even the replied message can't be found. There is always a delay between an action and it is observable consequences, so there is no way to guarantee, that the message will not be sent without reply. After all the message, which was replied, can be deleted right after the replied message is sent.

**Comment by p1v0zavr** [comment]
> No, it means exactly as stated, that message is sent even the replied message can't be found.

Yeah, but if `allow_sending_without_reply = True` means that the message is sent even if the replied message can't be found, then logically, setting it to `False` should imply the opposite behavior, shouldn't it? If no and in both cases we send the message even if the replied message can't be found, then I don't really understand the value of this parameter.

I'm not here to argue or blame someone. I'm simply curious and trying to understand this situation better, just in case.

> There is always a delay between an action and it is observable consequences, so there is no way to guarantee, that the message will not be sent without reply.

I've just got 4 minutes between deleting the message to reply and sending a new message via the bot with `allow_sending_without_reply = False`. I don't understand why `sendMessage` method cannot verify if the message to reply is still there if such mechanism seems to exist. When I call `forwardMessage` or `copyMessage` methods with `message_id = {{some deleted message}}` I get `Bad Request: replied message not found` right away, so they know somehow that the message is not there anymore, why `sendMessage` doesn't?

An interesting discovery indeed: even after calling the `forwardMessage` and `copyMessage` methods for a deleted message and receiving `Bad Request: replied message not found` twice, the `sendMessage` method, when invoked with `allow_sending_without_reply = False` and `reply_to_message_id = {{that deleted message}}`, still sends the message. So it doesn't know about the state of the message even though it's been processed by two other methods which were aware of the message's absence. 

I tried to figure this out myself, but I'm just not really into c++ and the code looks a bit too complicated for me 😥

**Comment by levlam** [comment]
> Yeah, but if allow_sending_without_reply = True means that the message is sent even if the replied message can't be found, then logically, setting it to False should imply the opposite behavior, shouldn't it?

No, If A implies B, it doesn't mean that not A implies not B. Logic doesn't work this way.

> An interesting discovery indeed: even after calling the forwardMessage and copyMessage methods for a deleted message and receiving Bad Request: replied message not found twice,

This is not possible. The methods can't return the error.

**Comment by p1v0zavr** [comment]
> No, If A implies B, it doesn't mean that not A implies not B. Logic doesn't work this way.

Okay, I got this, the flag is here and guarantees only the behavior that is described (True = message is sent even if the replied message can't be found). Thanks.

> This is not possible. The methods can't return the error.

But what do you mean by this? That those two methods can't return the errors in general or the specific ones that I described, cause yes, I made a mistake a put incorrect error text there.
- `forwardMessage` returns
![image](https://github.com/tdlib/telegram-bot-api/assets/139656146/19ddfa05-42b6-428c-b1da-e4ca50eeae5d)
- copyMessage returns
![image](https://github.com/tdlib/telegram-bot-api/assets/139656146/e0122945-4722-4f59-b3db-3bba1afbe89e)

**Comment by p1v0zavr** [comment]
A bit of context: my wrong flag's understanding comes from the need to ignore the messages from the users that were deleted before the bot reacts to them (it's hosted on the Azure Portal, so there's like about 10-15 seconds to get awake), and I thought that this flag works in the other way as well (False = doesn't allow to send the message if the message to reply is gone), apparently is doesn't.

So I tried to find another way to verify the message existence, and as there's no `getMessageById` method or something, I found those two methods `forwardMessage` and `copyMessage` which could easily detect is the message is deleted or not.

Thus, I thought that there might be a bug in the sendMessage method as the mechanism for detecting the message existence does exist, but is not used there when allow_sending_without_reply = False. As now I'm inventing the wheel by trying to copy the message (to check if it exist) and only then reply to it.

**Comment by levlam** [comment]
Bot may not know that a message is deleted and may allow to reply it even the message has already been deleted and `allow_sending_without_reply == false`. But message identifiers passed as `reply_to_message_id` are resolved by the same function as message identifiers for `forwardMessage` and `copyMessage`. There is no way that the methods will return "message to ... not found", but then a message is sent without reply despite `allow_sending_without_reply == false`.

**Comment by p1v0zavr** [comment]
> But message identifiers passed as `reply_to_message_id` are resolved by the same function as message identifiers for `forwardMessage` and `copyMessage`. There is no way that the methods will return "message to ... not found", but then a message is sent without reply despite `allow_sending_without_reply == false`.

I'm not a c++ dev, but I was digging a little in the source code with my limited knowledge, and I also remember that those methods call the same "verification" function for the message id. But the behavior still differs, there is the representation: https://youtu.be/Vh6Vcz5Fka4

**Comment by levlam** [comment]
The last two sentences were a reply to
> An interesting discovery indeed: even after calling the forwardMessage and copyMessage methods for a deleted message and receiving Bad Request: replied message not found twice, the sendMessage method, when invoked with allow_sending_without_reply = False and reply_to_message_id = {{that deleted message}}, still sends the message. So it doesn't know about the state of the message even though it's been processed by two other methods which were aware of the message's absence.

This isn't possible and the video contains no disproof.

**Comment by p1v0zavr** [comment]
> The last two sentences were a reply to
> 
> > An interesting discovery indeed: even after calling the forwardMessage and copyMessage methods for a deleted message and receiving Bad Request: replied message not found twice, the sendMessage method, when invoked with allow_sending_without_reply = False and reply_to_message_id = {{that deleted message}}, still sends the message. So it doesn't know about the state of the message even though it's been processed by two other methods which were aware of the message's absence.

I'm sorry, I didn't realize you were talking about these particular sentences. There I recreated the described steps from those sentences: https://youtu.be/POXKgDGcdW8

**Comment by levlam** [comment]
Yes, this can happen when `copyMessage`/`forwardMessage` return "MESSAGE_ID_INVALID", but not "message to copy not found"/"message to forward not found",

**Comment by p1v0zavr** [comment]
> Yes, this can happen when `copyMessage`/`forwardMessage` return "MESSAGE_ID_INVALID", but not "message to copy not found"/"message to forward not found",

I believe the error messages were different two months ago when I created this issue, but, unfortunately, there's no way to prove it now with video, I have only the screenshots left https://github.com/tdlib/telegram-bot-api/issues/469#issuecomment-1710811848.

But still, even if the error message is different, why `sendMessage` method doesn't return the same "MESSAGE_ID_INVALID" if those three methods use the same verification function? Or if the "MESSAGE_ID_INVALID" error message is returned by different function, some additional verification, also why isn't it used in `sendMessage` method?

**Comment by levlam** [comment]
"MESSAGE_ID_INVALID" is a server-side verification.
