### ISSUE TITLE
force_reply does not work in Topic aka Forum chats

### ISSUE THREAD

**Issue by vkz** [tdlib/telegram-bot-api#470]
Hi. This is easy to reproduce. Simply have your bot send a message with `reply_markup {force_reply true}` as per documentation, You'll find that a reply to message interface pops up as expected in (a) private chats, (b) group chats. But the moment you convert to Topics aka Forum, message will arrive but no force reply interface will show - chat will receive an ordinary message from your bot without forcing the user to reply. Playing with `selective` and replying to user directly or `@user` in text to ensure correct target is chosen makes no difference.

Kind of a big problem tbh. Thank you

Telegram  v 10.0.3.250866 installed from Apple AppStore

**Comment by levlam** [comment]
It is a bug of the app that you use. You can create an issue for the app at https://bugs.telegram.org, or upvote one if it has been created already.

**Comment by vkz** [comment]
my bad, moving there and closing
