### ISSUE TITLE
force_reply fails to clean up its input_field_placeholder after reply

### ISSUE THREAD

**Issue by vkz** [tdlib/telegram-bot-api#471]
Exactly as reported. After user replies to `force_reply` message `input_field_placeholder` persists for subsequent messages and you can only override it by another `force_reply` with a different placeholder

Telegram v 10.0.3.250866 installed from Apple AppStore

**Comment by levlam** [comment]
It is a bug of the app that you use. You can create an issue for the app at https://bugs.telegram.org, or upvote one if it has been created already.

**Comment by vkz** [comment]
my bad, moving there and closing
