### ISSUE TITLE
When I send messages on threads, return error

### ISSUE THREAD

**Issue by tumusx** [tdlib/telegram-bot-api#472]
When I send news messages on threads, API return this error: 
{
	"ok": false,
	"error_code": 400,
	"description": "Bad Request: message thread not found"
}

I dont know, but it happened after I created a new thread.

**Comment by levlam** [comment]
The error means that you specified a wrong message thread identifier. See https://github.com/tdlib/telegram-bot-api/issues/356#issuecomment-1405378400 for explanation on what are message threads and how to correctly use them.
