### ISSUE TITLE
access to local request fails using local telegram api. ask for help !!!!

### ISSUE THREAD

**Issue by Wenboli11** [tdlib/telegram-bot-api#473]
I have been trying to deploy the local telegram api. I logOut the bot from the official website. When I start the local api, my access to 127.0.0.1:10802/botToken/getMe keeps failing. 10802 is the port I set. how should i do? What could go wrong

**Comment by levlam** [comment]
The specified parameters are correct.

What exactly is "keeps failing"?
Also, you should be able to see in the "D:/TG/test.log" file, whether the request reached the server.
