### ISSUE TITLE
The telegram-bot-api keeps increasing its memory usage

### ISSUE THREAD

**Issue by BOBOWA01** [tdlib/telegram-bot-api#477]
The telegram-bot-api keeps increasing its memory usage, and it requires a restart every time to resolve it. Is there any other way to handle this?

**Comment by levlam** [comment]
If you have a high loaded bot you may need more memory. There is no way to avoid this without sacrificing app's performance. The amount of needed memory is almost constant for the given bot, so you can just double available memory to avoid non-update restarts completely.
