### ISSUE TITLE
After the installation is completed, there will be a prompt for SSL error 8081. Normally, messages cannot be pushed

### ISSUE THREAD

**Issue by liergouzi88** [tdlib/telegram-bot-api#478]
{"ok":true,"result":{"url":"xxxxxxx","has_custom_certificate":false,"pending_update_count":4,"last_error_date":1695467428,"last_error_message":"SSL error {error:140840FF:SSL routines:ssl3_connect:unknown state}","max_connections":40,"ip_address":"xxxxxxx"}}[root@iZj6cjcffozs3yw1zn3ou5Z ~]#
My cloud server is Centos 7.6 from Alibaba Cloud

**Comment by levlam** [comment]
Connection to the specified webhook address is not possible. Check that you have an HTTPS-server run on the specified address and port.
