### ISSUE TITLE
 /lib64/libm.so.6: version `GLIBC_2.29' n

### ISSUE THREAD

**Issue by TNT-ma** [tdlib/telegram-bot-api#480]
./plugin: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./plugin)
./plugin: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./plugin)
./plugin: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./plugin)
./plugin: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./plugin)
./plugin: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./plugin)
./plugin: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./plugin)

**Comment by levlam** [comment]
Likely, you built executable file on one server and tried to run it on another. Binaries aren't portable. Generally, you can move them only between identical operating systems.

**Comment by bodqhrohro** [comment]
> Generally, you can move them only between identical operating systems.

Can you suggest how to build it against an old libc?

**Comment by levlam** [comment]
The simplest way to build against an old glibc is to build on an old enough OS, but then you will be also required to link OpenSSL statically.

**Comment by bodqhrohro** [comment]
I know, but I'd prefer a way which involves old library builds in dedicated directories.

I'm already on the way of experimenting, but it's far from successfully compiling yet.
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_CXX_FLAGS="-fno-builtin -Wl,-rpath=/home/bodqhrohro/git/glibc/lib/x86_64-linux-gnu -static-libstdc++ -Wl,-rpath=/home/bodqhrohro/git/libstdc++/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28 -Wl,-rpath=/home/bodqhrohro/git/libgcc-s1/lib/x86_64-linux-gnu/libgcc_s.so.1 -Wl,--dynamic-linker=/home/bodqhrohro/git/glibc/lib64/ld-linux-x86-64.so.2" ..
```
But still have to come over `libgcc_s.so`, and did not even reach libssl/libcrypto yet. Can I suppress the default one at all, or I need old GCC?

**Comment by bodqhrohro** [comment]
`generate_mime_types_gperf` compiled successfully after adding `-static -Wl,-Bdynamic,-lgcc_s,-Bstatic`, waiting if the rest would compile well.

**Comment by levlam** [comment]
Compiler version doesn't matter.

**Comment by bodqhrohro** [comment]
Almost well, but I still cannot fight
```
/usr/bin/ld: attempted static link of dynamic object `/usr/lib/x86_64-linux-gnu/libcrypto.so'
collect2: error: ld returned 1 exit status
gmake[2]: *** [td/generate/CMakeFiles/generate_json.dir/build.make:117: td/generate/generate_json] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:955: td/generate/CMakeFiles/generate_json.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
despite specifying
```
-static -Wl,-Bdynamic,-lgcc_s,-lcrypto,-lssl,-Bstatic
```
If I replace it with `-static-libgcc`, I still end up with non-executable `generate_mime_types_gperf`. How do I overcome this, so OpenSSL is linked dynamically, but the rest after `-Bstatic` is linked statically? (I'm not actually sure what remains and intervenes there).

**Comment by levlam** [comment]
Did you built OpenSSL yourself? System-provided OpenSSL definitely depends on the system libc.

**Comment by bodqhrohro** [comment]
If it's linked dynamically, I expect it to link to the system-wide OpenSSL on the target machine, which is compatible with an older libc.
