### ISSUE TITLE
Freeing up space in the sqlite directory of accounts on telegram-bot server

### ISSUE THREAD

**Issue by mpak2** [tdlib/telegram-bot-api#481]
Tell me how you can free up space in the sqlite table used by telegram-bot server to store data. Directories are growing and already contain a lot of space. I would like to clean them without violating authorization.

**Comment by levlam** [comment]
Telegram Bot API server doesn't use SQLite.

**Comment by levlam** [comment]
There is nothing else to clean either. For example, downloaded files are automatically deleted within 24 hours.

**Comment by mpak2** [comment]
On my server, I started the telegram-bot-api process for the user account and the bot application creates a directory tdlib_\d{11} going into which I see db.sqlite files with a size of 4.5G, there is also a smaller size of 1.2G over time, the size of this file increases. Perhaps this creates tdlib, which at one time uses telegram-botapi, is it possible to clean these directories somehow?

**Comment by levlam** [comment]
Then you launched not the Bot API server from this repository.
