### ISSUE TITLE
How can I deduplicate sent messages?

### ISSUE THREAD

**Issue by dankondr** [tdlib/telegram-bot-api#482]
Used SendMessage and SendMedia dont have random_id argument. Why is it like this? What are the other ways I can deduplicate sent messages? And is it ok to use MTProto API as a bot for this functionality?

**Comment by levlam** [comment]
The `random_id` isn't exposed for bots, because It is highly unlikely that they will be able to use `random_id` correctly, which requires a thoughtful usage of a cryptographically secure pseudorandom number generator. You can control a bot through MTProto API, if you don't use the Bot API server and has logged out all other bot instances.

**Comment by dankondr** [comment]
You said about logging out all bot instances, does it mean I can't use 2 connections from different machines to the same bot?

**Comment by levlam** [comment]
No, a bot can be logged in only once to function correctly.

**Comment by levlam** [comment]
If other sessions are never used after some time, then they shouldn't harm, but it would be bad to constantly switch between different sessions. Hence, other sessions should be logged out.

**Comment by Mart-Bogdan** [comment]
I think it would be really useful if bot server support this. Many other APIs support this feature. Random ID can be either hash of message, or of incoming data. Or if our bot stores reply in DB before sending it to bot api, it can be stored in our db or be actual message id from our side. 

related to #126

**Comment by levlam** [comment]
> Would not it be possible to expose it as an optional parameter for people confident that they will be able to use it correctly?

No. But if you are sure that you can use it correctly, then you should be able to add a very small patch to TDLib and the Bot API server, allowing to receive `random_id` from the external request.

**Comment by faucct** [comment]
Thanks, will do!

**Comment by levlam** [comment]
@faucct
Just add `random_id` to `td_api::messageSendOptions` and process it in the same way as other options.
