### ISSUE TITLE
bug: error when change local server back to telegram cloud

### ISSUE THREAD

**Issue by gradus0** [tdlib/telegram-bot-api#484]
I use two bots, on the first one everything works fine. I transferred it to a local server and then called the logout method and then setWebhook, and the bot returned to the cloud telegram.
However, on the second bot where there are many users, the bot does not return and always shows the error message: {"ok":false,"error_code":400,"description":"Logged out"}.
I am doing the same thing on both bots, but it only works on one and not on the other. I have already called the logout method multiple times everywhere.
I have been waiting for over an hour and the error still persists.
Please help me, I have many users, but the bot is not working now. The support team has not responded to me yet.

**Comment by levlam** [comment]
Could you send the bot's username to https://t.me/tdlib_bot?

**Comment by gradus0** [comment]
Sent)
I had to forcefully and urgently deal with the local server, the test migration turned out to be final 🙂
I don't need help anymore, but I think the bug still needs to be fixed.

**Comment by ridhodo** [comment]
I faced this issue too. how about the solution ?

**Comment by levlam** [comment]
@ridhodo 
Could you send the bot's username to https://t.me/tdlib_bot?

**Comment by darkbyteCn** [comment]
I faced this issue too. how about the solution ?

**Comment by levlam** [comment]
@darkbyteCn How much time passed since the last `logOut` call at api.telegram.org?

**Comment by Follow19910325** [comment]
I faced this issue too. how about the solution ?

**Comment by levlam** [comment]
@Follow19910325 If you still receive the error, then you have called `logOut` again recently.
