### ISSUE TITLE
"Quote & Reply" messages are not received by bots in public chats

### ISSUE THREAD

**Issue by romanrm** [tdlib/telegram-bot-api#487]
A few days ago a new kind of replies was implemented, "Quote & Reply", allowing to quote a part of a message to reply to.

I'm seeing that such messages in public chats are not being received at all by participating bots. Could you please clarify if this is a bug or not implemented yet and planned (when)? Thanks

**Comment by levlam** [comment]
The messages are received by bots since Bot API 6.9.2.
