### ISSUE TITLE
Bots can't post to channels

### ISSUE THREAD

**Issue by WinoGarcia** [tdlib/telegram-bot-api#489]
New telegram update broke the bots in channels. They can't send messages though they should.

**Steps to reproduce**

- add bot to channel
- add full rights in the bot's settings and the channel settings
- check if it posts
- it doesnt

Other users have [the same error](https://bugs.telegram.org/c/33784)

**Comment by AYMENJD** [comment]
It will be fixed soon. Just be patient.

**Comment by mircoianese** [comment]
> It will be fixed soon. Just be patient.

5+ hours for this kind of bug seems a little bit too much honestly

**Comment by AYMENJD** [comment]
@mircoianese The fix is delayed due to it's bad timing.

**Comment by mahdi2000bm** [comment]
> @mircoianeseتعمیر به دلیل زمان بندی نامناسب آن به تعویق افتاده است.

Announce a schedule to fix this problem

**Comment by mahdi2000bm** [comment]
> @mircoianese The fix is delayed due to it's bad timing.

How long might it take? Announce a time

**Comment by AYMENJD** [comment]
This should be fixed now.

**Comment by mircoianese** [comment]
> This should be fixed now.

Confirm it's working again. Thank you for your feedback!

**Comment by Shamshod-Nematullayev** [comment]
I have this error too but it fixed. Now all of these OK 😉
