### ISSUE TITLE
Updating photo via multipart/form-data

### ISSUE THREAD

**Issue by hrkcz001** [tdlib/telegram-bot-api#491]
How to update sent photo using multipart/form-data?
editMessageMedia expects InputMedia as JSON-serialized object which should contain attached file as a part. Maybe I'm dumb but is it even possible? Description says it's possible somehow to update via multipart/form-data but how actually this request may look like?

https://core.telegram.org/bots/api#editmessagemedia

**Comment by levlam** [comment]
You can pass `“attach://<file_attach_name>”` in the "photo" field if the photo is uploaded using multipart/form-data under `<file_attach_name>` name
