### ISSUE TITLE
Web Speech API in Telegram bot Web app

### ISSUE THREAD

**Issue by morfeusys** [tdlib/telegram-bot-api#494]
Looks like web speech api _webkitSpeechRecognition_ is available but the window that requests user to allow microphone access doesn't appear once the user taps to the mic button in web UI.

Is it true that I cannot use _webkitSpeechRecognition_ in Telegram mini web apps?

**Comment by erfanmola** [comment]
This has nothing to do with the Telegram Bot API, you should ask for each Telegram Client dev to allow this. WebApps are just basically WebViews with injected data into an iframe that is all handled by Client side other than receiving the initData. Clients allow some methods and deny some, based on what they are ready to offer right now.

**Comment by levlam** [comment]
The response by @erfanmola is 100% correct. You can create feature requests for `webkitSpeechRecognition` support for macOS/iOS apps at https://suggestions.telegram.org/ if it doesn't work now.
