### ISSUE TITLE
How to set up dependencies to OpenSSL 3.0?

### ISSUE THREAD

**Issue by redstone1994** [tdlib/telegram-bot-api#495]
I'm trying to run it on debian12, which has OpenSSL version 3.0 by default.
thanks

**Comment by redstone1994** [comment]
When I run it I get the message 
`error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
#openssl version  
OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

**Comment by redstone1994** [comment]
Does this have anything to do with me moving the binaries to another server?

**Comment by redstone1994** [comment]
When I run it on the build servers it does work, they are all debian12, is there any way to get another server to go directly to the binary that relies on openssl3, the server I'm running it on is too low configured for builds!

**Comment by levlam** [comment]
> Does this have anything to do with me moving the binaries to another server?

Yes. Binaries aren't portable.

> When I run it on the build servers it does work, they are all debian12, is there any way to get another server to go directly to the binary that relies on openssl3, the server I'm running it on is too low configured for builds!

It is definitely possible to create a cross-compilation environment, but this could be too hard. The simplest way is to build executable file on the target server.

**Comment by redstone1994** [comment]
ok, thank you very much
