### ISSUE TITLE
CMAKE build stucks

### ISSUE THREAD

**Issue by rojserbest** [tdlib/telegram-bot-api#5]
When following the installing instructions generator for Linux, Ubuntu 20 at running the command "cmake --build . --target install", this displays:
Scanning dependencies of target tdsqlite
[  0%] Building C Object tg/sqlite/CMakeFiles/tdsqlite.dir/sqlite/sqlite3.c.o

And the program freezes

**Comment by levlam** [comment]
How lond did you wait?

**Comment by rojserbest** [comment]
> How lond did you wait?

30 mins+

**Comment by rojserbest** [comment]
I tried clang too, it's the same thing

**Comment by YehudaEi** [comment]
I have now tried and it works great for me!
Maybe you do not have enough memory?

**Comment by rojserbest** [comment]
Oh let me kill other processes then

**Comment by levlam** [comment]
@rojserbest Did it help? g++ needs at least 4GB of RAM. For clang 2GB should be enough.

**Comment by rojserbest** [comment]
@levlam thanks, I was able to deploy it on a DigitalOcean droplet with 2GB and clang. Sorry for the late response.
