### ISSUE TITLE
Asynchronies download file and return immediately?

### ISSUE THREAD

**Issue by jnxyatmjx** [tdlib/telegram-bot-api#503]
when i use bot server in local model, the getFile method only return when download successfully and it take a long time. is there any way to return immediately the result?

**Comment by jnxyatmjx** [comment]
if address this problem  need edit code, should you told me how?

**Comment by levlam** [comment]
No, it is not possible. `getFile` must download the file locally, otherwise, there would be no way to access it by the bot.

**Comment by jnxyatmjx** [comment]
> No, it is not possible. `getFile` must download the file locally, otherwise, there would be no way to access it by the bot.

Can getfile directly return the json result and the download operation continues to be executed in the background?

**Comment by levlam** [comment]
No. How would you know that you the file can be used?
