### ISSUE TITLE
Documentation: missing information about can_send_media_messages in new_chat_members

### ISSUE THREAD

**Issue by techiedesu** [tdlib/telegram-bot-api#504]
https://core.telegram.org/bots/api#user doesn't have information about `can_send_media_messages` field.

https://core.telegram.org/bots/api#message `new_chat_members`

https://github.com/Dolfik1/Funogram/issues/64

**Comment by RememberTheAir** [comment]
`Update.Message.new_chat_members` is an array of [`User`](https://core.telegram.org/bots/api#user), which is not supposed to have any attribute regarding an user's permission in a group. The type that contains this information is [`ChatMember`](https://core.telegram.org/bots/api#chatmember) (or one of its subclasses)

**Comment by levlam** [comment]
Objects can contain arbitrary fields besides those that are documented. Otherwise, there would be no way to add backward compatible changes to API. If a field isn't documented, then it must not be used by new bots.

**Comment by levlam** [comment]
Documentation describes fields provided by API and their types, other fields aren't part of the contract.
