### ISSUE TITLE
Can I rely on channel.Id uniqueness?

### ISSUE THREAD

**Issue by dankondr** [tdlib/telegram-bot-api#508]
In my bot I want to use channel.Id as a primary key for my entity. Does telegram guarantees that it is unique among all channels and wont be changed (taken by other channel) in the future? And if not, what should I use for this purpose?

**Comment by levlam** [comment]
Yes, `supergroup.id` is unique among all supergroups and channels.

**Comment by dankondr** [comment]
Thank you!
