### ISSUE TITLE
file is too big

### ISSUE THREAD

**Issue by alekssamos** [tdlib/telegram-bot-api#51]
I built the server, got the ID and hash, and started it. I still keep getting the error, when trying to download a file larger than twenty megabites.
http://127.0.0.1:8081/bot%token%/getFile?file_id=%fileid%
```{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: file is too big"
}```

**Comment by levlam** [comment]
You didn't specified `--local` option to the server.
