### ISSUE TITLE
Stop of the terminal when we want to set --api-id and --api-hash

### ISSUE THREAD

**Issue by mobagheri** [tdlib/telegram-bot-api#511]
Hi. I hope you are doing well. I want to set the telegram bot API on my Ubuntu Linux server, but I need help modifying the --api-id and --api-hash. When I tried to put these two codes, my terminal indicator stopped and did not move forward. Could you help me run the bot API service in this particular case?

<img width="472" alt="Screenshot 2023-12-17 200150" src="https://github.com/tdlib/telegram-bot-api/assets/89096340/7231aeb4-c935-4cc1-9078-e1494588d943">

**Comment by levlam** [comment]
It didn't stop. The server is launched now and you can send requests to it to the specified `http-port` (default is 8081).

**Comment by mobagheri** [comment]
Thanks, Sir, and I appreciate your great response. I have two complementary questions.
First, what can I do if I want to close the terminal and the server process does not stop?

**Comment by mobagheri** [comment]
> It didn't stop. The server is launched now, and you can send requests to the specified `http-port` (default is 8081).

Thanks, Sir, and I appreciate your great response. I have two complementary questions.
First, how can I close the terminal so the server process does not stop?
The second question is how can I test the server so the request can be processed without any problem.

Thanks for your time and consideration.

**Comment by levlam** [comment]
You can use `nohup` to run the process, and there are multiple better alternatives to it depending on your OS.

You need to send an HTTP request to your server to port 8081 and check response.

**Comment by mobagheri** [comment]
Honestly, I appreciate your help. 🙏🏻🙏🏻🙏🏻

**Comment by mobagheri** [comment]
> You can use `nohup` to run the process, and there are multiple better alternatives to it depending on your OS.
> 
> You need to send an HTTP request to your server to port 8081 and check response.

Honestly, I appreciate your help. 🙏🏻🙏🏻🙏🏻
