### ISSUE TITLE
Feature Request: Add "preview_above_text" option to sending message

### ISSUE THREAD

**Issue by wiz0u** [tdlib/telegram-bot-api#513]
In TDLib, linkPreviewOptions already supports "show_above_text" option

It shouldn't be too complex to support it in Bot API also, via a "preview_above_text" option, next to the existing "disable_web_page_preview" option

Currently, bot method `Client::get_input_message_text` always pass "false" for show_above_text

**Comment by harshil21** [comment]
Possible with `LinkPreviewOptions` in Bot API 7.0. Issue can be closed.
