### ISSUE TITLE
Memory is not deallocated after calling get_file()

### ISSUE THREAD

**Issue by awerks** [tdlib/telegram-bot-api#514]
After downloading large files and saving them to the disk, they still stay in memory forever. This leads to unnecessary high RAM usage. Here's a minimal working example (in python-telegram-bot):
https://pastebin.com/ZD0hvaiY
P.S this is not the problem of the python library, inspecting processes in the task manager shows it's telegram-bot-api using gigs of RAM.

I understand this may be a default behaviour to cache files, but is there a way to disable this for files completely? I'm running this server in a docker container, so keeping large files constantly in memory is expensive and I'm fed up with having to restart it everyday.

![image](https://github.com/tdlib/telegram-bot-api/assets/23458479/b9f21d5b-1847-463d-be5a-4ca982907c69)

**Comment by levlam** [comment]
Files aren't stored in the memory by the Bot API server at all. Small file chunks are stored on disk immediately after they are downloaded.

Instead, you are likely to have a high-loaded mode with big amount of users and updates from them. Such bots may require a lot of RAM to cache information about the users to work reliably.

**Comment by awerks** [comment]
@levlam okay, I tested this locally and you're right - neither python process nor telegram-bot-api consumes any RAM. The issue is that writing to the disk within the docker container leads to high RAM usage. I'm still trying to understand why
