### ISSUE TITLE
 Telegram Bot API rate limits

### ISSUE THREAD

**Issue by jjordan-quantum** [tdlib/telegram-bot-api#516]
Do the same Telegram Bot API rate limits apply if you are running your own API server for your bots?

**Comment by levlam** [comment]
Yes.

**Comment by jjordan-quantum** [comment]
My own deployment of the self-hosted bot server is still giving me status code 429s when I am strictly sending at most 1 message at a time on a 50ms loop -> IE max 20 msgs/sec. why do you figure this is happening?

**Comment by jjordan-quantum** [comment]
I am sending a maximum of 10 message requests per second to my self-hosted api server. Still getting code 429's. I wait 30 seconds before trying another request when i get one of these errors - but to no avail.

**Comment by levlam** [comment]
Likely, you are trying to send messages to the same chat at the speed noone can read.

**Comment by jjordan-quantum** [comment]
messages are only generated on a 12 sec interval. typically 0 - 10 messages per batch. not often more than 10 at a time. the generated messages are passed to a queue that sends them to the self-hosted server on an interval of no more than 1 message every 100ms.

would the outcome be different if i was sending 10 messages to 10 different users - 1 messages each?

i am just doing initial load testing and sending all the messages to myself.

**Comment by levlam** [comment]
Yes, it definitely would be different.

**Comment by Jacksonm93** [comment]
If the same rate limit applies, then what is the purpose of having this telegram API server?
