### ISSUE TITLE
transfer bot from local server to telegram server 

### ISSUE THREAD

**Issue by morteza102030** [tdlib/telegram-bot-api#518]
hi
i use polling method in local bot api server for 3 years 
now i want to move my bot from local server to telegram server 
i use logout in local server and i waited for 30 minutes 
but my bot can't receive any updates or can't send any method like getMe to api.telegram.org
i always get this error 
{'ok': False, 'error_code': 404, 'description': 'Not Found'}

I have tried many times to transfer my bot but always failed
can you check what is the problem and what should I do ?
![image](https://github.com/tdlib/telegram-bot-api/assets/32270152/8a084a9c-51ae-44b7-8731-b66e019af629)

**Comment by levlam** [comment]
Do you still have the issue now?

**Comment by morteza102030** [comment]
Hello
I have several other bots on that server and I plan to transfer them all
Now only one of those bots has its problem solved
If possible, apply the necessary settings to all the bots in my server

**Comment by levlam** [comment]
Do they also receive 404?

**Comment by morteza102030** [comment]
Now only one of those bots has its problem solved
Bot other my bots in that server still getting 404 error 
if you need can i send you my bot id and server ip
![image](https://github.com/tdlib/telegram-bot-api/assets/32270152/2fa87325-ee04-488b-b40a-f1249986d738)

**Comment by morteza102030** [comment]
> Do they receive 404 still?

There is no more error
everything ok
thank you
