### ISSUE TITLE
[Question] Can i move an active bot with many users to local?

### ISSUE THREAD

**Issue by smaznet** [tdlib/telegram-bot-api#52]
Hi
i have a bot with thousand users i want to move it from telegram api to local api

Can i do it without losing data?

In case of moving from one local to another local you said we should also move bot directory to newer server but how about telegram severs to local? is there is a way to download my bot data from telegram servers?

**Comment by levlam** [comment]
There is no way to do that. The full phrase from the documentation is
```
If you want to avoid losing updates between logging out on the old server and launching on the new server, you can ...
```
While moving to a local server nothing is lost except updates between logging out and launching on the new server.

**Comment by smaznet** [comment]
No my issue is about telegram data on telegram server
For example getChat will works after moving to local server?
or you handled this?🤔

**Comment by smaznet** [comment]
I know some things about mtproto and there is a access_hash it can only received from updates and when i move to local server where i can find old access_hashes?

**Comment by IRGC** [comment]
access_hash remain same across all session.

**Comment by levlam** [comment]
@smaznet While moving to a local server **nothing** is lost except updates between logging out and launching bot on the new server.

**Comment by smaznet** [comment]
Okay thank you for responding 🙂
