### ISSUE TITLE
Question on restrictions

### ISSUE THREAD

**Issue by SUNsung** [tdlib/telegram-bot-api#523]
It is planned to develop a highly loaded bot.
At the start, it is expected to 10K users.
This is a bot to an existing website.

The bot itself will have buttons, process commands and dialogue with the client.
The most important thing is the passive alerts.

The resource itself is distributed on multiple servers in different countries (failure-stability and laws of the country)

The idea was that to install on each server a local server telegram-api  and disassemble the asynchronously webhooks on each server independently.
Responses and alerts-messages occur locally on each server.

=======≈=========≈==========

**Question:**

1. Limits for 30 messages per second to send for each local server or globally, regardless of which server sent?
2. Webhooks will come to each local server or balancing will happen?
3. Is it possible to split webhook processing on multiple servers?

It is known that there are many highly loaded telegrams bots - it is possible.
We need to understand how to implement this with the preservation of the legality (GDPR)

**Comment by levlam** [comment]
10K users is a small amount for a bot, but "passive alerts" can exceed the limits much sooner. See https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once for message broadcasting limits.

> The resource itself is distributed on multiple servers in different countries (failure-stability and laws of the country)

Then, you definitely need a separate bot for each server to comply with laws of the countries.

**Answers**:

1. Local server has nothing to do with bot limits. Also, there is no such limit as "30 messages per second", only sending a lot of "passive alerts" is limited.
2. A bot can use only one server at a time, including local servers and the server at api.telegram.org.
3. After receiving updates from the server you are free to process them on as many servers as you want to.

**Comment by Etherdrake** [comment]
@levlam 

> Local server has nothing to do with bot limits. Also, there is no such limit as "30 messages per second", only sending a lot of "passive alerts" is limited.

Could you elaborate on this? I am reading some conflicting / confusing information about what exactly causes flood errors. If I have 20K users and 200 of them are clicking buttons on my bot, at a rate of 20 buttons presses per minute, and I am sending updates in their respective chat on every button press, what are the implications in terms of there being "no such limit as 30 messages per second".

Also, what is the advantage of using local servers versus the server at api.telegram.org in terms of bot limits. Are there none? 

Thank you!

**Comment by levlam** [comment]
> Could you elaborate on this?

I can't elaborate on specific conditions, but good bots are supposed to never run into any limits.

> Also, what is the advantage of using local servers versus the server at api.telegram.org in terms of bot limits. Are there none?

All differences are described in https://github.com/tdlib/telegram-bot-api?tab=readme-ov-file#usage.

**Comment by Jacksonm93** [comment]
I want to know if deploying my own Telegram Bot API server still limits me to 30 messages per second.

**Comment by levlam** [comment]
1. Local server has nothing to do with bot limits.
2. Yes, editing a message is no different from sending a new one.
