### ISSUE TITLE
When trying to download file, server always returns 404 when it's not in `local` mode

### ISSUE THREAD

**Issue by jimchen5209** [tdlib/telegram-bot-api#540]
I set up the Telegram Bot API server and launched it without `--local` option.

While I was trying to download file, for example user's profile photo:
1. First I used [getUserProfilePhotos](https://core.telegram.org/bots/api#getuserprofilephotos) to get a list of files.
2. Then I used [getFile](https://core.telegram.org/bots/api#getfile) to get the [File](https://core.telegram.org/bots/api#file) object of one of the file.
3. After that I followed the instruction to download file by visiting `http://localhost:8081/file/bot<token>/<file_path>`.

Then I got the following response:
```json
{
    "ok": false,
    "error_code": 404,
    "description": "Not Found"
}
```

While I followed the same step on `https://api.telegram.org` and downloaded the file successfully.

When using the Telegram Bot API server with `--local` option, I can access the file because the path returned is a local path.

**Comment by levlam** [comment]
See https://github.com/tdlib/telegram-bot-api/issues/26.

**Comment by jimchen5209** [comment]
So the API server doesn't serve these file even when running in non local mode?

**Comment by levlam** [comment]
Yes, the server only downloads the files, and they needs to be served by another web server.

**Comment by jimchen5209** [comment]
Got it! Thanks!
It would be nice if the server also serves these downloaded files just as `api.telegram.org` do when running in non-local mode.
Or at least mention this in the document.
