### ISSUE TITLE
Invalid JSON from API

### ISSUE THREAD

**Issue by dm-sizov** [tdlib/telegram-bot-api#542]
With local Bot Api Server I have this:
`FetchError invalid json response body at http://<SERVER>/bot<TOKEN>/sendVideo reason: Unexpected end of JSON input`
This happens when sending a video as buffer, the same requests to https://api.telegram.org work successfully.
How can I track possible problems between bot and API server?
API logs are currently empty.
<img width="253" alt="screen" src="https://github.com/tdlib/telegram-bot-api/assets/73843294/98a3bc11-7da3-4c9f-857b-40104fde4fe5">

**Comment by levlam** [comment]
Likely, you are trying to parse as JSON an HTTP response with an error HTTP code and an empty body.

You should be able to log raw response received by your HTTP client, or see it in the Bot API server log with log verbosity level set to 4 or bigger.

**Comment by dm-sizov** [comment]
> You should be able to log raw response received by your HTTP client, or see it in the Bot API server log with log verbosity level set to 4 or bigger.

I got the response body and it's really empty. Is there any way to fix this? What could be the problem with a request containing binary data?

**Comment by levlam** [comment]
You received an HTTP error code and error message, which describes the cause of the error, and why the request was incorrect.

**Comment by dm-sizov** [comment]
> You received an HTTP error code and error message, which describes the cause of the error, and why the request was incorrect.

No error message, only 400 Bad Request.

**Comment by levlam** [comment]
Then see server logs with big enough verbosity level.

**Comment by dm-sizov** [comment]
> Then see server logs with big enough verbosity level.

`[ 3][t 5][1709082263.241864442][HttpConnectionBase.cpp:134][!HttpInboundConnection] [Error : 400 : Bad Request: Invalid chunk size [size:29215172]]`

**Comment by levlam** [comment]
Currently, Bot API server doesn't support https://en.wikipedia.org/wiki/Chunked_transfer_encoding with chunks of length bigger than 15 MB.
You can change the constant in the file td/tdnet/td/net/HttpChunkedByteFlow.h at line 20 from 15 << 20, for example, to 256 << 20 and rebuild Bot API server after the change.

**Comment by dm-sizov** [comment]
> Currently, Bot API server doesn't support https://en.wikipedia.org/wiki/Chunked_transfer_encoding with chunks of length bigger than 15 MB. You can change the constant in the file td/tdnet/td/net/HttpChunkedByteFlow.h at line 20 from 15 << 20, for example, to 256 << 20 and rebuild Bot API server after the change.

Good, thank you. But why is the behavior of the local API differs from the global API? It successfully handles these requests

**Comment by levlam** [comment]
At api.telegram.org requests are handled by NGINX and are proxied to the server using Content-Length encoding.

**Comment by dm-sizov** [comment]
> At api.telegram.org requests are handled by NGINX and are proxied to the server using Content-Length encoding.

Is it possible to deploy NGINX so that there will be minimal differences from api.telegram.org?
Can you add a recommended config for such cases?

**Comment by levlam** [comment]
I can't help with NGINX deployment for your scenario, but it should be pretty easy.

**Comment by dm-sizov** [comment]
Fixed with NGINX. Thanks for your help!

> Maybe something like [this](https://github.com/aiogram/telegram-bot-api/blob/master/example/nginx/default.conf).

**Comment by dm-sizov** [comment]
Fixed with NGINX. Thanks for your help!

> Maybe something like [this](https://github.com/aiogram/telegram-bot-api/blob/master/example/nginx/default.conf).
