### ISSUE TITLE
How to connect webhook to telegram-bot-api on server ubuntu

### ISSUE THREAD

**Issue by khamid4575** [tdlib/telegram-bot-api#545]
I downloaded telegram-bot-api to the server. Got domain and SSL too. How do I get updates now? How to connect webhook?

https://api.telegram.org/bot{bottoken}/setWebhook?url=https://mydomain.com

or

https://mydomain/bot{bottoken}/setWebhook?url=https://mydomain.com

which one is correct and how do I get the update from the webhook.

**Comment by levlam** [comment]
You must either use the server at api.telegram.org, or the local Bot API server. You must call `logOut` once on the other server and must not call any other method on the other server after that, so all requests must be sent to the used server.
