### ISSUE TITLE
Low speeds on local server

### ISSUE THREAD

**Issue by kupeepla** [tdlib/telegram-bot-api#546]
Hello,

I having problem regarding the speed of responses to commands and other requests
earlier my bot was on api.telegram.org but later i planned to move bot to local server because sometimes i might need to send files over 50MB

but i noticed that even 5-10MB file takes 60-70 seconds sometimes 2-3 mins to deliver/uploaded and user gets it.

Before you guys ask for the log file please let me know where do i find the log file. 

Thank you

**Comment by levlam** [comment]
Do you have a high-speed internet connection on the server where the Bot API server is hosted?

You can enable logs by adding parameters -v4 -l log.txt to the Bot API server and send the file `log.txt` to https://t.me/tdlib_bot to know the exact reason.

**Comment by levlam** [comment]
Why do use domain at all and don't host the Bot API server on the same server as the bot?

**Comment by kupeepla** [comment]
Bot and BOT API both are hosted on same server, i think because i am using HTTP://ip:port  and not HTTPS my download/upload speed is capped to certain kbps maybe 

And i thought if i use HTTPS with domain name i will get good speeds

What to do ?

**Comment by levlam** [comment]
> Bot and BOT API both are hosted on same server, 

Then you should send request to http://127.0.0.1:<port>. You should also consider to send local files using file:// URI scheme as specified in https://github.com/tdlib/telegram-bot-api?tab=readme-ov-file#usage.

**Comment by kupeepla** [comment]
Files are not on the disk i am sending media link directly to user using replywithVideo / replywithphoto with url, 
My bot really works fast on api.telegram.org and i am using same sending methods and i do succeed its just that its super slow on BOT API 

These are my logs,
[botlogs.txt](https://github.com/tdlib/telegram-bot-api/files/14460185/botlogs.txt)

**Comment by kupeepla** [comment]
Files are not on the disk i am sending media link directly to user using replywithVideo / replywithphoto with url,
My bot really works fast on api.telegram.org and i am using same sending methods and i do succeed its just that its super slow on BOT API

[botlogs.txt](https://github.com/tdlib/telegram-bot-api/files/14460213/botlogs.txt)

These are my logs,

**Comment by levlam** [comment]
In the log upload speed is less than 1 megabit per second. The speed depends on your server and there is no way to upload files with a higher speed.

**Comment by kupeepla** [comment]
<img width="1263" alt="image" src="https://github.com/tdlib/telegram-bot-api/assets/161818109/d1242658-202b-4fce-9c54-0a046b129837">

This is my speed tests, also download and uploading speed on other apps are very impressive

**Comment by kupeepla** [comment]
thats the sample code 

const { Telegraf } = require('telegraf');

const bot = new Telegraf('<TOKEN>', {
  telegram: {
    apiRoot: 'http://IP:PORT'   },
});

bot.start((ctx) => ctx.reply('Welcome! Use /send to get a video.'));

bot.command('send', (ctx) => {
    const videoUrl = '<VIDEOURL>';
    ctx.replyWithVideo(videoUrl);
});

bot.launch();

**Comment by BigBroFinch** [comment]
I also have the **### same problem,** is there an answer now?

**Comment by BigBroFinch** [comment]
> thats the sample code
> 
> const { Telegraf } = require('telegraf');
> 
> const bot = new Telegraf('', { telegram: { apiRoot: 'http://IP:PORT' }, });
> 
> bot.start((ctx) => ctx.reply('Welcome! Use /send to get a video.'));
> 
> bot.command('send', (ctx) => { const videoUrl = ''; ctx.replyWithVideo(videoUrl); });
> 
> bot.launch();

I also have the ### same problem, is there an answer now?
