### ISSUE TITLE
Feature Request: Rename StickerSet

### ISSUE THREAD

**Issue by Defuera** [tdlib/telegram-bot-api#547]
Hi, I'm funning Telegram Sticker Maker app and one of the most popular requests by users is to be able to rename sticker pack. Since there're two fields, stickerset name and stickerset title. I believe it should be possible to implement it and expose an API method for it. 

Many people would be very grateful if it's implemented. Thank you.

**Comment by levlam** [comment]
Sticker set's name is used as its unique identifier which isn't supposed to be changed.

**Comment by Defuera** [comment]
@levlam then sticker set title can be changed, right?

**Comment by levlam** [comment]
Yes, Using https://core.telegram.org/bots/api#setstickersettitle.
