### ISSUE TITLE
sometimes slow response

### ISSUE THREAD

**Issue by downygg** [tdlib/telegram-bot-api#550]
hello, i got some issue after 2 - 3 weeks local server running. 
after i change working directory parameter, bot will fast to response.
why it happened?

fyi, i use supervisor as daemon for keep local server running.

thank you,

**Comment by levlam** [comment]
There should be no significant difference in speed depending on the working directory.

**Comment by downygg** [comment]
i think this issue from tqueue.binlog or cache fro working dir but i don't really so.

**Comment by levlam** [comment]
None of this can cause significant difference in speed.

**Comment by DoNotWannaTry** [comment]
I am experiencing the same issue, but switching the working directory hasn't made any difference. Specifically, both receiving requests and sending responses are extremely slow on the local server, and I'm unsure why this is happening.

**Comment by downygg** [comment]
> I am experiencing the same issue, but switching the working directory hasn't made any difference. Specifically, both receiving requests and sending responses are extremely slow on the local server, and I'm unsure why this is happening.

I think this issue from telegram datacenter's are slow or maybe on maintenance. But I'm not sure every week is slow at telegram datacenter's

**Comment by DoNotWannaTry** [comment]
![image](https://github.com/tdlib/telegram-bot-api/assets/5683892/6902801e-738d-45a9-85b8-a8849b88195a)
I've outputted some logs, and here is a screenshot of a part of them, where there are numerous instances of "timeout." I'm unsure if this is related to the issue.

**Comment by DoNotWannaTry** [comment]
@levlam

**Comment by DoNotWannaTry** [comment]
> > I am experiencing the same issue, but switching the working directory hasn't made any difference. Specifically, both receiving requests and sending responses are extremely slow on the local server, and I'm unsure why this is happening.
> 
> I think this issue from telegram datacenter's are slow or maybe on maintenance. But I'm not sure every week is slow at telegram datacenter's

After deploying a local server, I understand that requests are forwarded and responses are handled by a local server proxy. How does this process relate to Telegram's data centers?

**Comment by downygg** [comment]
> > > I am experiencing the same issue, but switching the working directory hasn't made any difference. Specifically, both receiving requests and sending responses are extremely slow on the local server, and I'm unsure why this is happening.
> > 
> > 
> > I think this issue from telegram datacenter's are slow or maybe on maintenance. But I'm not sure every week is slow at telegram datacenter's
> 
> After deploying a local server, I understand that requests are forwarded and responses are handled by a local server proxy. How does this process relate to Telegram's data centers?

you can check this diagram how to this lib work. Source :  https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-721873231

**Comment by levlam** [comment]
@DoNotWannaTry The logs on the screenshot shows that everything works as expected. The only suspicious line is getUpdates request with timeout 0 instead of some big value, but this is an issue in the bot's code.

**Comment by DoNotWannaTry** [comment]
> @DoNotWannaTry The logs on the screenshot shows that everything works as expected. The only suspicious line is getUpdates request with timeout 0 instead of some big value, but this is an issue in the bot's code.

I restarted the local server and re-registered the bots, and it seems to be normally now.
