### ISSUE TITLE
How to handle errors from API

### ISSUE THREAD

**Issue by thwerks** [tdlib/telegram-bot-api#554]
When i lose internet connection I receive errors to the console, such as:

`error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: getaddrinfo ENOTFOUND api.telegram.org"}`

`Unhandled rejection RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org                                                           
    at new RequestError (/apps/node_modules/request-promise-core/lib/errors.js:14:15) `

I want to direct these errors to somewhere else other than the console but i dont know how to catch the error:

normally it would look something like this:

```
 bot.on('error', (error) => {
      //do something with 'error'
 })
```
but when i try this, i still get "unhandled error". What is the correct way to catch "on error" events to avoid multi line logging to the console?

**Comment by levlam** [comment]
The errors are received from the library that is used to implement the bot. You need to ask the question in the library's repository or its discussion group.
