### ISSUE TITLE
Unable to Start Server with SSL Certificate

### ISSUE THREAD

**Issue by martindotts** [tdlib/telegram-bot-api#555]
Problem:
I am currently trying to start the Telegram Bot API server with an SSL certificate, but I haven't found documentation on how to do it in the provided guide. Although I have OpenSSL installed on my system, the server continues to run on HTTP instead of HTTPS.

Questions:

What is the correct way to start the Telegram Bot API server with an SSL certificate?
Where can I specify the location of my OpenSSL files (certificate and private key) for the server to use upon startup?
Additional Details:

Operating System: Windows 11
Telegram Bot API Server Version: Bot API 7.1
Actions Tried: I have attempted to start the server with the "--ssl-cert" and "--ssl-key" arguments, but the server still runs on HTTP.

**Comment by levlam** [comment]
The server doesn't support HTTPS connections. You need to use a TLS-terminating reverse proxy if you want to send requests from a remote server.

**Comment by martindotts** [comment]
Got it, thanks for the clarification
