### ISSUE TITLE
Make InlineQueryResultVideo title optional

### ISSUE THREAD

**Issue by Sarisan** [tdlib/telegram-bot-api#557]
Is there a real reason to keep it required? I have to use InlineQueryResultMpeg4Gif for videos to make it look standardized with titleless InlineQueryResultPhoto and InlineQueryResultGif.

**Comment by levlam** [comment]
Currently, videos are shown as articles, because they can be big and often can't be downloaded when used as a result in inline mode. Therefore, the title is required for them.
