### ISSUE TITLE
message expired less than 24 hour

### ISSUE THREAD

**Issue by RealYukiSan** [tdlib/telegram-bot-api#561]
telegram docs says:
> Incoming updates are stored on the server until the bot receives them either way, but they will not be kept longer than 24 hours.

but when I fetch the getUpdates endpoint, it's return empty, but my last message was today morning at 08:30
how to prevent it?

**Comment by levlam** [comment]
Either the bot has already received the update, or was logged in after the message was sent.

**Comment by RealYukiSan** [comment]
I believe this information may be included in the documentation, but I'm not sure. Could you please point me to the relevant section? I may have missed it

**Comment by RealYukiSan** [comment]
I see, thanks for the response >///<
