### ISSUE TITLE
How to set timeout getUpdates

### ISSUE THREAD

**Issue by RealYukiSan** [tdlib/telegram-bot-api#562]
the telegram bot docs says the time unit is in seconds, but when I try to set to 5 minutes (300 sec) it didn't work

```
time curl --keepalive-time 300 https://api.telegram.org/bot<token>/getUpdates?timeout=300&offset=<last update_id + 1>
real    0m50.585s
user    0m0.036s
sys     0m0.016s
```

**Comment by levlam** [comment]
There are no reasons to wait for 5 minutes before sending response. Such big timeouts can make bots too unreliable.

**Comment by RealYukiSan** [comment]
To optimize performance and minimize resource usage, I'd like to establish a persistent connection and wait indefinitely for a non-empty `result`. This approach eliminates the overhead of repeatedly opening and closing connections.

**Comment by levlam** [comment]
> and wait indefinitely for a non-empty result. This approach eliminates the overhead of repeatedly opening and closing connections.

This approach makes your connections unreliable. You may never know that TCP connection has failed and will never return you any data.

**Comment by RealYukiSan** [comment]
If the worst case happened, re-connecting would be the last option.
anyway I will close the issue, thanks for the response!
