### ISSUE TITLE
request Timeout

### ISSUE THREAD

**Issue by RealYukiSan** [tdlib/telegram-bot-api#563]
I've test my internet connectivity by running this command:
```shell
curl "https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
"https://api.telegram.org/bot<token>/getUpdates" \
```

and I not see timeout using curl, but when it uses fetch, sometimes timeout arises, how to fix the timeout problem in fetch nodejs?
I also tried fetch with keepAlive and timeout but not work:
```javascript
const param = `timeout=300&offset=${last_update}`;
const response = await fetch(`${process.env.BASE_URL}/getUpdates?${param}`, { keepalive: true, signal: AbortSignal.timeout(1000 * 300) }).then(res => res.json())
```

**Comment by levlam** [comment]
You must set request timeout bigger than `timeout` parameter of the request.

**Comment by levlam** [comment]
Check how much time has passed between request start and response. If it is 200+ seconds, then there were a network issue, which is normal.

**Comment by RealYukiSan** [comment]
thanks for the help!
