### ISSUE TITLE
{"ok":false,"error_code":400,"description":"Logged out"}   

### ISSUE THREAD

**Issue by ruthwern** [tdlib/telegram-bot-api#566]
when switching from local to main api server - i am getting error -{"ok":false,"error_code":400,"description":"Logged out"} - before switch, i loggout from local server.

**Comment by levlam** [comment]
The error means that you sent `logOut` request to the api.telegram.org server.

**Comment by lindionez** [comment]
And how do you get it to work again after sending this request? Even after restarting, it now no longer turns on, giving me this error, I wanted to restart the code to not kill it permanently

**Comment by levlam** [comment]
@lindionez 

> Even after restarting

What did you restart?

Do you receive the error from api.telegram.org?

**Comment by lindionez** [comment]
yes, even restarting the API it continued to return "{"ok":false,"error_code":400,"description":"Logged out"}"
I restarted it several times, adding and removing different functions from the client and it continued the same, until after an hour it started working again as if nothing had happened, I don't know what was my mistake for taking so long to return, I just know that I'll never get close again of the logOut function.
Sorry for the English, I used a translator for much of the text.

**Comment by levlam** [comment]
You didn't answer the questions.

**Comment by masok139188** [comment]
> Anda tidak menjawab pertanyaannya.
tolong dibantu permasalahan bot telegram saya 
{"ok":false,"error_code":400,"description":"Logged out"}
