### ISSUE TITLE
bot my_chat_member

### ISSUE THREAD

**Issue by alvvaysxxx** [tdlib/telegram-bot-api#567]
Are there any limits for my_chat_member in large groups (>1000 people)?

The problem I am experiencing is that my bot perfectly works in groups and supergroups, but when it comes to large groups, it does nothing.
I can't even track the problem because it doesn't show any bad logs and I can't test it without doing something with production build because I don't have any 1000+ members group so I can manually test it...

**Comment by levlam** [comment]
"my_chat_member" is a type of an update. What do you mean by "limits" for an update?
