### ISSUE TITLE
/answerInlineQuery weird issue

### ISSUE THREAD

**Issue by busslina** [tdlib/telegram-bot-api#568]
I use with success `/sendMessage`, `/deleteMessage`, `/setWebhook`, `/deleteWebhook`, `/getWebhookInfo`, ... but when calling `/answerInlineQuery` I'm receiving this:
```
{ok: false, error_code: 400, description: Bad Request: USER_BOT_INVALID}
```
It's weird because I'm using the same HTTP client configured with base url to `'$telegramApiBase/bot$token'`, ...

Any help?

Thanks

**Comment by levlam** [comment]
Check that inline mode is enabled for the bot and it has just received an inline query.

**Comment by busslina** [comment]
> Check that inline mode is enabled for the bot and it has just received an inline query.

Thank you, and I'm sorry because it was my error. I was supposed to use `answerCallbackQuery`.

Now works fine.

Anyway, can you suggest me a Forum to discuss Telegram (Api), like a Discord or something?

Thanks

**Comment by levlam** [comment]
You can ask questions at https://t.me/BotTalk.
