### ISSUE TITLE
Slow HTTP connection: migrate to 4

### ISSUE THREAD

**Issue by KartaviK** [tdlib/telegram-bot-api#57]
Why this message showing locally in telegram log?

**Comment by levlam** [comment]
This is a log message in INFO log, which just tells what is happening.

**Comment by levlam** [comment]
So, I would say, that the message is shown in the log, because you set log verbosity level at least to 3.

**Comment by KartaviK** [comment]
Yes, my question is next. When i try to send local file the success try 1 of 10, and in 9 failed tries i see that message

**Comment by levlam** [comment]
No, it is printed every time you try to upload a file.

**Comment by KartaviK** [comment]
So my problem in timeout for this upload process?

**Comment by levlam** [comment]
I don't know, where the problem, but it is definitely not there.

**Comment by KartaviK** [comment]
Ok, thanks for help)
