### ISSUE TITLE
Error while getting api_hash and api_id.

### ISSUE THREAD

**Issue by DrArsen** [tdlib/telegram-bot-api#573]
Hello dear support team,
Please suggest me solution for resolving an issue with Error.
I cannot get API_HASH and API_ID from my.telegram.org/apps.
When I try to create application so I can get hash and id, I get an error : https://imgur.com/NIN6dqV
Are there other ways to get API_HASH and API_ID? How I can overcome this issue?
Thank you in advance!
Best regards,
Arsenii

**Comment by levlam** [comment]
In most cases disabling of VPN helps to get API_HASH and API_ID.

**Comment by DrArsen** [comment]
Thank you for the reply!
I'm not using VPN or any similar technology.

**Comment by levlam** [comment]
Then you can only try with some other internet provider.

**Comment by Batyodie** [comment]
I have the same problem, I can't find a way to solve it.

**Comment by Batyodie** [comment]
My colleague was able to create an api thanks to a static api from his phone in the firefox browser. Maybe this will help someone.

VPN was not used.

**Comment by DrArsen** [comment]
> https://www.youtube.com/watch?v=V4lxe4ly5GY&t=377s, Here's the solution you need and that's how I tried and succeeded

Restricted link.
But thank you!

**Comment by DrArsen** [comment]
> > > https://www.youtube.com/watch?v=V4lxe4ly5GY&t=377s, Here's the solution you need and that's how I tried and succeeded
> > 
> > 
> > Restricted link. But thank you!
> 
> The content of the video is to repeat the application until it is successful when the error prompt appears. Although it sounds ridiculous, I successfully applied through this method.

Thank you for your advice! I will definitely try that!

**Comment by cnstephen** [comment]
Has expired,I clicked for several hours, and the Enter key and left mouse button almost stopped working.

**Comment by mrseawood** [comment]
try to use sell phone data, don't use wifi. That should be work.

**Comment by gandimhmed** [comment]
The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.

**Comment by RootedOne** [comment]
> Hello dear support team, Please suggest me solution for resolving an issue with Error. I cannot get API_HASH and API_ID from my.telegram.org/apps. When I try to create application so I can get hash and id, I get an error : https://imgur.com/NIN6dqV Are there other ways to get API_HASH and API_ID? How I can overcome this issue? Thank you in advance! Best regards, Arsenii

https://github.com/RootedOne/Telegram-Api-Error

**Comment by f4tih35** [comment]
> The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.

It worked, thanks.

**Comment by BobbyJoonz** [comment]
> > Hello dear support team, Please suggest me solution for resolving an issue with Error. I cannot get API_HASH and API_ID from my.telegram.org/apps. When I try to create application so I can get hash and id, I get an error : https://imgur.com/NIN6dqV Are there other ways to get API_HASH and API_ID? How I can overcome this issue? Thank you in advance! Best regards, Arsenii
> 
> https://github.com/RootedOne/Telegram-Api-Error

Thanks a lot man!

**Comment by WuXiaoShining** [comment]
> The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.

Thanks a lot. It turned out that the issue has less thing to do with using VPN. Your approach worked perfectly and solved my headache which bothered me for months.

**Comment by winposs** [comment]
> The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.

error - September 1, 2024

**Comment by winposs** [comment]
> > The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.
> 
> Thanks a lot. It turned out that the issue has little to do with using VPN (I used VPN). Your approach worked perfectly and solved my headache which bothered me for months.


App title and Short name, do you use 16 bits?

**Comment by teleblack** [comment]
The issue with the proxy — this video provides a free solution

https://yyoutube.com/watch?v=BV_UYI9G4hM

**Comment by winposs** [comment]
> The issue with the proxy — this video provides a free solution
> 
> https://yyoutube.com/watch?v=BV_UYI9G4hM

这个是不是盗号的？
Is this account stolen?

**Comment by teleblack** [comment]
> > The issue with the proxy — this video provides a free solution
> > https://yyoutube.com/watch?v=BV_UYI9G4hM
> 
> 这个方法有账号被盗的风险吗？ Is there any risk of account being stolen with this method?

你自己好好想想嘛，这怎么盗号？这个验证码只能用来获取API，又不能用来登录

**Comment by WuXiaoShining** [comment]
> > > The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.
> > 
> > 
> > Thanks a lot. It turned out that the issue has little to do with using VPN (I used VPN). Your approach worked perfectly and solved my headache which bothered me for months.
> 
> App title and Short name, do you use 16 characters?

Nope, both of mine are 15 characters.
没有，我的两个都是15字符长度

**Comment by nguyenanh29** [comment]
> https://www.youtube.com/watch?v=V4lxe4ly5GY&t=377s, Here's the solution you need and that's how I tried and succeeded

not available any more

**Comment by mxx910** [comment]
> The whole problem is related to App title and Short name. Go to the Avast Random Password Generator website https://www.avast.com/random-password-generator then copy and paste in App title and Short name.

This method may not be directly successful, but still need to keep clicking to try and apply. I successfully applied after clicking about 50 times in a row，anyway thanks lot

**Comment by guang12386** [comment]
Help apply for telegram application in seconds, no matter what account, solve telegram application error problem

请联系Telegram ： @guang8886667

**Comment by guang12386** [comment]
Help apply for telegram application in seconds, no matter what account, solve telegram application error problem

请联系Telegram ： @guang8886667

**Comment by RatrixVerus** [comment]
Hello everyone! I had the same error - it didn't work whether I used VPN or not. What helped was that I upgraded to a premium account and logged in without using VPN or WiFine (i.e., via mobile network) and in Chrome's incognito mode. I'm not sure which of these steps did the trick, but it worked out in the end.

**Comment by noxur05** [comment]
I also have same issue and i submitted form more than 300 times. Are there other solutions?
