### ISSUE TITLE
The terminal does not respond after the command is executed

### ISSUE THREAD

**Issue by ghost** [tdlib/telegram-bot-api#574]
I have installed the project and the required libraries correctly
When I entered the command Telegram-bot-api --api-id=myid --hash-id=myhash --local, the terminal did not respond. I kept waiting for a long time but still did not respond

The sensitive information in the command has been replaced by the parameter name

**Comment by levlam** [comment]
The server has been launch successfully and works now. You can send HTTP requests to the local port 8081.
