### ISSUE TITLE
Add support for `channels.toggleForum` (as per documentation)

### ISSUE THREAD

**Issue by kyrylo** [tdlib/telegram-bot-api#575]
The docs at https://core.telegram.org/method/channels.toggleForum mention that "Bots can use this method".

However, https://core.telegram.org/bots/api doesn't mention anything about "toggleForum".

Can we add support for this call if it's not supported?

**Comment by levlam** [comment]
Bots definitely can't use this method. If a bot needs a forum it should ask the user for it using [KeyboardButtonRequestChat](https://core.telegram.org/bots/api#keyboardbuttonrequestchat) with chat_is_forum == true.

**Comment by kyrylo** [comment]
Thank you! That is better than nothing.

Please consider improving the documentation.

**Comment by kyrylo** [comment]
I think I misunderstood the original comment. I thought that a bot could ask the user to convert a channel to a forum explicitly, but that's not the case.

My desired use case:

1. Create a new group manually
2. Invite my bot to it
3. The bot converts this group to a forum and starts managing topics automatically

Why I think it would be nice is because it's not easy to find the "Topics" toggle. I have to ask the users of my bot to go to the group settings and flip the switch manually. If a bot could do this for me, then my onboarding process would've been very smooth.

**Comment by kyrylo** [comment]
I see. What I realized is that Telegram Desktop (10.10.2.261795 Stable) doesn't offer the "Create Group" option:

Mobile | Desktop
-- | --
![Screenshot 2024-04-22 at 18 32 02](https://github.com/tdlib/telegram-bot-api/assets/1079123/353ecc8a-1f57-4e41-b1f5-a25d59bccb92) | <img width="366" alt="Telegram 2024-04-22 18-31-52" src="https://github.com/tdlib/telegram-bot-api/assets/1079123/1f6456e2-14bf-4814-8947-106e5221fe24">

**Comment by levlam** [comment]
You can report this as a bug at https://bugs.telegram.org.

**Comment by kyrylo** [comment]
Thank you: https://bugs.telegram.org/c/39325
