### ISSUE TITLE
send a pdf document with sendMessage

### ISSUE THREAD

**Issue by salicius** [tdlib/telegram-bot-api#577]
Hi, how can i attach a document with the sendMessage method ?

**Comment by levlam** [comment]
To send a document you need to pass `inputMessageDocument` as `input_message_content` to `sendMessage`.

**Comment by levlam** [comment]
In Bot API you can use https://core.telegram.org/bots/api#senddocument.

**Comment by levlam** [comment]
> sendMessage
Use this method to send text messages. 

> sendDocument
Use this method to send general files.

**Comment by levlam** [comment]
See `link_preview_options` parameter.

**Comment by fiorins** [comment]
> See `link_preview_options` parameter. If the document is small enough it can be seen in link preview.

I can't use `link_preview_options` in sendDocument

**Comment by levlam** [comment]
Currently, caption is always shown below the corresponding document.
