### ISSUE TITLE
How legal is using getChannelDifference for public channels

### ISSUE THREAD

**Issue by dankondr** [tdlib/telegram-bot-api#581]
Using telegram api as a bot, I can send getChannelDifference for any channel my bot isn't participant of and get messages from it.
Is it normal behavior I can use?

**Comment by levlam** [comment]
TDLib doesn't have such method, because it doesn't need to be used by real apps directly.

**Comment by dankondr** [comment]
Is there any other way to get messages from public channel I'm not a participant of?

**Comment by levlam** [comment]
In TDLib you need to use `openChat`, `getChatHistory` and handle updates.

**Comment by dankondr** [comment]
Can I do the same using HTTP api?

**Comment by levlam** [comment]
All available to bots methods are described at https://core.telegram.org/bots/api.
