### ISSUE TITLE
Does telegram-bot-api still not support uploading files up to 4G?

### ISSUE THREAD

**Issue by nbtu** [tdlib/telegram-bot-api#583]
I am already a premium member of telegram. I tried to use telegram-bot-api to upload files, but it does not seem to support files larger than 2G.

```
curl -F video=@20240503.mp4 -X POST "http://localhost:8081/bot${TOKEN}/sendVideo?chat_id=${chat_id}&supports_streaming=true"|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3495M    0    77  100 3495M      0  8050k  0:07:24  0:07:24 --:--:-- 4071k
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: FILE_PARTS_INVALID"
}
```

**Comment by levlam** [comment]
Bot API server supports uploading of files of any size allowed by Telegram, but the user must be a Premium user to be able to upload files bigger than 2000 MB. Bots can't be Premium users, therefore they aren't allowed to upload files bigger than 2000 MB.

**Comment by nbtu** [comment]
> Bot API server supports uploading of files of any size allowed by Telegram, but the user must be a Premium user to be able to upload files bigger than 2000 MB. Bots can't be Premium users, therefore they aren't allowed to upload files bigger than 2000 MB.

Thanks for your reply.

**Comment by mostafa-norouzi** [comment]
Recently I faced with a bot that can upload files to telegram up to 4gig! So how can it possible?

**Comment by nbtu** [comment]
> Recently I faced with a bot that can upload files to telegram up to 4gig! So how can it possible?

a bot≠ bot api
Are you sure it is using bot api to upload files to Telegram?
The bot's backend can also use Telegram API

**Comment by mostafa-norouzi** [comment]
Telegram API isn't limited to 50MB ? So how a bot can use it and send 4gig!?

**Comment by Sarisan** [comment]
> Telegram API isn't limited to 50MB ? So how a bot can use it and send 4gig!?

I presume it doesn't upload any files, instead it passes the file_id of already uploaded document by premium user.

**Comment by mostafa-norouzi** [comment]
The bot receive URL and give the file, So it can't do such a thing, but with your hint , maybe bot split file with zip based on limit (2gigs). I don't already have membership and it's just a guess!

**Comment by mostafa-norouzi** [comment]
Finally I did it, As Zip can not split result by size natively, I switched to .rar format and compressed target file with parts less than 2gig. So now I can send more than 2gig.

**Comment by kalmatiii** [comment]
Use Telegram's CDN link to fetch files directly
When a user sends a file, grab the file_id from the update and call getFile to get file_path.
Then build a direct link: https://api.telegram.org/file/bot<TOKEN>/<file_path>.
Use curl, wget, or fopen on your server to download files up to 2GB.
This bypasses the 20MB Bot API limit.
Once the file is stored on your server, you're done.

**Comment by nbtu** [comment]
> > Use Telegram's CDN link to fetch files directly When a user sends a file, grab the file_id from the update and call getFile to get file_path. Then build a direct link: [api.telegram.org/file/bot](https://api.telegram.org/file/bot)/<file_path>. Use curl, wget, or fopen on your server to download files up to 2GB. This bypasses the 20MB Bot API limit. Once the file is stored on your server, you're done.
> 
> Should it be : https://api.telegram.org/file/bot<bot_token>/<file_path> ???
> 
> I tried to do the same but get error :
> 
> ```
> A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: file is too big
> ```
> 
> I am trying to get url of 300MB file forwarded by user.

If you want ti only use telegram-bot-api,you need run a local telegram-bot-api (I recommend use telegram user api,such telethon/Pyrogram ..)

`
./telegram-bot-api --api-id=$API_ID --api-hash=$API_HASH --local -v 2
`

and then forward file to your bot，getUpdates get info

```
root@localhost:~# curl "http://127.0.0.1:8081/bot7698720134:AAFI7pQFK_-y5PE1zBJ2NDQYcBpz95n9-4E/getUpdates"|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1352  100  1352    0     0   874k      0 --:--:-- --:--:-- --:--:-- 1320k
{
  "ok": true,
  "result": [
   xxxxxx
...
        "video": {
          "duration": 1804,
          "width": 1920,
          "height": 1080,
          "file_name": "xxxxx.mp4",
          "mime_type": "video/mp4",
          "thumbnail": {
.....
          },
          "thumb": {
......
          },
          "file_id": "BAACAgQAAx0CfVovtgABDp36aQsmvIfgIuk_DlRm3cpfuXujH2gAAoQoAALDgFhQkWVNn7UNm9Y2BA",
          "file_unique_id": "AgADhCgAAsOAWFA",
          "file_size": 1382075422
        },

xxxxx
}
```
getFile to download

```
root@localhost:~# curl "http://127.0.0.1:8081/bot${TOKEN}/getFile?file_id=BAACAgQAAx0CfVovtgABDp36aQsmvIfgIuk_DlRm3cpfuXujH2gAAoQoAALDgFhQkWVNn7UNm9Y2BA"|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   252  100   252    0     0      2      0  0:02:06  0:01:29  0:00:37    58
{
  "ok": true,
  "result": {
    "file_id": "BAACAgQAAx0CfVovtgABDp36aQsmvIfgIuk_DlRm3cpfuXujH2gAAoQoAALDgFhQkWVNn7UNm9Y2BA",
    "file_unique_id": "AgADhCgAAsOAWFA",
    "file_size": 1382075422,
    "file_path": "/root/xxxxx/videos/file_4"
  }
}
root@localhost:~# ls /root/xxxxxx/videos/ -lh
total 1.3G
-rw-r----- 1 root root 1.3G Nov  6 02:47 file_4
```
