### ISSUE TITLE
How to create a service on Ubuntu

### ISSUE THREAD

**Issue by MoYuYuDe** [tdlib/telegram-bot-api#584]
I'm trying to run the telegram-bot-api as a service on the Ubuntu server, but it didn't work .The error message is this
![image](https://github.com/tdlib/telegram-bot-api/assets/107624890/ea105c5b-f554-44ec-8251-77dc85e0c95e)
and this is my config 
![image](https://github.com/tdlib/telegram-bot-api/assets/107624890/4e8b32f0-45b7-47ad-acc2-301bc2aa1af5)

**Comment by levlam** [comment]
This error is from `systemd` and is unrelated to Telegram Bot API.
