### ISSUE TITLE
Cannot download file

### ISSUE THREAD

**Issue by zickkeen** [tdlib/telegram-bot-api#59]
Where are the files located?
I'm using a generic url:
`https://hostlocal.api/file/bot<token>/path/file_id.ext`
and
`https://hostlocal.api/file/bot<token>/<file_path>?file_id=<file_id>`
But the return always:
```json
{
"ok": false,
"error_code": 404,
"description": "Not Found"
}
````

**Comment by levlam** [comment]
The files are downloaded to bot's folder inside server's working directory. You need to set up your HTTPS server serve static files from subfolders of these folders. "/file/bot&lt;token>/path/file_id.ext" should be translated to a path "&lt;server's working directory>/&lt;token>/path/file_id.ext".

**Comment by zickkeen** [comment]
That means we have to set up an http/https server to serve these folders/files?

**Comment by levlam** [comment]
Yes. You already have a HTTPS server to serve https://hostlocal.api. You need to set up it to serve files also.

**Comment by zickkeen** [comment]
can we run telegram-bot-api in https mode?

**Comment by levlam** [comment]
No. You must have an SSL-terminating web server,

**Comment by noplanman** [comment]
I'm busy implementing this functionality to the @php-telegram-bot

@levlam So basically `tdlib` does not offer any way to access the files via its internal HTTP server?
i.e. We need to set up a separate webserver that proxies the files?

**Comment by levlam** [comment]
@noplanman Yes. Bot API server downloads files and saves them locally. In `--local` mode it returns full path to the file, otherwise it returns a relative path to the file, which can be then served using any HTTPS server.

**Comment by noplanman** [comment]
@levlam Ok, thanks for the confirmation 👌

**Comment by kiran-venugopal** [comment]
How we can set it up to serve static files? I am using docker in heroku. 

`FROM alpine

RUN export BUILD_ONLY_PKGS="alpine-sdk cmake git gperf linux-headers openssl-dev zlib-dev" \
	&& apk add --no-cache $BUILD_ONLY_PKGS \
	&& git clone --recursive https://github.com/tdlib/telegram-bot-api.git /tmp/telegram-bot-api \
	&& mkdir /tmp/telegram-bot-api/build \
	&& cd /tmp/telegram-bot-api/build \
	&& cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local .. \
	&& cmake --build . --target install \
	&& rm -rf /tmp/* \
	&& apk del $BUILD_ONLY_PKGS

RUN apk add --no-cache libstdc++ openssl zlib

CMD telegram-bot-api --local -p $PORT`

**Comment by marcoslp010** [comment]
**If you, like me, are not willing to create a server just to serve files, you can change the url to the default Telegram url (api.telegram.org), here it worked perfectly**

**Comment by levlam** [comment]
@marcoslp010 You must not use api.telegram.org and a local server at the same time.

**Comment by marcoslp010** [comment]
> @marcoslp010 You must not use api.telegram.org and a local server at the same time.

use and only for downloading attachments

**Comment by AYMENJD** [comment]
@marcoslp010 You must never use them both for any purpose. Even for downloading. Otherwise you will ran into too many issue with your bot.
