### ISSUE TITLE
How can I be sure that Telegram BOT API local server is running properly?

### ISSUE THREAD

**Issue by mostafa-norouzi** [tdlib/telegram-bot-api#591]
Hi

I installed API on my centos 7.x and then below command :

**bin/telegram-bot-api --api-id $TELEGRAM_API_ID --api-hash $TELEGRAM_API_HASH --local &**

So in task manager I can see it, also at first in trace process there are a lot of 

```
clock_gettime(CLOCK_MONOTONIC, {tv_sec=6937094, tv_nsec=628648907}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=6937094, tv_nsec=628717456}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=6937094, tv_nsec=628755808}) = 0
```

And after a few minutes, a lot of  :

```
clock_gettime(CLOCK_MONOTONIC, 0x7fffc67fb2d0) = -1 ENOSYS (Function not implemented)
clock_gettime(CLOCK_MONOTONIC, 0x7fffc67fb2c0) = -1 ENOSYS (Function not implemented)
clock_gettime(CLOCK_MONOTONIC, 0x7fffc67fb470) = -1 ENOSYS (Function not implemented)
clock_gettime(CLOCK_MONOTONIC, 0x7fffc67fb4f0) = -1 ENOSYS (Function not implemented)
```

So that means local server is not working?

**Comment by levlam** [comment]
If you send requests and receive responses, then server works.
If it is running, then it should work.

**Comment by levlam** [comment]
You must connect to 8081 unless you specified a different port.

**Comment by mostafa-norouzi** [comment]
Yes I changed port number to 9090. I Switched https to http and problem fixed! Just to answer my question to be sure service is working properly, need to check below URL  in browser:

`http://xxxx:[port]/
`
and result is something like below in json format same as Telegram server:

`{"ok":false,"error_code":404,"description":"Not Found"}`
