### ISSUE TITLE
get 404 error on download file!

### ISSUE THREAD

**Issue by mostafa-norouzi** [tdlib/telegram-bot-api#594]
Hi

I send a request for [file_path] based on file id and result is something like this :
/root/telegram-bot-api/[token]/documents/file_1.exe

But when send the second request to fetch it: 
http://x.x.x.x:8081/file/bot[token]/root/telegram-bot-api/[token]/documents/file_1.exe

404 error returns :
{"ok":false,"error_code":404,"description":"Not Found"}

The strange thing is the file exists in /root/telegram-bot-api/[token]/documents/file_1.exe on my server! So what is the reason? Can be a permission issue or some extra setting needed for local server? (The server is up with --local switch )

**Comment by mostafa-norouzi** [comment]
The requests are sending from bot server to api server! They are on two different server. So I'm a little confused, if API server can not send files , why it store them?

**Comment by levlam** [comment]
> The requests are sending from bot server to api server! 

Do you send HTTP requests between different servers? This is already a very bad idea. You need an HTTPS-reverse proxy on the server with Bot API and then the reverse proxy can serve the files from disk.

> Even if they were in same server, the bot surely can not access to the root to get files.

It is also a very bad idea to allow the Bot API server to access /root, given it can work from a regular user.

The common setup is to run Bot API server and HTTPS proxy server under different non-root users from the same group, so the HTTPS server can access files created by the Bot API server.

**Comment by mostafa-norouzi** [comment]
Ok, I did setup reverse proxy and now request are sending through SSL protocol, also API is running on a non-root. So new pattern should be like : 

https://sample.com/file/bot[token]/home/[user]/telegram-bot-api/[token]/documents/file_1.exe

But still 404 error returns! **Is it normal?**

I also Thought about getting file through https request (like direct access to the file) but because of reverse proxy, my requests will be redirected to the telegram API and not the default http web server :|

**Comment by levlam** [comment]
Yes, it can work like this, but you need to set up the reverse proxy to serve paths starting with "/file" from local disk by taking the path to the file from the rest of the URL.

The HTTPS server shouldn't affect upload/download speed significantly. The situation described isn't normal.

**Comment by mostafa-norouzi** [comment]
I changed the reverse proxy rules and now the URL of files are valid. The amazing point is API writes the files in this folder with permission **0640** (not public) and the link is not accessible from public (and the bot server) !!! I also checked the API switches and there is no config to change it. Now I don't know what was the benefits of all this path ...

**Comment by levlam** [comment]
The HTTPS server has to be run under user from the same group as the user that is used for the Bot API server to allow the HTTPS server read access to files created by the Bot API server.

**Comment by mostafa-norouzi** [comment]
Yes, currently I started the API server with the non-root user and this user has full access to the folder and files. The problem is the [remote server] that host the bot, needs to access the files through direct link and obviously it should be public! How two different servers can be in same group!?

Just as the same as Telegram bot server! if you open the URL [api.telegram.org/file/...] in browser, download would be start. So this prove files has permission 644 or higher whereas my local server set files permission as 640. Anyway As I said before I bypass this issue with a script and there is no problem anymore. 

Did I missed something ?

**Comment by levlam** [comment]
The link should contain the bot's token (or other secret), so noone except the bot knows the URL to access the files.

At api.telegram.org exactly the same Bot API server is used, and all files have 0640 permissions. The files are served by an HTTPS server from the same group, which can read them. But your approach with a script also should be fine.

**Comment by levlam** [comment]
@AH-dark No, it is not possible to change this.
