### ISSUE TITLE
Bot latency

### ISSUE THREAD

**Issue by si2w** [tdlib/telegram-bot-api#595]
Since few weeks, my bot haves a latency between 5 and 12 seconds or do not receive some messages.

I tried : 
- tested the network [OK] : datacenter hosted in Paris, 10ms ping to api.telegram.org, no packets lost
- tested with another bot [OK] : the same code on the same host works perfectly for months with high latency
- tested on other machines [DOESN'T CHANGE ANYTHING] : Debian 12, Docker 26.0.0 and MacOs Sonoma
- tested on other networks [DOESN'T CHANGE ANYTHING]
- deleted the bot and recreated it [OK for some hours then NOK : high latency is back] : At for the first hours, the bot was super fast with a latency below 1 second. Now, the problem came back again.

The code is running python-telegram-bot==20.8.

How can I solve this issue ?

**Comment by levlam** [comment]
You need to find the cause of the issue. For example, check the way you get updates.

**Comment by si2w** [comment]
If I changed the bot token an got a working software. The issue shouldn't be on my side, right ? If I need to check something else, explain me what. I tested already some much things. Thanks for your help.

**Comment by levlam** [comment]
> If I changed the bot token an got a working software. The issue shouldn't be on my side, right ? 

No, this implies nothing.

Do you use api.telegram.org?

**Comment by si2w** [comment]
I don't define any host so defaults are used. 

According to the documentation, https://api.telegram.org/bot is used.
`class telegram.Bot(token, base_url='https://api.telegram.org/bot', base_file_url='https://api.telegram.org/file/bot', request=None, get_updates_request=None, private_key=None, private_key_password=None, local_mode=False)`

I check also dns resolution : 
`total_time=0; for i in {1..10}; do sleep 30;query_time=$(dig +noall +stats api.telegram.org | awk '/Query time:/ {print $4}'); echo "$query_time";total_time=$((total_time + query_time)); done; mean_query_time=$(echo "scale=2; $total_time / 10" | bc); echo "Mean Query Time: $mean_query_time ms"`
The result is Mean Query Time: .80 ms Max 4ms

**Comment by levlam** [comment]
Could you write details to https://t.me/tdlib_bot?

**Comment by si2w** [comment]
The problem disappeared without changing anything on my side (no reboot, restart, ...).

In the meantime, I did pcap when everything works well, take logs of typical timings. If the issue come back, I will do a more detailed report on https://t.me/tdlib_bot. Thanks
