### ISSUE TITLE
Failed to forward message: 'Bad Request: message thread not found'

### ISSUE THREAD

**Issue by dxyspx** [tdlib/telegram-bot-api#596]
**Description:**

I am encountering an issue with the `forwardMessage` API. Previously, I was able to successfully forward messages to `message_thread_id`. However, in the past few days, I have been receiving an increasing number of errors:

```
Failed to forward message: {'ok': False, 'error_code': 400, 'description': 'Bad Request: message thread not found'}.
```

Almost all topics are no longer receiving forwarded messages. This issue has become widespread and is impacting functionality significantly.

Please advise on how to resolve this issue.

Thank you.

**Comment by levlam** [comment]
Do you have more than a million messages in the target forum?

**Comment by dxyspx** [comment]
> Do you have more than a million messages in the target forum?

Yes. Is this related to the number of messages?

**Comment by levlam** [comment]
Yes, this happens when the total number of messages in the forum exceeds one million, the oldest forum messages are archived and become inaccessible.

**Comment by dxyspx** [comment]
Thank you. So, is the best solution to delete some of the forwarded messages to allow subsequent forwarding to continue working?

**Comment by levlam** [comment]
No, it will not help. You can only create new forum topics and stop using the old ones. Messages from the old topics will become inaccessible anyway after the new topics will have more than a million messages.

**Comment by dxyspx** [comment]
> No, it will not help. You can only create new forum topics and stop using the old ones. Messages from the old topics will become inaccessible anyway after the new topics will have more than a million messages.

Thank you for helping me resolve the issue. After creating new topics, I am now able to receive forwarded messages. However, do I need to repeat this process every time the message count exceeds one million?

**Comment by levlam** [comment]
Yes.

**Comment by FattyWeasel** [comment]
> No, it will not help. You can only create new forum topics and stop using the old ones. Messages from the old topics will become inaccessible anyway after the new topics will have more than a million messages.

I don't think these are accurate and correct conclusions.

I have several bots working in my supergroup, and they all work via forwarding, but some bots can send messages, and some can't! And at the same time, sending messages via Pyrogram simply using not message_thread_id, but reply_to_message_id - everything works!
