### ISSUE TITLE
Persistent "ERROR" When Creating Telegram Application

### ISSUE THREAD

**Issue by McxCZE** [tdlib/telegram-bot-api#597]
I am experiencing persistent "ERROR" messages when attempting to create a Telegram application via the [my.telegram.org](https://my.telegram.org/) site. Despite following various suggested fixes, the problem remains unresolved.
Steps to Reproduce:

_Fill in the required fields for creating a new application on [my.telegram.org](https://my.telegram.org/apps).
Click the "Create Application" button._

Expected Result:

_The application should be created successfully without errors._
Actual Result:

_An "ERROR" message is displayed, and the application is not created._
What I Have Tried:

Python Script for Automation:
```
import requests
import time
import logging

# Set up logging
logging.basicConfig(filename='telegram_app_creation.log', level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')

# URL and headers for the request
url = "https://my.telegram.org/apps/create"
headers = {
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0',
    'Cookie': 'stel_token=MY_STEL_TOKEN',
    'Origin': 'https://my.telegram.org',
    'Referer': 'https://my.telegram.org/apps',
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'cs,en;q=0.9,en-GB;q=0.8,en-US;q=0.7',
    'X-Requested-With': 'XMLHttpRequest'
}

# Form data
data = {
    'hash': 'MY_HASH',
    'app_title': 'AppTitlev20240906',
    'app_shortname': 'AppShortv20240906',
    'app_url': 'https://my.telegram.org/apps',
    'app_platform': 'web',
    'app_desc': 'Chat Application is designed to help you read groups as quickly as possible. This app leverages the Telegram API, ensuring seamless integration with the Telegram ecosystem.'
}

def send_request():
    response = requests.post(url, headers=headers, data=data, verify=False)
    return response

def worker():
    retries = 3
    for _ in range(retries):
        response = send_request()
        if response.status_code == 200 and "ERROR" not in response.text:
            logging.info("Application created successfully.")
            logging.info(response.text)
            break
        else:
            logging.error("Encountered ERROR, retrying...")
            logging.error(response.text)
            time.sleep(1)  # Wait for 1 second before retrying

num_requests = 50
requests_per_worker = num_requests // 2

for _ in range(2):  # 2 workers
    for _ in range(requests_per_worker):
        worker()
```
JavaScript Console Script:
```
    (function retryCreateApp() {
        // Define a function to override the default alert behavior
        window.alert = function(message) {
            if (message === "ERROR") {
                console.log("Error encountered, retrying...");
                // Re-run the createApp function after a brief delay
                setTimeout(createApp, 1000);
            } else {
                // Restore the default alert behavior for other messages
                alertOriginal(message);
            }
        };

        // Save the original alert function to restore it later if needed
        var alertOriginal = window.alert;

        // Function to start the process
        function startCreateApp() {
            createApp();
        }

        // Add an event listener to the button to start the process
        document.getElementById("app_save_btn").addEventListener("click", startCreateApp);
    })();
```

Tried without VPN: I am from Europe, and I have tried accessing the site with my home IP address and phone number.

Community Suggestions Attempted:

- Using different browsers (Edge, Chrome)
- Disabling ad-blockers
- Changing platform (web, Android, etc.)
- Ignoring "ERROR" message and retrying

Environment:

- Location: Europe
- Browser: Multiple browsers (Chrome, Edge)
- VPN: Tried with and without VPN (I tried with some datacenter VPN in Russia, but to no avail...)

Request for Assistance:

I would greatly appreciate any further insights or solutions from the community or developers to resolve this persistent issue.

**Comment by levlam** [comment]
It looks like you are trying to automatically create application. This makes no practical sense, supposed to fail, and you are supposed to receive "ERROR" as the response.

**Comment by McxCZE** [comment]
It was a desperate attempt, someone referenced a video that when clicking it automatically sometimes helps, I have tried countless times to do it in different browsers, by hand with no luck, I just get this generic error. There is no details nothing.

![obrazek](https://github.com/tdlib/telegram-bot-api/assets/2656561/74e7d969-c312-4deb-9206-0ae09c053946)

**Comment by McxCZE** [comment]
I have basically tried everything there is to try in this thread, and I have noticed that it is closed, but with no solution that would work for me, nothing. 

I am using my own phone number, and I am logging in from my own home IP address, in desperation I have tried a VPN, but to no avail, as I have written before

https://github.com/tdlib/telegram-bot-api/issues/273

**Comment by levlam** [comment]
If you receive an error from your home IP address, then you can only try to register application from some other place.

**Comment by www222fff** [comment]
same error with me, have you got the fix? @McxCZE

**Comment by pickfire** [comment]
I tried to manually register an app I get the same error too.

**Comment by shamp-dev** [comment]
It would seem that telegram developer portal is purposely rejecting applications. are they not accepting new applications?

I create a brand new telegram account with brand new phone number. Still Doesn't work.

**Comment by annamarchenkova** [comment]
any news on how to solve the issue?

**Comment by shamp-dev** [comment]
> any news on how to solve the issue?

I asked my indian friend to do. Worked Perfect.

**Comment by eagle1maledetto** [comment]
Same error. Tested with different browsers, without any extension activated. Same IP from my Telegram session. I just get the ERROR window and no otther clue. Any hints?

**Comment by alexlnkp** [comment]
Same issue. Lack of actual error message is annoying.

**Comment by eagle1maledetto** [comment]
> Same issue. Lack of actual error message is annoying.

Try to use an Android phone with mobile/carrier IP. Worked for me.

**Comment by alexlnkp** [comment]
> > Same issue. Lack of actual error message is annoying.
> 
> Try to use an Android phone with mobile/carrier IP. Worked for me.

Oh, yeah, that worked! Why though...
Regardless, thank you so much!

**Comment by eagle1maledetto** [comment]
> > > Same issue. Lack of actual error message is annoying.
> > 
> > 
> > Try to use an Android phone with mobile/carrier IP. Worked for me.
> 
> Oh, yeah, that worked! Why though... Regardless, thank you so much!

I think to stop/limit bot interaction from creating new API key in a programmatic way

**Comment by fat1** [comment]
is there anyone apply successfully?

**Comment by Octoober** [comment]
This mistake is many years old. It's amazing that developers ignore this problem and don't give any comments. I've tried using different devices, different phone numbers, enabling/disabling VPN, etc. Nothing has worked for me. About 4 years ago I managed to register the app on the first try and never had such luck again. I was hoping that in 4 years they would fix this bug, but no....
I'm making an application, the essence of which is tied to the userAPI and this error has completely ruined the whole idea.

**Comment by mr-v-v-v** [comment]
we need fix asap!!!!

**Comment by shbchk** [comment]
> Try to use an Android phone with mobile/carrier IP. Worked for me.

Wow, that worked for me too.

**Comment by Octoober** [comment]
By trial and error I came to the conclusion that one suspicious attempt (e.g. phone number mismatch with actual IP) is enough to get a temporary blocking. After about 24 hours, I tried again from my PC, and I was able to register the app. I used a phone number that matched the IP.

I think they purposely don't display detailed error information to make it harder for automatic spambots to create. But from the looks of it, it's not effective, it's more of a hindrance to regular developers.

**Comment by TheMarwin** [comment]
For those who are still having this problem, try this:
- Turn off any Adblocker extensions in your browser (some browsers like Brave have it by default, just turn it off)
- Use Cloudflare warp VPN or any VPN that hides your current location.
- Use a fresh browser to be sure

**Comment by spidy0x0** [comment]
> > > > Same issue. Lack of actual error message is annoying.
> > > 
> > > 
> > > Try to use an Android phone with mobile/carrier IP. Worked for me.
> > 
> > 
> > Oh, yeah, that worked! Why though... Regardless, thank you so much!
> 
> I think to stop/limit bot interaction from creating new API key in a programmatic way

I just created a telegram app pragmatically after 5 days of core debugging and workaround hacks.
if this comment gets enough requests, i will find time, arrange the full code and release the repo...

**Comment by behradiy** [comment]
> > > > > Same issue. Lack of actual error message is annoying.
> > > > 
> > > > 
> > > > Try to use an Android phone with mobile/carrier IP. Worked for me.
> > > 
> > > 
> > > Oh, yeah, that worked! Why though... Regardless, thank you so much!
> > 
> > 
> > I think to stop/limit bot interaction from creating new API key in a programmatic way
> 
> I just created a telegram app programmatically with JS after 5 days of core debugging and workaround hacks. if this comment gets enough requests, i will find time, arrange the full code and release the repo...

Bro not even the devs bother to care
please you do and release that code

**Comment by salmansoltaniyan** [comment]
Cloudflare warp worked for me. I used my real location + real number + wrap.

**Comment by guang12386** [comment]
帮助申请telegram application 秒成功 无论什么账号 解决telegram application error问题

Help apply for telegram application in seconds, no matter what account, solve telegram application error problem

请联系Telegram ： @guang8886667

请联系Telegram : https://t.me/guang8886667

**Comment by spidy0x0** [comment]
It’s possible lol
But a crazy workaround and too much stealth needed

I will create the repo soon

**Comment by bas-kirill** [comment]
Same issue

**Comment by Ability08035** [comment]
tell me what to do

.com

**Comment by guang12386** [comment]
帮助申请telegram application 秒成功 无论什么账号 解决telegram application error问题

Help apply for telegram application in seconds, no matter what account, solve telegram application error problem

请联系Telegram ： @guang8886667

请联系Telegram : https://t.me/guang8886667

**Comment by rashed019sy** [comment]
Hello brother, the solution is very simple and from the phone .

1- turn on any VPN

2- Clear all data browser

3- problem sloved

**Comment by ShoomanKhatri** [comment]
i have tried data instead of wifi, it worked. 
and also , it worked after chaning dns

**Comment by darcyda1** [comment]
Telegram app account registration on your behalf—approved in seconds. Contact on Telegram: @darcydai
telegram apps 代注册，秒过，telegram 联系 @darcydai
telegram： https://t.me/darcydai

**Comment by HelloYie** [comment]
https://cheapproxy.net/tgapi 一键申请

**Comment by RuiZhang2016** [comment]
> Hello brother, the solution is very simple and from the phone .
> 
> 1- turn on any VPN
> 
> 2- Clear all data browser
> 
> 3- problem sloved

Thanks bro, this worked for me. What I did is to use Incognito Window and it worked perfectly.

**Comment by YukiNo420** [comment]
yeah same

**Comment by TGAutom** [comment]
TG群发.采集.监控.私信--自动化引流
联系：https://t.me/TGAutom 
联系：https://t.me/aD_DngBot

**Comment by firedotguy** [comment]
any solves?
tried with/without vpn, data/wifi, phone/web, firefox/waterfox/chrome
chnaged description, app types, name, just clicked over 100 times

**Comment by behradiy** [comment]
@firedotguy 
You can work around it with warp. your IP needs to match your country. That worked for me back in the day.

**Comment by YukiNo420** [comment]
> any solves? tried with/without vpn, data/wifi, phone/web, firefox/waterfox/chrome chnaged description, app types, name, just clicked over 100 times

I uesed  EU sim data and it works
https://www.giffgaff.com/

**Comment by telephrag** [comment]
Same. Tried with firefox, librewolf, Opera on iOS, nothing works.

**Comment by telephrag** [comment]
Those who solved via android phone, did you download Telgram from the official site or Google Play? There is seems to be no option to register app in official site version.

Edit: Same crap with Google Play version. There is no button for creating an app.

**Comment by fi-res** [comment]
Idk how but i registered.. Without vpns or browser changing
Just tried after about 2 months from last attempt

**Comment by vignesh679** [comment]
Wait for 5-10 min, then resubmit.

**Comment by happybhaigamer78-blip** [comment]
Facing this issue, & also telegram banned in my country , so I had to use VPN proxy to access,  what should I do

**Comment by FALLE0** [comment]
ip纯净度要高才行

**Comment by MuuJian** [comment]
any solves?

**Comment by r0otx** [comment]
I live from Russia, my phone number have russia prefix, but I can't open my.telegram.org without vpn, he has another country. After make app I see ERROR, how I can solve this problem?

**Comment by cent-dxv** [comment]
use your own mobile  and try it work form me

**Comment by overddosed** [comment]
https://github.com/Flowseal/zapret-discord-youtube/discussions/11494#top

thread for people from Russia
