### ISSUE TITLE
[Error : 0 : Option "api_id" is unrecognized]

### ISSUE THREAD

**Issue by ZloySega** [tdlib/telegram-bot-api#6]
Sorry for very stupid question
how to run?
I try next command from terminal:
`./telegram-bot-api --api_id=123456 --api-hash=dabcdegzlol232346773b1d9e2`
(with right params)
and got:
```
./telegram-bot-api: [Error : 0 : Option "api_id" is unrecognized]
Usage: telegram-bot-api --api_id=<arg> --api-hash=<arg> [--local] [OPTION]...
```

**Comment by demget** [comment]
It should be `--api-id`

**Comment by ZloySega** [comment]
thank you!
