### ISSUE TITLE
[Bug] author_signature not exists for non-anonymous admins

### ISSUE THREAD

**Issue by smaznet** [tdlib/telegram-bot-api#60]
There is field which show author_signature for anonymous admins but this field isn't exists for non-anonymous and there is no other field to know their title in group

**Comment by levlam** [comment]
This is not a bug. Custom administrator title is not used as author signature for non-anonymous administrators. They have their first name and last name for that.

You can find administrator custom titles in [ChatMember](https://core.telegram.org/bots/api#chatmember) object, returned by various methods.
