### ISSUE TITLE
[ASK] Why not found method getinvoicelink ?

### ISSUE THREAD

**Issue by azkadev** [tdlib/telegram-bot-api#603]
The createInvoiceLink method exists but why doesn't the getinvoiceLink method exist?

please add

**Comment by levlam** [comment]
It is useless for bots. Only users can pay invoices.

**Comment by azkadev** [comment]
how to solve this feature? is there a sandbox mode like common payment gateways? btw I'm trying to use Telegram Stars

**Comment by levlam** [comment]
Any invoice can be paid multiple times by the same or multiple users. The question "how to check if the user has paid" makes no sense.

The bot receives a "successful_payment" message when the payment is completed with the specified `invoice_payload`.
