### ISSUE TITLE
Reactions order in MessageReactionUpdated is not preserved?

### ISSUE THREAD

**Issue by wkpn** [tdlib/telegram-bot-api#604]
1-1 chat with the bot, steps are:

1. put one non-premium reaction (🐳 in the example)
2. put second non-premium reaction (🤡 in the example)
3. put third **premium** reaction (numbers in the example)
4. remove **premium** reaction

Expected: order is preserved at all steps
Actual: it is not: 
<img width="371" alt="image" src="https://github.com/tdlib/telegram-bot-api/assets/1161827/211fa4b5-f60f-470a-9955-72d2a699a4ab">

second setup, this time non-premium reactions only

1. put 🐳
2. put 👀
3. put 🤡 - order in `old_reaction` is not preserved already (swapped)
4. given ['🐳', '👀', '🤡'] as a current reactions set, remove the middle one (👀) - order is not preserved again

Expected: order is preserved at all steps
Actual: it is not:
<img width="246" alt="image" src="https://github.com/tdlib/telegram-bot-api/assets/1161827/56490b99-0504-44a1-93f5-62c6ee85d66e">

**Comment by levlam** [comment]
Reaction order depends on the number of times the reactions were chosen by other users. Therefore there can be no any order on reactions of other users and it doesn't make sense to pretend that there is any order on reactions of the current user.

**Comment by wkpn** [comment]
so, to summarize: in 1-1 chats there is no way to tell which reaction was set earlier/later, right?

**Comment by levlam** [comment]
Yes.
