### ISSUE TITLE
Error sending fileid of flac audio in inline request

### ISSUE THREAD

**Issue by Rovniced** [tdlib/telegram-bot-api#609]
For audio files in flac format, if the file has a Content-Type set to audio/x-flac in the request, and then the fileid is used to reply in inline mode. An error BadRequest: audio_content_type_invalid will occur.

If you set the Content-Type to audio/mpeg, application/octet-stream, etc., the fileid you get can be used in inline mode.

Some third-party libraries upload with the file type labeled will cause an error, for example:
https://github.com/python-telegram-bot/python-telegram-bot/issues/4352

The official api only supports mp3 and aac format, but flac format can be played normally, is it possible to do some support for inline mode?

**Comment by levlam** [comment]
See documentation of [InlineQueryResultCachedAudio](https://core.telegram.org/bots/api#inlinequeryresultcachedaudio): "Represents a link to an MP3 audio file stored on the Telegram servers". If you pass parameters that don't conform to the documentation, then the request can fail or may not work in another way.

**Comment by Rovniced** [comment]
> See documentation of [InlineQueryResultCachedAudio](https://core.telegram.org/bots/api#inlinequeryresultcachedaudio): "Represents a link to an MP3 audio file stored on the Telegram servers". If you pass parameters that don't conform to the documentation, then the request can fail or may not work in another way.

The fileid are all obtained by sending in the group via sendAudio request, and after several tests, it is found that the fileid obtained from the request with Content-Type set to audio/x-flac will report an error in the inline request. The parameters are normal.

**Comment by levlam** [comment]
FLAC files can't be played normally. If you try to pretend that a FLAC file is an MP3, then you pass parameters that don't conform to the documentation and the request can fail or may not work in another way in any Telegram app.

**Comment by Rovniced** [comment]
Ok, thanks for your answers.

**Comment by Rovniced** [comment]
Ok, thanks for your answers.
