### ISSUE TITLE
Unpaired UTF-8 Bidi Control Character Detected During Build

### ISSUE THREAD

**Issue by AmirShCO** [tdlib/telegram-bot-api#611]
I encountered a warning when building the Telegram Bot API on AlmaLinux 8. The warning indicates the presence of unpaired UTF-8 bidirectional control characters in the misc.cpp file.

Operating System: AlmaLinux 8
Note: This issue does not occur on Ubuntu or CentOS!!

Error Message:

```
Building CXX object td/CMakeFiles/tdcore.dir/td/telegram/misc.cpp.o /root/telegram-bot-api/td/td/telegram/misc.cpp:164:88: warning: unpaired UTF-8 b idirectional
 control
character detected
2F".
u8"Iu2008",
u8"Iu2009".
[-Wbidi-chars=1
u8"Iu200A"
u8"Iu202E".
u8"u20
```

**Comment by levlam** [comment]
The characters are intentionally used in the strings and are written using UCN, so the warning is wrong. See the corresponding GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104030, which was fixed almost immediately.

**Comment by levlam** [comment]
The warning doesn't affect library in any way.
