### ISSUE TITLE
add WebApp.navigateTo() into the telegram web app js script

### ISSUE THREAD

**Issue by moh0009** [tdlib/telegram-bot-api#612]
Hi,

I have a webpage with buttons that redirect to another webpage when used in a browser. However, in the Telegram web app, clicking the button does not change the web app link. I checked the documentation and found that the WebApp API doesn't include this function.

I was wondering if it could be implemented like this:
```javascript
Telegram.WebApp.navigateTo(url);
```

**Comment by levlam** [comment]
Web Apps have `openLink` method. If you want something other, you can leave your suggestion at https://suggestions.telegram.org/.
