### ISSUE TITLE
send file

### ISSUE THREAD

**Issue by arshiay** [tdlib/telegram-bot-api#614]
i use docker image build from this source but cant upload biger than 150MB how fix it?

**Comment by levlam** [comment]
Check that you run the server with the parameter `--local`.

**Comment by arshiay** [comment]
hi as i said i use docker image from https://hub.docker.com/r/aiogram/telegram-bot-api
and set -e TELEGRAM_LOCAL=1 for local

**Comment by arshiay** [comment]
code in github for that image >>> https://github.com/aiogram/telegram-bot-api

**Comment by levlam** [comment]
The server has no limits on the size of uploaded files besides the limits set for all Telegram users.
