### ISSUE TITLE
[Question] How is synchronization between servers implemented?

### ISSUE THREAD

**Issue by Forden** [tdlib/telegram-bot-api#63]
Hi
How is it possible to sync access_hash between local and main BotAPI servers? Docs says to manually move bot's data from old server to new, but it's not possible when migrating from main server to local one.
I'm building custom BotAPI server and doesn't understand this part.

**Comment by levlam** [comment]
Bot API server doesn't store access hashes. You need to synchronize nothing between servers. The full sentence from the documentation is
> If you want to avoid losing updates between logging out on the old server and launching on the new server, you can ...

**Comment by Forden** [comment]
Thx for fast reply!
But how will user's bots send messages to users if my server doesn't have any access hashes? They're required to send messages and other methods in MTProto
And the only way to get access hash for user without username is from handling updates. So after moving bot from one server to another and trying to send message to user that didn't use bot after moving will lead to situation when bot is trying to send message to active user, but server doesn't have access hash with that user and it can't send MTProto request. This can happen whole broadcasting to bot's users

**Comment by levlam** [comment]
Bots don't need to know access hashes in advance. You can find exact way the requests are handled in the Bot API server's source code.

**Comment by smaznet** [comment]
Hi @levlam 
i have another question about moving to local

do file_ids will be changed and old file_ids work on local server?

**Comment by levlam** [comment]
Nothing changes when you move to a local server.
