### ISSUE TITLE
Bot not respond DeepLink with "?start=Help.Contact"

### ISSUE THREAD

**Issue by iWECon** [tdlib/telegram-bot-api#632]
I checked the api description and only supports A-Z, a-z, 0-9, _ and -
refer: [Deep Linking](https://core.telegram.org/bots/features#deep-linking)

Why not support “.”, and will there be plans to support “.“ in the future?

**Comment by levlam** [comment]
No. The start parameter isn't seen by users, hence there are no reasons to allow characters besides base64url-safe characters.

**Comment by iWECon** [comment]
> No. The start parameter isn't seen by users, hence there are no reasons to allow characters besides base64url-safe characters.

All right :(
