### ISSUE TITLE
[Feature request]add cluster mode

### ISSUE THREAD

**Issue by LimLex** [tdlib/telegram-bot-api#635]
please,add cluster mode,sir.so we can decrease the delay caused by  **different datacenter problem**.(user's and bot's)

**Comment by levlam** [comment]
What do you mean?

**Comment by LimLex** [comment]
> What do you mean?
There is currently an issue with my local server where it cannot deploy my bot in cluster mode. If you can add compatibility for cluster mode, it will solve the following two problems:

1. The performance bottleneck caused by a single machine. If I have multiple machines and can use a cluster, I will be able to improve performance at a lower cost.
2. When I tried to deploy my local server, I found that it can only communicate well with a few specific Telegram data centers, while communication with other data centers is slow. If you support cluster mode, it would allow bot nodes to be deployed near different data centers, improving communication speed.

**Comment by levlam** [comment]
This is not possible and even it would be possible, it can't improve communication speed with different datacenters. Data transmission speed can't be faster than the speed of light.

**Comment by LimLex** [comment]
> This is not possible and even it would be possible, it can't improve communication speed with different datacenters. Data transmission speed can't be faster than the speed of light.

Why is that? Could you explain it for learning purposes? Thank you very much!

**Comment by levlam** [comment]
Users from multiple locations can be in the same chat.

Also, there is no way to provide consistency guarantees if bot communicates with multiple datacenters without making the bot extremely slow increasing latency multiple times.

**Comment by LimLex** [comment]
alright,thank you very much! If there is a method can resolve this problem?

**Comment by levlam** [comment]
There is no way to speed up bot responses for all users around the world.

**Comment by LimLex** [comment]
alright,thank you very much
