### ISSUE TITLE
URL upload failure due to filesize/filetype

### ISSUE THREAD

**Issue by spookyahell** [tdlib/telegram-bot-api#640]
Would it possibly make sense to support a built-in feature for locally downloading files from URLs that fail fetchig in remote download mode (too large or wrong file type)?

Q: _Did I understand this correctly that the document paramter (if it's an url) is merely forwarded "as is" to Telegram MTProto API Servers?_

I'm hoping the answer is "No, I misinterpreted that." (... _No, you_)

If I'm wrong, I'd kindly ask for help finding a jump start to where I need to change parameters to modify the default behaviour.

**Comment by levlam** [comment]
The files are downloaded by Telegram servers to avoid repeated downloads of the sasme file. If you want the file to be manually downloaded, then this should be done by the bot and the file should be uploaded using multipart/form-data.

**Comment by spookyahell** [comment]
Alright (I already tried that) which brings me to:
Is there an (easy) way to get the api have to not wait until the entire data is available before it starts uploading it?
_Basically using upload whilest still receiving the file_

**Comment by levlam** [comment]
No, Bot API has no support for this.

**Comment by spookyahell** [comment]
Alright, thanks for your prompt replies.
