### ISSUE TITLE
Allow to send any type of file with InlineQueryResultDocument

### ISSUE THREAD

**Issue by Sarisan** [tdlib/telegram-bot-api#644]
It is not officially supported by Bot API yet, but you can actually put any file like PNG there and set mine type to zip. It will be sent and displayed properly in any client, except for the moment when file is being downloaded by Telegram server, it will show it as file.zip during download. Can all other mime types like gif, png, jpg, mp4, webm, webp and other popular ones be supported too?

**Comment by levlam** [comment]
It can't be supported now. Inline mode isn't different from sending files by URL on behalf of the user. It works by downloading content of the specified URL server-side and using it as message content. The content of the URL must uniquely determine the type of the message. PNG and JPG files are treated as photos and therefore can be used only for `InlineQueryResultPhoto`.

**Comment by Sarisan** [comment]
> PNG and JPG files are treated as photos and therefore can be used only for `InlineQueryResultPhoto`.

In this case they are supposed to be sent as files, original files, not compressed photos.

**Comment by levlam** [comment]
> I just noticed that official API reference tells that sendDocument is also valid for GIF, PDF and ZIP only, while in reality it can be used with absolutely any other type of file.

Both propositions are not true. The documentation says
> In [sendDocument](https://core.telegram.org/bots/api#senddocument), sending by URL will currently only work for GIF, PDF and ZIP files.

which is correct up to the possibility to send photos as documents and the ability of `sendDocument` to detect type of the file, therefore acceptimg MP3/GIF/WEBP. PDF and ZIP are the only types that are supposed to be sent by URL using `sendDocument`.
