### ISSUE TITLE
Can't sendMessage (sendPhoto,...) to reply a specific message from other bot in supergroups

### ISSUE THREAD

**Issue by anhdung98** [tdlib/telegram-bot-api#657]
According to the [Telegram Bot API document](https://core.telegram.org/bots/api#sendmessage), methods like `sendMessage`, `sendPhoto`, etc., contain a parameter `reply_parameters` to describe the message to reply to. In this parameter, there is a field called `message_id`, which is the ID of the message that needs to be replied to. 

When I use the Bot API to call these methods in a supergroup, the bot can only reply to messages sent by that bot itself or by users; it cannot reply to messages sent by other bots. In that case, the API responds with the error `Bad Request: message to be replied not found`.

Specifically, if the supergroup has 3 members: U1 (user), B1 (bot), and B2 (bot):

- U1 sends a message -> B1 can reply, B2 can reply.
- B1 sends a message -> B1 can reply, B2 cannot reply.
- B2 sends a message -> B1 cannot reply, B2 can reply.

Is there a bug in these APIs, or have I passed an incorrect/missing parameter?

### Steps to reproduce

1. Create a supergroup.
2. Add at least two bots to group, make sure that it have Send Messages permission.
3. From Bot1, send a message, e.g. message_id = 1
4. From Bot2, send other message to reply message_id=1 (reply_parameters={"message_id":1})
5. API response error code 400 with error message `Bad Request: message to be replied not found`.

**Comment by levlam** [comment]
Bots have no access to messages of other bots, and therefore can't reply them.
