### ISSUE TITLE
`getFile` stopped returning `file_path`

### ISSUE THREAD

**Issue by Bibo-Joshi** [tdlib/telegram-bot-api#658]
Hi.

Today some of our test cases over at [`python-telegram-bot`](https://github.com/python-telegram-bot/python-telegram-bot/actions/runs/11607799025/job/32340491289) started failing. After investigating the cause, I found out that calls to `getFile` apparently do not provide the `file_path` as before.
While debugging this, I was not able to come up with realibale circumstances on when `file_path` is returned and when it's not. Maybe this is a hick-up due to the API update that was released today?
Nevertheless, this incident made be aware that `File.file_path` is actually documented to be optional even though so far I (AFAIK) I could always rely on it being present. Would it be possible to specify (also in the documentation) under which conditions the `file_path` might be missing?

Thanks
Hinrich

**Comment by levlam** [comment]
Could you reproduce the issue with the latest local Bot API server with logs verbosity level set to 4 and send the logs to https://t.me/tdlib_bot?

**Comment by wiz0u** [comment]
interestingly, the first getFile fails to fill file_path, but a second call to getFile succeeds

**Comment by Bibo-Joshi** [comment]
I've managed to reproduce on a local api server. I've combiled the server in debug mode (don't know if that matters) and set verbosity level to 4. Attached, please find:

* MWE I used, tested with python-telegram-bot version 21.6
* logs of the python MWE as well as the api server. These cover 4 runs of the MWE.
* excerpt of a shell where ran the same MWE using curl. I did not save the api server logs for this, as the behavior was the same.

From this test, I can see that

* for sending files via URL, `getFile` immediately returns the `file_path` on the first try
* for uploading new files, the first call to `getFile` does not return the `file_path`. 2nd & 3rd call do, as reported by @wiz0u 

Posting this all here for completeness, I'll also ping on TG as requested.

[ptb.py](https://github.com/user-attachments/files/17604175/ptb.py.txt)
[tg-bot-api.log](https://github.com/user-attachments/files/17604171/tg-bot-api.log)
[ptb.log](https://github.com/user-attachments/files/17604172/ptb.log)
[shell.log](https://github.com/user-attachments/files/17604173/shell.log)

**Comment by Bibo-Joshi** [comment]
Was my comment deleted because I had attached logs? Should I repeat my statement without attaching files? Was my message via tdlib_bot received - I did not get a response yet?

**Comment by levlam** [comment]
Yes. No. Yes.

**Comment by Bibo-Joshi** [comment]
The issue was resolved on TG side, thanks very much for the support!
