### ISSUE TITLE
ChatMemberUpdated.via_chat_folder_invite link is empty

### ISSUE THREAD

**Issue by lorien** [tdlib/telegram-bot-api#663]
While trying to fight with spammers who bulk join chats via chat folders I have observed this behavior of bot API.

1. I am admin of some chat group. I create chat folder and add this group to the folder. Then I share my folder with a user. If user joins my chat group via this folder then the ChatMemberUpdated event has  `via_chat_folder_inivte_link = true` field.

2. I am NOT admin of some chat group. I create chat folder and add this group to the folder. Then I share my folder with a user. If user joins this chat group via this folder then the ChatMemberUpdated event has NO `via_chat_folder_inivte_link` field.

Is it a bug?

**Comment by lorien** [comment]
Same bug in telegram bug tracker: https://bugs.telegram.org/c/45651

**Comment by levlam** [comment]
The bug was fixed.
