### ISSUE TITLE
[Feature Request] add elements to channel messages

### ISSUE THREAD

**Issue by startup-001-steve** [tdlib/telegram-bot-api#666]
I would like to be able to have 3 elements to include in a channel message, 
such as 

    Title - large text heading, max length x
    Image - URL to image to display
    Body - regular message content
 
It could look similar to the Mini App example Durger King

![25 11 2024_15 29 48_REC](https://github.com/user-attachments/assets/efc4543f-29cd-4d73-9655-f56ff7716a10)

All the elements would be combined together.
Currently, I need to create 2 or 3 separate messages, and there is no method to increase the text size.

It would make the channel look better.

if this would be too much work, could you consider allowing more html tags to be used, such as H1 and img ?

**Comment by levlam** [comment]
You can use https://suggestions.telegram.org for general suggestions.

**Comment by startup-001-steve** [comment]
thanks, i did not know that subdomain existed, I did not see it linked from the tlegram.org website.
