### ISSUE TITLE
Inconsistent User ID for Anonymous Admin

### ISSUE THREAD

**Issue by Nusab19** [tdlib/telegram-bot-api#667]
I want to implement a "Admin only" feature in a group.

Here's the scenario. "X" is an Anonymous Group Admin.

1. **X** sends a command `/settings` [ Bot gets `1087968824` as the `user.id` ]
2. Bot replies with a message containing an **Inline Keyboard**
3. **X** presses a key. [ Bot gets the user's real `user.id` eg. `5596148289` and not `1087968824` ]
4. Bot tries to get the group administrators. But the real user's id is not there.

Now, there is no way for the bot to determine if the user who pressed the button is a group admin or not.

If when pressed the button, it returned `1087968824` as the `user.id`, it wouldn't have been a problem.

Is there any other workaround for this?

Note: `1087968824` is the userID of **Group Anonymous Bot**

**Comment by Sarisan** [comment]
I don't think Telegram servers themselves support it. I would rather ignore any incoming requests from `1087968824` and `777000` to avoid user data leak or undefined behavior.

**Comment by Nusab19** [comment]
@Sarisan The problem is, because of the "Anonymous Admin" feature, I can't add a command for the admins of the group.

Because I have no way of knowing if the user is an admin or not.

Maybe providing a `is_group_admin` property with the _Update_ would be lot better than the classical approach.

Example:
```json
{
 "update_id": 936805440,
 "message": {
  "message_id": 1340,
  "from": {
   "id": 123123123,
   "is_bot": false,
   "first_name": "Someone",
   "username": "notMe",
   "is_group_admin": true
  },
  "sender_chat": {
   "id": -1002068831209,
   "title": "Bot Test Group",
   "is_forum": true,
   "type": "supergroup"
  },
  "chat": {
   "id": -1002068831209,
   "title": "Bot Test Group",
   "is_forum": true,
   "type": "supergroup"
  },
  "date": 1732920638,
  "text": "/start",
  "entities": []
 }
}

**Comment by Nusab19** [comment]
I think I can use the `sender_chat` to determine if it's the Anonymous admin.

But again, why does the bot gets the user's (anonymous admin's) real userID when he interacts with any `InlineKeyboard` Button?

**Comment by levlam** [comment]
Any user can press the button in any chat. The bot has no way to know that the user pressed the button is an administrator.

**Comment by Nusab19** [comment]
Got it. Thanks for the information.

**Comment by joybiswas007** [comment]
> Any user can press the button in any chat. The bot has no way to know that the user pressed the button is an administrator.

It's possible to know who clicked the button, even if the admin is anonymous. When any user clicks the button, you get the user_id and check it against the list of administrator IDs obtained from `getChatAdministrators`. You can then handle the rest accordingly. Additionally, you need to set up a callback to manage this process effectively.

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_administrators.html
