### ISSUE TITLE
[Feature request] Private bot

### ISSUE THREAD

**Issue by Geobert** [tdlib/telegram-bot-api#67]
Hi,

I don't know if this is the place or if this repo is related to Telegram dev or not. So I'm sorry if it's not and you can close this.

I would like to have the ability to make a bot private and only accessible to its creator.

Cheers,

**Comment by jumoog** [comment]
https://stackoverflow.com/a/46018195/2398537

**Comment by Geobert** [comment]
Thank you for your answer, I know this method but it feels a bit hacky to have a private bot. Discord bot API have such a concept of private bot: on creation, you can define the bot as private and only you can add it in a server. What I'm asking here is something similar, so no need to jiggle with `/setjoingroup` everytime I want to add the bot somewhere :)

It's just an idea, if it's not wanted, feel free to close :)

**Comment by levlam** [comment]
This can be easily implemented in the bot's source code. Adding additional concept for that is an unneeded complication.

**Comment by Geobert** [comment]
Well, if it's in the bot's code, the bot can still be hit by stranger before being shut off. Again, I though it was a nice idea, if Telegram team doesn't think it is, feel free to close this, and we will stuck with hacky way to manage this use case ¯\_(ツ)_/¯

**Comment by levlam** [comment]
A simple check in the bot source code allows to ignore all private messages from unauthorized users and leave all unauthorized groups and channels. Such check can't harm a bot.

**Comment by Geobert** [comment]
Even from a DDOS? (That what I'm worry about :) )

**Comment by levlam** [comment]
Who would need to DDOS a private bot? The attackers will not be able to know even, whether the DDOS attack succeeds or not. And given that any bot should easily drop thousands of incoming updates per second, it should be very hard for a DDOS attack of a private bot to succeed.

**Comment by Geobert** [comment]
OK, closing then :) Thank you for your insight
