### ISSUE TITLE
sendMediaGroup file size limitation

### ISSUE THREAD

**Issue by HeliosVicious** [tdlib/telegram-bot-api#671]
I used a local Telegram Bot API server to upload files to my group. The 2000 MB size limitation was ok because I split the files into archives and sent them separately. Now I need to send a video, so I decided to use sendMediaGroup and split the video into chunks smaller than 2000 MB. It worked fine as long as the total video size was under 4000 MB.

However, trying to send a media group containing three videos with a total size of ~4200 MB results in an error:
[HttpConnectionBase.cpp:134][!HttpInboundConnection]     [Error : 413 : Request Entity Too Large: content length is 4294967295].

I chose sendMediaGroup because it looks better in my case. I want to send the video with a caption, but sending 10 separate videos and only adding the caption to the last one looks odd.
If it’s impossible to send more than 4000 MB in total, I’ll probably stick to sending two videos per message.

Thanks in advance.

**Comment by levlam** [comment]
Bot API HTTP server will not allow requests with payload bigger than 4000 MB. It is a bad idea to send that big HTTP requests anyway. You must pass local paths of the files to send using "file:" protocol instead when local Bot API server is used.

**Comment by HeliosVicious** [comment]
Thanks for the answer. I completely forgot about that option and kept running into the same wall.
