### ISSUE TITLE
Questions about moving telegram-bot-api from server A to B

### ISSUE THREAD

**Issue by mhw0** [tdlib/telegram-bot-api#672]
Hello. I was using server A and recently switched to server B. I think I forgot to follow the "Moving a bot from one local server to another" section and deleted server A. Then, I created telegram-bot-api instance on server B. Everything works just fine, except the method `getChatMember`. It shows I left the channel even if I'm in the channel.

If I call API's `/close` method on server B, the method `getChatMember` starts working as intended, but for some time. After, let's say 5 hours? it stops working again.

Is this because I didn't close the session on server A? If so, how can I close it? but I don't have access to the server A and it's not running (just deleted the server)

**Comment by levlam** [comment]
You must not use the same bot on multiple servers simultaneously.

**Comment by levlam** [comment]
There should be no issues if only one server is running.

**Comment by mhw0** [comment]
I can guarantee that it's running in only one server. Even tried revoking the token, same issue. 

The thing I don't understand is, if I `close` on the server the bot running in right now, the method `getChatMember` shows correct data. But after some time, it starts showing wrong thing again.

**Comment by mhw0** [comment]
Two local bot servers were using the same token. Closing the second one fixed the issue.
