### ISSUE TITLE
[Issue] Some process uses tqueue.binlog

### ISSUE THREAD

**Issue by pyonic** [tdlib/telegram-bot-api#673]
Hi, I had just one instance of telegram bot api server running in local mode, and one bot working with it

It was working fine for 3 - 4 days, no any changes or smth were done, today it throw an error and shutdown and didn't wanted to run again, it kept saying this:
```
Unexpected status [posixerror : resource temporarily unavailable : 11 : can't lock file "/home/documents/telegram-bot-api/build/tqueue.binlog", because it is already in use; check for another program instance running] in file /home/documents/telegram-bot-api/telegram-bot-api/clientmanager.cpp at line 326
```

I checked process using tqueue.binlog, and it was telegram api server, if I am not mistaking, I just quickly killed that pocess without paying attention on what was that (seems some background running thing of bot server ?)

So server run again after I killed that process

So I didn't really launched other instances of telegram bot server, everything was working but that error suddenly happened

**Comment by levlam** [comment]
The error can happen only if you launch two Telegram Bot API servers with the same working directory.

**Comment by pyonic** [comment]
> The error can happen only if you launch two Telegram Bot API servers with the same working directory.

I see, however I am 100% sure I didn't launched second one  :/
Like as I said, everything was working and I didn't touched anything on my VM, it all just suddenly happened

I can write some bash to monitor if more then one server launched and kill it automatically, assuming it somehow spawns new server... but that's workaround

**Comment by pyonic** [comment]
I will go with workaround then, or will figure out how new server spawned...

**Comment by levlam** [comment]
Next time you can use `lsof` to find the process that keeps the file open and locked.
