### ISSUE TITLE
request_users with max_quantity and user_is_bot doesn't work across all platforms

### ISSUE THREAD

**Issue by mnemotiv** [tdlib/telegram-bot-api#675]
https://core.telegram.org/bots/api#keyboardbuttonrequestusers

--

set max_quantity: 10 and user_is_bot: true

windows desktop & webK - it works: it shows bots multi-select screen
android/ios - it doesn't work: it shows only contacts selection screen

--

set max_quantity: 1 and user_is_bot: true

windows desktop & webK - it works: it shows bots single-select screen
android/ios app - it works: it shows bot selection screen, but I can select only 1 bot

--

expected result: to select more than 1 bot-user at once on android/ios

**Comment by mnemotiv** [comment]
https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.cpp#L7785

@levlam

**Comment by mnemotiv** [comment]
I've reported the issue on other "channels" - but I got no response

**Comment by levlam** [comment]
Those are client-side bugs and nothing can be done on the bot side. You need to create a separate issue for Android at https://bugs.telegram.org and wait for them to be fixed.

**Comment by mnemotiv** [comment]
sure, I've just done it for Android too.

though it wasn't fixed for almost a year already... would be nice if you coud "ping" your mobile colleagues, thanks!
