### ISSUE TITLE
Prevent 429 Too Many Requests (Rate Limit)

### ISSUE THREAD

**Issue by dev-whoan** [tdlib/telegram-bot-api#677]
Hello, I am looking for operate Telegram Bot API (instance of this repo).
The purpose is to prevent 429 Too Many Requests from occurring when many users are using the same bot to perform some action.
- Providing single bot to many users without `429 Too Many Requests`. (Let's assume 1,000 users or more)
- Users will interact with the bot using slash commands the bot provides like `/start`, `/options`, 
- In this situation, `api.telegram.org` will return 429 Too Many Requests, bot will be down for retry_after or ...

I searched `Rate Limit` in `Issues`, however, I understand that this application cannot achieve its purpose.
- https://github.com/tdlib/telegram-bot-api/issues/516#issuecomment-1884342070

So I want to double check, so this instance cannot be used for providing my single bot to handle lots of users, right?

**Comment by levlam** [comment]
The self-hosted Bot API server doesn't affect request flood limits. But even bots with millions users don't exceed limits unless they try to incorrectly use API due to a bug. Bots have no issues with handling a lot of users. This is their primary purpose.

**Comment by dev-whoan** [comment]
@levlam Thanks.
