### ISSUE TITLE
`forward message` with `VideoNote` and `show sender name` disabled

### ISSUE THREAD

**Issue by hyperion-cs** [tdlib/telegram-bot-api#680]
Hello. In a bot, I want to determine if a `VideoNote` really owns a user who sends it to the bot. However, if it uses the "_forward message_" feature and disables the "_show sender name_" option, then in an [Update](https://core.telegram.org/bots/api#update) object, that `VideoNote` looks like it was sent by that user (which, in general, match the description of this feature, but see below for the problem).

Is there any way to determine if the `VideoNote` owns this user? I don't require to know the specific user, it's enough for me to understand that it was forwarded from an "anonymous" user.
If not, is it possible to implement them (on the _Telegram Bot API_ side)?

By the way, in general this question can be extended from `VideoNote` to any attachment at all (_photo_, _video_, _document_, _voice_, etc). Or even for any forwarded messages (it looks more accurate). But I am primarily interested in `VideoNote`.

Right now the situation is such that scammers can use a bot and impersonate other people by sending someone else's `VideoNote` (pretending to be their own). In an environment where bot users interact with each other, sometimes the number of scammers reaches up to 70-80% of all users, and such functionality can be **critical**.

upd: This doesn't seem to fall under the purview of this project and I should discuss it [here](https://bugs.telegram.org/?type=suggestions), right?

**Comment by hyperion-cs** [comment]
On the other hand, a "disallow forwarding any messages to the bot" feature would be fine, it looks more accurate. However, now it is also impossible to do this if the user turns off the “show sender name” option.

**Comment by levlam** [comment]
> Is there any way to determine if the VideoNote owns this user

No. And it is definitely impossible to implement this, because any user or bot can upload any file without message forwarding.

**Comment by hyperion-cs** [comment]
@levlam,
> any user or bot can upload any file without message forwarding

Well, for `{ Photo, Video, Document }` formats this is true, but for `{ VideoNote, Voice }` - not really, because in official clients there is no way to select them from a file, only if it is directly recorded from a camera/microphone. At the same time, I realize that they are generated on the client, and that can be faked if you want it badly enough.

**Comment by levlam** [comment]
Bots clearly don't use the official apps.

**Comment by hyperion-cs** [comment]
@levlam,
True. But scammers are real humans, and often use official apps (at least in my practice). In short, some of them work on quality, not quantity (it's a form of social engineering, not, e.g., spam).

Anyway, we are trying to better methods of defense against scammers, and scammers are trying to better methods of attacks, it's a never ending fight.

Thanks for the reply. You may close this issue if you feel the matter has been exhausted.
