### ISSUE TITLE
Issue with file upload over 50MB

### ISSUE THREAD

**Issue by MohamadOday** [tdlib/telegram-bot-api#684]
Hello!
I'm trying to upload videos bigger than 50MB so I'm using telegram local server and python-telegram-bot library 

But when I try to upload a video let's say 80Mb in size I get httpx read error in PTB
and 
```
500 internal server error couldn't upload the file
``` 
In the telegram-bot-api logs

Python version : 3.11.2
Bot api version : 8.1

note that the video is playable and downloadable directly from the host.

**Comment by levlam** [comment]
This doesn't look like an error from the Bot API server.

You need to check logs of the Bot API server.

**Comment by MohamadOday** [comment]
![Screenshot_20241231-172744](https://github.com/user-attachments/assets/0dac8257-ff3f-4423-b159-d91cb1707ef1)
![Screenshot_20241231-172758](https://github.com/user-attachments/assets/047d9937-600d-42fd-8404-75e32521e7bc)
![Screenshot_20241231-172809](https://github.com/user-attachments/assets/7bafe67e-bcda-4aad-89af-5437fe8deb55)
![Screenshot_20241231-173007](https://github.com/user-attachments/assets/7342df1b-1dbe-4fdb-a9d1-aa11ffe5ff72)

Really sorry for sharing the logs like this but this terminal doesn't support copying for some reason

**Comment by levlam** [comment]
Log level 2 would be enough. You need the error from the last line, which is truncated on the screenshot.

**Comment by levlam** [comment]
It is likely that you have no enough disk space in the temp directory of the server.

**Comment by MohamadOday** [comment]
Are you suggesting that I change the temp directory? Because the host has like 10Gb of free storage

**Comment by MohamadOday** [comment]
Changing the temp directory fixed this issue.
Thanks dude
