### ISSUE TITLE
This system does not appear to be a Raspberry Pi

### ISSUE THREAD

**Issue by rowland-cook** [tdlib/telegram-bot-api#70]
I'm trying to install this software on a Raspberry PI 4 4GB.

when I execute the command:
sudo pip3 install --no-binary :all: https://github.com/FutureSharks/rpi-security/archive/1.5.zip

I get this error:
File "/tmp/pip-install-ys2_2iay/picamera/setup.py", line 109, in run
        raise ValueError('This system does not appear to be a Raspberry Pi')
    ValueError: This system does not appear to be a Raspberry Pi
    
    Is there anything I'm doing wrong?
    
    Many thanks

**Comment by levlam** [comment]
How is it related to Telegram Bot API?

**Comment by lukaszraczylo** [comment]
@rowland-cook I have created raspberry pi docker image if you are interested - please see my comments on - https://github.com/tdlib/telegram-bot-api/issues/65

**Comment by levlam** [comment]
@lukaszraczylo How is this related to the question except accidental "Raspberry Pi" mention?

**Comment by lukaszraczylo** [comment]
@levlam you are right, I missed the picamera setup part 👍
