### ISSUE TITLE
Add manage voice chats admin permission

### ISSUE THREAD

**Issue by Poolitzer** [tdlib/telegram-bot-api#72]
I would suggest naming it `can_manage_voice_chats`.

Needs to be added to `ChatMember` (suggested description: _Optional_. Administrators only. True, if the administrator can manage voice chats), as well as `PromoteChatMember` (suggested description: Pass True, if the administrator can manage voice chats).

**Comment by levlam** [comment]
Yes, this administrator right will be a part of Bot API 5.1 update. It was added exactly in the way you described. The corresponding commit will be pushed to Github along with Bot API 5.1 update when it happens.

**Comment by Poolitzer** [comment]
great :)

**Comment by levlam** [comment]
Bot API 5.1 was released: https://core.telegram.org/bots/api-changelog#march-9-2021.
