### ISSUE TITLE
Unable to upload sticker via URL in sendSticker method

### ISSUE THREAD

**Issue by nitreojs** [tdlib/telegram-bot-api#76]
_sorry, i may be sending the question in the wrong place, but i cant find a better place than this repository_

everything's described in the header: i tried `1280x720 .jpg` urls, `512x512 .jpg` urls, `512x512 .png` urls - every single url was sent by the bot as a **document**, so i can not understand how do i upload the sticker via **url** in `sendSticker` method

**Comment by levlam** [comment]
Stickers are webp images, which have suitable size. For example, you can try
```
https://api.telegram.org/bot%3CTOKEN%3E/sendsticker?chat_id=%3CCHAT_ID%3E&sticker=https://upload.wikimedia.org/wikipedia/commons/9/90/Discord-512.webp
```

**Comment by nitreojs** [comment]
![изображение](https://user-images.githubusercontent.com/40319427/103686822-6e5ecb80-4fa0-11eb-9092-1053c10bdd07.png)

maybe im doing something wrong? my code:
![изображение](https://user-images.githubusercontent.com/40319427/103686885-83d3f580-4fa0-11eb-8412-a275e747faef.png)

**Comment by nitreojs** [comment]
if you want to ask me how does context.sendSticker work, it just adds key sticker with value <URL> to form-data

**Comment by nitreojs** [comment]
by the way, used the URL you sent to me and just fetched it and got the same result - bot is sending a document, not a sticker! is this a bug in api? 🤔 

![изображение](https://user-images.githubusercontent.com/40319427/103687918-1b861380-4fa2-11eb-82ad-1941528a256a.png)

**Comment by nitreojs** [comment]
and THIS shows up when i go in bots chat on phone:
![image](https://user-images.githubusercontent.com/40319427/103688554-0493f100-4fa3-11eb-884d-ebba680876f6.png)

**Comment by nitreojs** [comment]
okay, i logged in from phone, went into bot's chat and what do you think? these all files are stickers in mobile client, but in desktop windows client it shows up like a document, seems like a desktop client bug, thanks for helping! i will write that down right into telegram desktop client issues

**Comment by levlam** [comment]
Telegram Desktop shows them as stickers only if the biggest side is 512 pixels.

**Comment by nitreojs** [comment]
i think that's the bug? because it does pretty good job on iOS client, i even scrolled up for 1280x720 stickers and iOS is good with all these stickers, but not Telegram Desktop

**Comment by levlam** [comment]
It's a feature, added because nowadays webp is widely used for ordinary images instead of stickers. See https://github.com/telegramdesktop/tdesktop/issues/8284.

**Comment by nitreojs** [comment]
🤔 that makes sense, thanks! didnt actually see this issue, even tho i searched for `stickers` in `tdesktop`'s issues lol
