### ISSUE TITLE
Revoke token breaks the bot

### ISSUE THREAD

**Issue by manshgil** [tdlib/telegram-bot-api#77]
The bot token was revoked and then the bot stopped working (using the new API token):

This command used to work previously `https://api.telegram.org/botxxxxxxxxx:yyyyyyyyyyyyyyyyyyyy/sendMessage?text=Hello&chat_id=-100zzzzzzzz`, now it gives the error:
`{"ok":false,"error_code":401,"description":"Unauthorized"}`

Trying to set a webhook:
 `code: 401,
  response: { ok: false, error_code: 401, description: 'Unauthorized' },
  description: 'Unauthorized',
  parameters: {},
  on: {
    method: 'setWebhook',
    payload: { url: 'https://xxxxxxxxxxx.xxx:8443/' }
  }
`

Even at getMe there's an error: {"method": "getMe", "payload": {}}
{"ok": false, "error_code": 401, "description": "Unauthorized"}

This started after the bot owner was changed (maybe unrelated).
The new owner revoked the token a few more times and yet the same error appears.

When trying the same thing with a token of a different bot - everything works as expected.

**Comment by manshgil** [comment]
The getMe command got through about 2 out of 20 trials. Very odd

**Comment by manshgil** [comment]
When the query succeeds, the result is:
`{"ok":true,"result":{"id":144#######,"is_bot":true,"first_name":"**********","username":"************","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}`

But most of the time it fails with the 401 Unauthorized error.

**Comment by levlam** [comment]
Send bot username to @tdlib_bot in Telegram.

**Comment by manshgil** [comment]
> @tdlib_bot

Done. Thanks

**Comment by manshgil** [comment]
The issue resolved on it's own after about 24 hours..

**Comment by manshgil** [comment]
Were you able to determine the cause for the bug?
It would be useful to document here how to prevent this issue and how to resolve it if it occurs again.
Thanks

**Comment by levlam** [comment]
@manshgil This exact issue will never happen again, so there is nothing to prevent.

**Comment by nicitaacom** [comment]
How to revoke exposed to client ticket?
