### ISSUE TITLE
Creating bots via telegram-bot-api

### ISSUE THREAD

**Issue by prashant-warrier-93** [tdlib/telegram-bot-api#79]
Is it possible to create a bot using this API by issuing an HTTP request to it?

I.e. can I make a request like this to the telegram-bot-api server

```bash
curl -X POST -d '{"foo": "bar"}' http://localhost:8080/createBot
```

and get a telegram bot?

The reason I'm asking this is because your README.md says that this 
> provides an HTTP API for creating Telegram Bots

![image](https://user-images.githubusercontent.com/74758972/104449413-95cb1f00-55c4-11eb-9d10-df6ccc30a21a.png)

**Comment by levlam** [comment]
No, bots can be created only through @BotFather.

**Comment by watzon** [comment]
@prashant-warrier-93 there is a difference between "creating" (aka programming) a bot, and "registering" a bot through BotFather. Seems to be a common source of confusion.

**Comment by 0964770939** [comment]
Vào 16:31, Th 2, 1 thg 2, 2021 Aliaksei Levin <notifications@github.com> đã
viết:

**Comment by 0964770939** [comment]
Vào 8:01, Th 4, 3 thg 2, 2021 Hà Cherry <hanguyen1993.hn84@gmail.com> đã
viết:
