### ISSUE TITLE
Always getting 401 unauthorized

### ISSUE THREAD

**Issue by buzz3rs** [tdlib/telegram-bot-api#80]
My api is recently getting 401 error code, description : unauthorized.
it used to work just fine before, 
I tried reinstalling, changing tokens, revoking or even changing app id and app hash..  i got nothing
For tests : 
http://Ibotcorp.com:8081
I can provide any logs if needed..

**Comment by levlam** [comment]
The only way to receive error with code 401 is to provide a wrong bot token.

**Comment by buzz3rs** [comment]
You can check any token you want, here’s mine 
1566826077:AAFhbjb4riec70dMdNfGzCq3N1nmNU2-VQ8

It works on the official one but not mine :
https://api.telegram.org/bot1566826077:AAFhbjb4riec70dMdNfGzCq3N1nmNU2-VQ8/getme
——————
http://ibotcorp.com:8081/bot1566826077:AAFhbjb4riec70dMdNfGzCq3N1nmNU2-VQ8/getme

**Comment by levlam** [comment]
Do you use `--filter` option?

**Comment by buzz3rs** [comment]
Nope

**Comment by buzz3rs** [comment]
just a regular installation with 8082 as the stats port

**Comment by buzz3rs** [comment]
I installed on another server with same issue
http://206.189.106.43:8081/
(It's a fresh ubuntu 18 install)

I really cant see the problem

**Comment by buzz3rs** [comment]
I am running the API server via this cmd :
```
./telegram-bot-api --local --api-id=1126**** --api-hash=4308793e16c******68617c687fcb5 -s 8082 --verbosity=4
```

**Comment by levlam** [comment]
Redirect log to a file using option `--log`, reproduce 401 and send the log to @tdlib_bot in Telegram.

**Comment by buzz3rs** [comment]
> @tdlib_bot

Done

**Comment by buzz3rs** [comment]
Actually after reading the log i sent i noticed a typo in the app_id
This is on me (Rookie mistake)
It's all working now
Thank you for your help, I will close this issue now

**Comment by horak** [comment]
> The only way to receive error with code 401 is to provide a wrong bot token.

You also get a 401 if you've just made a GET request to `/logOut` and it's been under ten minutes.

**Comment by levlam** [comment]
@horak Yes, all requests produce 401 first 10 minutes after a successful call to `logOut`.

**Comment by levlam** [comment]
ChatGPT uses Telegraf.

**Comment by majorro** [comment]
same here, not a typo tho
i had a working bot-local server duo, but when added one more instance with fresh token `Unauthorized: invalid api-id/api-hash`
