### ISSUE TITLE
sendMediaGroup doesnt support reply_markup ?

### ISSUE THREAD

**Issue by foremtehan** [tdlib/telegram-bot-api#86]
I need inline buttons for `sendMediaGroup` method but looks like it doesnt accept `reply_markup` field, So i'm just wondering why ? I really need inline button for my albums.

My use case : In my bot i want to paginate 100 photos splitted by 10 photo so the inline button shows the next 10 photo but i cannot use them

**Comment by levlam** [comment]
Clients are unable to show inline keyboards for albums, so server doesn't allow to send them.
