### ISSUE TITLE
Can't edit downloaded files

### ISSUE THREAD

**Issue by Nickelza** [tdlib/telegram-bot-api#89]
When I try to edit/rename a downloaded file (path: bot_token/documents), I get an error which informs me I haven't got the necessary permissions. This was confirmed by the fact that downloaded files are owned by root (the local api is ran with sudo), so i need to edit the permissions for the downloaded files.
I've tried both `chmod g+s bot_token/documents` and `setfacl -d -m u::rwx,g::rwx,o::- bot_token/documents`, but none seem to do the trick. Any advice?

OS: Ubuntu 20.04 LTS

**Comment by levlam** [comment]
This sounds like a system administration problem not related to Bot API.

Between, it is a bad idea to run a software under root. You can use options `--username` and `--groupname` to switch to another user right after server is launched.

**Comment by Nickelza** [comment]
Solved. I used the following inotify script to reset permissions:

```
inotifywait -m /path/to/download/folder -e create -e moved_to -r |
while read dir action file; do
    chmod 755 $dir$file 
done
```
