### ISSUE TITLE
How to setting webhook Bot Api Server ?

### ISSUE THREAD

**Issue by yudaapratama** [tdlib/telegram-bot-api#91]
Bot API server success running in my server, when I want to set my bot to webhook, I get an error 

> {"ok":false,"error_code":400,"description":"Bad Request: bad webhook: HTTPS url must be provided for webhook"}

how to run Bot API server with my HTTP ?
or I have miss configuration ?

thank you

**Comment by arseny30** [comment]
You should pass `--local` option to your server.

But you should be careful, your http address should be on the same server as bot api server or in the same private network.
