### ISSUE TITLE
Why do I need internet connection?

### ISSUE THREAD

**Issue by yvikt** [tdlib/telegram-bot-api#95]
Why do I need internet connection in case I have running telegram-bot-api, bot as well and telegram desktop client locally on same machine? Why client can't send message to bot directly to my local telegram-bot-api instance? Is it possible to ask Telegram "Father" <strike>or God</strike> to tell my client that my bot lives on my local telegram-bot-api instance and that my client needs to send messages via localhost or via my home local network? )))

**Comment by levlam** [comment]
This is impossible. All messages must be sent through Telegram servers. Bot API server must never communicate directly with user client, because it would lead to a lot of security issues.

**Comment by yvikt** [comment]
Thanks for so fast response. Telegram is really fast staff )))
I thought I'll get pure (full) local development environment without needing internet connection (
