### ISSUE TITLE
Files/photos are being duplicated after telegram-bot-api restarted

### ISSUE THREAD

**Issue by ihoru** [tdlib/telegram-bot-api#96]
1. I start local bot (with flag `--local`)
2. I make request `getFile` with `file_id` to it
3. I get local `file_path` in response -- everything is good for now
4. I stop the process and start it again
5. I request `getFile` again with the same `file_id` and I get another local `file_path`, but file is actually the same. I check local storage there are duplicated files.

This issue happens every time after every restart of `telegram-bot-api` process.

**Comment by levlam** [comment]
This is expected behavior. There is no way to save file path between Bot API restarts and there are no reasons to do that. The returned file path is still guaranteed to be valid at least for 1 hour and old files are deleted once a day.
