### ISSUE TITLE
Use some tdlib methods not in bot api document

### ISSUE THREAD

**Issue by SeyyedKomeil** [tdlib/telegram-bot-api#97]
Hey
Can i use some methods with local telegram bot api server?
for example using [save-big-file-part](https://docs.pyrogram.org/telegram/functions/upload/save-big-file-part)

**Comment by levlam** [comment]
This is not a TDLib's method.

Anyway, the answer would be no. This is exactly the same server running at https://api.telegram.org. Only usage of `--local` command-line argument changes some functionality and the difference is fully described in https://github.com/tdlib/telegram-bot-api#usage.

**Comment by SeyyedKomeil** [comment]
for send message i send request to this url:
http://domain:8081/botTOKEN/sendMessage

for save-big-file-part what should i do?

this is not in [bot api doc](https://core.telegram.org/bots/api)

**Comment by levlam** [comment]
You can't call this method using an HTTP request. This method is available only over MTProto.
