### ISSUE TITLE
setMyCommands Returns Success for Invalid Payload

### ISSUE THREAD

**Issue by muya** [tdlib/telegram-bot-api#98]
### Description

When sending an API request to create commands for your bot, sending a request payload with an invalid `command` field  value (command name with upper case letters) doesn't result in a failed request.

### How to reproduce?

Try use the `setMyCommands` API endpoint to create commands for your bot

- Send API request to `setMyCommands` endpoint
```
curl --request POST \
  --url https://api.telegram.org/botApiKey/setMyCommands \
  --header 'Content-Type: application/json' \
  --data '[
    {
        "command": "InvalidCommandWithUpperCaseLetters",
        "description": "demo issue with setMyCommands"
    }
]'
```

### Expected Response:
Something like:
```json
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: command cannot have upper case letters"
}
```

### Actual Response:
```json
{
  "ok": true,
  "result": true
}
```

It would be great if this endpoint could return an error message in case of an invalid payload.

**Comment by levlam** [comment]
If a specified command is wrong, Bot API returns "Bad Request: BOT_COMMAND_INVALID".

You are sending the request in a wrong way. `setMyCommands` expects one parameter, named `commands`, and your request doesn't have it. So, the request sets empty list of commands and succeeds in this.

**Comment by muya** [comment]
@levlam Thanks for your response. I updated the request payload to be as follows, and it started working:
```json
    {
        "commands": [
            {
                "command": "validcommandformat",
                "description": "demo correct format for setMyCommands"
            }
        ]
    }
```

Full curl example:
```
curl --request POST \
  --url https://api.telegram.org/botApiKey/setMyCommands \
  --header 'Content-Type: application/json' \
  --data '[
    {
        "commands": [
            {
                "command": "validcommandformat",
                "description": "demo correct format for setMyCommands"
            }
        ]
    }
]'
```

**Comment by Ghassanee** [comment]
make sure the command does not have an uppercase

**Comment by damozhang** [comment]
> make sure the command does not have an uppercase

You saved my day.
